import { L, type Group } from '../types.ts';

const group: Group = {
  key: 'agentops',
  order: 70,
  name: L('AgentOps: Deploy & Operate', '智能体运维：部署与运营'),
  groupSummary: L('Running agents in production: rollout, versioning, scaling, idempotent retries, cost control, incident response.', '在生产中运行智能体：灰度、版本化、扩缩、幂等重试、成本控制与事故响应。'),
  entries: [
    { page: 'durable-state-and-resumability', slug: 'durable-state-and-resumability', title: L('Durable State & Resumability','持久状态与可恢复性'), summary: L('Make the agent loop a durable computation — event-sourced history, journal-before-effect, and resume that replays rather than re-derives, so a crash or redeploy never restarts a half-done task.','把智能体循环做成一次持久计算——事件溯源式历史、先写日志再产生副作用、以重放而非重新推导来恢复，使崩溃或重新部署绝不重启一个做了一半的任务。') },
    { page: 'concurrency-and-scaling', slug: 'concurrency-and-scaling', title: L('Concurrency, Queues & Scaling','并发、队列与扩缩容'), summary: L('Agents are batch jobs, not requests: a queue with leased workers, per-tenant concurrency caps, journal-as-state for horizontal scale, and bounded fan-out are what survive production load.','智能体是批处理作业而非请求：带租约 worker 的队列、按租户并发上限、以日志为状态实现横向扩缩、以及有界扇出，才是能扛住生产负载的形态。') },
    { page: 'idempotency-and-retries', slug: 'idempotency-and-retries', title: L('Idempotency, Retries & Side-Effect Safety','幂等、重试与副作用安全'), summary: L('Four stacked retry sources mean every write tool will fire twice unless you construct exactly-once with intent-derived idempotency keys, failure classification, and a durable side-effect ledger.','四个叠加的重试源意味着每个写工具都会触发两次——除非你用源自意图的幂等键、失败分类与持久副作用账本构造出恰好一次。') },
    { page: 'cost-control-in-the-loop', slug: 'cost-control-in-the-loop', title: L('Cost Control at the Loop Level','在循环层面控制成本'), summary: L('Agent cost is unbounded by default; treat the per-task token/step/dollar ceiling as a fail-closed circuit breaker, then tune model cascades, prompt and tool caching, and early-exit against a quality metric.','智能体成本默认无界；把按任务的 token/步数/美元上限当作 fail-closed 熔断器，再对着质量指标调模型级联、提示与工具缓存、以及提前退出。') },
    { page: 'rollout-and-versioning', slug: 'rollout-and-versioning', title: L('Rollout, Versioning & Pinning','灰度发布、版本化与固定'), summary: L('Behavior is the (model, prompt, tools) triple; pin it to dated snapshots, stamp it on every run, and promote new versions only through shadow/canary plus an eval gate with instant config-flip rollback.','行为是（模型、提示、工具）三元组；固定到带日期的快照、在每次运行上打戳，并只经影子/灰度加评估闸门提升新版本，配以即时配置切换回滚。') },
    { page: 'feature-flags-for-agents', slug: 'feature-flags-for-agents', title: L('Feature flags for agents','面向智能体的特性开关'), summary: L('Flags scoped to prompts, models, tools, and policies — what to gate, how to roll, and why "off by default" is a non-negotiable for agent flags.','面向 prompt、模型、工具与策略的开关——该把什么放进开关、如何放量，以及为何"默认关"对智能体开关是没得商量的。') },
    { page: 'kill-switches', slug: 'kill-switches', title: L('Kill switches','急停开关'), summary: L('A button that stops a running agent fleet — what it must actually stop (in-flight calls, queued work, scheduled retries), and how to test it before you need it.','一个能停下整支正在运行的智能体队伍的按钮——它真正要拦下的东西（飞行中调用、排队任务、计划重试），以及如何在你真用上它之前就把它演练好。') },
    { page: 'incident-response-for-agents', slug: 'incident-response-for-agents', title: L('Incident Response & Runaway Containment','事故响应与失控遏制'), summary: L('A runaway agent fails open and keeps acting; detect from rate and progress, contain with in-loop fail-closed kill switches the resume path respects, rely on pre-installed blast-radius bounds, and turn every incident into a regression test.','失控的智能体 fail-open 且持续行动；从速率与进展检测、用恢复路径也遵守的循环内 fail-closed 熔断遏制、依赖预装的爆炸半径界限，并把每桩事故变成回归测试。') },
    { page: 'rate-limits-and-provider-capacity', slug: 'rate-limits-and-provider-capacity', title: L('Rate Limits & Provider Capacity','速率限制与厂商容量'), summary: L('A 429 is a capacity contract, not a transient error, and retrying it turns a shortfall into an outage; agents burn tokens-per-minute quadratically, so the fix is a shared admission-control bucket, deliberate load shedding, and treating cross-provider failover as a behavior change your evals must cover.','429 是一份容量合同而非瞬时故障，重试它会把缺口变成宕机；智能体的每分钟令牌消耗是平方级的，所以修法是一个共享的准入控制令牌桶、有意识的负载卸载，以及把跨厂商故障转移当作评估必须覆盖的行为变更。') },
    { page: 'model-deprecation-and-migration', slug: 'model-deprecation-and-migration', title: L('Model Deprecation & Migration','模型退役与迁移'), summary: L('A model ID is a dependency with an expiry date you cannot vendor: notice floors of 60 days or less, why the swap is a re-qualification rather than a string replacement, silent platform auto-upgrades as the worst failure mode, and the generated inventory plus warm candidate lane that turn a retirement into a one-day operation.','模型 ID 是一个带保质期、且无法 vendor 的依赖：通知下限低至 60 天甚至更短、为何切换是一次重新资格认证而非字符串替换、平台静默自动升级才是最糟的失败模式，以及把一次退役变成一天工作量的自动生成清单与常热候选通道。') },
    { page: 'self-hosted-inference-for-agents', slug: 'self-hosted-inference-for-agents', title: L('Self-Hosted Inference for Agents','为智能体自建推理'), summary: L('Leaving the provider API changes the currency from tokens to KV-cache bytes: capacity is concurrent sequences times context length, prefix-cache hit rate is a routing problem rather than an engine one, autoscaling does not work at agent timescales, and the break-even is a utilisation number.','离开厂商 API，计价单位就从 token 变成 KV 缓存字节：容量是并发序列数乘上下文长度、前缀缓存命中率是路由问题而非引擎问题、自动扩缩在智能体的时间尺度上不管用，而盈亏平衡点是一个利用率数字。') },
    { page: 'multi-tenancy-for-agents', slug: 'multi-tenancy-for-agents', title: L('Multi-Tenancy for Agents','智能体的多租户'), summary: L('An agent adds five stores your row-level policy never touched — prompt cache, semantic cache, vector index, memory and the rate-limit pool — and only the semantic cache can hand one tenant another tenant’s answer.','智能体新添了五个你的行级策略从未触及的存储——提示词缓存、语义缓存、向量索引、记忆与限流额度池——而其中只有语义缓存会把一个租户的答案交给另一个租户。') },
    { page: 'slos-and-error-budgets', slug: 'slos-and-error-budgets', title: L('SLOs & Error Budgets for Agents','智能体的 SLO 与错误预算'), summary: L('Correctness fails every test an SLI must pass, so budget the mechanical indicators you can compute deterministically, run a second harm budget denominated in actions taken rather than requests served, and demote judge-scored quality to a control chart that never pages.','正确性在 SLI 必须通过的每一项测试上都不及格，所以对你能确定性计算的机械指标做预算、跑一份以"已采取动作数"而非"已服务请求数"为分母的第二份危害预算，并把裁判打分的质量降格到一张永不传呼的控制图上。') },
    { page: 'graceful-degradation-and-fallback', slug: 'graceful-degradation-and-fallback', title: L('Graceful Degradation &amp; Fallback','优雅降级与备用方案'), summary: L('The fallback is a different agent — different tool dialect, context ceiling and refusal profile — running your most traffic down your least-tested path under thresholds calibrated for a model that stopped answering: decide what to shed before what to swap, fail closed on side effects, and make degraded mode a named state with an exit.','备用方案是另一个智能体——不同的工具方言、上下文上限与拒答画像——它让最大的一股流量走上测试最少的路径，头顶还是照着一个已停止作答的模型校准的阈值：先决定卸掉什么再决定换成什么、对有副作用的操作失败闭合，并把降级做成一个有出口的具名状态。') },
    { page: 'exiting-a-managed-agent-runtime', slug: 'exiting-a-managed-agent-runtime', title: L('Exiting a Managed Agent Runtime','退出一个托管智能体运行时'), summary: L('Maintenance mode promises existing workloads keep running, which is exactly what makes teams wait — the real deadline is the day the frozen model catalog stops carrying a model you need, and meanwhile the loop everyone assumes is the hard part ports in a sprint while the conversation state nobody inventoried is the migration: prove the export on day one, dual-write, then port code against a backlog that has stopped growing.','维护模式承诺既有负载继续运行，而这恰恰是让团队一等再等的原因——真正的期限是被冻结的模型目录不再提供你需要的某个模型的那一天；与此同时，人人以为最难的那个循环一个迭代周期就搬完了，而没人清点过的对话状态才是那次迁移：第一天就把导出验证掉、开双写，然后在一个已停止增长的积压面前去搬代码。') },
    { page: 'third-party-tool-drift', slug: 'third-party-tool-drift', title: L('Third-Party Tool Drift','第三方工具漂移'), summary: L('A tool description is part of your prompt and someone else owns the text, so behaviour changes with no commit and no error — the loud structural breaks are the harmless kind, while a reworded docstring moves tool-selection rates silently: snapshot the catalog, stamp its hash on every trace, and absorb the change in a facade rather than the prompt.','工具描述是你 prompt 的一部分，而那段文字归别人所有，于是行为会在没有提交、也没有报错的情况下改变——吵闹的结构性破坏反倒是无害的那一类，而一句改写过的文档串会悄悄挪动工具选择率：给目录做快照、把它的哈希打在每条 trace 上，并在门面层而不是 prompt 里吸收这次变化。') },
    { page: 'scheduled-and-triggered-agents', slug: 'scheduled-and-triggered-agents', title: L('Scheduled & Triggered Agents','定时与事件触发的智能体'), summary: L('With no user present, ask becomes abstain, retry becomes reconcile, and the default failure is silence rather than an error — so put a dead-man’s switch on every schedule, end each firing in an acted / no-op / blocked verdict, and rate-limit the notification channel independently of the agent’s own judgement.','没有用户在场时，"问"变成"弃权"，"重试"变成"对账"，默认的失效是沉默而不是报错——所以给每条排程装上守尸开关、让每次触发以"动了/无事/卡住"的判定收尾，并独立于智能体自身判断给通知频道限流。') },
    { page: 'load-testing-agents', slug: 'load-testing-agents', title: L('Load-Testing an Agent System','给智能体系统做压测'), summary: L('The first decision is what to do about side effects, and every answer changes the measurement — mocked tools delete the seconds of real latency that dominate a trajectory. Size the run from Little’s Law, generate sampled tasks rather than one repeated prompt, grade quality under load because degradation is silent, and report the concurrency where success starts falling plus which dependency returned the first 429.','第一个决定是拿副作用怎么办，而每一个答案都会改变测量本身——mock 掉的工具抹去了主导一条轨迹的那几秒真实延迟。用利特尔法则定规模、用采样出的真实任务而不是一条重复的提示来造负载、在负载下给质量打分（因为退化是无声的），并报出成功率开始下滑处的并发数，以及第一个返回 429 的依赖是谁。') },
  { page: 'reindexing-and-embedding-migrations', slug: 'reindexing-and-embedding-migrations', title: L('Re-indexing &amp; Embedding Migrations','重建索引与向量模型迁移'), summary: L('An embedding model is a schema with no in-place migration — two models occupy different spaces, so there is no canary and no dual-read, only a complete second index and an atomic cutover — and the rebuild that discovers your chunker drifted is the one where the quality delta can no longer be attributed to anything.','向量模型是一份没有原地迁移路径的 schema——两个模型身处不同空间，于是没有灰度、没有双读，只有一套完整的第二索引加一次原子切换——而那次发现切块器早已漂移的重建，正是质量差值再也归不了因的那一次。') },
  { page: 'repairing-agent-side-effects', slug: 'repairing-agent-side-effects', title: L('Repairing What the Agent Already Did','修复智能体已经做过的事'), summary: L('Containment fires in four seconds against a fault that landed three weeks ago, and almost nothing tells you what to do about the four thousand wrong actions already committed — each was a judgement rather than a row, so scope by decision instead of by record, sort the damage into recompute, compensate, irreversible and derived, replay against the pinned versions in force at the time, and run the backfill as a staged compute-then-apply migration keyed on the original run id.','遏制机制在四秒内触发，对付的却是三周前落地的故障；而几乎没有人告诉你，已经提交出去的那四千次错误动作该怎么办——每一次都是一个判断而不是一行记录，所以要按决策而非按记录划定范围，把损害分进重算、补偿、不可逆与派生四个桶，对照当时生效的钉住版本重放，并把回填做成一次以原始 run id 为幂等键、先计算后执行的分段迁移。') },
  ],
};
export default group;
