import { L, type Group } from '../types.ts';

const group: Group = {
  key: 'economics-roi',
  order: 140,
  name: L('Economics & ROI', '经济性与投资回报'),
  groupSummary: L('The unit economics of agents — pricing, cost attribution, ROI measurement, build-vs-buy, failure modes.', '智能体的单位经济性——定价、成本归因、ROI 度量、自建对外购、失败模式。'),
  entries: [
  { page: 'build-vs-buy', slug: 'build-vs-buy', title: L('Build vs Buy vs Orchestrate','自建 vs 采购 vs 编排'), summary: L('Not a cost comparison but a question of which layer is your durable moat: the three-branch decision tree, the hidden costs each path omits, and the lock-in you price today but pay later.','不是成本比较，而是哪一层是你持久护城河的问题：三分支决策树、每条路略去的隐性成本，以及你今天定价、以后才付的锁定。') },
  { page: 'unit-economics', slug: 'unit-economics', title: L('Agent Unit Economics','智能体单位经济学'), summary: L('Cost per token is the wrong unit; cost per successful task is the right one, with the success rate in the denominator where small reliability gains swing margin hardest.','每 token 成本是错误的单位；每个成功任务的成本才对，成功率在分母上——那里一点可靠性提升对毛利的撬动最猛。') },
  { page: 'per-customer-economics', slug: 'per-customer-economics', title: L('Per-customer economics','按客户的单位经济模型'), summary: L('Whole-system unit economics hide which customers cost you money — a per-tenant cost view, what drives the heavy-tail user, and the levers you actually have.','整盘的单位经济模型会把哪些客户亏钱遮起来——按租户的成本视图、什么造就长尾用户，以及你手上真正能用的杠杆。') },
  { page: 'cost-attribution', slug: 'cost-attribution', title: L('Cost Attribution & Budgets','成本归因与预算'), summary: L('The provider bill is at the wrong granularity to act on: tag spend by feature, tenant, user, and version, propagate it through fan-out, and make budgets runtime circuit breakers, not reports.','厂商账单的粒度无法据以行动：按功能、租户、用户、版本给花费打标签，让它穿过扇出传播，并把预算做成运行时熔断器，而非报表。') },
  { page: 'measuring-roi', slug: 'measuring-roi', title: L('Measuring Agent ROI','衡量智能体投资回报'), summary: L('Value over a defensible counterfactual, net of the human still in the loop, on a cumulative time-to-value curve — and why the "agent replaces a human" framing is a category error.','相对站得住脚的反事实、扣除仍在循环里的人、放在累计价值实现曲线上的价值——以及为何"智能体替代一个人"是范畴错误。') },
  { page: 'pricing-models', slug: 'pricing-models', title: L('Pricing & Packaging Agent Products','智能体产品的定价与打包'), summary: L('Seat, usage, and outcome pricing each misalign somewhere; align price with delivered value but defend the floor, because more autonomy means you hold more variable-cost risk.','席位、用量、结果定价各在某处错位；让价格与交付价值对齐但守住下限，因为越自主你持有的可变成本风险越大。') },
  { page: 'economics-failure-modes', slug: 'economics-failure-modes', title: L('Where the Economics Breaks','经济性在何处崩溃'), summary: L('Unit economics do not erode gradually — they invert at retry storms, the long tail, escalation, the eval bill, and the silent-failure tax; watch the failure surface, not the average.','单位经济学不会渐渐侵蚀——它在重试风暴、长尾、上报、评估账单与无声失败税处反转；盯着失败面，而非平均。') },
  { page: 'provisioned-throughput-and-commitments', slug: 'provisioned-throughput-and-commitments', title: L('Provisioned Throughput &amp; Commitments','预置吞吐量与容量承诺'), summary: L('A 30% discount means breaking even at 70% sustained utilisation, which bursty agent traffic never reaches — so reserved capacity is a latency guarantee you can put in front of a customer, not a saving, and a term commitment quietly freezes your model choice in a market that moves quarterly.','打七折意味着要在 70% 的持续利用率上才打平，而突发式的智能体流量从来到不了那里——所以预留容量是一份你能摆到客户面前的延迟保证，而不是一笔节省；而一份期限承诺会在一个按季度移动的市场里悄悄冻住你的模型选择。') },
  { page: 'cost-of-evaluation', slug: 'cost-of-evaluation', title: L('The Cost of Evaluation','评测的成本'), summary: L('Eval spend scales with change rate, not traffic, and its price is set by the smallest regression you insist on catching — which costs quadratically, so a two-point threshold buys roughly 7,700 runs where a five-point one buys 1,400.','评测开销随变更速率而非流量增长，而它的价格由你坚持要抓到的最小回归决定——这个价格按平方增长：两个百分点的阈值大约要买 7,700 次运行，五个百分点只要 1,400 次。') },
  { page: 'cost-of-human-review', slug: 'cost-of-human-review', title: L('The Cost of Human Review','人工复核的成本'), summary: L('The reviewer costs ten to fifty times what the tokens do, and it is the only line that does not shrink when the agent gets better — because a reviewer has to read the correct outputs too; only calibrated selective review removes it.','复核者的成本是 token 的十到五十倍，而且这是唯一一条不会因为智能体变好而缩小的开销——因为复核者连正确的输出也得读；唯一能消掉它的，是经过校准的选择性复核。') },
  { page: 'scaling-back-an-agent-deployment', slug: 'scaling-back-an-agent-deployment', title: L('Scaling Back an Agent Deployment','收缩一次智能体部署'), summary: L('Nearly half of enterprise leaders cut an agent deployment last quarter over cost, and "scaled back, narrowed, delayed or paused" is four names for one blunt instrument — inside a single deployment one workflow can clear its manual baseline by 55× while another loses money every run, so cut the task class instead, carve out the tail before condemning the class, and write the resume condition down as a number.','上个季度，接近半数的企业负责人因成本砍了智能体部署，而"收缩、收窄、推迟或暂停"是同一件钝器的四个名字——在同一个部署内部，一条工作流能把人工基线甩开 55 倍，另一条却每跑一次都在亏，所以要切的是任务类；在给这个类定罪之前先把长尾切出去，并把恢复条件写成一个数字。') },
  { page: 'forecasting-agent-spend', slug: 'forecasting-agent-spend', title: L('Forecasting Agent Spend','预测智能体开销'), summary: L('An agent’s per-task cost is heavy-tailed, so the mean forecasts nothing and is biased low — worse at scale, because more volume draws more of the tail. Forecast a sum over task classes carrying each class’s p95, cap every class so the tail has a finite number, drive it off retry rate, context growth, route mix and cache hit rate, and reconcile each month into volume, mix and per-task drift.','智能体的每任务成本是重尾的，于是均值什么也预测不了且系统性偏低——规模越大越糟，因为用量越大抽到的长尾越多。要预测一个跨任务类的求和、各类带上自己的 p95，给每一类封顶好让长尾有一个有限的数，用重试率、上下文膨胀、路由组合与缓存命中率来驱动它，并每个月把误差对账为用量、组合与每任务漂移。') },
  ],
};
export default group;
