import { L, type Group } from '../types.ts';

const group: Group = {
  key: 'governance-compliance',
  order: 160,
  name: L('Governance & Compliance', '治理与合规'),
  groupSummary: L('Accountability, audit, policy enforcement and the regulatory landscape — making agent decisions defensible.', '问责、审计、策略执行与监管版图——让智能体的决策可被解释与辩护。'),
  entries: [
  { page: 'audit-trails', slug: 'audit-trails', title: L('Audit Trails & Provenance','审计轨迹与溯源'), summary: L('What to capture to reconstruct any decision, hash-chained tamper-evidence, retention vs erasure, and the four-strand provenance of model, prompt, tools and data.','为重建任何决策该捕获什么、哈希链式防篡改可察觉、保留期与擦除权，以及模型／提示词／工具／数据的四线溯源。') },
  { page: 'policy-enforcement', slug: 'policy-enforcement', title: L('Policy Enforcement & Controls','策略执行与管控'), summary: L('Policy-as-code outside the model, enforcing pre/in/post loop, allowlist-by-default, and separation of duties so a compromised agent cannot close the loop alone.','模型之外的策略即代码、在循环前／内／后执行、默认白名单，以及职责分离使被攻陷的智能体无法独自闭环。') },
  { page: 'regulatory-landscape', slug: 'regulatory-landscape', title: L('The Regulatory Landscape','监管版图'), summary: L('A qualitative map (not legal advice): risk-tiered regulation, documentation and human-oversight duties, the provider/deployer split, and how NIST AI RMF and ISO/IEC 42001 operationalize it.','一张定性地图（不是法律意见）：风险分级监管、文档与人工监督义务、提供方／部署方之分，以及 NIST AI RMF 与 ISO/IEC 42001 如何把它操作化。') },
  { page: 'eu-ai-act-for-agents', slug: 'eu-ai-act-for-agents', title: L('EU AI Act, for agents','欧盟《人工智能法案》——智能体视角'), summary: L('The AI Act\'s risk tiers explained from an agent builder\'s perspective — what triggers high-risk, what general-purpose AI obligations look like, and the dates that matter.','从智能体开发者视角解读《人工智能法案》的风险分层——什么会触发高风险、通用人工智能义务是什么样子，以及关键时间点。') },
  { page: 'nist-ai-rmf-for-agents', slug: 'nist-ai-rmf-for-agents', title: L('NIST AI RMF, for agents','NIST AI RMF——智能体视角'), summary: L('Map / Measure / Manage / Govern read as a checklist for agent teams — what each function actually demands when the system is an autonomous agent rather than a model.','把"映射 / 度量 / 管理 / 治理"四件套当作智能体团队的清单来看——当系统是自主智能体而不仅仅是一个模型时，每个职能真正要求什么。') },
  { page: 'accountability-and-roles', slug: 'accountability-and-roles', title: L('Accountability & Ownership','问责与归属'), summary: L('Accountability never transfers to the agent: the named operator role, RACI on the autonomous action, sign-off that means something, and an accountability ladder set in advance.','问责绝不转移到智能体：具名操作者角色、对自主行动做 RACI、有分量的签字，以及事先设定的问责阶梯。') },
  { page: 'data-governance', slug: 'data-governance', title: L('Data Governance for Agents','智能体的数据治理'), summary: L('An agent is a data-flow machine: lineage through the loop, purpose/consent enforced at point of use, boundary minimization for PII, governed training data, and invisible cross-border flow.','智能体是一台数据流机器：穿过循环的血缘、在使用点执行目的／同意、对 PII 做边界最小化、受治理的训练数据，以及无形的跨境流动。') },
  { page: 'governance-in-practice', slug: 'governance-in-practice', title: L('Governance Without Gridlock','不卡死的治理'), summary: L('Make governance an enabler: risk-proportionate tiers, the safe default as the easy path, automated evidence with humans on judgment, and counting gridlock as a real cost.','把治理做成使能者：风险相称的分级、安全默认即省事路径、证据自动化而把人留给判断，以及把卡死当作真实成本来算。') },
  { page: 'third-party-model-and-vendor-risk', slug: 'third-party-model-and-vendor-risk', title: L('Third-Party Model &amp; Vendor Risk','第三方模型与供应商风险'), summary: L('The question with teeth is not "is your model safe" but "what can change without telling me": version stability, subprocessor notice and retention terms as the three clauses that decide whether your evals stay true — plus the gateway that gives you all of it without the vendor\'s cooperation.','真正有牙齿的问题不是"你的模型安全吗"，而是"什么可以不通知我就变"：版本稳定性、子处理方通知与留存条款，是决定你的评测还算不算数的三条条款——外加那个不需要供应商配合就能把这一切给你的网关。') },
  { page: 'disclosure-and-content-provenance', slug: 'disclosure-and-content-provenance', title: L('Disclosure &amp; Content Provenance','披露与内容来源'), summary: L('Disclosure is a property of an artifact as it travels, and in an agent topology the person who must be told is rarely where your code is — so put it at one egress layer with a CI test per channel, and accept that text provenance rests on a record you hold, not a watermark a paraphrase removes.','披露是一件产物在流转过程中的属性，而在智能体拓扑里，必须被告知的那个人很少就在你代码所在之处——所以把它放在统一的出口层、每个渠道配一条 CI 测试，并接受：文本的来源依赖的是你握着的一份记录，而不是一个改写就能抹掉的水印。') },
  { page: 'ip-and-copyright-for-agent-output', slug: 'ip-and-copyright-for-agent-output', title: L('IP &amp; Copyright for Agent Output','智能体产出的知识产权与著作权'), summary: L('Whether you can stop others copying the output and whether your vendor will defend you if it infringes are the same variable read from opposite ends — how much human judgement is still in the artifact — so autonomy spends your ownership and your indemnity at once.','你能否阻止别人复制这份产出，与厂商是否会在它侵权时替你辩护，是同一个变量从两头读出来的结果——这份产物里还剩下多少人的判断——所以提高自主性会同时花掉你的所有权和你的赔偿保障。') },
  { page: 'retention-and-legal-hold', slug: 'retention-and-legal-hold', title: L('Retention &amp; Legal Hold for Agent Traces','智能体追踪记录的留存与法务保全'), summary: L('Your tracing platform\'s default TTL is a legal decision an engineer made to control storage cost — and the trap is not the primary store, which you can hold, but the copies: eval golden sets, fine-tuning extracts and vendor-side retention all escape both the deletion request and the hold.','你追踪平台上那个默认 TTL，是一名工程师为了压存储成本而做出的法律决定——而陷阱不在主存储（那个你保全得住），而在副本：评测黄金集、微调抽取与厂商侧留存，既躲过了删除请求，也躲过了法务保全。') },
  { page: 'serious-incident-reporting', slug: 'serious-incident-reporting', title: L('Serious-Incident Reporting','严重事件报告'), summary: L('Live since 2 August 2026, the AI Act\'s two-day track for widespread fundamental-rights infringements is an engineering deadline, not a legal one — the clock starts at the causal link, and sampled traces, rotated model versions and a deployer who is not the provider are what make it unmeetable.','自 2026 年 8 月 2 日起生效，《AI 法案》针对大范围基本权利侵害的两天通道是一条工程期限而非法务期限——时钟从因果关联确立那一刻起跑，而被采样掉的轨迹、轮换过的模型版本，以及"看见损害的部署者并非须申报的提供者"，正是让它无法达成的原因。') },
    { page: 'agent-inventory-and-registry', slug: 'agent-inventory-and-registry', title: L('Agent Inventory &amp; Registry','智能体清单与登记册'), summary: L('Every governance regime opens with "enumerate your AI systems" and almost everyone answers with a voluntary spreadsheet, which omits exactly the agents that carry risk — derive the inventory from credential issuance, the gateway and the bill, make the grant rather than the name the unit of record, and put the register in the issuance path so it cannot drift.','每一套治理规制的开篇都是"把你的 AI 系统列全"，而几乎所有人都用一张靠自愿填写的表格作答——它漏掉的恰恰是那些承载风险的智能体。要从凭据签发、网关与账单三处把清单推导出来，把"授权"而不是"名字"作为记录单元，并把登记册放进签发路径，让它漂移不了。') },
    { page: 'delegated-access-and-consent-records', slug: 'delegated-access-and-consent-records', title: L('Delegated Access &amp; Consent Records','委托访问与同意记录'), summary: L('Connecting a user account creates a token every system stores and a consent almost nobody does — grantor, scope, purpose text, client ID and time — so the questions you will actually be asked are answered by the record you discarded; keep an append-only ledger, stamp its ID on every action, log exercised scope alongside granted scope, and rehearse revocation like a restore because the credential dies while the derived data, the queued job and the downstream effects do not.','连上一个用户账号，会造出一个每个系统都存的令牌，和一份几乎没人存的同意——授权人、范围、用途文本、客户端 ID 与时间——于是你真正会被问到的那些问题，答案都在那份被你丢掉的记录里；请保留一份只追加的台账、把它的 ID 打在每次动作上、把实际行使的范围与被授予的范围一并记录，并像演练恢复那样演练撤销，因为凭据会失效，而派生数据、排队任务与下游后果不会。') },
  ],
};
export default group;
