import { L, type Group } from '../types.ts';

const group: Group = {
  key: 'governance-compliance',
  order: 160,
  name: L('Governance & Compliance', '治理与合规'),
  groupSummary: L('Accountability, audit, policy enforcement and the regulatory landscape — making agent decisions defensible.', '问责、审计、策略执行与监管版图——让智能体的决策可被解释与辩护。'),
  entries: [
  { page: 'audit-trails', slug: 'audit-trails', title: L('Audit Trails & Provenance','审计轨迹与溯源'), summary: L('What to capture to reconstruct any decision, hash-chained tamper-evidence, retention vs erasure, and the four-strand provenance of model, prompt, tools and data.','为重建任何决策该捕获什么、哈希链式防篡改可察觉、保留期与擦除权，以及模型／提示词／工具／数据的四线溯源。') },
  { page: 'policy-enforcement', slug: 'policy-enforcement', title: L('Policy Enforcement & Controls','策略执行与管控'), summary: L('Policy-as-code outside the model, enforcing pre/in/post loop, allowlist-by-default, and separation of duties so a compromised agent cannot close the loop alone.','模型之外的策略即代码、在循环前／内／后执行、默认白名单，以及职责分离使被攻陷的智能体无法独自闭环。') },
  { page: 'regulatory-landscape', slug: 'regulatory-landscape', title: L('The Regulatory Landscape','监管版图'), summary: L('A qualitative map (not legal advice): risk-tiered regulation, documentation and human-oversight duties, the provider/deployer split, and how NIST AI RMF and ISO/IEC 42001 operationalize it.','一张定性地图（不是法律意见）：风险分级监管、文档与人工监督义务、提供方／部署方之分，以及 NIST AI RMF 与 ISO/IEC 42001 如何把它操作化。') },
  { page: 'eu-ai-act-for-agents', slug: 'eu-ai-act-for-agents', title: L('EU AI Act, for agents','欧盟《人工智能法案》——智能体视角'), summary: L('The AI Act\'s risk tiers explained from an agent builder\'s perspective — what triggers high-risk, what general-purpose AI obligations look like, and the dates that matter.','从智能体开发者视角解读《人工智能法案》的风险分层——什么会触发高风险、通用人工智能义务是什么样子，以及关键时间点。') },
  { page: 'nist-ai-rmf-for-agents', slug: 'nist-ai-rmf-for-agents', title: L('NIST AI RMF, for agents','NIST AI RMF——智能体视角'), summary: L('Map / Measure / Manage / Govern read as a checklist for agent teams — what each function actually demands when the system is an autonomous agent rather than a model.','把"映射 / 度量 / 管理 / 治理"四件套当作智能体团队的清单来看——当系统是自主智能体而不仅仅是一个模型时，每个职能真正要求什么。') },
  { page: 'accountability-and-roles', slug: 'accountability-and-roles', title: L('Accountability & Ownership','问责与归属'), summary: L('Accountability never transfers to the agent: the named operator role, RACI on the autonomous action, sign-off that means something, and an accountability ladder set in advance.','问责绝不转移到智能体：具名操作者角色、对自主行动做 RACI、有分量的签字，以及事先设定的问责阶梯。') },
  { page: 'data-governance', slug: 'data-governance', title: L('Data Governance for Agents','智能体的数据治理'), summary: L('An agent is a data-flow machine: lineage through the loop, purpose/consent enforced at point of use, boundary minimization for PII, governed training data, and invisible cross-border flow.','智能体是一台数据流机器：穿过循环的血缘、在使用点执行目的／同意、对 PII 做边界最小化、受治理的训练数据，以及无形的跨境流动。') },
  { page: 'governance-in-practice', slug: 'governance-in-practice', title: L('Governance Without Gridlock','不卡死的治理'), summary: L('Make governance an enabler: risk-proportionate tiers, the safe default as the easy path, automated evidence with humans on judgment, and counting gridlock as a real cost.','把治理做成使能者：风险相称的分级、安全默认即省事路径、证据自动化而把人留给判断，以及把卡死当作真实成本来算。') },
  { page: 'third-party-model-and-vendor-risk', slug: 'third-party-model-and-vendor-risk', title: L('Third-Party Model &amp; Vendor Risk','第三方模型与供应商风险'), summary: L('The question with teeth is not "is your model safe" but "what can change without telling me": version stability, subprocessor notice and retention terms as the three clauses that decide whether your evals stay true — plus the gateway that gives you all of it without the vendor\'s cooperation.','真正有牙齿的问题不是"你的模型安全吗"，而是"什么可以不通知我就变"：版本稳定性、子处理方通知与留存条款，是决定你的评测还算不算数的三条条款——外加那个不需要供应商配合就能把这一切给你的网关。') },
  { page: 'disclosure-and-content-provenance', slug: 'disclosure-and-content-provenance', title: L('Disclosure &amp; Content Provenance','披露与内容来源'), summary: L('Disclosure is a property of an artifact as it travels, and in an agent topology the person who must be told is rarely where your code is — so put it at one egress layer with a CI test per channel, and accept that text provenance rests on a record you hold, not a watermark a paraphrase removes.','披露是一件产物在流转过程中的属性，而在智能体拓扑里，必须被告知的那个人很少就在你代码所在之处——所以把它放在统一的出口层、每个渠道配一条 CI 测试，并接受：文本的来源依赖的是你握着的一份记录，而不是一个改写就能抹掉的水印。') },
  { page: 'ip-and-copyright-for-agent-output', slug: 'ip-and-copyright-for-agent-output', title: L('IP &amp; Copyright for Agent Output','智能体产出的知识产权与著作权'), summary: L('Whether you can stop others copying the output and whether your vendor will defend you if it infringes are the same variable read from opposite ends — how much human judgement is still in the artifact — so autonomy spends your ownership and your indemnity at once.','你能否阻止别人复制这份产出，与厂商是否会在它侵权时替你辩护，是同一个变量从两头读出来的结果——这份产物里还剩下多少人的判断——所以提高自主性会同时花掉你的所有权和你的赔偿保障。') },
  ],
};
export default group;
