import { L, type Group } from '../types.ts';

const group: Group = {
  key: 'safety-and-security',
  order: 50,
  name: L('Safety & Security', '安全与防护'),
  groupSummary: L('Prompt injection, sandboxing, exfiltration, red-teaming, deployment safety — the threat model an agent\'s environment creates.', '提示注入、沙箱、数据外泄、红队、部署安全——智能体环境制造的威胁模型。'),
  entries: [
    { page: 'agentic-threat-model', slug: 'agentic-threat-model', title: L('The Agentic Threat Model','智能体威胁模型'), summary: L('Why autonomy and tool use widen the attack surface, and the four channels attacker-influenced text reaches an agent.','为何自主性与工具使用扩大攻击面，以及攻击者可影响的文本进入智能体的四个通道。') },
    { page: 'prompt-injection', slug: 'prompt-injection', title: L('Prompt Injection: Direct & Indirect','提示词注入：直接与间接'), summary: L('How prompt injection works, why no clean fix exists, and the layered defense pattern for defenders.','提示词注入的机理、为何无干净修复，以及面向防御者的分层防御模式。') },
    { page: 'data-exfiltration-risks', slug: 'data-exfiltration-risks', title: L('Data Exfiltration & Tool Misuse','数据外泄与工具滥用'), summary: L('The confused-deputy pattern in agents: exfiltration sources, hidden sinks, and how to cut the chain.','智能体中的混淆代理模式：外泄的源、隐蔽的汇，以及如何切断攻击链。') },
    { page: 'guardrails', slug: 'guardrails', title: L('Guardrails: Filtering, Sandboxing & Scoping','护栏：过滤、沙箱与作用域'), summary: L('Probabilistic vs deterministic guardrails and how to layer input, output, sandbox and capability controls.','概率性与确定性护栏，以及如何分层输入、输出、沙箱与能力控制。') },
    { page: 'agent-identity', slug: 'agent-identity', title: L('Agent identity','智能体的身份'), summary: L('Who is acting when an agent calls a tool? Service accounts, on-behalf-of patterns, and the audit consequences of getting the answer wrong.','智能体调用工具时，到底是"谁"在动作？服务账号、on-behalf-of 模式，以及把这个答案搞错时的审计后果。') },
    { page: 'scoped-credentials-for-agents', slug: 'scoped-credentials-for-agents', title: L('Scoped credentials for agents','面向智能体的范围受限凭证'), summary: L('Why agents should never hold human-grade credentials — short-lived, narrowly-scoped, per-action tokens, and the failure modes when you try to take shortcuts.','为何智能体绝不该持有人类级别的凭证——短期、范围窄、按动作签发的令牌，以及走捷径时会撞上的失败模式。') },
    { page: 'human-in-the-loop', slug: 'human-in-the-loop', title: L('Human-in-the-Loop & Least Privilege','人在回路与最小权限'), summary: L('Bounded autonomy by design: least privilege as default and consequence-based approval gates.','以设计实现有界自主：以最小权限为默认，并按后果设置审批关卡。') },
    { page: 'safety-red-teaming', slug: 'safety-red-teaming', title: L('Red-Teaming & Safety Evaluation','红队与安全评估'), summary: L('Adversarial testing of agents as a repeatable, outcome-graded pipeline gate, not a one-off session.','把对智能体的对抗性测试做成可重复、按结果评分的流水线关卡，而非一次性演练。') },
    { page: 'alignment-basics', slug: 'alignment-basics', title: L('Alignment Basics: Intent & Oversight','对齐基础：意图与监督'), summary: L('Instruction-following vs intent, reward hacking, and scalable oversight as the practical builder lever.','遵循指令与意图、奖励黑客，以及作为可行杠杆的可扩展监督。') },
    { page: 'deployment-safety-checklist', slug: 'deployment-safety-checklist', title: L('The Pre-Ship Safety Review','上线前安全评审'), summary: L('A practical, fail-closed-first deployment checklist including MCP/third-party supply-chain trust.','一份实用、失败趋关闭优先的部署清单，含 MCP/第三方供应链信任。') },
    { page: 'rag-security', slug: 'rag-security', title: L('RAG Pipeline Security','RAG 管道安全'), summary: L('Why retrieved context is untrusted input that skipped the guard — corpus poisoning, indirect injection, embedding leakage, and the trust-boundary design that contains them.','为何检索上下文是绕过守卫的不可信输入——语料库投毒、间接注入、嵌入泄露，以及遏制它们的信任边界设计。') },
    { page: 'egress-control-for-agents', slug: 'egress-control-for-agents', title: L('Egress Control for Agents','智能体的出站控制'), summary: L('Three labs disclosed models reaching real systems from an eval sandbox in three weeks, and the boundary turned out to be a sentence in the prompt — compute isolation says nothing about routing, a domain allowlist is a scope control rather than a confidentiality one, and the only workable boundary is a proxy scoped to the task.','三周之内三家实验室先后披露模型从评测沙箱触达了真实系统，而那道边界原来只是提示词里的一句话——算力隔离对路由什么也没说，域名允许清单是范围控制而非保密控制，唯一可行的边界是一个按任务收窄的代理。') },
    { page: 'rendering-agent-output-safely', slug: 'rendering-agent-output-safely', title: L('Rendering Agent Output Safely','安全地渲染智能体输出'), summary: L('EchoLeak exfiltrated data from Copilot with no click and no tool call — the model was steered into writing a markdown image and the client fetched it, which means model output is untrusted input to every renderer and the leak happens downstream of every egress control you built.','EchoLeak 把数据从 Copilot 里带走时没有点击、也没有工具调用——模型被诱导写下一张 markdown 图片，客户端把它取了回来；这意味着模型输出对每一个渲染器而言都是不可信输入，而泄漏发生在你所建的每一道出站控制的下游。') },
    { page: 'vulnerability-management-for-agent-platforms', slug: 'vulnerability-management-for-agent-platforms', title: L('Vulnerability Management for Agent Platforms','智能体平台的漏洞管理'), summary: L('The highest-severity bugs in an agent stack arrive with no patch to apply — the vendor fixes them service-side and tells you afterwards — so the asset inventory learns nothing, the scanner cannot confirm remediation, and the only lever that changed your exposure was a credential grant made months before disclosure.','智能体栈里严重度最高的缺陷，到达时没有任何补丁可打——厂商在服务端修好、事后才通知你——于是资产台账学不到东西、扫描器确认不了修复完成；而唯一改变过你暴露面的杠杆，是披露之前几个月做的那次凭据授权。') },
    { page: 'secrets-management-for-agents', slug: 'secrets-management-for-agents', title: L('Secrets Management for Agents','智能体的密钥管理'), summary: L('An agent reads attacker-influenced text on every step, so any secret reachable from inside the loop is one crafted instruction away from a log, a tool argument, or an exfiltration URL — the fix is to move the credential out of the model’s reach entirely and have a broker attach it at the egress boundary, so the model handles the name of a capability and never the secret behind it.','智能体在每一步都读到受攻击者影响的文本，于是任何从循环内部可触及的密钥，都只差一条精心构造的指令，就会进到日志、某个工具参数或一个外泄 URL 里——解法是把凭据彻底移出模型能触及的范围，由一个代理在出口边界处附加它，让模型经手的是能力的名字，而绝非它背后的密钥。') },
  { page: 'denial-of-wallet-and-cost-attacks', slug: 'denial-of-wallet-and-cost-attacks', title: L('Denial of Wallet &amp; Cost Attacks','钱包耗尽与成本攻击'), summary: L('A request-per-second limit stopped bounding your spend the moment one request could fan out into an unbounded loop, so the attacker optimises amplification rather than volume and leaves every latency graph green — attach a money-denominated ceiling to each run, enforce it in the component that issues the calls rather than in a prompt, and watch cost per principal instead of aggregate spend.','当一次请求可以扇出成一个没有上界的循环，每秒请求数限制就不再框得住你的花销了；于是攻击者优化的是放大倍数而不是流量，并且让每一张延迟曲线都保持全绿——给每次运行挂一道以货币计价的上限，在真正发出调用的那个组件里执行、而不是在提示词里，并盯住按主体的成本而不是总花费。') },
  { page: 'permission-aware-retrieval', slug: 'permission-aware-retrieval', title: L('Permission-Aware Retrieval','带权限的检索'), summary: L('Indexing strips the container that carried the access rules, so retrieval becomes the widest read your system performs — and filtering the answer is not a control, because anything the model saw is disclosed and even the count of hidden results leaks. Enforce before the search, store permission keys rather than resolved member lists so revocation lands on the next query, late-bind the few chunks that reach the prompt, and test it with two users and a canary string.','建索引会剥掉承载访问规则的那个容器，于是检索成了你系统里最宽的一次读取——而过滤答案不算控制，因为模型看见的一切都已算披露，连“被隐藏了几条”这个计数本身都在泄漏。请在检索之前强制、存权限键而不是解析后的成员名单以便撤销在下一次查询就生效、对真正进到提示词里的那几个 chunk 做延迟绑定检查，并用两个用户加一条哨兵字符串把它测起来。') },
  ],
};
export default group;
