import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-08-05',
  title: L(
    'Two AI Blog posts on rerankers and the Open Secure AI Alliance, plus five pages on mixture-of-experts, undo, debugging agents, eval cost and IP in agent output',
    '两篇 AI 博客——重排序模型与 Open Secure AI Alliance——外加五个页面：专家混合、撤销、调试智能体、评测成本，以及智能体产出的知识产权',
  ),
  items: [
    L(
      'New blog post — *Cohere vs Voyage vs Jina vs Qwen3: The Retrieval Model You Can Actually Un-Choose*. The mirror image of the embeddings comparison: a reranker writes nothing and touches no index, so swapping one is an afternoon rather than a migration — which finally makes chasing the leaderboard rational, except relevance is the axis where these four differ least (a two-to-four nDCG band that reorders by domain). What differs by more than an order of magnitude is the billing unit. Cohere Rerank 4 charges $0.002–$0.0025 per search regardless of document length; Voyage rerank-2.5 charges $0.05 per million tokens. On a hundred short candidates Voyage is two to five times cheaper; on twenty three-thousand-token sections the order reverses. Also covers the auto-chunking rule that made v3.5\'s "flat" per-search price a per-500-tokens price, why jina-reranker-v3.5 tops the group on BEIR under a CC BY-NC 4.0 licence that excludes commercial use, and why a reranker\'s latency is multiplied by every retrieval in an agent loop — 188ms becomes 7.5 seconds across forty hops, and a second becomes forty. Four themeable SVGs.',
      '新博客文章——《Cohere、Voyage、Jina 与 Qwen3：检索栈里唯一一个你真能反悔的模型》。它是嵌入模型那一篇的镜像：重排序模型什么也不写、也不碰索引，所以换一个只要一个下午而不是一次迁移——这终于让"追排行榜"变得理性了，只可惜相关性恰是这四家差异最小的那条轴（两到四个 nDCG 点的区间，还会随领域重新排序）。真正差出一个数量级以上的是计费单位：Cohere Rerank 4 无视文档长度，每次检索 $0.002–$0.0025；Voyage rerank-2.5 则是每百万令牌 $0.05。在一百个短候选上 Voyage 便宜两到五倍；换成二十个三千令牌的小节，顺序就反过来。文中还讲了那条把 v3.5"平坦"的按次价悄悄变成"每 500 令牌"价的自动切块规则、为何 jina-reranker-v3.5 在 BEIR 上领先全组却挂着一份排除商业用途的 CC BY-NC 4.0 许可证，以及为何重排序模型的延迟会被智能体循环里的每一次检索乘上去——188ms 摊到四十跳就是 7.5 秒，一秒就是四十秒。配四张可随主题变色的 SVG。',
    ),
    L(
      'New blog post — *Agent Security Just Picked a Layer, and It Is the One You Own*. NVIDIA and the Linux Foundation launched the Open Secure AI Alliance on 27 July 2026 with thirty-seven founding members — Microsoft, IBM, Red Hat, Cisco, Cloudflare, CrowdStrike, Hugging Face, LangChain, vLLM among them — and without OpenAI, Google, Anthropic or Meta. The published scope is entirely runtime: identity, permissions, isolation, guardrails, logs, model formats, scanning, the agent harness. The argument is that an alliance can only standardise what its members control, so the split predicts what will and will not get standards; that the model-side members who are present (Mistral, Hugging Face) ship open weights, making the real line artifacts you can inspect versus services you can only call; that the CVE and CVSS machinery it inherits fits sandbox escapes and model-format defects but has nowhere to put prompt injection; and that NVIDIA contributing an agent harness rather than a scanner is a claim that the harness is a security boundary. Three SVGs including the two-layer split and a CVE-fit matrix.',
      '新博客文章——《智能体安全刚刚选定了一层，而那一层归你所有》。NVIDIA 与 Linux Foundation 于 2026 年 7 月 27 日发起 Open Secure AI Alliance，三十七家创始成员——包括 Microsoft、IBM、Red Hat、Cisco、Cloudflare、CrowdStrike、Hugging Face、LangChain、vLLM——而 OpenAI、Google、Anthropic 与 Meta 都不在其中。公布的范围全是运行时：身份、权限、隔离、护栏、日志、模型格式、扫描、智能体外壳。文章主张：一个联盟只能标准化其成员所掌控的东西，所以这道分界预告了什么会有标准、什么不会；在场的模型侧成员（Mistral、Hugging Face）发布的都是开放权重，于是真正的分界是"你能检视的产物"对"你只能调用的服务"；它继承的 CVE 与 CVSS 机制装得下沙箱逃逸与模型格式缺陷，却无处安放提示词注入；而 NVIDIA 贡献的是一个智能体外壳而非一个扫描器，这本身就是在主张外壳是一道安全边界。配三张 SVG，含两层分界图与一张 CVE 适配矩阵。',
    ),
    L(
      'New Concept (AI Foundations) — *Mixture of Experts*. A 400B model can be cheaper per token than a 70B one, which retires parameter count as a proxy for cost. MoE splits the bill: compute follows the parameters that fire per token, memory follows all of them. So the same model is a bargain on a rented API — where you are billed against roughly 13B to 50B active parameters — and an expensive mistake on your own GPUs, where 400B total is about 800 GB at bf16 before any KV cache. Works through the published pairs (Qwen3-235B-A22B, Llama 4 Maverick, Mistral Large 3, DeepSeek-V4), why the saving changes shape with batch size, and the reproducibility wrinkle where per-expert capacity caps make batch composition part of your output.',
      '新增概念页（AI 基础）——《专家混合（MoE）》。一个 4000 亿参数的模型每令牌成本可以低于一个 700 亿的，这让"参数量约等于成本"就此作废。MoE 把账单劈开：算力跟着每个令牌激活的参数走，显存跟着全部参数走。于是同一个模型，在租来的 API 上是笔划算买卖——那里按大约 130 亿到 500 亿的激活参数计价——而在自己的 GPU 上却是一次昂贵的误判：4000 亿总量在 bf16 下约 800 GB，还没算 KV 缓存。文中逐一走了公开的那几对数字（Qwen3-235B-A22B、Llama 4 Maverick、Mistral Large 3、DeepSeek-V4）、这份节省如何随批大小改变形状，以及那个可复现性小坑：当每个专家有容量上限时，批次构成会成为你输出的一部分。',
    ),
    L(
      'New Playbook (Agent UX & Human Interaction) — *Undo & Reversibility*. Teams gate agent actions by asking "is this dangerous?", which produces a product that interrupts constantly and still ships the one action nobody can take back. Sort by cost of reversal instead, and the system boundary rather than the destructiveness of the verb turns out to be the cliff edge. Names three grades of undo — rollback, compensation, mitigation — plus the fourth that is not one, argues that reversibility has a half-life killed by observers rather than by time, and gives the mechanism: a hold window on outbound actions, a revert handle returned by every mutating tool, and undo rendered next to the effect rather than in a settings page.',
      '新增实战手册（智能体体验与人机交互）——《撤销与可逆性》。团队给智能体动作设卡时问的是"这件事危险吗"，结果做出一个不停打断人、却依然放行了那个唯一收不回来的动作的产品。改按撤销代价来排序，你会发现真正的悬崖是系统边界，而不是动词的破坏力。文中命名了撤销的三个等级——回滚、补偿、缓解——以及那个根本不算撤销的第四级；主张可逆性有半衰期，而杀死它的是观察者而非时间；并给出机制：给对外动作加一个延迟窗口、让每个改动型工具返回一个撤销句柄，并把撤销渲染在效果旁边而不是设置页里。',
    ),
    L(
      'New Playbook (Coding & Computer-Use Agents) — *Debugging & Triage Agents*. An agent that reads a stack trace and emits a diff has pattern-matched, not debugged, and will hand you a confident, well-tested, entirely wrong fix for a bug it never observed. Make the failing test the deliverable and the eval criterion becomes machine-checkable, most of the spend moves from generation to observation, and "cannot reproduce" becomes a result you can trust. Covers the three inputs a coding agent never needed (runtime state, history, the ability to re-run), bisection as the loop discipline with an explicit suspect list, triage as a separate cheaper agent that runs first, the read-everything-run-nothing rule for production access, and why reproduction rate and false-repro rate beat merge rate as metrics.',
      '新增实战手册（编码与计算机操作智能体）——《调试与分诊智能体》。一个读完调用栈就吐出 diff 的智能体是在做模式匹配而不是调试，它会为一个自己从未观察过的 bug 递给你一份自信、测试齐备、彻头彻尾错误的修复。把失败的测试定为交付物，评测标准就变得机器可校验，大部分开销从生成挪到观察，而"复现不出来"也成了一个你可以信任的结果。文中讲了编码智能体从不需要的三样输入（运行时状态、历史、重跑的能力）、以显式嫌疑清单支撑的二分循环纪律、作为独立且更便宜、且先跑的分诊智能体、生产环境"什么都能读、什么都别跑"的规则，以及为何复现率与伪复现率作为指标胜过合入率。',
    ),
    L(
      'New Operation (Economics & ROI) — *The Cost of Evaluation*. Eval spend scales with change rate, not traffic, so budgeting it as COGS underfunds exactly the pre-launch phase where change is highest and evaluation decides whether you ship. Its price is set by the smallest regression you insist on catching, and it grows quadratically: from a 90% baseline, catching a ten-point drop needs about 400 runs, five points about 1,400, two points about 7,700, one point about 30,000. Covers what to multiply that by, why paired designs on identical task sets are the saving to take before buying more runs, a three-tier suite so the expensive comparison runs on release candidates only, and which costs shrink with engineering versus which are floors.',
      '新增运维页（经济性与投资回报）——《评测的成本》。评测开销随变更速率而非流量增长，所以把它编进 COGS，恰好会在变更最密集、且评测决定你能否发布的发布前阶段拨不够钱。它的价格由你坚持要抓到的最小回归决定，且按平方增长：以 90% 为基线，抓十个百分点的跌幅约需 400 次运行，五个百分点约 1,400 次，两个百分点约 7,700 次，一个百分点约 30,000 次。文中讲了该拿什么去乘、为何"在同一批任务上做配对设计"是加买运行次数之前就该拿走的那份节省、如何用三层测试集让昂贵的那次比较只在候选发布版上跑，以及哪些成本靠工程能缩、哪些是地板。',
    ),
    L(
      'New Operation (Governance & Compliance) — *IP & Copyright for Agent Output*. "Who owns what the agent produced?" is two questions wearing one sentence, and both answers move with the same variable. Ownership runs through human creative choices — the US requires human authorship case by case, the UK\'s s.9(3) CDPA exception is under active review after the government\'s 18 March 2026 report, and China\'s Beijing Internet Court granted protection in Li v. Liu but has since required evidence of creative effort. Indemnity runs through conditions agents break by construction: enterprise SKU only, safety systems enabled, you did not supply infringing input, you had no reason to know. So autonomy spends your ownership and your indemnity at once, and the one control that pays twice is a record of which human decisions shaped which artifact.',
      '新增运维页（治理与合规）——《智能体产出的知识产权与著作权》。"智能体产出的东西归谁"是两个问题套在一句话里，而两个答案都随同一个变量移动。所有权要穿过人的创作性选择——美国逐案要求人类作者身份；英国 CDPA 第 9(3) 条的例外在政府 2026 年 3 月 18 日的报告之后正被重新审议；中国北京互联网法院在"李某诉刘某"案中给予了保护，但此后要求拿出创作性投入的证据。赔偿保障则要穿过一堆智能体按构造就会违反的条件：仅限企业档位、安全系统须保持启用、你不得提供侵权输入、你不得"本应知道"。于是提高自主性会同时花掉你的所有权和你的赔偿保障，而那个能付两次账的控制手段，是一份"哪些人的哪些决定塑造了哪份产物"的记录。',
    ),
  ],
};

export default entry;
