import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-09-17',
  title: L(
    'Two AI Blog posts — on the enrichment field that fails without leaving evidence, and on the four services that sell you the research loop instead of the documents — plus three pages on scaling laws, the callers your average hides, and seconds as a cost line',
    '两篇 AI 博客——一篇讲那个失效时不留证据的富化字段，一篇讲那四个卖给你研究循环而不是文档的服务——外加三个页面：缩放定律、被你的平均值遮住的那些来电者，以及作为一条成本线的秒',
  ),
  items: [
    L(
      'AI Blog — “CPE is a join key, not a score — NIST is putting an agent inside the NVD”: NIST presented its AI agent enrichment workflow for the National Vulnerability Database on 17 September, five weeks after an RFI that asks which vulnerability tasks suit AI and how AI-driven decisions stay auditable, and after disclosing an unreleased tool called V-etalon. The pressure is real — CVE submissions up 263% from 2020 to 2025, roughly 42,000 records enriched in 2025, and about 29,000 pre-March records reclassified “Not Scheduled” in April. The argument is that enrichment emits three fields with three failure shapes: a wrong CVSS is argued about in a triage meeting, a wrong CWE degrades a corpus over a year, and a wrong CPE returns no rows, because a CPE is a join key and the failure mode of a join is an empty result rather than a wrong answer. So an aggregate accuracy figure conceals which of the three moved, and “90% beats a blank field” is a category error: the blank field is what triggers the fallback to vendor advisories that a present-but-wrong value suppresses. One field fixes it — per-value provenance plus a confidence the API exposes as a filter — and comments close on 13 October.',
      'AI 博客《CPE 是一个连接键，不是一个评分——NIST 正在把一个智能体放进 NVD》：9 月 17 日，NIST 介绍了它为国家漏洞数据库搭建的 AI 智能体富化工作流；五周前那份信息征询问的是哪些漏洞任务适合交给 AI、以及由 AI 驱动的决策如何保持可审计，同时还披露了一款尚未发布、名为 V-etalon 的工具。压力是真实的——CVE 提交量自 2020 至 2025 年上升 263%，2025 年富化了约 42,000 条记录，而 4 月又有约 29,000 条 3 月之前的记录被重划为「未排期」。文章的论证是：富化吐出的三个字段有三种失效形状——CVSS 错了会在分诊会上被争论，CWE 错了会用一年时间劣化一个语料，而 CPE 错了则一行都返回不出来，因为 CPE 是一个连接键，而连接的失效模式是空结果、不是错答案。于是一个总体准确率数字会把「究竟是哪一样动了」藏起来；而「九成总比空字段强」是一次范畴错误：正是那个空字段触发了「退回厂商公告」，而一个有值但错的 CPE 会把它压制掉。一个字段就能修好——逐值的出处，加上一个由 API 暴露为过滤条件的置信度——意见于 10 月 13 日截止。',
    ),
    L(
      'AI Blog — “OpenAI vs Gemini vs Perplexity vs Exa: the research API sells you the loop”: a search API returns documents and leaves the loop in your process; a research API takes the loop, and with it the plan, the query budget, the read/skip decision and the stopping rule — which collapses your eval surface from a trajectory to a final report written by the system you would be debugging. The axis nobody tables is what a citation is: OpenAI and Perplexity return a bibliography, Gemini gives per-claim sourcing, and Exa alone binds grounding to a field in your own outputSchema with a confidence, which is the only shape a downstream record can act on. Corpus is the second split — OpenAI requires at least one data source and takes a search/fetch-shaped MCP server, Gemini takes remote MCP and file search but no custom functions, Perplexity and Exa are the open web — so build-versus-buy is really the question of whether your research corpus is public. And the meters are incommensurable: two for OpenAI, a per-task price with $14/1K search underneath it for Gemini, five for Perplexity including citation and reasoning tokens you never see in advance, one for Exa. All four are jobs rather than calls, so the durable-state work you bought the loop to avoid is still yours.',
      'AI 博客《OpenAI、Gemini、Perplexity 与 Exa：研究 API 卖给你的是那个循环》：搜索 API 返回文档、把循环留在你的进程里；研究 API 把循环拿走了，连同规划、查询预算、「读还是跳过」的决定与停止规则——于是你的评测面从一条轨迹塌缩成一份由你正想调试的那个系统写的最终报告。没人列进表格的那根轴是「引用到底是什么」：OpenAI 与 Perplexity 交还的是一份参考文献，Gemini 给的是按论断的出处，而只有 Exa 把依据绑到你自己 outputSchema 里的某个字段上并附带置信度——那是下游记录唯一能据以行动的形状。语料是第二处分野——OpenAI 要求至少挂一个数据源、并接受一个 search/fetch 形状的 MCP 服务端，Gemini 接远程 MCP 与文件检索但不支持自定义函数，Perplexity 与 Exa 则是公开网络——所以「自建还是购买」真正的问题，是你的研究语料是不是公开的。而那些计量表无法通约：OpenAI 两个，Gemini 是一个按任务价格、底下压着每千次 14 美元的搜索，Perplexity 五个（含你事先根本看不到的引用令牌与推理令牌），Exa 一个。四家全都是作业而不是调用，所以那套你本想靠买下循环来避开的持久状态工作，仍然是你的。',
    ),
    L(
      'Concepts — Scaling Laws: the most famous one was revised in 2022 by more than a factor of ten, and that is the lesson rather than the trivia. Kaplan’s 2020 fit said parameters should outgrow data, and GPT-3 was built on it at about 1.7 tokens per parameter; Chinchilla refitted with models trained to convergence and per-size learning-rate schedules, landed on roughly 20 tokens per parameter, and a 70B model on 1.4T tokens beat a 280B one. What the curve predicts is cross-entropy loss on the pretraining distribution — accurately — and the mapping from loss to task success is measured after the fact, per task, which is why 98% per-step reliability is a 45% success rate over forty steps and why the only honest answer to “will the next model fix this?” is an eval run. Meanwhile the axes that set your bill moved to post-training and inference-time compute, and sparsity broke the parameter-to-cost link entirely. Delete parameter count from your selection criteria and replace it with success at your horizon and cost per completed task.',
      '概念 — 缩放定律：最有名的那一条在 2022 年被修正了十倍以上，而值得记住的是那堂课、不是那条冷知识。Kaplan 2020 年的拟合说参数应当比数据长得更快，GPT-3 正是照它造的，约合每参数 1.7 个令牌；Chinchilla 用「训练到收敛的模型」与「按规模逐一调过的学习率调度」重新拟合，落在每参数约 20 个令牌上，而一个用 1.4 万亿令牌训练的 700 亿参数模型打败了一个 2800 亿的。这条曲线预测的是预训练分布上的交叉熵损失——而且很准——但从损失到任务成功的映射是事后一个任务一个任务测出来的；这正是为什么每步 98% 的可靠性在四十步上是 45% 的成功率，也是为什么「下一个模型会不会把这个修好」唯一诚实的回答是跑一次评测。与此同时，决定你账单的那几根轴已经挪到了后训练与推理期算力上，而稀疏性彻底打断了「参数—成本」的连接。把参数量从选型标准里删掉，换成「在你的任务跨度上的成功率」与「每完成任务成本」。',
    ),
    L(
      'Playbooks — Accessible Voice Agents: your agent does not have a failure rate, it has one per kind of voice, and the cohorts that fail hardest have the fewest alternatives, so their failures arrive as hang-ups and never reach a metric. Recognition is the layer that breaks and the disparity is measured, not speculative — 35% word error rate against 19% for matched conversational speech in the 2020 Koenecke study of five commercial systems, degraded accuracy for accented speech across three major engines in work published this year, and a read-versus-conversational gap for disordered speech that personalisation narrows but does not close. The design defect is endpointing: a 500–800ms silence threshold tuned on fluent speakers fires mid-utterance for anyone who pauses to breathe, to find a word, or because a stammer blocked, and the re-prompt loop that follows is deterministic rather than occasional. Stratify by speech rate rather than by any label about a person, raise the threshold to 1,500ms permanently after the first re-prompt, keep DTMF and a zero-out live at every turn, place one test call through a relay service, and gate the build on worst-cohort over median-cohort success.',
      '实战手册 — 无障碍语音智能体：你的智能体没有一个失败率，它对每一种嗓音各有一个；而失败得最惨的那些人群替代选择最少，于是他们的失败以挂断的形式抵达，永远进不了任何一个指标。坏掉的是识别这一层，而那份差距是被测量出来的、不是猜的——2020 年 Koenecke 对五套商用系统的研究在配对对话语料上测得 35% 对 19% 的词错误率，今年发表的工作在三套主流引擎上测得带口音语音的准确率显著劣化，而言语障碍者在朗读与对话之间的落差，个性化只能收窄、合不上。设计缺陷在端点检测：一个在流利说话者身上调出来的 500–800 毫秒静音阈值，会在任何一个停下来换气、找词、或因口吃卡住的人的话说到一半时触发，而随之而来的重新提示循环是确定发生的、不是偶尔发生的。按语速而不是按任何关于人的标签分层，第一次重新提示之后把阈值永久抬到 1,500 毫秒，让 DTMF 与「按 0 转人工」在每一轮都活着，亲自通过中继服务打一通测试电话，并用「最差人群比中位人群的成功率」给构建设闸。',
    ),
    L(
      'Operations — Pricing Latency: forty seconds of p50 on a task that blocks a $60-an-hour employee costs $0.67 against a four-cent token bill, a sixteen-to-one ratio that has widened every year inference got cheaper — so the cheaper, slower model is a cost increase and the wait is the fourth line missing from your unit economics. The cost is convex: nearly free under a second, linear to about ten, then a step change when the person context-switches away and you start paying a re-entry cost measured in minutes, plus a non-resumption rate nobody instruments. That convexity means budgeting the p95 rather than the mean, and it makes streaming — which removes no latency whatsoever — frequently the largest dollar win available, ahead of buying a faster model. Classify each deployment as blocking-interactive, async, realtime voice or deadline-bound first, because seconds are worth nothing in two of the four, and be honest that skipping verification buys them out of the error bill.',
      '运维 — 给延迟定价：在一个阻塞着时薪 60 美元员工的任务上，40 秒的 p50 要花 0.67 美元，对上四分钱的令牌账单，是十六比一——而推理每便宜一年，这个比值就扩大一分；于是那个更便宜、更慢的模型其实是一次成本上涨，而等待是你的单位经济性里缺掉的第四条线。这笔成本是凸的：一秒以内近乎免费，到大约十秒为止是线性的，然后是一级台阶——人切换到别处去了，你开始支付一笔以分钟计的重新进入成本，外加一个没人插桩的「不再续做率」。凸性意味着该拿 p95 而不是均值做预算，也让根本不削减任何延迟的流式输出，常常成为手边最大的一笔美元收益，排在「买一个更快的模型」前面。先把每个部署归类成阻塞式交互、异步、实时语音或有截止期限，因为四种里有两种秒数根本不值钱；并且要诚实：跳过校验换来的秒数，是从错误账单里买的。',
    ),
  ],
};

export default entry;
