import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-08-24',
  title: L(
    'Two AI Blog posts on agent skill scanners being read around and on picking a graph store for agent memory, plus three pages on vulnerability remediation, denial of wallet and embedding migrations',
    '两篇 AI 博客——技能扫描器被绕着读，以及为智能体记忆挑图存储——外加三个页面：漏洞修复、钱包耗尽，以及向量模型迁移',
  ),
  items: [
    L(
      'New blog post — *Skill scanners read a different file than the agent runs*. Three results across eleven weeks say the same thing: Trail of Bits bypassed the detectors on ClawHub, Cisco AI Defense and the three scanners wired into Vercel\'s skills.sh on 3 June, with three of its four bypasses built in under an hour each; a Cloud Security Alliance note on 10 June found eight open-source scanners bypassed across the board; and the July SkillCloak work packed 1,613 in-the-wild malicious skills so that self-extracting packing cleared every one of eight scanners more than 90% of the time while the payloads still executed correctly in Claude Code and Codex. On 17 August OWASP gave the finding a number, listing poor scanning (AST08) and update drift (AST07) in the first Agentic Skills Top 10. Argues the mechanism is a parser differential — a skill is prose that only becomes a program when a model reads it, so the scanner inspects the bundle at rest while the agent constructs something else at run time by unpacking an archive, importing bytecode or fetching a URL — compounded by LLM scanners being prompt-injectable (one bypass simply framed a malicious registry config as an enterprise requirement and got it downgraded to low) and by verdicts that expire on the next update. Concludes the checkmark is the product defect, since it converts unknown into approved on a registry that a February audit found roughly one in eight malicious, and prescribes scanning for inventory, pinning by content hash, and putting the control you rely on at run time where it binds capability instead of appearance. Three themeable SVGs.',
      '新博客文章——《技能扫描器读的文件，和智能体真正运行的那个不是同一份》。十一周内的三项结果说的是同一件事：6 月 3 日，Trail of Bits 绕过了 ClawHub、Cisco AI Defense 以及接入 Vercel skills.sh 的那三个扫描器，其四种绕过中有三种每种不到一小时就做了出来；6 月 10 日云安全联盟的一份简报发现八个开源扫描器全线被绕；7 月的 SkillCloak 工作把 1,613 个在野恶意技能打了包，自解压式打包对八个扫描器中的每一个绕过率都超过 90%，而载荷在 Claude Code 与 Codex 里照样正确执行。8 月 17 日，OWASP 给这个结论编上了号：首版《Agentic Skills Top 10》里列有"扫描不力"（AST08）与"更新漂移"（AST07）。文章论证其机制是一处解析器差异——技能是散文，只有当模型读到它时才变成程序，于是扫描器检查的是静止的包，而智能体在运行时通过解压压缩包、导入字节码或去取一个 URL，构造出了另一样东西——再叠加上"LLM 扫描器本身可被提示注入"（有一种绕过只是把恶意的仓库配置说成企业要求，就把它降成了低危），以及判定会在下一次更新时过期。结论是那个对勾才是产品缺陷，因为它在一个 2 月审计发现约八分之一为恶意的注册表上，把"未知"转换成了"已批准"；处方是：扫描用来做清单、按内容哈希锁定，并把你真正倚仗的控制放到运行时，让它约束能力而不是外观。配三张可随主题变色的 SVG。',
    ),
    L(
      'New blog post — *Neo4j vs Memgraph vs FalkorDB vs LadybugDB: picking a graph store for agent memory*. Every performance number published about these four was authored by one of the vendors — FalkorDB\'s 55ms-versus-577ms median against Neo4j, Memgraph\'s 114× throughput claim — on workloads those vendors designed, and all of them measure reads against a statically loaded graph while agent memory is a concurrent-write workload with a read latency budget. Compares what is actually checkable: licence (GPLv3 open core, BSL 1.1, SSPLv1, MIT), deployment shape, write-path concurrency, and whether a memory framework already ships a driver — which produces the inversion the piece is built on, since SSPL-licensed FalkorDB is the default backend of the Graphiti MCP server while MIT-licensed LadybugDB, the only genuinely in-process engine here, has no first-party driver anywhere and a single-read-write-process rule that disqualifies it from shared multi-tenant memory. Uses the Kuzu timeline as the cautionary case — archived October 2025, the Apple acquisition surfacing only in a February 2026 EU filing, three forks of which one is alive, and Graphiti deprecating its driver with "the upstream Kuzu project is no longer maintained" — to argue that maintenance trajectory and governance are technical constraints on a store that holds accumulating state. Includes the honest cost caveat that Microsoft\'s widely-quoted GraphRAG cost ratios come from a November 2024 post. Three SVGs.',
      '新博客文章——《Neo4j vs Memgraph vs FalkorDB vs LadybugDB：为智能体记忆挑一个图存储》。关于这四者发布过的每一个性能数字，都由某家厂商自己撰写——FalkorDB 对比 Neo4j 的中位数 55 毫秒对 577 毫秒、Memgraph 的 114 倍吞吐主张——跑的都是那些厂商自己设计的负载，而它们测的全是对一个一次性加载好的图做读，可智能体记忆是一种带读延迟预算的并发写负载。文章比较真正可核验的几件事：许可证（GPLv3 开放核心、BSL 1.1、SSPLv1、MIT）、部署形态、写入路径并发，以及记忆框架有没有现成驱动——由此得出全篇所依托的那处倒置：以 SSPL 发布的 FalkorDB 是 Graphiti MCP 服务器的默认后端，而 MIT 许可、也是这里唯一真正进程内的 LadybugDB，在任何地方都没有第一方驱动，且"单个读写进程"的规则让它在共享多租户记忆上出局。文章用 Kuzu 的时间线作为警示案例——2025 年 10 月归档、苹果收购直到 2026 年 2 月才从欧盟备案里浮现、三个分叉里只有一个活着、Graphiti 以"上游 Kuzu 项目已不再维护"为由弃用了自家驱动——论证对一个装着不断累积状态的存储而言，维护走向与治理都是技术约束。文中还诚实标注：被广泛引用的微软 GraphRAG 成本比例出自一篇 2024 年 11 月的博文。配三张 SVG。',
    ),
    L(
      'New Playbook (Coding &amp; Computer-Use Agents) — *Vulnerability Remediation Agents*. Generating a patch is the cheap half: across roughly six thousand model-written patches for post-cutoff CVEs, about 26% fixed the bug without changing behaviour, about 20% fixed it and changed behaviour, and about 54% failed or introduced a new problem, with roughly half leaving an existing exploit path open — while the PVBench work found more than 40% of patches that pass the obvious validation (functional tests plus the PoC) fail under mutated exploit variants, and for about 28% of vulnerabilities every patch produced was a false positive. Argues the deliverable is therefore evidence, not a diff: triage on reachability, EPSS and KEV before generating anything (only around 6% of published CVEs are ever observed exploited), build the reproduction first so "cannot reproduce" becomes a legitimate cheap ending, spend model budget on root cause rather than patch attempts (fix rates run ~65% with correct guidance and collapse to ~15% with incorrect guidance), and ship a bundle carrying the call path, the failing-then-passing test, the variant results and the behaviour delta. Closes on the merge queue as the throttle and on curl ending its bounty in January and HackerOne pausing the IBB in March: send a patch and a reproduction, or send nothing.',
      '新增实战手册（编码与计算机操作智能体）——《漏洞修复智能体》。写补丁是便宜的那一半：在针对训练截止之后 CVE 生成的约六千个模型补丁里，约 26% 在不改变行为的前提下修好了问题，约 20% 修好了但改了行为，约 54% 没修好或引入了新问题，其中约一半还留着一条既有的可利用路径没堵——而 PVBench 的工作发现，通过了那条显而易见的校验（功能测试加 PoC）的补丁里，超过 40% 在变异过的利用变体下失败，且约 28% 的漏洞上产出的每一个补丁都是假阳性。文章据此论证交付物是证据而不是 diff：在生成任何东西之前先按可达性、EPSS 与 KEV 分诊（已公布的 CVE 中仅约 6% 曾被观测到在野利用），先把复现建起来，好让"复现不出来"成为一个正当且廉价的结局；把模型预算花在根因而不是多试补丁上（有正确引导时修复率约 65%，引导错误时暴跌到约 15%）；并交付一个带调用路径、"打补丁前失败/打补丁后通过"的测试、变体结果与行为差异的证据包。文末落在"合并队列才是节流阀"，以及 curl 在 1 月关掉赏金、HackerOne 在 3 月暂停 IBB 这两件事：要么发补丁加复现，要么什么都别发。',
    ),
    L(
      'New Operation (Safety &amp; Security) — *Denial of Wallet: when your bill is the attack surface*. A request-per-second limit works as a cost control only because a conventional request has a roughly constant cost, and an agent voids that premise — one request fans out into however many model calls, tool calls, retries and sub-agents the loop decides on, so the attacker optimises the amplification ratio rather than volume and every latency graph stays green while the damage lands on an invoice or an exhausted quota. Enumerates the multiplicative amplifiers (loop depth, superlinear context growth, invisible reasoning tokens, sub-agent fan-out, stacked retries, deliberate cache-prefix busting), names free tiers and third-party triggers as the cheap entry points, and treats prompt injection as a cost attack that needs no forbidden request — "search each of these fifty terms" is a complete attack, which is why the ceiling cannot live in a prompt. Prescribes a money-denominated budget per run enforced in the component that issues the calls, admission control before the expensive path, degrade-before-deny, a per-principal ceiling kept separate from the global kill switch, and detection on cost per inbound request at p99 and cost per principal — since throttling the service instead of the principal hands the attacker the outage they could not achieve directly.',
      '新增运维页（安全与防护）——《钱包耗尽：当账单成为攻击面》。每秒请求数限制之所以能当成本控制用，只是因为常规请求的成本大致恒定，而智能体作废了这个前提——一次请求会扇出成循环认为需要的任意多次模型调用、工具调用、重试与子智能体，于是攻击者优化的是放大倍数而不是流量，所有延迟曲线保持全绿，伤害却落在一张发票或一份耗尽的配额上。文章逐项列出相乘的放大因子（循环深度、超线性的上下文增长、看不见的推理 token、子智能体扇出、层层叠加的重试、故意打掉缓存前缀），点名免费档位与第三方触发器是最廉价的入口，并把提示注入当作一种不需要索要任何违禁内容的成本攻击——"把下面这五十个词分别搜一遍"就是一次完整的攻击，这也正是上限不能住在提示词里的原因。处方是：每次运行一道以货币计价的预算，由真正发出调用的那个组件强制执行；在昂贵路径之前做准入控制；先降级再拒绝；把按主体的上限与全局急停分开；并对"每次入站请求成本的 p99"与"按主体的成本"做检测——因为去节流整个服务而不是那个主体，等于把攻击者直接办不到的那场停机送给他。',
    ),
    L(
      'New Operation (AgentOps) — *Re-indexing &amp; Embedding Migrations*. An embedding model is a schema with no in-place migration: two models occupy different coordinate systems, a mixed index returns confident nonsense rather than an error, and so there is no canary, no dual-read and no partial cutover — only a complete second index, double storage, and an atomic switch with a rollback that is free only while the old index survives. Notes the trigger is usually external (a retired endpoint, a changed chunker, a residency requirement, a corpus that outgrew the model), so the real requirement is being able to rebuild from source on demand. Names the failure that ruins attribution: between the first build and the rebuild, the chunker, the cleaning rules and the document set all drifted, so the quality delta belongs to no single variable — fixed by versioning the whole pipeline onto every vector, keeping raw sources rather than chunks, changing one variable per rebuild, and rehearsing a rebuild quarterly. Adds that agent memory has no quiescent window, so the migration is a dual-write with a checkpointed backfill and a reconciliation before cutover, and that the cutover decision belongs to a frozen production query set scored on retrieval per segment, not on end-to-end answers in aggregate.',
      '新增运维页（AgentOps）——《重建索引与向量模型迁移》。向量模型是一份没有原地迁移路径的 schema：两个模型身处不同的坐标系，混合索引返回的是笃定的胡话而不是一个错误，于是没有灰度、没有双读、没有部分切换——只有一套完整的第二索引、双倍存储，以及一次原子切换，而回滚只在旧索引还活着时才免费。文章指出触发时机通常来自外部（端点下线、切块器改了、数据驻留要求、语料长大到模型不再匹配），所以真正的要求是能够按需从源头重建。文中点名那个毁掉归因的失败：在第一次构建与这次重建之间，切块器、清洗规则与文档集合全都漂移了，于是质量差值不归属于任何单一变量——解法是把整条流水线的版本盖在每一个向量上、留着原始源文件而不只是块、每次重建只改一个变量，并每季度演练一次重建。文章还补充：智能体记忆没有安静窗口，所以迁移必须是双写加带检查点的回填，并在切换前对账；而切换与否的决定，应交给一套冻结的生产查询集，按分段对检索本身打分，而不是看聚合的端到端答案。',
    ),
  ],
};

export default entry;
