import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-08-26',
  title: L(
    'Two AI Blog posts on what Microsoft charges for agent governance and on what you are really buying in a voice-agent test suite, plus three pages on bot verification, accessible agent interfaces and multi-agent credit assignment',
    '两篇 AI 博客——微软为智能体治理收的到底是什么费，以及一套语音智能体测试套件你真正买到的是什么——外加三个页面：机器人验证、无障碍的智能体界面，以及多智能体的功劳分配',
  ),
  items: [
    L(
      'New blog post — *Microsoft priced agent governance per human; your fleet has no meter*. Agent 365 went generally available on 1 May 2026 at $15 per user per month, or inside Microsoft 365 E7 at $99, and the licence is per person — the human who owns, sponsors, manages or is served by an agent — with no per-agent fee at all. Works the arithmetic for a 500-seat tenant: $7,500 a month whether you run 50 agents or 5,000, which is $150 each or $1.50 each, and nothing on the invoice distinguishes the two. Grants that per-seat is the right call for adoption, since charging per agent would tax the disclosure the registry depends on, then names what the choice costs: cost was the only fleet-size feedback most organisations ever had, and an agent built for a campaign that ended in March now keeps its identity and permissions indefinitely without producing a signal anywhere in finance. Two further mismatches: the licensing unit assumes every agent has a human sponsor, which is false for the scheduled job, the service-account agent, the sub-agent and the partner agent arriving over A2A — Microsoft keeps those in a separate Frontier preview priced per agent instance with GA pricing unannounced — and the Shadow AI discovery view, which found the unmanaged local agent, reaches only Intune-enrolled Windows, so the inventory\'s completeness is bounded by device-enrolment coverage. Prescribes an owner and an expiry on every registered agent, enrolment coverage published beside the agent count, and a budget line for the per-instance meter now. Three themeable SVGs.',
      '新博客文章——《微软把智能体治理按人头定价，于是你的机群没有一块计价表》。Agent 365 已于 2026 年 5 月 1 日正式上市，每用户每月 15 美元，或包含在每用户每月 99 美元的 Microsoft 365 E7 里；授权按人计——那个拥有、担保、管理智能体或被智能体服务的人——完全不按智能体收费。文章为一个 500 席位租户把账算了出来：无论你跑 50 个还是 5000 个智能体，都是每月 7500 美元，也就是每个 150 美元或每个 1.5 美元，而账单上没有任何东西能把这两种处境区分开。文中承认按席位计价对推广而言是正确选择——按智能体收费等于向注册表所依赖的"如实申报"征税——随后点名这个选择的代价：成本是多数组织唯一拥有过的机群规模反馈，而一个为三月就结束的活动而建的智能体，如今会无限期保留它的身份与权限，却不在财务的任何角落激起一丝涟漪。另有两处对不齐：计费单元假设每个智能体都有一位人类担保人，而这对定时任务、服务账号智能体、子智能体以及经 A2A 抵达的合作方智能体都不成立——微软把这些留在一个按智能体实例计价、正式价格尚未公布的 Frontier 预览里——而那个发现了未纳管本地智能体的 Shadow AI 视图，只够得着已在 Intune 注册的 Windows，于是清单的完整度被设备注册覆盖率封了顶。处方是：每个在册智能体都配负责人与到期日、把设备注册覆盖率与智能体计数并排公布，以及现在就为按实例的那块计价表留一条预算。配三张可随主题变色的 SVG。',
    ),
    L(
      'New blog post — *Coval vs Hamming vs Cekura vs Bluejay: you are buying a simulated caller*. The argument is that a voice-agent suite does not measure your agent, it measures your agent against a caller somebody generated, so the realism of that caller is the ceiling on everything the suite can report — which makes the number all four lead with, concurrent simulations, the axis that matters least. Sorts them by where the test caller comes from: generated personas that can only exhibit the failures you already thought of, replayed production audio that carries the accents and cross-talk you did not know to write down, a pinned CI suite from Coval\'s autonomous-vehicle lineage where the value is longitudinal rather than realistic, and Cekura\'s cheap high-volume generation. Reads pricing as a coverage constraint rather than a budget one: Cekura publishes from $30 a month at roughly five credits per voice minute, about twenty cents for a one-minute call, while Coval publishes $100 / $500 / from $4,500 and Hamming and Bluejay are sales-led — and only a computable unit price lets you decide to run the four-hundredth variation of the scenario that keeps failing. Argues the scoring problem is separate from the simulation problem, with Hamming\'s audio-native evaluation and Cekura\'s rule-based Conditional Actions answering the same judge-flakiness complaint from opposite ends, and prescribes splitting deterministic assertions on barge-in, endpointing, latency and DTMF from a judge used only on content. States plainly that most head-to-head pages in this category are published by one of the four. Three SVGs.',
      '新博客文章——《Coval vs Hamming vs Cekura vs Bluejay：你买的是一位模拟来电者》。核心论点是：语音智能体测试套件量的不是你的智能体，而是你的智能体面对一位由别人生成出来的来电者时的表现，于是那位来电者有多真实，就是这套测试所能报告的一切的上限——这也让四家都主推的那个数字（并发模拟量）成了最不重要的那条轴。文章按"测试来电者从哪儿来"给它们分类：只能表现出你已经想到过的失败的生成人设、承载着你不知道该写下来的口音与抢话的生产音频回放、来自 Coval 自动驾驶血统、价值在纵向而非真实度的钉住式 CI 套件，以及 Cekura 便宜的大批量生成。文中把定价读成覆盖度约束而不是预算约束：Cekura 公开每月 30 美元起、语音约每分钟 5 积分，折合一通一分钟通话约两毛美元；Coval 公开 100 / 500 / 4500 美元起；Hamming 与 Bluejay 则是销售驱动——而只有一个能自行计算的单价，才让你有底气去把那个总是失败的场景跑上第四百个变体。文章论证打分问题与仿真问题是两码事，Hamming 的音频原生评测与 Cekura 基于规则的 Conditional Actions，是从相反两端回应同一个"评审不稳"的抱怨，并给出处方：把插话打断、断句、延迟与 DTMF 上的确定性断言，与只用于内容的评审劈开。文中明说这一品类里多数正面对比页都由这四家之一自己发布。配三张 SVG。',
    ),
    L(
      'New Concept (AI Ecosystem) — *Bot Verification &amp; Agent Web Access*. The web spent thirty years guessing who was knocking and has started checking signatures, and the practical consequence is that an agent\'s cryptographic identity is now a retrieval-quality setting. Separates the three regimes that keep getting confused: robots.txt is a request with no enforcement, llms.txt sits around 10% adoption with no major provider consuming it in production as of early 2026, and edge enforcement is the only layer with teeth — Cloudflare now blocks AI crawlers by default on new domains, returns more than a billion 402 responses a day across its network, and from 15 September 2026 blocks mixed-use crawlers from ad-bearing pages by default. Explains Web Bot Auth as an IETF draft built on RFC 9421 HTTP Message Signatures with implementations at Cloudflare, Akamai, AWS WAF, Vercel and Shopify and adoption under agent-payment work, and is precise that a signature is an accountability primitive rather than an authorization one. The load-bearing section is what unverified traffic actually meets — a challenge page returned as 200, a stale cache, a thinner document, rate limiting that only bites on the eleventh call — all of which parse, making this a grounding failure your evals will miss. Closes on signing with one key per purpose, making blocked-and-degraded its own failure class, and asserting on content invariants rather than HTTP status.',
      '新增概念页（AI 生态）——《机器人验证与智能体的网页访问权》。互联网花了三十年去猜敲门的是谁，如今开始核验签名，其实际后果是：智能体的密码学身份成了一项检索质量设置。文章把三套总被混为一谈的机制分开：robots.txt 是一份没有任何强制力的请求；llms.txt 采用率约在 10% 上下，且截至 2026 年初没有主要厂商在生产中消费它；边缘强制是唯一长着牙的一层——Cloudflare 如今对新域名默认阻止 AI 爬虫，其网络每天返回超过十亿次 402，并自 2026 年 9 月 15 日起默认阻止混合用途爬虫访问带广告的页面。文中解释 Web Bot Auth 是建立在 RFC 9421 HTTP 消息签名之上的 IETF 草案，已有 Cloudflare、Akamai、AWS WAF、Vercel 与 Shopify 的实现，并被智能体支付工作采纳为基座，同时精确指出：签名是问责原语，不是授权原语。最吃重的一节是未经验证的流量实际会遇到什么——以 200 返回的挑战页、过期缓存、更薄的文档、只在第十一次调用才咬人的限速——它们统统都能被解析，于是这成了一次你的评测会漏掉的接地失败。文末落在：签名且一个用途一把密钥、把"被拦与被降级"设成独立的失败类别，以及断言内容不变式而不是断言 HTTP 状态码。',
    ),
    L(
      'New Playbook (Agent UX &amp; Human Interaction) — *Accessible Agent Interfaces*. Every failure that matters here is timing rather than markup, which is why an agent UI can pass every automated check and still be undrivable with a screen reader: assistive technology assumes a page that settles, and an agent produces one that never does. Names the single most common defect — wiring the streaming answer itself to aria-live, which makes the interface talk over its own user for forty seconds — and replaces it with a terse status region that announces at semantic boundaries plus an answer region that is a document with an explicit completion signal. Treats the approval dialog as the place where safety and accessibility genuinely collide, and rules out auto-approval countdowns on irreversible actions as a decision made by a stopwatch that discriminates precisely against whoever reads most slowly. Covers the rest of the clocks (interruption windows, voice endpointing thresholds as an accessibility setting, idle timeouts, auto-scroll, reduced motion), argues that run-to-run non-determinism is a cognitive-accessibility problem answered by fixed landmarks and a stable action vocabulary the model does not get to name, and closes on testing behaviourally — one real run with a screen reader and the monitor off, a keyboard-only approve-and-undo cycle, and the announcement sequence snapshotted as a CI fixture.',
      '新增实战手册（智能体体验与人机交互）——《无障碍的智能体界面》。这里真正要紧的失败没有一样是标记，全是时序——这正是一个智能体界面可以通过每一项自动化检查、却依然没法用读屏软件驾驶的原因：辅助技术假定页面会安定下来，而智能体产出的页面从不安定。文章点名了最常见的那个缺陷——把流式答案本身接到 aria-live 上，于是界面连着四十秒盖过自己的用户说话——并用一块在语义边界上播报的简练状态区，加上一个带显式完成信号、本质是文档的答案区来替代它。文中把审批弹窗视作安全与无障碍真正冲突的地方，并否决了给不可逆动作装自动批准倒计时：那是一块秒表做出的决定，且精确地歧视了读得最慢的那批人。其余的"钟"也一并覆盖（中断窗口、作为无障碍设置的语音断句阈值、空闲超时、自动滚动、减少动效），并论证逐次运行的非确定性是一个认知无障碍问题，其答案是固定的地标与一套不许模型来命名的稳定动作词汇。文末落在行为化测试——关掉显示器用读屏软件跑一次真实运行、只用键盘完成一次"批准并撤销"循环，以及把播报序列快照成 CI 固件。',
    ),
    L(
      'New Deep-Dive (Multi-Agent Systems) — *Credit Assignment: Which Agent Do You Change?*. A failed multi-agent run hands you one number and eight components, and that number contains no gradient, so teams reach for per-agent judges and then act on the result as though it were causal. Names the problem properly as credit assignment borrowed from RL — which solves it with millions of episodes and a value function, against your forty traces and a person — and lays out the three available estimators as answers to three different questions: per-agent judges measure local quality and systematically exonerate every component of a coordination failure, ablation measures marginal contribution causally but needs a power calculation most teams never do before a four-point delta against an eight-point noise floor gets reported as a contribution, and counterfactual replay answers specific causation but requires traces stored as a replay log and a resumable environment. Closes with the protocol that actually works at forty traces: hand-mark the first divergence across twenty failed traces, cluster before fixing, re-run the same twenty to watch the divergence point move, escalate to an estimator only for the question you now have, and never act on a per-agent score as if it were causal.',
      '新增深入解析（多智能体系统）——《功劳分配：你到底该改哪个智能体？》。一次失败的多智能体运行交给你一个数字和八个组件，而那个数字里没有梯度，于是团队伸手去拿逐智能体评审，然后把结果当作因果去行动。文章把问题的名字叫对——这是借自强化学习的功劳分配，而强化学习用数百万幕和一个价值函数来解它，你手上却只有四十条轨迹和一个人——并把三个可用的估计量摆成对三个不同问题的回答：逐智能体评审量的是局部质量，会系统性地为一次协作失败赦免全部组件；消融以因果方式量边际贡献，但需要一次多数团队从不去做的功效计算，否则噪声底八个点、差值四个点也会被写成"贡献"；反事实回放回答具体因果，但要求轨迹被存成重放日志、环境可恢复。文末给出在四十条轨迹这个量级上真正管用的流程：手工标注二十条失败轨迹的第一处偏离、先聚类再动手修、重跑同样的二十条去看偏离点有没有移动、只为你此刻真正持有的那个问题才升级到估计量，以及永远不要把逐智能体分数当作因果去行动。',
    ),
  ],
};

export default entry;
