import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-08-21',
  title: L(
    'Two AI Blog posts on Stripe buying the AI meter rather than the router and on which text-to-speech number actually decides a phone call, plus three pages on AI gateways, online experiments and collections agents',
    '两篇 AI 博客——Stripe 买下的是 AI 计量器而不是路由器，以及语音合成里到底哪个数字决定一通电话——外加三个页面：AI 网关、线上实验，以及催收智能体',
  ),
  items: [
    L(
      'New blog post — *Stripe bought the meter, not the router*. Bloomberg reported on 16 August 2026 that Stripe was closing on OpenRouter for more than $7 billion, and Stripe confirmed the agreement days later without disclosing terms — seven months after completing its acquisition of the usage-metering vendor Metronome. Argues the priced asset is the ledger rather than the routing: of the five separable jobs an AI gateway does (routing and failover, key custody, caching, policy, metering with attribution) only the last is hard to rebuild, because it means normalising usage across providers that report it differently, joining spend to run, tenant and outcome, and being able to refuse the next call rather than email a report. Works the numbers behind the deal (400-plus models, roughly 25 trillion tokens routed a week by mid-2026 against about 5 trillion six months earlier, an approximately 5% take on inference spend, a $113M Series B in May at a reported $1.3B) and then the arithmetic that matters to builders: a percentage take is a levy on loop depth, largest on the runs that failed and retried, so buying cost control priced as a percentage of cost hires an auditor whose fee rises when the audit fails. Steelmans the deal, then prescribes deciding data plane versus control plane, keeping your own provider accounts, and testing the bypass on a schedule. Three themeable SVGs.',
      '新博客文章——《Stripe 买下的是计量器，不是路由器》。彭博社 2026 年 8 月 16 日报道，Stripe 正以超过 70 亿美元敲定对 OpenRouter 的收购，数日后 Stripe 确认达成协议但未披露条款——而这距它完成收购用量计量厂商 Metronome 才过去七个月。文章论证被定价的资产是那本账而不是路由：AI 网关做的五件可拆分差事（路由与故障转移、密钥托管、缓存、策略、带归因的计量）里，只有最后一件难以自建，因为它意味着把各家口径不一的用量归一化、把支出接到运行、租户与结果上，并且要能拦下下一次调用而不只是发一封报表邮件。文章摆出交易背后的数字（400 多个模型、到 2026 年年中每周约 25 万亿令牌而半年前约 5 万亿、对推理支出抽约 5%、5 月完成的 1.13 亿美元 B 轮据报估值 13 亿），随后给出真正与开发者相关的那笔算术：按比例抽成是对循环深度征的税，而它在失败重试的运行上收得最多——所以把成本控制按"成本的百分之几"买下来，等于雇了一位在审计失败时报酬更高的审计。文章为这笔交易做了最强的正面论证，随后开出处方：先分清这是数据面还是控制面采购、保留你自己名下的提供方账号，并按计划定期演练旁路。配三张可随主题变色的 SVG。',
    ),
    L(
      'New blog post — *ElevenLabs vs Cartesia vs Deepgram vs Rime: buy the tail, not the average*. Four text-to-speech vendors advertise time-to-first-audio between roughly 40 and 200 ms, while an independent 2026 harness measured their cloud medians at 188 ms (Cartesia Sonic-3, with about 100 ms of interquartile spread), 264 and 288 ms (ElevenLabs Turbo and Flash v2.5, about 28 ms each) and 313 ms (Deepgram Aura-2, about 68 ms). Argues the deciding number is the spread rather than the median, because a voice turn composes endpointing, model first token, synthesis and a 200–400 ms jitter buffer against a roughly 300 ms conversational threshold — so a tighter distribution at a worse median never surprises the caller. Adds the two barge-in consequences no comparison chart carries: effective latency on an interrupted turn is cancel-to-silence rather than first-audio, and character billing means you pay for speech nobody heard, with whether you pay decided by a contract clause rather than a benchmark. Notes list pricing clusters around $0.02–$0.05 per thousand characters and predicts neither latency nor consistency, then lands on deployment as the only lever that moves the tail by an order of magnitude — Rime on-prem generally available as containers, Deepgram self-hosted with two dedicated GPUs per TTS engine, Cartesia on-prem in early access at a seven-figure commit, ElevenLabs cloud-first. Three SVGs.',
      '新博客文章——《ElevenLabs vs Cartesia vs Deepgram vs Rime：买的是长尾，不是平均值》。四家语音合成厂商宣称的首字节音频时延在大约 40 到 200 毫秒之间，而 2026 年一份独立测试台量到的云端中位数是：188 毫秒（Cartesia Sonic-3，四分位距约 100 毫秒）、264 与 288 毫秒（ElevenLabs Turbo 与 Flash v2.5，各约 28 毫秒）、313 毫秒（Deepgram Aura-2，约 68 毫秒）。文章论证起决定作用的是离散度而不是中位数：一次语音轮次由断句判定、模型首令牌、合成与 200–400 毫秒的抖动缓冲叠成，而对面是大约 300 毫秒的对话临界线——所以"中位数更差但分布更紧"的那家，从不让来电者感到意外。文章还补上了对比表从不写的两个打断后果：被打断轮次的有效延迟是"取消到静音"而不是首字节音频；以及按字符计费意味着你为没人听见的语音付了钱，而付不付由一条合同条款而非任何跑分决定。文中指出标价集中在每千字符 0.02–0.05 美元，且既预测不了延迟也预测不了稳定性，最后落在部署方式——唯一能把长尾挪动一个数量级的杠杆：Rime 本地部署已以容器形式正式可用，Deepgram 自托管需每个 TTS 引擎两块专用 GPU，Cartesia 本地部署处于早期开放且需七位数承诺额，ElevenLabs 则云优先。配三张 SVG。',
    ),
    L(
      'New Concept (AI Ecosystem) — *AI Gateways*. Names the five separable jobs sold under one product name and argues only metering with attribution is genuinely hard to rebuild — so the question to settle before comparing vendors is which jobs you want in the request path. Prices the hop honestly: availability multiplies down (99.9% in front of 99.9% is about 99.8%), 10–50 ms of proxy overhead disappears in a chat response and does not disappear in a twenty-step loop or a voice turn, and a percentage of spend is a per-step tax that arrives exactly when agent adoption works. Notes that untested failover is a configuration rather than a capability, since prompts are not as portable across vendors as gateway marketing implies. Closes on the shape few teams consider — direct provider calls for the data plane, the gateway as a control plane reading telemetry you already emit — plus the three properties that keep an exit open: an OpenAI-compatible surface on both sides, your own provider accounts for the models you depend on, and a bypass exercised on a schedule.',
      '新增概念页（AI 生态）——《AI 网关》。文章点名了被装进同一个产品名之下的五件可拆分差事，并论证其中只有"带归因的计量"真的难以自建——所以在比较厂商之前该先定的问题是：这五件里你想让哪几件待在请求路径上。它老实地为这一跳定价：可用性是相乘着往下走的（99.9% 挡在 99.9% 前面约得 99.8%），10–50 毫秒的代理开销会消失在一次聊天响应里、却不会消失在二十步的循环或一次语音轮次里，而按支出抽成是一笔按步数征收的税，且恰在智能体真正跑起来时到账。文中指出，没测过的故障转移是一项配置而不是一项能力，因为提示词并不像网关营销所暗示的那样在各家之间可移植。文末落在一种很少有人考虑的形态——数据面直连提供方，网关只当控制面去读你本就在发的遥测——以及能让退路一直敞着的三条性质：两侧都是 OpenAI 兼容接口、对你依赖的模型保留自己名下的账号，以及一条按计划定期演练的旁路。',
    ),
    L(
      'New Operation (Evaluation &amp; Observability) — *Online Experiments for Agents*. Detecting a three-point lift in task success needs roughly 3,700 sessions per arm at 80% power, and clustering by user typically triples it via a design effect of about 2.9 at twenty sessions per user — so most agent A/B tests are decided before they start, not by the result but by whether a result could ever arrive. Argues for randomising the user or tenant rather than the request, because agents carry memory, users adapt and a single task can span sessions, and warns that analysing clustered data as independent invents significance by shrinking the standard error. Prescribes one pre-committed decision metric chosen for its variance — steps to completion, escalation rate, edit distance, retry rate — with everything else as a guardrail that can stop a rollout but never be promoted to the win condition, plus a sequential method or a sealed horizon because five looks turns a 5% false-positive rate into something nearer 15%. Adds the variance-reduction techniques that are cheaper than traffic (pre-period covariates, stratification, paired offline replay) and ends on the guarded rollout: gate offline, shadow, ramp with automatic rollback on guardrails, and record in the changelog that no measurement happened.',
      '新增运维页（评估与可观测性）——《智能体的线上实验》。要在 80% 检验效能下看清任务成功率三个百分点的提升，每组约需 3,700 次会话；而按用户聚类通常还要再乘三——在每位用户二十次会话时，设计效应约为 2.9。所以多数智能体 A/B 测试在开跑前就已见分晓：不是被结果决定的，而是被"结果究竟有没有可能出现"决定的。文章主张按用户或租户而非按请求随机分组，因为智能体带记忆、用户会适应，而一个任务可以横跨多次会话；并警告把聚类数据当独立数据分析，会通过缩小标准误而凭空造出显著性。处方是：事先锁定唯一一个按方差挑选的决策指标——完成步数、升级率、编辑距离、重试率——其余一律作为护栏，它们可以叫停发布，但永远不能被提拔为胜利条件；再配上序贯方法或一个封存的样本量上限，因为看五次就能把 5% 的假阳性率推到接近 15%。文中还给出了比加流量更便宜的降方差手法（实验前协变量、分层、配对离线回放），并以带护栏的灰度发布收尾：先用离线评测设闸、影子运行、按档放量并让护栏自动回滚，然后在变更记录里写明——这次没有发生任何测量。',
    ),
    L(
      'New Playbook (Domain Playbooks) — *Collections &amp; Dunning Agents*. Regulation F presumes a violation above seven calls per debt per seven days and bars calling within seven days of a phone conversation, while New York City\'s SHIELD rule caps attempts at three per account across all channels, extends to original creditors, and takes effect on 1 January 2027 after a postponement — so the product is a single authoritative contact governor keyed to consumer, account and jurisdiction that every channel must decrement before composing a word. Makes right-party contact structural rather than a prompt instruction, since a helpful model asked "who is this and what is it about" answers both halves and discloses a debt to a third party. Covers the three disclosures that land in the first fifteen seconds (the FCC\'s 2024 ruling pulling AI voices under TCPA robocall rules with $500–$1,500 statutory damages, the collector notice, and all-party recording consent, which makes starting a call unrecorded an architectural requirement), draws the code-versus-model line at prescribed text, balances and settlement authority, wires dispute, cease, attorney and hardship signals to a suppression store that propagates in seconds, and closes on measuring net recovery against complaints per thousand attempts rather than contact volume.',
      '新增实战手册（领域实战手册）——《催收与账款催缴智能体》。联邦 Regulation F 规定七天内就同一笔债务拨打超过七通电话即推定违规，并禁止在通话后七天内再次致电；而纽约市的 SHIELD 规则把上限压到每个账户跨所有渠道三次接触、适用范围扩展到原始债权人，并在一次推迟后于 2027 年 1 月 1 日生效——所以真正的产品，是一个按消费者、账户与司法辖区计数的唯一权威联系配额管理器，任何渠道在动笔之前都必须先去扣它。文章主张把"先确认正主"做成结构性约束而不是一条提示词指令，因为一个乐于助人的模型被问到"你哪位、有什么事"会把两半都答了，从而向第三方透露了债务。文中覆盖了落在通话头十五秒里的三项披露（FCC 2024 年裁定把 AI 语音纳入 TCPA 自动拨号规则、法定赔偿每通 500–1,500 美元；催收方告知；以及要求全体同意的录音州——这让"能以不录音状态开始一通电话"成为一项架构要求），把代码与模型的分界线划在规定文本、金额与和解授权上，并把争议、停止联系、律师与困境四种信号接到一个数秒内即可传播的抑制存储上；文末主张以净回收额对每千次接触的投诉数来衡量，而不是看接触量。',
    ),
  ],
};

export default entry;
