import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-09-05',
  title: L(
    'Two AI Blog posts — on the ten-hour intrusion that needed no zero-day, and on four graph-RAG systems that are really three write patterns — plus three pages on system cards, guardrail evaluation, and expense audit agents',
    '两篇 AI 博客——一场不需要零日的十小时入侵；以及四套 graph-RAG 系统其实只是三种写入模式——外加三个页面：系统卡、护栏评估，以及费用稽核智能体',
  ),
  items: [
    L(
      'New AI Blog post `/blogs/ten-hours-and-no-zero-days` — Unit 42 published an intrusion on 2 September 2026 in which a human ransomware operator drove frontier models through attack-specific agentic frameworks and took cloud, identity, CI/CD and SaaS in under ten hours, against an estimated two weeks for a coordinated human red team. The post argues the finding is not the ten hours but the absence of a zero-day: more than fifty already-documented ATT&CK techniques, every link an authorised use of a standing credential — repositories to secrets manager to unauthorised CI/CD builds to cloud keys — so nothing distinguishing fired anywhere in the chain and the control that failed was the response clock. Reads the 80-page audit the documentation agent left behind as a measurement rather than a taunt: agent-driven enumeration of an unfamiliar estate now produces a complete weakness inventory in hours, which is the one part defenders can reproduce legitimately. Closes on pre-authorised containment, ending standing master credentials, and treating CI/CD as a production boundary — and on why another content detector does not move a clock.',
      '新增 AI 博客 `/blogs/ten-hours-and-no-zero-days`——Unit 42 于 2026 年 9 月 2 日公布了一起入侵：一名人类勒索软件操作者用攻击专用的智能体框架驱动前沿模型，在不到十小时内拿下云、身份、CI/CD 与 SaaS，而一支协同的人类红队做同样的事估计需要两周。本文主张真正的发现不是那十小时，而是零日的缺席：五十多种早已被记录在案的 ATT&CK 技术，每一环都是对一个常驻凭据的授权使用——从仓库到密钥管理系统、到未经授权的 CI/CD 构建、再到云密钥——所以整条链上没有任何有区分度的告警被触发，而失效的那项控制是响应时钟。文中把文档智能体留下的那份 80 页审计读作一次测量而非一次示威：由智能体驱动、对一个陌生资产面的枚举，如今能在数小时内产出一份完整的弱点清单，而这恰是防守方可以名正言顺复现的那一部分。文末落在预授权遏制、取消常驻主凭据、以及把 CI/CD 当作生产边界——并说明为何再加一个内容检测器移动不了一口钟。',
    ),
    L(
      'New AI Blog post `/blogs/graphrag-vs-lightrag-vs-graphiti-vs-cognee` — the answer-quality gap between the four is roughly good versus slightly better; the gap in what one corpus update costs is two orders of magnitude, so the decision is the write pattern. Build (Microsoft GraphRAG re-derives community summaries across the corpus, which is the only mechanism here that answers a whole-corpus question and makes every update a re-index), append (LightRAG drops the hierarchy for dual-level retrieval and per-document update pricing), mutate (Graphiti writes episodes and invalidates the edges they contradict, the only pattern where a fact can stop being true), or compose (Cognee gives you pipelines, ontologies and pluggable stores, plus every decision the others made for you). The post ends on the failure all four share: entity deduplication by string matching, so naming variants become separate nodes — a false node means false edges, and because the generated answer stays fluent, answer-quality evaluation never surfaces it.',
      '新增 AI 博客 `/blogs/graphrag-vs-lightrag-vs-graphiti-vs-cognee`——四者之间答案质量的差距大致是「好」与「略好一点」之差；而一次语料更新代价的差距是两个数量级，所以真正要决定的是写入模式。构建（Microsoft GraphRAG 在整个语料上重算社区摘要，这是此处唯一能回答全语料级问题的机制，代价是每次更新都等于一次重建索引）、追加（LightRAG 砍掉层级，换来双层检索与按文档计价的更新）、改写（Graphiti 写入情节并作废被其推翻的边，是唯一让一个事实可以停止为真的模式），或者自组（Cognee 给你管线、本体与可插拔存储，外加别人替你做过的每一个决定）。文末落在四者共享的那个失败上：用字符串匹配去重实体，于是命名变体变成互相独立的节点——一个假节点意味着假的边，而因为生成出的答案依旧流畅，答案质量类的评测永远浮不出它。',
    ),
    L(
      'New Concept `/concepts/system-cards` (E22) — a system card is a safety-testing record about one checkpoint, written by the party with the most to lose from it, and the question you brought to it (can this model do my job) is the one it structurally cannot answer. Separates the three documents people conflate — the 2019 model card describing weights, the system card describing a deployed configuration of model plus classifiers plus policy, and the regulatory technical documentation an EU AI Act Article 53 provider keeps for an AI Office that has had formal enforcement authority over general-purpose models since 2 August 2026. Names what a card cannot tell you (your task, what you are actually served as aliases move and routers re-tier, and how hard they tried) and what to read it for instead: the elicitation methodology first and before the results table, the refusal and gating boundary, the safeguard inventory, and the capability-threshold declarations that predict your next migration. Closes on pinning versions, diffing consecutive cards, and never citing a vendor safety argument as your own.',
      '新增概念页 `/concepts/system-cards`（E22）——系统卡是一份关于某一个检查点的安全测试记录，由最输不起这份记录的那一方撰写；而你带着来的那个问题（这个模型能不能干我的活），恰恰是它在结构上无法回答的。本页把常被混为一谈的三份文件分开——2019 年那种描述权重的模型卡、描述「模型加分类器加政策」这一部署配置的系统卡，以及欧盟《AI 法案》第 53 条下提供者留存的监管技术文档（AI 办公室自 2026 年 8 月 2 日起已对通用模型拥有正式执法权）。它点名了卡说不出的东西（你的任务、别名迁移与路由分档之下你实际被服务到的是什么，以及他们究竟有多用力），以及该读的四样：先读、且要在结果表之前读的能力激发方法、拒答与准入边界、保障措施清单，还有那些预示你下一次迁移的能力阈值声明。文末落在钉住版本、把前后两张卡当 diff 来读，以及绝不把厂商的安全论证当成自己的。',
    ),
    L(
      'New Operation `/operations/evaluation-and-observability/evaluating-guardrails-and-detectors` (E19) — every injection classifier is sold on recall, which is the one number that does not transfer. At a 1-in-10,000 attack base rate a 99%-recall, 1%-false-positive detector yields under 1% precision — about a hundred false alarms per real one — and a 50/50 public benchmark hides that arithmetic completely. The page moves the unit of evaluation from the detector to the operating point (report false-positive rate at a fixed recall, derive the threshold from the cost ratio of the two errors, and tier it by what the agent can do with the input), insists on a blind uniform sample of production traffic as the only honest prevalence estimate, splits the frozen regression set from a red-team set that rotates because the attacker is allowed to move the distribution, and adds the half nobody measures: added p95, an explicit fail-open-or-closed decision with a counter for "not evaluated", cost per protected request, and the human cost of a block. Closes on shadow mode, the narrow surface first, and the honest entry in the risk register — a content detector bounds the rate of compromise, never the duration.',
      '新增运维页 `/operations/evaluation-and-observability/evaluating-guardrails-and-detectors`（E19）——每一个注入分类器都靠召回率来卖，而这恰恰是那个无法迁移的数字。在万分之一的攻击基础发生率下，99% 召回、1% 误报的检测器精确率不到 1%——大约每抓到一次真攻击附送一百次假警报——而一个 50/50 的公开基准把这个算术彻底掩盖了。本页把评估的单位从检测器挪到操作点（报「固定召回率下的误报率」、用两类错误的代价比推出阈值、并按「智能体拿这段输入能干什么」分档），坚持把生产流量的盲标均匀样本当作唯一诚实的发生率估计，把冻结回归集与轮换的红队集分开（因为攻击者有权移动那个分布），并补上没人去测的那一半：新增的 p95、一个带「未评估」计数器的显式 fail-open/fail-closed 决定、每个受保护请求的成本，以及一次拦截的人力代价。文末落在影子模式、先上窄接触面，以及风险登记册里那句诚实的话——内容检测器约束的是被攻陷的发生率，从来不是持续时间。',
    ),
    L(
      'New Playbook `/playbooks/domain-playbooks/expense-and-travel-audit-agents` (Y31) — the money in T&E is not in the fraud, and building the agent to hunt for it turns the programme into a tax on the honest majority. Most organisations audit a 20–30% sample, and the recoverable cash sits in unreclaimed VAT, duplicate submissions and priced-in policy leakage, none of which needs judgement. The page splits the deterministic checks that scale to 100% coverage from the judgement calls that get worse at it, keeps policy in an effective-dated rule engine evaluated against the date of the expense rather than the date of processing, and gives the model exactly one job — reconciling the receipt image, the card feed and the claim into one typed record with per-field locators, scored nightly against a card-settlement ground truth that arrives free. Argues reclaimability must be checked at submission, when the employee can still obtain a compliant invoice, and closes on the flag budget: a published auto-approve band, routing by reason code, never an automated accusation, flag rates monitored by grade and country, and a blind holdout on the old sampled process.',
      '新增实战手册 `/playbooks/domain-playbooks/expense-and-travel-audit-agents`（Y31）——差旅与费用报销里的钱不在舞弊上，而把智能体建成一台猎弊机器，会把整个项目变成向诚实的大多数征税。多数机构只抽审两三成，而能追回的现金在未抵扣的增值税、重复提交与被计入成本的政策渗漏里，这三样都不需要判断。本页把「可以扩到 100% 覆盖的确定性检查」与「覆盖到 100% 只会更糟的判断题」分开，把政策放进一个按费用发生日期（而非处理日期）求值的带生效日期规则引擎，并只给模型一件事做——把票据图像、卡账流水与员工申报对账成一条带逐字段定位的强类型记录，每晚用免费送达的卡账清算真值给它打分。文中主张可抵扣性必须在提交那一刻就查，因为那是员工还能去要一张合规发票的唯一时点；文末落在标记预算：公布一条自动通过带、按原因码分流、绝不自动生成指控、按职级与国家监控标记率，以及为旧抽审流程保留一个盲留出组。',
    ),
  ],
};

export default entry;
