import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-09-06',
  title: L(
    'Two AI Blog posts — on a fourth device standard that finally writes down what a machine must not do, and on four redaction tools that are really three boundaries — plus three pages on the generator–verifier gap, agents that move things, and database-migration agents',
    '两篇 AI 博客——第四份设备标准终于把「机器不该做什么」写了下来；以及四个脱敏工具其实是三道边界——外加三个页面：生成-核验落差、会动手的智能体，以及数据库迁移智能体',
  ),
  items: [
    L(
      'New AI Blog post `/blogs/mhs-vs-sila-2-vs-opc-ua-lads-vs-ros-2` — lab and factory interoperability has been standardised three times already (SiLA 2 shipped v1.0 in 2019, eleven years after the consortium formed; OPC UA LADS was released in January 2024 on top of an industrial installed base it did not have to build; ROS 2 is the de facto robotics middleware), and instruments still arrive with a vendor SDK — so the specification was never the hard part, and a fourth one needs a better argument than fragmentation. The post finds it: SiLA 2, LADS and ROS 2 were all designed for machine-to-machine control, where the caller is software written by an engineer who read the manual, so the physical envelope could safely stay in the manual. Anthropic\'s Model Hardware Standard, in research preview since late August 2026 with AWS, Universal Robots and Hugging Face among the partners, is the only one that moves the payload ceiling, travel range and temperature limit into a description a caller can read and a driver enforces whichever model is driving. Closes on the distinction that gets lost in summaries — a driver-enforced limit is ordinary software in the command path, not a rated protective function of the kind ISO 10218-1 and -2:2025 made explicit when they replaced the 2011 editions and absorbed ISO/TS 15066 — and on the evaluation worth running: the same envelope under a different model, a different orchestrator and a third-party driver.',
      '新增 AI 博客 `/blogs/mhs-vs-sila-2-vs-opc-ua-lads-vs-ros-2`——实验室与工厂的互操作已经被标准化过三次（SiLA 2 在联盟成立十一年后的 2019 年才发布 1.0；OPC UA LADS 于 2024 年 1 月发布，站在一个它不必自建的工业装机量之上；ROS 2 则是事实上的机器人中间件），而仪器出厂时依旧配着厂商自家的 SDK——所以难的从来不是规范，第四份规范需要一个比「太碎片化」更好的理由。本文把它找了出来：SiLA 2、LADS 与 ROS 2 都是为机器对机器的控制而设计的——在那里，调用方是一位读过手册的工程师写的软件，所以物理包络可以安全地留在手册里。而 Anthropic 的 Model Hardware Standard（2026 年 8 月下旬起进入研究预览，合作方包括 AWS、Universal Robots 与 Hugging Face）是唯一一个把负载上限、行程范围与温度限值挪进「一份调用方读得懂、并由驱动强制」的描述里的。文末落在那个在转述中总被丢掉的区分——驱动强制的限值是命令路径上的普通软件，不是 ISO 10218 第 1、2 部分 2025 年版（取代 2011 年版并吸收了 ISO/TS 15066）所显式化的那种经评级的防护功能——以及那项值得一跑的评估：换一个模型、换一个编排器、换一份第三方驱动，跑同一个包络。',
    ),
    L(
      'New AI Blog post `/blogs/presidio-vs-limina-vs-skyflow-vs-nightfall` — the four are sold as four ways to keep personal data out of model traffic and are actually three boundaries: a vault that substitutes the value at collection (Skyflow — a guarantee, not a detection, and only for data whose collection you control), a transform on the wire (Presidio, MIT-licensed and community-governed under Data Privacy Stack since 2026, and Limina, the former Private AI after its March 2026 rebrand), and a platform that finds exposures after they land (Nightfall, whose unit of work is an incident, and which bounds how long an exposure lasts rather than whether it happens). The post argues the two detectors carry an asymmetry that points the opposite way from an injection classifier — the expensive error is the false negative, the identifier forwarded verbatim while nothing in the pipeline emits a signal — so the only honest measurement is a blind uniform sample of post-redaction traffic. Ends on the three costs nobody puts in the comparison table: an agent that cannot address the customer by name, a trace store holding the copy with the evidence removed, and a placeholder map that is a re-identification key with no owner on the asset register.',
      '新增 AI 博客 `/blogs/presidio-vs-limina-vs-skyflow-vs-nightfall`——这四家都被当成「把个人数据挡在模型流量之外」的四种做法来卖，实则是三道边界：在采集处替换掉值的保险库（Skyflow——那是一种保证而非检测，且只对采集环节归你掌控的数据成立）、在链路上做的变换（Presidio，MIT 许可，2026 年起转入社区治理的 Data Privacy Stack；以及 Limina，即 2026 年 3 月更名后的 Private AI），以及在数据落地之后去找暴露的平台（Nightfall，其工作单元是一起事件，它约束的是暴露持续多久，而不是暴露会不会发生）。本文主张，那两个检测器身上的不对称方向与注入分类器恰好相反——昂贵的错误是漏报：标识符被逐字转发，而管道里没有任何东西发出信号——所以唯一诚实的测量，是对脱敏后流量做盲标均匀抽样。文末落在没人写进对比表的三笔成本：一个没法称呼客户名字的智能体、一份留着「证据已被移除」那一版的追踪存储，以及一份在资产清单上无人认领、却是重新标识密钥的占位符映射。',
    ),
    L(
      'New Concept `/concepts/generator-verifier-gap` (B25) — every autonomous loop is a wager that checking costs less than doing, and where the wager fails the loop has nothing to converge against, which is why intrinsic self-correction reliably disappoints and extrinsic correction works. The sharper consequence is the one teams meet in production: an agent allowed to retry until the verifier is satisfied ends up with the verifier\'s false-accept rate rather than the model\'s, because the retry loop is searching for the inputs that fool it — reward hacking arriving at inference time. Hence false accepts as the only verifier metric that matters, retry budgets as a safety parameter, and independence from the generator being worth more than raw accuracy. Closes on the decision rule: cheap sound check means real autonomy is on the table, expensive-but-possible means a review-throughput problem, and genuinely-as-hard-as-generation means you are shipping a drafting tool and should say so.',
      '新增概念页 `/concepts/generator-verifier-gap`（B25）——每一个自主循环都在赌「检查比做更便宜」，而赌注不成立时，循环就没有任何东西可以收敛过去；这正是内生自我纠错稳定令人失望、而外生纠错有效的原因。更锋利的推论是团队在生产里会撞上的那一条：一个被允许「重试到核验器满意为止」的智能体，最终拿到的是核验器的误接受率，而不是模型的——因为这个重试循环正在搜索那些能骗过它的输入，等于把奖励攻陷搬到了推理期。于是：误接受是核验器唯一重要的指标、重试预算是一个安全参数、而「与生成方相互独立」比纯准确率更值钱。文末落在那条决策规则：存在便宜而可靠的检查，真自主才谈得上；核验可行但昂贵，那是评审吞吐问题；核验真的和生成一样难，那你交付的是一个起草工具，并且应该这么说出来。',
    ),
    L(
      'New Operation `/operations/safety-and-security/physical-actuation-safety` (S22) — every control in the agent-safety stack quietly assumes the action can be taken back, and an agent driving a syringe or a robot arm loses reversibility, idempotency, the sandbox and exact observation all at once (retry-on-timeout, the most common resilience pattern in agent infrastructure, becomes a collision). So enforcement moves below the model into a driver that cannot be argued with, and the human decision moves from approving a step — impossible at machine tempo — to authorising a bounded, machine-checkable envelope for a whole run. The page keeps a driver limit and a rated protective function firmly apart, adds the tier most programmes skip (real hardware, worthless material), requires a per-device safe state with a watchdog and an emergency stop outside the software path, and replaces the throughput dashboard with unplanned stops, runs that ended outside the envelope, measured time to physical stop, and material burned by failed runs.',
      '新增运维页 `/operations/safety-and-security/physical-actuation-safety`（S22）——智能体安全体系里的每一项控制都在悄悄假设动作可以被收回，而一台驱动注射泵或机械臂的智能体，会同时失去可逆性、幂等性、沙箱与精确观测（「超时就重试」这条智能体基础设施里最常见的韧性模式，在这里变成一次碰撞）。于是强制执行下沉到模型之下、进入一个无法与之争辩的驱动，而人的决定从「批准一个步骤」（在机器节奏下根本做不到）变成「为整次运行授权一个有界且机器可检的包络」。本页把驱动限值与经评级的防护功能牢牢分开，补上多数项目会跳过的那一档（真硬件、不值钱的材料），要求逐台设备定义安全状态并配看门狗、把急停留在软件路径之外，并用非计划停机数、在包络之外结束的运行数、实测的物理停止耗时、以及失败运行烧掉的材料，取代那块吞吐看板。',
    ),
    L(
      'New Playbook `/playbooks/coding-and-computer-use-agents/database-migration-agents` (U22) — a model writes correct DDL first time, which is exactly why this is the coding-agent task most likely to take production down: the statement is fine, the sequence is wrong, and CI runs it against an empty table with nobody else connected. The page moves items off the list CI cannot check and onto the list it can — deliverable is an ordered expand–backfill–contract sequence the currently-deployed code still fits, the agent defaults to additive-only changes with removals owned by a human release, every migration ships the short lock_timeout preamble because the outage is the FIFO lock queue rather than the statement, and the acceptance oracle is a shadow apply against a production-shaped clone under replayed traffic reporting lock duration, runtime, queries blocked and bytes written. Backfills leave as throttled, checkpointed, idempotent jobs; the agent authors and a controlled runner applies; and the dashboard tracks incidents attributable to a migration, p99 in migration windows, and the contract debt an additive-only rule quietly accrues.',
      '新增实战手册 `/playbooks/coding-and-computer-use-agents/database-migration-agents`（U22）——模型一次就能写对 DDL，而这恰恰是它成为最可能把生产打趴下的那类编码智能体任务的原因：语句没问题，错的是顺序，而 CI 是在一张空表上、没有别人连着的情况下跑它的。本页把条目从「CI 检查不了」的那张清单搬到「CI 检查得了」的那张上——交付物是「扩展-回填-收缩」这段当前已部署代码依然装得进去的有序序列；智能体默认只增不减，删除类变更归人类的发版所有；每一次迁移都带上那段短 lock_timeout 前导，因为把站点打趴下的是 FIFO 锁队列而不是那条语句；而验收判据是「在回放流量下、对一份生产形态克隆做的影子应用」，回报锁持有时长、总运行时长、被阻塞查询数与写入字节数。回填改以「限流、带检查点、幂等」的作业形式交付；智能体负责撰写、受控执行器负责应用；看板则盯可归因于迁移的事故、迁移窗口内的 p99，以及「只增不减」这条规则悄悄累积起来的收缩债。',
    ),
  ],
};

export default entry;
