import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-09-18',
  title: L(
    'Two AI Blog posts — on the sandbox escape that went through the hole the sandbox opens itself, and on the personal agent built as if the injection already landed — plus three pages on the jagged frontier, underwriting agents, and replay testing',
    '两篇 AI 博客——一篇讲那次从沙箱自己开的孔里走出去的逃逸，一篇讲那个「按注入已经得手」来造的个人智能体——外加三个页面：锯齿状前沿、核保智能体，以及回放测试',
  ),
  items: [
    L(
      'AI Blog — “The microVM held; the mount did not — two escapes in Docker Sandboxes”: Docker’s 15 September advisory describes CVE-2026-77179 (critical, CVSS v4.0 9.4, macOS, 0.28.0 up to 0.42.0) in the virtio-fs host server and CVE-2026-79994 (high, 0.37.0 up to 0.42.0) in the guest-to-host Unix socket relay, both fixed in 0.42.0 on 7 September, both symlink-substitution races. Neither touched the hardware boundary — they went through the two channels the sandbox opens on purpose, because a microVM that cannot see the repository is not a product. The argument is that isolation strength is a property of the whole perimeter: rank your channels by how much guest-controlled input reaches host-side code and you predict where the CVEs land. And the guest here is your own coding agent running with prompts disabled, so one poisoned README in a transitive dependency is the whole precondition. Upgrade, then change what the share points at — the mount fixes the class, the patch fixes two bugs.',
      'AI 博客《微 VM 守住了，挂载没有——Docker Sandboxes 的两次逃逸》：Docker 9 月 15 日的公告描述了 virtio-fs 宿主机服务端里的 CVE-2026-77179（严重，CVSS v4.0 9.4，macOS，0.28.0 至 0.42.0 之前）与客户机到宿主机 Unix 套接字转发里的 CVE-2026-79994（高危，0.37.0 至 0.42.0 之前），两者都在 9 月 7 日的 0.42.0 中修复，也都是符号链接替换竞态。谁都没碰到那道硬件边界——它们走的是沙箱有意开出的那两条通道，因为一个看不见仓库的微 VM 算不上产品。文章的论证是：隔离强度是整条周界的属性——按「有多少客户机可控的输入抵达宿主机侧代码」给你的通道排序，你就能预测 CVE 会落在哪。而这里的「客户机」，是你自己那个关掉了授权提示的编码智能体，于是某个传递依赖里一份被投毒的 README，就是全部前提。先升级，再改共享指向何处——挂载修的是这一类，补丁修的是这两个。',
    ),
    L(
      'AI Blog — “Meta built Muse assuming the injection lands — and priced the rest at $130,000”: the per-user VM is the headline and the least interesting layer. Everything load-bearing in Meta’s 8 September personal agent sits downstream of a successful injection — credentials brokered in an isolated daemon so the model only ever holds surrogate tokens, a Sentinel gatekeeper outside the agent’s reach authorising every connector call and network request at layers 4 and 7, kernel-level taint on any tool process that read user data — and the bounty schedule, up to $300,000 with up to $130,000 for a single-user prompt injection, says out loud that the company expects injections to work. The residual risk is not exfiltration: it is the harmful action that travels over an approved channel to an approved destination, where the only defence positioned to catch it is a human confirmation step that erodes with frequency. Copy the sequencing — containment first, and say in public that injection is unsolved.',
      'AI 博客《Meta 是假定「注入会得手」来造 Muse 的——剩下的部分标价 13 万美元》：每用户一台虚拟机是标题，也是最不有趣的一层。Meta 这个 9 月 8 日上线的个人智能体里，真正吃力的东西全都坐落在「注入已经得手」之后——凭据放在隔离守护进程里中介，模型手上永远只有替身令牌；一个位于智能体够不着之处的 Sentinel 把关进程，在第四层与第七层为每一次连接器调用与网络请求授权；任何读过用户数据的工具进程都会被打上内核层的污染标记——而那份最高 30 万美元、其中「影响单个用户的提示注入」最高 13 万美元的赏金表，等于公开说出：公司预期注入会成功。剩下的风险不是外泄，而是那个走在获准通道上、飞向获准目的地的有害动作；在那里，唯一站在能抓住它的位置上的，只有一个会随频次而磨损的人工确认。该抄的是这个先后次序——先围堵，并且公开承认注入尚未解决。',
    ),
    L(
      'Concepts — The Jagged Frontier: capability is a coastline, not a level. The 758-consultant BCG field experiment found 12.2% more tasks completed, 25.1% faster and over 40% higher quality on 18 tasks inside the frontier — and, on the one task built to sit outside it, AI users 19 percentage points less likely to be correct than people working alone. The edge is invisible because failure keeps the shape of success: just past it the output has the same fluency and structure, and the reviewer’s attention is lowest because the previous nine were fine. What puts a task outside is structural rather than hard — the answer depends on something absent from context, the correct output is a refusal, the task is a rare combination of common parts — and an agent loop compounds one excursion into the premise of thirty more steps. Pilot per task, prefer tasks where verifying is cheaper than producing, and treat the map as perishable.',
      '概念 — 锯齿状前沿：能力是一条海岸线，不是一个水位。那项有 758 名 BCG 顾问参与的田野实验发现，在 18 项界内任务上多完成了 12.2% 的任务、快了 25.1%、质量高出 40% 以上——而在唯一一项被构造成落在界外的任务上，用 AI 的人给出正确答案的可能性比单干的人低了 19 个百分点。边缘之所以看不见，是因为失败保持着成功的形状：刚越过一点点，输出的流畅度与结构照旧，而复核者的注意力恰在此时最低，因为前面九个都没问题。把一项任务推到界外的性质是结构性的，而不是「难」——答案取决于上下文里没有的东西、正确输出是一次拒答、这项任务是常见零件的罕见组合——而智能体的循环会把一次越界复利成之后三十步的前提。按任务试点、优先选核验比生成更便宜的任务，并把这张地图当成会过期的东西。',
    ),
    L(
      'Playbooks — Insurance Underwriting Agents: bind rate arrives in seconds and loss experience arrives after the development tail, so any loop closed on the fast signal selects for the risks your competitors declined. The second constraint is that the regulated artifact is the enumerable factor that sets eligibility and price — filed, examinable, testable — which an LLM judgement structurally cannot be. So the agent emits declared variables with a source span and an explicit unknown, and a deterministic engine rates; the model never produces a score, a tier or a recommendation phrased as one. Colorado’s ECDIS regime tests outcomes with race imputed by BIFSG from name and geolocation, extended in October 2025 to private passenger auto and health with compliance due 1 July 2026, and the NAIC model bulletin was formally adopted in 25 states by July 2026 with its evaluation tool piloted across twelve. Run the proxy test on your own book, derive decline reasons from the rule that tripped, and make the decline path a referral.',
      '实战手册 — 保险核保智能体：成交率几秒钟就到手，赔付经验要等发展尾部走完才到，于是任何照着快信号闭环的循环，选出来的都是竞争对手拒掉的那些风险。第二重约束是：受监管的那件东西，是决定承保资格与价格的、可枚举的因子——要报备、可被检查、可被测试——而 LLM 的判断在结构上当不了它。所以智能体产出的是带来源片段与显式「未知」的申报变量，由一个确定性引擎去定费率；模型从不产出评分、层级，也不产出措辞等同于此的建议。科罗拉多的 ECDIS 制度检验的是结果，用 BIFSG 从姓名与地理位置推断种族，并在 2025 年 10 月扩展到私家车险与健康险、2026 年 7 月 1 日为合规期限；NAIC 示范公告到 2026 年 7 月已在 25 个州正式采纳，其评估工具在十二个州试点。请在自己的业务上跑那套代理变量检验，让拒保理由从被触发的那条规则推导出来，并把拒保那条路做成一次转人工。',
    ),
    L(
      'Operations — Replay Testing with Recorded Traces: evals measure the model and unit tests measure the code, and neither notices that a refactor moved authentication to step four. Replay catches that class for the price of a model call, but a recording pins the world, so it proves nothing past the first action the agent takes differently — which makes the cache-miss policy the entire design, and the three options (fail strictly, fall through to live, answer from a contract fixture) are three different instruments. Split the suite: twenty to fifty pinned trajectories pre-merge asserting tool sequence, step count and token budget rather than prose, and stateful contract fixtures scored on outcome nightly. Stamp every recording with provider, API version and capture date and expire it on a clock, because a fully green suite replaying a world that stopped existing is how third-party drift reaches production. And never use it as a quality gate — it says today behaves like yesterday, not that yesterday was good.',
      '运维 — 用录制轨迹做回放测试：评测量的是模型，单元测试量的是代码，而谁都不会注意到一次重构把认证挪到了第四步。回放能以一次模型调用的代价抓住这一类，但录制把世界钉死了，所以一旦智能体做出了不同的第一个动作，它此后什么都证明不了——于是「未命中怎么办」这条策略就是全部设计，而那三个选项（严格判失败、落空打到线上、由契约夹具应答）是三件不同的仪器。把套件拆开：合并前跑二十到五十段钉死的轨迹，断言工具序列、步数与令牌预算，而不是断言散文；每晚跑带状态的契约夹具，按结果打分。给每份录制盖上提供方、API 版本与采集日期，并让它按时钟过期，因为一个全绿、却在回放一个已不复存在的世界的套件，正是第三方漂移抵达生产环境的路径。并且绝不要拿它当质量闸门——它说的是「今天与昨天表现一致」，不是「昨天很好」。',
    ),
  ],
};

export default entry;
