import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-09-12',
  title: L(
    'Two AI Blog posts — on the week a vendor finally sold the agent loop and took the compaction step with it, and on the red-team scanners that all stand at the wrong boundary — plus three pages on adverse-event intake, shadow mode, and what “zero” retention still keeps',
    '两篇 AI 博客——终于有厂商把智能体循环卖了出去、并顺手带走了压缩那一步的这一周；以及那些统统站错了边界的红队扫描器——外加三个页面：不良事件接收、影子模式，以及"零"留存到底还留着什么',
  ),
  items: [
    L(
      'AI Blog — “The Agents API sells you the harness — compaction included”: OpenAI opened the Agents API in public beta on 10 September, putting the managed Codex harness behind one call — durable sessions, subagent orchestration, recovery and automatic context compaction — with no API fee beyond tokens and container time, and execution deliberately unbundled across nine sandbox partners or your own VPC. The post argues that the loop is not one thing you either own or do not: retry policy is a knob and subagent fan-out is observable from outside, but compaction is the only step that rewrites the sentence stating the goal, which makes it the primary mechanism behind goal drift and the one transformation your evals were silently holding constant. A harness version is not a model version, so the question is not whether its compaction is good but whether you can tell when it changed — and the free-at-the-point-of-use pricing means the component that decides how many tokens you burn has no line item of its own.',
      'AI 博客《Agents API 卖给你的是那套 harness——连同压缩》：OpenAI 于 9 月 10 日开放 Agents API 公测，把托管的 Codex harness 放到一次调用后面——持久会话、子智能体编排、恢复与自动上下文压缩——除 token 与容器时长外不另收 API 费用，而执行则被刻意解绑到九家沙箱合作方或你自有的 VPC。文章论证：循环并不是一个非有即无的整块——重试策略只是旋钮，子智能体扇出从外部可观测，但压缩是唯一会改写"陈述目标的那一句"的步骤，这使它成为目标漂移背后的首要机制，也正是你的评测一直默默当作常量的那一道变换。harness 版本不是模型版本，所以该问的不是"它的压缩好不好"，而是"它变了的时候你看不看得出来"——而"用时免费"的定价意味着，决定你烧掉多少 token 的那个组件，自己没有一条账单条目。',
    ),
    L(
      'AI Blog — “garak vs Promptfoo vs Giskard vs DeepTeam: none of them reach the tool result”: all four open-source red-team tools construct a hostile string and hand it to boundary one, the channel a user types into; an agent is compromised at boundary three, where text arrives inside a tool result it asked for and rarely re-checks. The post argues that reach, not probe count, is the buying axis — the counts are not even comparable across the four — and that the second axis, freshness, has no README badge: a static attack corpus is a regression suite, not a red team. Which makes maintenance the criterion, and 2026 changed it twice: Microsoft archived PyRIT on 27 March, read-only, while it is still recommended by most current guides, and OpenAI acquired Promptfoo in March, so the corpus deciding whether your agent is safe is now curated by a model vendor. The fix is twenty lines: register a hostile tool in your real catalogue and drive it with a benign prompt.',
      'AI 博客《garak、Promptfoo、Giskard 与 DeepTeam：没有一个够得到工具结果》：这四款开源红队工具都是构造一段敌意字符串、送进边界一——用户打字进去的那条通道；而智能体被攻陷发生在边界三：文字藏在一段它自己要来、又很少复核的工具结果里抵达。文章论证：选型该看的是"够得到哪里"，不是探针数量——这四者的计数本就不可比——而第二根轴"新鲜度"在 README 上没有徽章：静态攻击语料是一套回归护栏，不是一支红队。于是"谁在维护"成了标准，而 2026 年把它改了两次：微软于 3 月 27 日封存 PyRIT、仓库只读，而当下多数指南仍在推荐它；OpenAI 则于 3 月收购了 Promptfoo，于是决定你的智能体是否安全的那份语料，如今由一家模型厂商策展。补救只需二十行：把一个敌意工具注册进你真实的工具目录，再用良性提示词去驱动。',
    ),
    L(
      'Playbooks — Pharmacovigilance &amp; Adverse-Event Agents: pointing an agent at a channel is a legal act, because the reporting clock starts at first knowledge by anyone acting for the company — fifteen calendar days for a serious and unexpected case — so a system that reads a mailbox makes the company aware of everything in it, and the written channel scope has to exist before the model does. Build around the four elements that make a case valid and emit the missing-element follow-up question rather than a reportable yes/no; tune for recall with abstention as a routed outcome, because a false positive costs minutes and a false negative is a compliance finding; constrain coding to the dictionary version in force and stamp that version into the record; and keep the asymmetry that the agent may only escalate while a qualified person alone may dismiss.',
      '实战手册 — 药物警戒与不良事件智能体：把智能体对准一条通道是一次法律行为，因为上报时钟自任何代表公司行事的人首次知悉起算——既严重又非预期的个例是 15 个日历日——所以一套会读邮箱的系统，等于让公司知悉了邮箱里的一切，而书面的通道范围必须先于模型存在。围着让个例成立的那四个要素来建，输出"缺哪个要素、该追问什么"，而不是"可上报：是/否"；按召回率来调，并把弃答做成一条被路由的结果，因为一次假阳性只值几分钟、一次假阴性却是一条合规发现；把编码约束在当前生效的词典版本内，并把该版本盖进记录；并守住那份不对称——智能体只能上报，只有具资质的人才能驳回。',
    ),
    L(
      'Operations — Shadow Mode &amp; Dark Launches: a shadow agent never has to live with its own mistakes, so its errors do not compound and the observed per-task success rate drifts toward the per-step rate — an upper bound whose bias is worst on exactly the long multi-step runs you wanted reassurance about. Shadow is also neither free nor effect-free for an agent: writes disguised as reads, doubled third-party quota, full token price for output nobody reads, and notification tools that must be stubbed rather than trusted. Mirror 5–10% rather than everything, use live-parallel to compare single decisions and replay-from-trace to compare runs, adjudicate only the disagreements blind into three buckets, and write the promotion thresholds down before the first number arrives.',
      '运维 — 影子模式与暗发布：影子里的智能体从不必为自己的错误买单，于是错误不复利，观测到的逐任务成功率会漂向逐步成功率——那是一个上界，而它偏得最狠的地方，恰恰是你最想要定心丸的长多步运行。对智能体来说，影子也既不免费、也不无副作用：伪装成读的写、被翻倍的第三方配额、为没人会读的输出付的全价 token，以及那些必须打桩而不能被当成无害的通知类工具。镜像 5–10% 而不是全部，用实时并行比较单个决策、用轨迹回放比较整次运行，只对分歧做三桶盲裁，并在第一个数字出现之前就把晋级阈值写下来。',
    ),
    L(
      'Operations — Zero Data Retention &amp; Abuse Monitoring: ZDR is a property of a model-and-endpoint pair rather than of your account, and “zero” now carries carve-outs that are growing — as of mid-2026 one major provider requires thirty-day retention for its covered models regardless of ZDR, with flagged content kept far longer, so the longest windows attach to exactly the traffic most likely to be sensitive. One agent task fans out across six boundaries, including the failover route that fires during the provider incident nobody is watching, so inventory calls rather than vendors and enforce the approved list in the gateway with a test that proves the non-approved path fails. And note what the trade actually costs: buying ZDR deletes the vendor-side record you would want during an incident while leaving your own trace store — the larger exposure — completely untouched.',
      '运维 — 零数据留存与滥用监控：ZDR 是"模型 + 端点"这一对的属性，而不是你账户的属性；而"零"如今带着一份正在变长的例外清单——截至 2026 年年中，一家主要厂商对其 covered models 要求三十天留存，纵有 ZDR 亦然，被标记的内容则留得更久，于是最长的窗口恰恰附着在最可能敏感的那部分流量上。一次智能体任务会扇出到六条边界，其中包括那条在没人盯着的厂商事故期间才触发的切换路径；所以要清点调用而不是清点厂商，并在网关里强制批准清单、再配一个能证明未批准路径确实失败的测试。还要看清这笔交易的真实代价：买下 ZDR 删掉的是你在事故中想要的厂商侧记录，而你自己的追踪库——那个更大的敞口——则原封不动。',
    ),
  ],
};

export default entry;
