import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-10-10',
  title: L(
    'Two AI Blog posts — one reading the AgentCorruption disclosure for the fix that shipped without a version number, where the transport hardening took 51 days and the IAM grant that set the blast radius took 278, and one on four web-crawling projects where three ignore robots.txt out of the box, three send a spoofed browser User-Agent, none has a per-origin cap, and two carry a licence label that does not match the file — plus three pages on the four channels that put a credential inside an agent sandbox, the plan screen that trades twelve informed decisions for one uninformed one, and the memory store you cannot rebuild because the pipeline that built it is not yours',
    '两篇 AI 博客——一篇把 AgentCorruption 那份披露按「那次没有版本号的修复」来读：传输层加固用了 51 天，而决定爆炸半径的那项 IAM 授权用了 278 天；一篇讲四个网页抓取项目，其中三个开箱就忽略 robots.txt、三个发出伪装的浏览器 User-Agent、没有一个有按来源的并发上限，而有两个的许可证标签与文件不符——外加三个页面：把凭据放进智能体沙箱的那四条通道、那块「用十二个知情的决定换一个不知情的决定」的计划界面，以及那个你重建不了的记忆存储——因为建起它的那条流水线不是你的',
  ),
  items: [
    L(
      'AI Blog — “The fix shipped without a version number”: the most-quoted figure from Zenity Labs’ 8 October 2026 AgentCorruption disclosure is that one prompt reached every Amazon Bedrock AgentCore agent in an AWS account and region; the figure that matters more is the 278 days between the report and the day researchers observed the default execution role narrowed, against 51 days for IMDSv2-only on newly deployed agents. Argues the asymmetry is structural rather than negligent — a code defect has a patch, an over-broad grant can only be revoked, and revocation breaks every customer who was quietly depending on it. Reads the four stages as documented features rather than bugs, notes that AWS’s own security documentation promises a Firecracker microVM per session and that the boundary held at every step, walks the three channels a customer could have monitored (no CVE was issued, a default role has no changelog, and only the role itself carried the answer), and singles out the memory-poisoning stage as the one that outlives the fix because a planted instruction is a well-formed remembered fact. Closes on the afternoon of work that produces the one sentence leadership can act on.',
      'AI 博客《那次修复发布时没有版本号》：Zenity Labs 在 2026 年 10 月 8 日那份 AgentCorruption 披露里被引用最多的数字，是一个提示词触达了某个 AWS 账号与区域内的每一个 Amazon Bedrock AgentCore 智能体；而更要紧的那个数字，是从上报到研究者观察到默认执行角色被收窄之间的 278 天——对比「新部署智能体仅用 IMDSv2」那 51 天。文章主张这份不对称是结构性的、而非疏忽：代码缺陷有补丁，而一项过宽的授权只能撤回，而撤回会弄坏每一个悄悄依赖着它的客户。文中把那四个阶段读作有文档记载的功能、而不是 bug，指出 AWS 自己的安全文档承诺的是每会话一个 Firecracker microVM、而那道边界每一步都守住了，走了一遍客户本可以去盯的那三条通道（没有签发 CVE、一个默认角色没有变更日志，而只有那个角色本身承载了答案），并单独点出记忆投毒那一阶段是比修复活得更久的那一个——因为一条被植入的指令是一条格式良好的、被记住的事实。文章以那一个下午的工作收尾：它会产出高管可以据之行动的那一句话。',
    ),
    L(
      'AI Blog — “Firecrawl vs Crawl4AI vs ScrapeGraphAI vs Spider”: three of the four do not look at robots.txt unless you ask, three ship a spoofed browser User-Agent, and not one has a per-origin concurrency cap — while the fifteen-year-old incumbent they are replacing writes robots-obeying defaults, a self-identifying User-Agent and eight requests per domain into every generated project. Reads each licence from the file rather than the sidebar: Crawl4AI’s “Apache-2.0” carries a mandatory attribution rider the label omits and a README that calls it “recommended” one sentence before calling it “must”; Firecrawl’s AGPL server is accurate but silent on the best scraping engine being absent from the repository, so the self-hosted build is deliberately weaker; ScrapeGraphAI and Spider are clean MIT. Separates the pipelines by where the model sits — per task or per page, which decides cost, reproducibility and whether the source text survives — notes that ScrapeGraphAI’s robots node is wired into no shipped graph and asks a language model when it is, and shows why no performance comparison here is usable: Spider’s own test puts Firecrawl at 95.3% while a competitor’s puts it at 60.47%, and 185 pages in 50 ms is not a network-bound number.',
      'AI 博客《Firecrawl、Crawl4AI、ScrapeGraphAI 与 Spider 对比》：四者中有三个在你不主动要求时不会去看 robots.txt，三个出厂就带一个伪装的浏览器 User-Agent，而没有一个有按来源的并发上限——与此同时，它们正在取代的那个十五年的老前辈，会把「遵守 robots 的默认值、一个自报身份的 User-Agent、每域名八个请求」写进每一个生成出来的项目。文章按文件、而不是按侧栏来读每一份许可证：Crawl4AI 那个「Apache-2.0」带着一条标签没提的强制署名附则，而 README 在把它称作「必须」的前一句刚把它称作「推荐」；Firecrawl 的 AGPL 服务端标得准确，却对「那个最好的抓取引擎并不在仓库里」一字未提——所以自托管的构建是被刻意做得更弱的；ScrapeGraphAI 与 Spider 是干净的 MIT。文中按「模型坐在哪里」把流水线分开——按任务还是按页面，而这决定了成本、可复现性，以及源文本是否留得下来——指出 ScrapeGraphAI 那个 robots 节点没有被任何随库发出的图接进来、而你接进来了它还是去问一个语言模型，并说明为何此处没有一份性能对比是可用的：Spider 自己的测试把 Firecrawl 放在 95.3%，而一个竞品的测试把它放在 60.47%，而「50 毫秒 185 个页面」不是一个受网络限制的数字。',
    ),
    L(
      'Deep-Dives — “Credential delivery to the sandbox” (Agent Security): every sandbox decision answers whether agent code can get out of the box, and none answers what the platform put inside it before the agent started — which is the question that sets your blast radius, and the reason the AgentCorruption chain never needed an escape. Ranks the four delivery channels by the primitive that reads them, because a fetch tool is a metadata-service client and a shell tool is a filesystem reader and those are the capabilities the agent exists to have. Argues scope over lifetime with the arithmetic: a ten-minute token used by an agent completing a call in 400 milliseconds authorises on the order of a thousand actions, so rotation is the cheap half and the policy attached to the credential is the whole of it. Lands on the inversion — the sandbox holds a proof of which run this is, the entitlement lives in a broker outside it — and on the twenty-minute drill that turns the argument into one sentence: an injected prompt here authorises N actions across M resources.',
      '深入解析《凭据如何投递进沙箱》（智能体安全）：每一个沙箱决策回答的都是「智能体的代码能不能跑出这个箱子」，而没有一个回答「在智能体启动之前平台往箱子里放了什么」——而后者才是决定你爆炸半径的那个问题，也正是 AgentCorruption 那条链从不需要一次逃逸的原因。文章按「读它需要什么原语」给四条投递通道排序，因为取数工具就是一个元数据服务客户端、shell 工具就是一个文件系统读取器，而这些正是智能体存在的意义所在。文中用算术主张作用域优先于寿命：一个十分钟的令牌，被一个 400 毫秒完成一次调用的智能体使用，授权的动作数量级在一千次上下——所以轮换是便宜的那一半，而挂在凭据上的那条策略才是全部。文章落在那次倒置上——沙箱持有「这是哪一次运行」的证明，授权本体住在箱子外面的一个中介里——以及那个二十分钟的演练：它把论证变成一句话，「这里的一次注入提示授权 N 项动作、横跨 M 个资源」。',
    ),
    L(
      'Playbooks — “Plan review & editing” (Agent UX &amp; Human Interaction): a plan screen looks like the humane alternative to twelve confirmation dialogs, and the term nobody writes down is that it replaces twelve informed decisions with one uninformed one — because a plan is written before any tool has run, so name one step whose arguments are determined before the preceding step finishes and the honest answer is usually none past the first. Keeps steering and authorising apart, specifies the four edits users actually want and why a deletion has to become a standing constraint the planner re-reads on every regeneration, separates the two promises a plan makes silently (scope, and which steps will ask again), gives a mechanical re-ask rule for plan drift, names the four cases where the screen is the wrong product decision, and ends on the edit rate that tells you to delete it.',
      '实战手册《计划的审阅与编辑》（智能体体验与人机交互）：一块计划界面看起来是十二个确认弹窗的人性化替代品，而没人会写下的那一项条款是：它把十二个知情的决定换成了一个不知情的决定——因为计划是在任何工具跑起来之前写的，所以请点出一个「在它前一步跑完之前参数就已确定」的步骤，而诚实的答案通常是第一步之后一个也没有。文章把「掌舵」与「授权」分开，规定了用户真正想要的那四种编辑、以及为何一次删除必须变成一条规划器在每次重新生成时都会重读的常设约束，把计划默默做出的那两个承诺（作用域，以及哪些步骤会再问一次）分开，给出一条应对计划漂移的机械式重问规则，点出这块界面属于错误产品决定的那四种情形，并以那个会告诉你「该把它删掉」的编辑率收尾。',
    ),
    L(
      'Operations — “Migrating off a memory provider” (AgentOps: Deploy &amp; Operate): a vector index is a pure function of corpus and model, so re-indexing is a recomputation you always win; a memory row depends on the provider’s extraction prompt, extraction model, consolidation policy and the order your history arrived, so no re-run converges on what you have — which makes the export a hedge rather than a migration path. Reads the open-core boundary where it actually falls, with the projects’ own words: Mem0 notes its published figures come from a managed platform with optimisations not in the open-source SDK, Cognee labels its Postgres graph store a demo whose production version is a licensed product, and Zep publishes Graphiti while the product engine stays commercial. Shows that importing an export is re-extraction rather than restoration, and lands on the one write-path decision that preserves the exit: never let the provider be the system of record for raw history. Then runs the cutover as a replay with a token budget, and decides it on a frozen eval rather than on scores no vendor can publish on your behalf.',
      '运维《从一家记忆服务商迁走》（AgentOps：部署与运营）：一个向量索引是语料与模型的纯函数，所以重建索引是一次你总能赢的重算；而一条记忆取决于服务商的抽取提示词、抽取模型、整合策略，以及你的历史抵达的顺序——所以没有哪次重跑会收敛到你现在拥有的东西，这就使那份导出成了一份对冲、而不是一条迁移路径。文章把开放内核的边界按它实际落下的位置来读，并用项目自己的说法：Mem0 注明其已发表的数字出自一个托管平台、其优化不在开源 SDK 里；Cognee 把它的 Postgres 图存储标为演示、而可用于生产的版本是一件授权产品；而 Zep 发布 Graphiti、产品引擎则保持商业。文中说明导入一份导出是重新抽取、而不是恢复，并落在那个保住退路的写入通路决定上：绝不让服务商成为原始历史的权威记录方。接着把切换当成一次带 token 预算的重放来跑，并靠一份冻结评测、而不是靠没有哪家厂商能代你发表的那些分数来定夺。',
    ),
  ],
};

export default entry;
