import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-09-16',
  title: L(
    'Two AI Blog posts — on the campaign where nobody chose the 395 victims, and on the four servers that fetch your agent’s documentation from somebody else’s index — plus three pages on trajectories, reasoning that must be carried, and the accessibility agent that builds an overlay',
    '两篇 AI 博客——那场没人挑过那 395 名受害者的行动；以及那四个从别人家索引里给你的智能体取文档的服务端——外加三个页面：轨迹、必须被一路带着的推理，以及那个会造出覆盖层的无障碍智能体',
  ),
  items: [
    L(
      'AI Blog — “Target selection just became free — 395 organisations, 48 countries, one operator”: GreyNoise published a PaperCut campaign that began on 31 August, ran hundreds of AI agents in parallel, and reached 440-plus servers at 395 organisations in 48 countries, 11 of them inside the first twenty-six seconds. The speed is the part already argued elsewhere; the new claim is an economics one. Scanning was always cheap, but per-target exploit adaptation and the unglamorous work after initial access were not, which is why campaigns used to narrow to the victims worth an operator’s evening. This one barely narrowed — credentials taken from 280 of the 395 — and the sector hit hardest was education, at 204 victims, because when selection costs nothing the victim distribution simply tracks exposure, and exposure is highest where capacity is lowest. There is no AI-shaped signature to detect: the tooling was commodity and the model sat in the operator’s workflow. What is left is the asset question, a patch SLA priced against a mass-exploitation window measured in days, and containment nobody has to approve.',
      'AI 博客《挑目标这件事刚刚变成了免费的——395 家组织、48 个国家、一名操作者》：GreyNoise 公布了一场自 8 月 31 日开始的 PaperCut 行动：数百个 AI 智能体并行运行，触及 48 个国家、395 家组织的 440 余台服务器，其中 11 家是在头二十六秒内被拿下的。速度那部分别处已经论证过；新的那个论断属于经济学。扫描一向便宜，但逐目标的利用代码适配、以及初始访问之后那段不体面的活儿并不便宜——正因如此，从前的行动会收窄到「值得操作者一个晚上」的那些受害者。这一场几乎没收窄——395 家里有 280 家被取走凭据——而受灾最重的部门是教育，204 家受害者；因为当挑选不花钱，受害者的分布就只是跟着暴露面走，而暴露面恰恰在能力最薄弱的地方最高。没有什么「AI 形状」的特征可供检测：工具是现成货，模型待在操作者的工作流里。剩下的是那个资产问题、一份对着以天计的大规模利用窗口来定价的补丁 SLA，以及一项不需要任何人批准的遏制。',
    ),
    L(
      'AI Blog — “Context7 vs DeepWiki vs GitMCP vs Ref: your agent’s documentation is somebody else’s index”: all four fix the stale-API problem and the axis nobody tables is provenance. GitMCP serves upstream files as they were committed, preferring the repository’s own llms.txt; Context7 and Ref return fragments extracted from upstream, capped and deduplicated; DeepWiki returns prose a model wrote about the code, which is the right input for “how is this repo built” and the wrong one for “what is this signature”, because a generated error arrives in the same confident register as a generated truth. The second finding is that none of them closes the failure they are sold against: staleness is not version drift, and a tool that returns current upstream to a service pinned two years back has made the mismatch more plausible rather than smaller. Nothing reads your lockfile — Context7 takes a version you name in the prompt — so resolving the pin is fifteen lines of harness code. And every one of them is a retrieval channel into a model that is, by construction, in the mood to follow instructions it finds in documentation.',
      'AI 博客《Context7、DeepWiki、GitMCP 与 Ref：你的智能体读的文档，是别人家的索引》：四个都治好了「API 陈旧」这个问题，而没人列进表格的那根轴是出处。GitMCP 把上游文件按提交时的样子送出，并优先用仓库自己的 llms.txt；Context7 与 Ref 返回从上游抽取出来的片段，有上限也做去重；DeepWiki 返回的是模型写的、关于这份代码的散文——对「这个仓库是怎么搭起来的」它是对的输入，对「这个签名是什么」它是错的，因为一个生成出来的错误，与一个生成出来的真相，抵达时的笃定语气一模一样。第二个发现是：它们谁都没堵上自己被拿来对治的那处失效——陈旧不等于版本漂移，而一个把当前上游返回给一个钉在两年前的服务的工具，是把那处错配变得更像真的，而不是变小了。没有一个会读你的 lockfile——Context7 认的是你在提示词里点的那个版本——所以解析那个钉住的版本是十五行外壳代码。而它们每一个都是一条通向模型的检索通道，而那个模型从构造上就正处在「愿意照着文档里读到的指示办」的心情里。',
    ),
    L(
      'Concepts — Trajectories: an agent’s real output is the whole ordered path from goal to termination, and that path is the only place a correct answer and a lucky one look different — the final message is a summary written by the system you are trying to judge. Two agents can answer identically when one quoted the policy and the other guessed; the trajectory also separates “wrong output, sound process” (a stale tool) from a model failure someone is about to fix by editing the prompt. The obstacle is structural: most observability arrived from the LLM-API era where the natural row is one model call, so retries, resumes, delegation, model fallbacks and everything that is not a model call each break the thread. Mint a run ID when the goal arrives and make it the primary key, then treat the store as both the asset that makes replay and production-derived evals possible and the most concentrated copy of your data that exists.',
      '概念 — 轨迹：智能体真正的产出，是从目标到终止那条完整有序的路；而那条路是唯一一处能让「答对了」与「蒙对了」看上去不一样的地方——最后那条消息，是由你正要评判的那个系统写的一份摘要。两个智能体可以给出一模一样的答案，而其中一个引用了政策、另一个是猜的；轨迹还能把「输出错、过程稳」（一个返回陈旧数据的工具）与一次即将被某人靠改提示词去修的模型失灵区分开。障碍是结构性的：多数可观测性来自 LLM API 时代，那里天然的一行就是一次模型调用，于是重试、续跑、委派、模型降级，以及一切不是模型调用的东西，都会把线头弄断。目标到达时铸一个 run ID 并让它成为主键；随后把那个存储同时当作两样东西——让重放与源自生产的评测成为可能的那项资产，以及你的数据在世上最集中的那份副本。',
    ),
    L(
      'Deep-Dives — Carrying Reasoning Across Tool Calls: reasoning stopped being output you discard and became a signed, opaque input you must hand back unchanged, and three vendors built three incompatible versions of that rule — Anthropic’s thinking blocks with signatures, OpenAI’s reasoning items held server-side or returned encrypted, and Gemini 3 thought signatures whose omission is a validation error rather than a degradation. A tool call is a pause inside one assistant turn, so stripping the blocks converts one deliberation into a sequence of independent guesses. The part that breaks working harnesses is the prefix rule: a block stays valid only while the system prompt, the tool definitions and every earlier message are unchanged, which makes appending a reminder, adding a tool mid-run, trimming history and re-serialising the messages array all destructive operations. The quiet failures are worse than the 400 — toggling thinking mid-turn silently disables it, and a fallback down to an older model drops its reasoning without an error. Echo, never rebuild.',
      '深入解析 — 把推理一路带过工具调用：推理不再是你丢掉的产出，而变成了一个带签名、不透明、必须原样交还的输入；而三家厂商造出了这条规则的三个互不兼容的版本——Anthropic 的带 signature 的 thinking 块、OpenAI 那些留在服务端或加密返回的推理条目，以及 Gemini 3 的思维签名（漏掉它是一个校验错误，而不是一次降级）。一次工具调用是一个助手回合内部的暂停，所以把这些块剥掉，等于把一次深思熟虑换成一串彼此独立的猜测。会弄坏在跑的外壳的，是那条前缀规则：一个块只在系统提示词、工具定义与它之前的每条消息都没变时才保持有效——于是追加一句提醒、运行途中加个工具、裁剪历史、把消息数组重新序列化，全都成了破坏性操作。那些安静的失效比 400 更糟——在回合中途切换思考会悄悄把它关掉，而向下降级到一个更旧的模型会不报错地丢掉它的推理。回送，绝不重建。',
    ),
    L(
      'Playbooks — Accessibility Remediation Agents: “reduce scanner violations” is a reward-design mistake, and a competent agent finds its minimum — an aria-label that renames a control to anything, a role that promises keyboard behaviour the div does not implement, an aria-hidden that deletes the feature for the people the work was for. That is an accessibility overlay built inside your own repository, and overlays are the field’s cautionary tale for exactly this reason. Automated testing reaches roughly 57% of failures by count on the toolmaker’s own study and less on independent measurement, and counts are by instance rather than by impact, so four hundred footer contrast failures outrank one keyboard trap in the checkout. Make the unit of work a keyboard-only user journey driven in a real browser, fix in the design system rather than at four hundred call sites, forbid edits to the scanner config in CI, and require every pull request to carry a before-and-after focus trace plus an accessible-name assertion as its proof.',
      '实战手册 — 无障碍整改智能体：「减少扫描违规数」是一个奖励设计上的错误，而一个能干的智能体会找到它的极小值——一个把控件随便改名的 aria-label、一个承诺了 div 并未实现的键盘行为的 role、一个把功能从本该受益的那群人那里删掉的 aria-hidden。那就是在你自己仓库里造出来的一个无障碍覆盖层，而覆盖层之所以是这个领域的前车之鉴，原因正在于此。自动化测试按条数计，在工具制造方自家的研究里够到约 57% 的失效，独立测量还更低；而计数是按实例而不是按影响算的，于是页脚里四百个对比度失效会盖过结算流程里一个键盘陷阱。让工作的单位是一条在真实浏览器里仅用键盘走的用户旅程，在设计系统而不是在四百个调用点上修，在 CI 里禁止改动扫描器配置，并要求每个 PR 都带上修复前后的焦点轨迹与一条可访问名称断言作为它的证明。',
    ),
  ],
};

export default entry;
