import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-09-15',
  title: L(
    'Two AI Blog posts — on the browser API that turns your forms into an authenticated API surface, and on the four Python agent libraries where only one changes your threat model — plus three pages on subagents, prior authorization, and the sandbox pool nobody sized',
    '两篇 AI 博客——把你的表单变成一个带鉴权的 API 面的那个浏览器 API；以及那四个 Python 智能体库里唯一会改变你威胁模型的那一个——外加三个页面：子智能体、事前授权，以及那个没人算过大小的沙箱池',
  ),
  items: [
    L(
      'AI Blog — “WebMCP makes your page an API, and the session is the only auth it has”: the draft lets a page register named tools through document.modelContext, with a declarative path that turns an existing HTML form into a tool declaration for almost nothing. The post argues the interesting property is authority rather than discovery: a registered tool’s execute callback is ordinary page JavaScript in your origin, so it carries the logged-in user’s cookies to your backend and your server receives a request it cannot distinguish from a click — a confused deputy where your page is the deputy and a consent prompt granted once covers a task of forty calls. It is a W3C Draft Community Group Report, not a standard, tools-only with resources and prompts out of scope, shipping behind a flag in one engine, and the entry point has already moved from navigator.modelContext. Prototype the client half; ship the server half — label the tool path with a header, re-authorise per action, and give it its own quota.',
      'AI 博客《WebMCP 把你的页面变成了一个 API，而它唯一的鉴权就是那个会话》：草案让页面通过 document.modelContext 注册具名工具，还有一条声明式路径，几乎不花什么代价就能把一个既有的 HTML 表单变成一份工具声明。文章论证：有意思的性质是权限而不是发现——一个注册过的工具，其 execute 回调就是你来源下寻常的页面 JavaScript，于是它带着已登录用户的 cookie 去调你的后端，而你的服务器收到的是一个它无法与点击区分开的请求；这是一个「被搞糊涂的代理人」，代理人是你的页面，而一次给出的同意覆盖了一次含四十次调用的任务。它是一份 W3C Draft Community Group Report，不是标准，只做 tools 而 resources 与 prompts 不在范围内，只在一个引擎里藏在实验标志后面发布，入口还已经从 navigator.modelContext 挪走过。客户端那一半拿来做原型，服务端那一半才交付：用一个 header 给工具路径打标、按动作重新授权、给它单独的配额。',
    ),
    L(
      'AI Blog — “Pydantic AI vs Agno vs smolagents vs Strands: only one of them changes your threat model”: three of the four dispatch JSON against a table you populated, so the damage ceiling is the tools you registered and a capability review is a review of a list. smolagents has the model write Python — its default AST-walking executor allow-lists imports and caps operations, and the project says plainly it is safer than exec() and not a boundary — so the real comparison is smolagents plus a sandbox, and adopting it means adopting sandboxing as a subsystem. The second axis nobody prices is state: Pydantic AI (MIT) and smolagents own nothing durable and swap in a weekend, Agno’s AgentOS owns sessions, memory and approvals and becomes a system of record, and Strands is AWS-shaped by design. Which inverts the star chart — Agno leads at about 41.8k with the highest exit cost, and Strands trails above 2k with a cloud provider behind it.',
      'AI 博客《Pydantic AI、Agno、smolagents 与 Strands：只有一个会改变你的威胁模型》：四者中有三个是对着一张你填好的表派发 JSON，于是损害上限就是你注册过的那些工具，而一次能力评审就是一份清单的评审。smolagents 让模型写 Python——它默认那个遍历 AST 的执行器按白名单放行导入、给操作次数设上限，而项目直言它比 exec() 安全、但不是一道边界——所以真正该比的是「smolagents 加一个沙箱」，而采用它就意味着把沙箱化当作一个子系统来采用。第二根没人计价的轴是状态：Pydantic AI（MIT）与 smolagents 不持有任何持久之物，一个周末就能换掉；Agno 的 AgentOS 持有会话、记忆与审批，会变成一套记录系统；而 Strands 从设计上就是 AWS 形状的。这把那张 star 图倒了过来——Agno 以约 41.8k 领先，退出成本却最高；Strands 以 2k 出头垫底，背后却站着一家云厂商。',
    ),
    L(
      'Concepts — Subagents: a subagent buys exactly one thing, a second context window that fills up and vanishes, so the persona is free and does nothing while the isolation is the product. The test for whether one pays is a ratio — how much context it consumes against how much it returns — which most cast lists survive in two roles and lose the rest. And because the child’s evidence is unrecoverable the moment it returns, “I found nothing” and “I failed to look” arrive as the same sentence: return handles the parent can re-open, make absence explicit in the schema, and carry provenance so a later contradiction is resolvable. Delegation is not free either — every child is a full prompt, parallel only helps when the work is independent, and the goal reaches the child only through the task string, so drift compounds with depth.',
      '概念 — 子智能体：子智能体只买到一样东西，第二个会被填满、然后消失的上下文窗口；所以人设是免费的、也什么都不顶用，而隔离才是那件商品。判断它划不划算靠一个比值——它吃掉多少上下文，对比它返回多少——多数班底名单能靠这个活下来两个角色，其余全数出局。而由于孩子一返回、它的证据就无从追回，「我什么都没找到」与「我根本没找成」抵达时是同一句话：返回父方可重新打开的句柄，在 schema 里让「没有」显式存在，并把出处一路带上，好让日后的矛盾是可判的。委派也不免费——每个孩子都是一整段提示词，只有工作彼此独立时并行才帮得上忙，而目标只能经由那根任务字符串抵达孩子，于是漂移随深度复利。',
    ),
    L(
      'Playbooks — Prior Authorization Agents: statute has already split this workflow and handed the agent the half nobody sells. California’s SB 1120 and eleven states’ worth of 2025–2026 laws put medical-necessity denials with a licensed clinician while expressly permitting AI for administrative work and organising clinical information — so build an agent that can approve, assemble and escalate, with the denial branch absent from the code rather than gated behind a flag. Since 1 January 2026 impacted payers owe 72 hours expedited and 7 calendar days standard with a specific reason on every denial, while the FHIR Prior Authorization API does not arrive until 2027, so separate the portal-scraping layer from the evidence-assembly layer and expect to throw one away. Optimise first-pass completeness rather than approval rate, because 81.7% of appealed denials are overturned in full or part and the real label matures weeks late — and read WISeR, where Texas requests ran 62% approved by machine against 84% after human review, as a lesson about a vendor paid from the reductions it produces.',
      '实战手册 — 事前授权智能体：法律已经把这条工作流劈开，并把没人在卖的那一半交给了智能体。加州 SB 1120 与 2025–2026 年间十一个州的法律，把医疗必要性拒付交给持照临床医师，同时明确准许把 AI 用于行政性工作与整理临床信息——所以要建一个能批准、能组装、能上报的智能体，并让拒付那条分支在代码里干脆不存在，而不是藏在一个开关后面。自 2026 年 1 月 1 日起，受影响的付款方欠你的是加急 72 小时、常规 7 个日历日，且每一次拒付都须附具体理由；而 FHIR 的 Prior Authorization API 要到 2027 年才到，所以把门户抓取那一层与证据组装那一层分开，并预期要扔掉其中一个。该优化的是「一次过完整率」而不是批准率，因为 81.7% 被申诉的拒付会被全部或部分推翻，而真正的标签要几周后才成熟——再把 WISeR 读作一堂关于「厂商从自己产生的削减中取酬」的课：在得克萨斯，机器的初次批准率为 62%，人工复核后为 84%。',
    ),
    L(
      'Operations — Sandbox Pools &amp; Cold Starts: every sub-100ms sandbox number is a snapshot restore measured one at a time, and neither half survives a fan-out — on an open, dated benchmark one provider records an 83ms median sequentially and a 14.8-second median at concurrency 100, and the ordering between providers very nearly inverts between the two tables. Warm and clean turn out to be one knob: Firecracker’s own documentation calls resuming the same state more than once insecure, because the entropy pool, cached identifiers and any secrets fetched before the snapshot all repeat. So key the sandbox by your trust boundary rather than by the convenient name, size the pool with Little’s law at a hold time measured in minutes — one slow tool triples your concurrent count at unchanged traffic — and check the billing shape, because whether idle is free is a property of the provider and the answers are opposite.',
      '运维 — 沙箱池与冷启动：每一个「百毫秒以内」的沙箱数字都是一次快照恢复、且是一个一个量出来的，而这两半碰上扇出都活不下来——在一份公开、带日期的基准里，某家厂商串行录得 83 毫秒中位数，并发 100 时录得 14.8 秒中位数，而两张表之间各家的排序几乎完全倒置。「热」与「干净」原来是同一个旋钮：Firecracker 自家文档称从同一份状态恢复超过一次即不安全，因为熵池、缓存下来的标识符，以及快照拍下之前取到的任何凭证，全都会重复。所以按你的信任边界给沙箱定键，而不是按那个顺手的名字；用 Little 定律在一个以分钟计的持有时间上算池子大小——一个慢工具就能在流量不变时把并发数变成三倍；并去查计费形状，因为空转免不免费是厂商的属性，而各家给的答案是相反的。',
    ),
  ],
};

export default entry;
