import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-08-25',
  title: L(
    'Two AI Blog posts on what an AI code reviewer actually charges you and on A2A moving in with MCP, plus three pages on ad operations, agent notifications and model risk management',
    '两篇 AI 博客——AI 代码评审真正向你收取的是什么，以及 A2A 搬进 MCP 的屋檐——外加三个页面：广告运营、智能体通知，以及模型风险管理',
  ),
  items: [
    L(
      'New blog post — *CodeRabbit vs Greptile vs Bugbot vs Diamond: you are buying a comment budget*. In 2026 the four split into three billing shapes: CodeRabbit still sells a capped seat at $24 per developer per month on annual terms, Greptile moved in March to a $30 seat covering 50 reviews and $1 each after that, Bugbot dropped its $40 seat for per-run billing on 8 June at a reported $1.00–1.50 a run, and Diamond has no separate price because it arrives with Graphite — which Cursor acquired on 19 December 2025, so two of the four now share an owner. Runs the list prices out to show the seat and the meter crossing at roughly twenty reviews per developer per month, and argues the second-order effect matters more than the first: metered billing eventually produces a rule that excludes the small automated pull requests where regressions hide. Sets the published accuracy figures against each other honestly — Greptile\'s own benchmark on 50 open-source pull requests reports 82% catch and 11 false positives against CodeRabbit\'s 44% and 2, another 2026 comparison calls Greptile the quieter of the two, a third-party roundup puts Diamond at 0.62 comments per pull request and Bugbot at 0.91, and Martian\'s independent study ranked CodeRabbit first of ten — and concludes that the invariant is the steepness of the trade-off, not any tool\'s position on it. Prescribes a hard per-pull-request comment cap ranked worst-first, measuring dismissal rather than detection, and a two-week parallel bake-off as the only procedure that answers the question. Three themeable SVGs.',
      '新博客文章——《CodeRabbit vs Greptile vs Bugbot vs Diamond：你买的是一份评论预算》。2026 年，这四家分裂成三种计费形态：CodeRabbit 仍在卖带上限的席位，年付每人每月 24 美元；Greptile 3 月改成 30 美元席位含 50 次评审、之后每次 1 美元；Bugbot 6 月 8 日扔掉 40 美元席位改为按次计费，单次报道约 1.00–1.50 美元；而 Diamond 没有单独定价，因为它随 Graphite 一起来——Cursor 已于 2025 年 12 月 19 日收购 Graphite，于是四家里有两家如今同属一个东家。文章把公开价格拉成曲线，显示席位与计价表在每人每月约二十次评审处交叉，并论证二阶效应比一阶更要紧：按量计费迟早会催生一条把小型自动化 PR 排除在外的规则，而回归恰恰藏在那里。文中诚实地把各家公开的准确率数字摆在一起互相对照——Greptile 自己在 50 个开源 PR 上的跑分报出 82% 发现率与 11 个误报，对 CodeRabbit 的 44% 与 2 个；另一份 2026 年的对比却称 Greptile 是两者中更沉默的那个；一份第三方汇总把 Diamond 记作每 PR 0.62 条评论、Bugbot 0.91 条；而 Martian 的独立研究把 CodeRabbit 排在十个工具之首——并得出结论：不变量是这个权衡有多陡，而不是任何工具落在其上的位置。处方是：按最坏优先排序的每 PR 硬性评论上限、衡量驳回而不是检出，以及一次两周的并行对跑——那是唯一能回答这个问题的流程。配三张可随主题变色的 SVG。',
    ),
    L(
      'New blog post — *A2A moved in with MCP; the identity layer stayed outside*. On 20 August 2026 Google moved A2A into the Agentic AI Foundation, which was stood up under the Linux Foundation in December 2025 with 49 members and the MCP, goose and AGENTS.md donations, passed 170 members in April and now counts more than 250. Grants the steelman in full — trademark and repository continuity, a public Spec Enhancement Proposal process, and one technical committee that cannot ship contradictory answers to the authentication and delegation questions both specs face — then argues that no trust boundary moved: an MCP tool description is an installation decision you can pin, diff and roll back, while an A2A agent card is fetched at discovery time from a URL the counterparty controls, and its JWS signature proves origin rather than behaviour. Points at the detail nobody headlined: the MCP-Identity framework was donated in March 2026 not to the AAIF but to the Decentralized Identity Foundation, so the protocols consolidated while the primitive underneath them did not. Names the artefact that would prove consolidation is real — one delegation credential normatively referenced by both specifications — and notes that membership is a commercial commitment with no conformance test behind it, which is why a certification track sits on the foundation\'s own roadmap. Three SVGs.',
      '新博客文章——《A2A 搬进了 MCP 的屋檐，身份层却留在门外》。2026 年 8 月 20 日，谷歌把 A2A 迁入 Agentic AI Foundation；该基金会 2025 年 12 月在 Linux 基金会名下成立，起步 49 家会员，带着 MCP、goose 与 AGENTS.md 三项捐赠，4 月越过 170 家，如今已超过 250 家。文章先把最强的一面完整给足——商标与仓库的连续性、公开的规范增强提案（SEP）流程，以及一个不可能对两份规范共同面对的认证与委托问题给出互相矛盾答案的技术委员会——随后论证没有任何一条信任边界发生移动：一份 MCP 工具描述是一次你可以固定、比对、回滚的安装决定，而一张 A2A 智能体名片是在发现时从对方控制的 URL 取回的，其 JWS 签名证明的是来源而非行为。文章点出那个没人写成标题的细节：MCP-Identity 框架在 2026 年 3 月被捐给的不是 AAIF，而是去中心化身份基金会——于是协议合并了，底下的原语没有。文中给出能证明合并为真的那件产物——一份被两份规范同时规范性引用的委托凭证——并指出会籍是商业承诺、背后并无一致性测试，这也正是基金会自己的路线图上会有一条认证轨道的原因。配三张 SVG。',
    ),
    L(
      'New Playbook (Domain Playbooks) — *Marketing &amp; Ad-Operations Agents*. One of the few domains where the agent holds a live spend lever and a feedback number that updates hourly — and that number is close to pure noise at the timescale the agent wants to act on, so an agent left to optimise on it chases randomness with real money. Adds the constraint most builds miss: the ad platform already runs its own bidding optimiser on the account, so your agent is a second controller on a plant that has one, and every structural edit pushes a campaign back into an unrepresentative learning phase. Prescribes a minimum change interval enforced in the tool rather than the prompt, an observation window expressed in conversions instead of hours, pre-registered decision rules, an objective function taken from your own warehouse rather than from platform-reported conversions (every platform claims the same one), platform-side spend caps and a per-run change budget, and a first build with no write access at all — five checks covering broken conversion tracking, taxonomy violations, pacing exceptions, spend anomalies and reconciliation breaks, measured on money recovered from misconfiguration rather than on lift.',
      '新增实战手册（领域实战手册）——《营销与广告运营智能体》。这是少有的一个领域：智能体手里握着一根实时的花钱杠杆，还有一个每小时刷新的反馈数字——而在它想动手的时间尺度上，这个数字接近纯噪声，于是被放任去"优化"的智能体会拿真金白银追逐随机性。文章补上多数方案漏掉的那条约束：广告平台早已在账户上跑着自己的竞价优化器，所以你的智能体是投在一个已有控制器的被控对象上的第二个控制器，而每一次结构性编辑都会把广告系列推回一个不具代表性的学习期。处方包括：在工具而非 prompt 里强制的最小变更间隔、用转化数而不是小时数表达的观察窗口、预先登记的决策规则、取自你自己数仓而非平台上报转化的目标函数（每个平台都会认领同一笔转化）、平台侧花费上限与每次运行的变更预算，以及一个完全没有写权限的第一版——五项检查覆盖转化埋点损坏、分类规范违例、节奏异常、花费异常与对账断点，用"从配置错误里追回的钱"而不是用提升来衡量。',
    ),
    L(
      'New Playbook (Agent UX &amp; Human Interaction) — *Notifications &amp; Digests*. Deciding to interrupt someone is a second policy, separate from the one that does the work, and almost nobody builds it that way — which is why capable ambient agents die of mute rather than of error. The cost function is asymmetric and it ratchets: a useless notification permanently lowers the attention the next fifty get, and mute is an absorbing state. Argues for routing by decision deadline rather than importance (interrupt now / digest / log only), escalating to a different recipient rather than repeating, writing the notification so the decision fits inside it — what changed, the evidence, what happens if nobody replies, and the undo next to the action — and rate-limiting per recipient across all agents in the notification service, where the agent gets no vote and can declare no exception. Closes on the three numbers worth collecting: actioned-within-window rate as the primary metric, mute rate as the guard metric, and missed-signal rate, which almost nobody has because it can only be obtained by sampling incidents backwards.',
      '新增实战手册（智能体体验与人机交互）——《通知与摘要》。决定要不要打扰一个人，是与干活那套完全分离的第二套策略，而几乎没有人是这么建的——这正是有能力的环境智能体死于被静音、而不是死于出错的原因。这里的代价函数不对称且只进不退：一条无用的通知会永久压低接下来五十条所得到的注意力，而静音是一个吸收态。文章主张按决策期限而非重要性路由（立刻打断／摘要／只记日志）、无人响应时升级给另一位收件人而不是重发、把通知写成决策能在其内部完成的样子——变了什么、证据、没人回复会怎样，以及紧挨动作的撤销——并在通知服务里按收件人跨所有智能体限流，那里智能体没有投票权、也无权宣布例外。文末落在三个值得采集的数字：作为首要指标的"窗口内被处理率"、作为护栏指标的静音率，以及几乎没人拥有的信号漏报率——因为它只能靠倒着抽查事故才拿得到。',
    ),
    L(
      'New Operation (Governance &amp; Compliance) — *Model Risk Management for Agents*. On 17 April 2026 the Federal Reserve, OCC and FDIC issued SR 26-2, replacing SR 11-7 and putting generative and agentic AI outside its scope with separate guidance promised later — so an agent touching a credit decision or an AML alert lost the framework while the law over the decision stayed exactly where it was, and "we are waiting for the guidance" became the default failure mode. Argues the risk object is the action set rather than the model (two agents on identical weights, one read-only and one holding a payment tool, share no risk at all), re-points the three validation activities at trajectories — conceptual soundness as a design review of the loop, ongoing monitoring as tool-mix and escalation-rate drift, outcomes analysis as a permanent adjudicated sample because an agent has no backtest — fixes the inventory unit as the model/prompt/tools/policy tuple generated from deployment configuration, and files the agent under the existing three-lines-of-defence structure with a signed framework-determination memo per entry.',
      '新增运维页（治理与合规）——《面向智能体的模型风险管理》。2026 年 4 月 17 日，美联储、OCC 与 FDIC 发布 SR 26-2 取代 SR 11-7，并把生成式与智能体式 AI 排除在适用范围之外，另行指引留待日后——于是经手授信决定或反洗钱告警的智能体失去了框架，而管辖那个决定的法律一寸没挪，"我们在等新指引"也就成了默认的失效模式。文章论证风险对象是动作集合而不是模型（权重完全相同的两个智能体，一个只读、一个握着支付工具，二者毫无共同风险），把三项验证活动重新对准轨迹——概念健全性变成对循环的设计评审、持续监控变成工具组合与上报率的漂移、结果分析变成一份长期存在并经裁定的抽样，因为智能体没有回测——把清单的登记单元定为由部署配置生成的"模型／提示／工具／策略"四元组，并把智能体归入既有的三道防线结构，每条记录配一份签了字的框架归属备忘录。',
    ),
  ],
};

export default entry;
