import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-07-29',
  title: L(
    'Fixed more blog-chart labels hidden behind boxes, and hardened the SVG guard to catch that class of defect',
    '修复了更多被方框遮住的博客图表标签，并强化了 SVG 检测使其能发现这一类问题',
  ),
  items: [
    L(
      'Fixed: on the Exa vs Tavily vs Brave Search vs Firecrawl post, the context-cost bar chart\'s `.body-text { text-anchor: middle; }` rule silently beat every individual label\'s `text-anchor="start"/"end"` attribute — a CSS rule always wins that contest — recentring labels authored to sit flush against their bars. "Brave (snippet)" and "~200 tokens" overlapped by 46px, rendering as unreadable mashed-together text; "Tavily (basic)" and "~500 tokens" overlapped by 15px; and "~8,000 tokens" was pushed 8px past the viewBox, clipping its final letter. Split the shared class into `.row-label` (text-anchor: end) and `.value-label` (text-anchor: start) so the CSS matches each label\'s role instead of overriding it, and widened the viewBox from 900 to 980 so the widest value label — the one beside the 8,000-token bar, which reaches all the way to x=850 — can sit outside its bar exactly like the other three instead of needing different treatment. Same file, so the fix covers the Chinese post too.',
      '修复：在《Exa、Tavily、Brave Search 与 Firecrawl》一文的上下文开销柱状图里，`.body-text { text-anchor: middle; }` 这条规则悄悄压过了每个标签自己的 `text-anchor="start"/"end"` 属性——CSS 规则总是赢过表现属性——把本该贴紧柱子首尾对齐的标签统统拉回了居中。"Brave (snippet)" 与 "~200 tokens" 重叠 46px，两行字挤成一团难以辨认；"Tavily (basic)" 与 "~500 tokens" 重叠 15px；"~8,000 tokens" 被推出画布 8px，最后一个字母被裁掉。现在把共用的类拆成 `.row-label`（右对齐）与 `.value-label`（左对齐），让 CSS 与每个标签的角色对应而不是覆盖它，并把 viewBox 从 900 拓宽到 980，好让最宽的那个数值标签——挨着一路画到 x=850 的八千令牌那根柱子——能像其余三行一样安安稳稳地待在柱子外侧，而不必单独将就。中英文两个版本共用同一个文件，这一次修复两边都覆盖到了。',
    ),
    L(
      'Fixed a smaller instance of the same bug family on the pgvector vs Pinecone vs Weaviate vs Qdrant architecture diagram, where the "tenant_id, created_at…" and "tags, source, lang" captions in two adjacent boxes overlapped by 5px; trimmed both to 11px so they clear each other.',
      '同一类问题在《pgvector、Pinecone、Weaviate 与 Qdrant》架构图上还有一处更小的实例：相邻两个方框里的 "tenant_id, created_at…" 与 "tags, source, lang" 说明文字重叠了 5px；把两处字号都收到 11px，重叠随之消失。',
    ),
    L(
      'Fixed the same class-rule bug\'s second symptom, missed in the first pass and spotted on a live preview: a label recentred by a CSS override does not always collide with ANOTHER label — on the LiteLLM vs Portkey vs Cloudflare vs Kong and Exa vs Tavily vs Brave vs Firecrawl posts\' feature-matrix diagrams, `.body-text { text-anchor: middle; }` beat the row labels\' `text-anchor="end"` and the legend\'s `text-anchor="start"` the same way the context-cost chart\'s labels were beaten, but a row label\'s neighbour is a box, not another label, so nothing collided and nothing escaped the viewBox — the two checks the first pass added both stayed green while the diagrams were visibly broken. Recentred row labels bled into the first column of cells ("LiteLLM" rendering as "LiteLL", "Portkey" as "Portke", "Cloudflare" as "Cloudfla", "Firecrawl" as "Firecra"), and all three legend entries ("Strong", "Partial", "Not the job") sat on top of their own colour swatches. Split the shared class into role-specific `.row-head` (text-anchor: end) and `.legend-text` (text-anchor: start) classes — the pattern every newer feature-matrix diagram on the site already uses — so the CSS matches each label\'s role instead of overriding it. Also fixed two differently-caused but similarly-shaped defects on the ElevenLabs vs Vapi vs Retell vs OpenAI Realtime post\'s architecture diagram: "Call audio in" was clipped by the STT box because the label sat at the box\'s own mid-height instead of above the connector line, and the "Voice quality is the moat." annotation sat on top of the unrelated Tool-use box because its y-position put it in that box\'s row instead of under the TTS box it actually describes. All three SVGs are shared between the en and zh posts, so each fix covers both languages.',
      '修复了同一条 class 规则漏洞的第二种症状——第一轮排查漏掉了它，是在线上预览里被发现的：被 CSS 规则重新居中的标签，不一定会跟"另一个标签"重叠。在《LiteLLM、Portkey、Cloudflare 与 Kong》和《Exa、Tavily、Brave Search 与 Firecrawl》两篇文章的能力矩阵图里，`.body-text { text-anchor: middle; }` 同样压过了行标签的 `text-anchor="end"` 和图例的 `text-anchor="start"`——跟上下文开销图表的标签被压过的方式一模一样——但行标签紧挨着的是一个方框，不是另一个标签，所以既没有文字重叠，也没有跑出 viewBox，第一轮新增的那两道检测全程绿灯，图表却明显是坏的。被拉回居中的行标签一头扎进了第一列方框："LiteLLM" 显示成了 "LiteLL"，"Portkey" 显示成了 "Portke"，"Cloudflare" 显示成了 "Cloudfla"，"Firecrawl" 显示成了 "Firecra"；三条图例文字"Strong"、"Partial"、"Not the job" 也都叠在了各自的色块上面。现在把共用的类拆成按角色区分的 `.row-head`（右对齐）与 `.legend-text`（左对齐）——这正是全站更新的能力矩阵图早就在用的写法——让 CSS 与每个标签的角色对应，而不是覆盖它。同时修复了《ElevenLabs、Vapi、Retell 与 OpenAI Realtime》一文架构图上两处成因不同、但表现相似的问题："Call audio in" 被 STT 方框裁掉了一截，是因为标签停在方框自身的竖直中线上，而不是箭头线的上方；"Voice quality is the moat." 这行注解叠在了不相关的 Tool use 方框上，是因为它的纵坐标落进了那个方框所在的那一行，而不是它真正描述的 TTS 方框下方。这三张 SVG 都是中英文两篇文章共用的文件，一次修复两边都覆盖到了。',
    ),
    L(
      'Extended the SVG guard with a third check, added to the same test and reusing the same page load as the other two rather than a separate pass: fails when a `<text>` overlaps a filled `<rect>` (skipping `fill: none` and anything under 50% opacity, whether via fill-opacity or the element\'s own opacity — the decorative background wash behind the ElevenLabs pipeline diagram uses the latter) with real horizontal overlap and vertical overlap past 50% of the label\'s own height, AND the label\'s horizontal centre falls outside the box. The centre test is what separates a label that drifted onto a box it was never meant to touch from a caption deliberately centred over a wide band — an arrow-crossing annotation that legitimately grazes the boundary between the two boxes it connects, which is what most of the eight architecture diagrams\' fifteen edge captions turned out to be on inspection (each confirmed benign by screenshot, listed with its reason in an explicit `KNOWN_INTENTIONAL_BOXED_LABELS` allowlist rather than silently exempted by a loosened threshold, so a genuinely new instance of the bug can\'t hide behind it and a stale entry left behind by a diagram redesign fails the suite until removed). Verified the new check fails correctly: reverted the LiteLLM/Portkey/Cloudflare/Kong fix and confirmed the assertion named all six real defects by label and percentage — "LiteLLM" 16%, "Portkey" 15%, "Cloudflare" 24%, "Strong" 33%, "Partial" 32%, "Not the job" 28% — before restoring it.',
      '给 SVG 检测新增了第三项检查，加进了同一个测试、复用同一次页面加载，而不是另起一遍：只要某个 `<text>` 与某个填色的 `<rect>` 发生真实重叠（跳过 `fill: none`，以及不透明度低于 50% 的方框——不论是通过 fill-opacity 还是元素自身的 opacity，ElevenLabs 那张流程图背景的装饰性浅色底就是用后一种方式实现的），且水平方向有交叠、垂直方向的交叠超过标签自身高度的 50%，并且标签的水平中心点落在方框的横向范围之外，就判为不通过。"中心点是否在方框外"这一条，正是用来区分"标签被意外挪到了一个它本不该碰的方框上"和"标签本来就故意居中横跨在一条较宽的区域上"——后一种情况多是穿过箭头连接线、合理蹭到所连接两个方框边界的说明文字，八张架构图里的十五处这类标注逐一核实后确认基本都属于这种情况（每处都用截图确认过显示清晰无碍，各自带着理由列在明确的 `KNOWN_INTENTIONAL_BOXED_LABELS` 白名单里，而不是靠放宽阈值悄悄放过——这样真正的新缺陷藏不进去，图表改版后失效的旧白名单条目也会让测试失败，直到被删除为止）。也验证过这道新检测真的会失败：把 LiteLLM/Portkey/Cloudflare/Kong 那处修复先还原，检测精确报出了全部六处真实缺陷的标签与百分比——"LiteLLM" 16%、"Portkey" 15%、"Cloudflare" 24%、"Strong" 33%、"Partial" 32%、"Not the job" 28%——确认无误后再恢复修复。',
    ),
    L(
      'Updated the guard\'s description in the daily content batch routine (`docs/routines/daily-content-batch.prompt.md`) to cover all three checks — same-line collisions, viewBox escapes, and labels sitting on a filled box — not just the first two.',
      '更新了每日内容批处理流程文档（`docs/routines/daily-content-batch.prompt.md`）里对这道检测的说明，把三项检查——同一行文字重叠、跑出 viewBox、标签叠在填色方框上——都写全了，而不只是前两项。',
    ),
  ],
};

export default entry;
