import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-08-10',
  title: L(
    'Two AI Blog posts on DeepSeek building its own harness and what the four observability platforms actually meter, plus four pages on serious-incident reporting, citation UX, procurement agents and parameter-efficient fine-tuning',
    '两篇 AI 博客——DeepSeek 自建 harness，以及四个可观测性平台究竟在给什么装表——外加四个页面：严重事件报告、引用交互设计、采购智能体，以及参数高效微调',
  ),
  items: [
    L(
      'New blog post — *DeepSeek Is Building a Harness, and the Benchmark Score Already Includes the Scaffold*. DeepSeek reported a DeepSWE result of 54.4 for the re-post-trained V4-Flash on 31 July and noted in the same changelog that the harness which produced it would ship later, so nobody outside the company can reproduce it. On 1 August the harness team lead, Cui Tianyi, opened a closed beta to open-source agent projects and reporting put sign-ups at 712 projects within three days, spanning agent frameworks, coding agents and memory tooling. Argues that an agentic score has always been a property of a model-and-harness pair — the scaffold decides context budget, retry discipline, attempt count and tool schemas, several of which move the result by more than the gap between adjacent frontier models — and that the labs are now vertically integrating the half nobody publishes, which makes cross-lab rankings structurally uncheckable. The practical response costs nothing: fix your own harness, pin its version, and swap models inside it. Three themeable SVGs.',
      '新博客文章——《DeepSeek 在造自己的 Harness：那个基准分数里早已包含了脚手架》。7 月 31 日，DeepSeek 为重新后训练的 V4-Flash 报出 DeepSWE 54.4 分，并在同一份更新日志里注明产出它的 harness 稍后才会发布，于是公司之外无人能复现。8 月 1 日，harness 团队负责人崔天翼向开源智能体项目开放封闭测试，据报道三天内报名项目达 712 个，涵盖智能体框架、编码智能体与记忆工具。文章论证：智能体分数从来都是"模型与 harness 这一对"的属性——脚手架决定上下文预算、重试纪律、尝试次数与工具 schema，其中若干项对结果的影响超过相邻两代前沿模型之间的差距——而各家实验室如今正在把没人公布的那一半纵向整合进来，这让跨实验室排名在结构上无法核实。务实的应对一分钱不花：钉死你自己的 harness、固定其版本，在它里面换模型。配三张可随主题变色的 SVG。',
    ),
    L(
      'New blog post — *Langfuse vs LangSmith vs Phoenix vs Braintrust: The Meter Is the Product*. The feature grids have converged — all four ship tracing, evals, datasets and prompt versioning — so the decision lives in the licence and the billing meter. Langfuse is MIT with fully ungated self-hosting and kept both through the ClickHouse acquisition in January 2026; Phoenix is built on OpenTelemetry and maintains OpenInference alongside it, but ships under Elastic Licence 2.0, which is source-available rather than OSI open source and is routinely misreported; LangSmith is closed source and unmatched inside LangGraph; Braintrust is the only one where scores are the primitive and traces hang off them. Argues that every meter prices the trace archive that becomes your golden set, regression baseline and fine-tuning corpus, that an agent taking twenty steps bills like twenty calls, and that instrumenting against OpenTelemetry while dual-writing the stream to storage you own is worth more than the choice between the four. Three SVGs including a metering-shape comparison.',
      '新博客文章——《Langfuse vs LangSmith vs Phoenix vs Braintrust：计量方式才是产品》。功能表已经收敛——四家都有链路追踪、评估、数据集与提示词版本管理——所以真正的决定落在许可证与计费的计量单位上。Langfuse 是 MIT、自托管毫无阉割，并在 2026 年 1 月被 ClickHouse 收购后把这两点都保住了；Phoenix 建在 OpenTelemetry 之上并同时维护 OpenInference，但采用 Elastic License 2.0——源码可得而非 OSI 开源，且经常被误报；LangSmith 闭源，在 LangGraph 内部无可匹敌；Braintrust 是唯一一个以分数为基本单位、让轨迹挂在其下的。文章论证：每一种计量方式定价的都是那份日后会变成你的黄金集、回归基线与微调语料的轨迹存档；一个走二十步的智能体按二十次调用计费；而按 OpenTelemetry 做仪表化、同时把这份流双写到你自己拥有的存储，比"在这四家里选哪家"更值钱。配三张 SVG，含一张计量形态对比图。',
    ),
    L(
      'New Operation (Governance & Compliance) — *Serious-Incident Reporting*. Since 2 August 2026 an EU high-risk AI provider has had two days to report a widespread fundamental-rights infringement, ten days where a death may have been caused and fifteen otherwise — and the clock starts at the causal link, not at the legal review. Argues that two days is an engineering deadline: the trigger is an outcome rather than a misbehaviour, the Commission\'s draft guidance treats an indirect causal link as sufficient so a human approval step does not sever the chain, and the party that sees the harm (the deployer, under Article 26(5)) is not the party that must file. Names the five properties that make agents structurally bad at establishing causation — downstream harm, sampled traces, expired retention, rotated model versions and retrieval as a confounder — and closes on the drill: pick one deployed agent, invent a discrimination complaint, and time how long it takes to answer which runs, which version, and what the agent actually did.',
      '新增运维页（治理与合规）——《严重事件报告》。自 2026 年 8 月 2 日起，欧盟高风险 AI 提供者就大范围侵害基本权利只有两天时间上报，可能致人死亡的为十天，其余为十五天——而时钟从因果关联确立那一刻起跑，不是从法务开始审卷宗那一刻。文章论证两天是一条工程期限：触发条件是后果而非"模型干了坏事"，欧盟委员会的指南草案认为间接因果关联即已足够，所以人工审批这一步并不切断这条链；而看见损害的一方（依第 26(5) 条是部署者）并不是必须申报的那一方。文中点名让智能体在结构上难以确立因果的五条性质——损害在下游、轨迹被采样、保留期已过、模型版本轮换，以及检索作为混杂因素——并以一次演练收尾：挑一个已上线的智能体、编一起歧视投诉，计时看回答"涉及哪几次运行、哪个版本、智能体究竟做了什么"要多久。',
    ),
    L(
      'New Playbook (Agent UX & Human Interaction) — *Citations & Source-Attribution UX*. The Stanford audit of four generative search engines found only 51.5% of generated sentences fully supported by their citations and only 74.5% of citations supporting the sentence they were attached to, which makes an unverifiable citation worse than no citation: it suppresses scepticism without supplying evidence. Separates the two jobs a citation does — fast verification and durable attribution — and argues that post-hoc attribution structurally produces topically-relevant citations that do not support the claim, so spans must be emitted during generation with stable chunk IDs that survive re-indexing. Drives everything from one variable: the cost of checking a single claim. Hover-quote in place, deep links to the exact position, per-claim anchors, unsupported sentences rendered differently from supported ones, and measurement by planted-error detection rather than click-through.',
      '新增实战手册（智能体体验与人机交互）——《引用与来源归属的交互设计》。斯坦福对四款生成式搜索引擎的审计发现，只有 51.5% 的生成句子被其引用完全支撑，也只有 74.5% 的引用真正支撑了它所挂靠的那句话——这让一条无法核验的引用比没有引用更糟：它压住了怀疑，却没有补上证据。文章把引用承担的两件事分开——快速核验与耐久归属——并论证事后归属在结构上必然产出"主题相关却支撑不了主张"的引用，所以片段标识必须在生成过程中吐出，且切片 ID 要稳定到熬得过重建索引。此后一切都由一个变量驱动：核验一条主张的代价。就地悬停显示原文、深链到确切位置、按主张打锚点、让没有支撑的句子看起来就与有支撑的不同，并用埋入错误的识别率而不是点击率来测量。',
    ),
    L(
      'New Playbook (Domain Playbooks) — *Procurement & Sourcing Agents*. Under the EU public procurement directives a losing bidder must be told why it lost and gets a standstill period of at least ten calendar days to challenge before the contract is signed, so "the model scored you 6.8" is the one output the process cannot accept. The work that actually consumes the weeks is the requirement-coverage matrix — four hundred requirements across nine responses is 3,600 lookups — and that is retrieval, not judgement. Argues for a hard split: the agent locates, quotes, cites the page, classifies coverage as answered / partial / not addressed and normalises units, while ranking stays with a named human. Adds bid isolation as an architectural requirement rather than a policy (one index per bid, never two vendors in one context window, submitted documents treated as untrusted input), a wall-clock budget because the submission deadline does not move, and the sell-side mirror where auto-answered questionnaires have stopped discriminating and artefacts beat prose.',
      '新增实战手册（领域实战手册）——《采购与寻源智能体》。依欧盟公共采购指令，落标方必须被告知落标理由，并在合同签署前享有至少十个日历日的静默期用于提出质疑——所以"模型给你打了 6.8 分"恰恰是这个流程无法接受的那一种输出。真正吃掉几周时间的是需求覆盖矩阵——四百条需求乘以九份应答就是 3600 次查找——而那是检索，不是判断。文章主张一条硬性切分：智能体负责定位、引出原文、标注页码、把覆盖情况分为"已答／部分／未涉及"并归一单位，而排名留给一个具名的人。此外把标书隔离列为架构要求而非政策（一份标书一个索引、绝不把两家供应商放进同一个上下文窗口、把提交上来的文档当作不可信输入）、因提交截止时间不会挪动而设的挂钟预算，以及卖方侧的镜像：当问卷都由机器作答后，散文式回答已不再具有区分力，凭证胜过叙述。',
    ),
    L(
      'New Concept (AI Foundations) — *Parameter-Efficient Fine-Tuning*. LoRA won not because training got cheap but because the specialisation ships as a 50 MB file, so one base model in GPU memory can serve a hundred variants and switching between them becomes a routing decision. Explains where the saving actually comes from (the optimiser state and gradient buffers, not the weights), and makes rank the load-bearing point: rank 8–16 teaches behaviour — format, tone, refusal boundaries, a schema the model keeps bending — rank 64–256 starts teaching content, and no rank teaches facts economically, which is why so many fine-tuning projects are declared failures when the requirement was retrieval. Then the part that changes system design: multi-adapter serving, per-tenant and per-task adapters, merge-or-swap as a real trade, rank ceilings on the serving cluster, and the fact that every adapter is invalidated at once when the base checkpoint is deprecated.',
      '新增概念页（AI 基础）——《参数高效微调》。LoRA 赢下来，不是因为训练变便宜了，而是因为特化的产物是一个 50 MB 的文件：显存里一份基座就能服务上百个变体，在它们之间切换降格成一次路由决策。文章解释省下来的到底是什么（是优化器状态与梯度缓冲，而不是权重本身），并把"秩"立为承重点：秩 8–16 教的是行为——格式、语气、拒绝边界、一个模型老爱变形的 schema；秩 64–256 才开始教内容；而没有哪个秩能经济地教会事实——这正是那么多微调项目被判定为失败的原因，它们真正的需求其实是检索。随后是真正改变系统设计的那部分：多适配器服务、按租户与按任务的适配器、"合并还是热切换"这个真实取舍、服务集群上的秩上限，以及基座 checkpoint 一旦被弃用、所有适配器同时作废这件事。',
    ),
  ],
};

export default entry;
