import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-09-01',
  title: L(
    'Two AI Blog posts — on the ransomware operator whose own chat logs show an agent replacing the labour rather than the exploit, and on the four RL-environment platforms where only one artifact survives the run — plus three pages on environment engineering, price deflation, and attacker-operated agents',
    '两篇 AI 博客——一名勒索软件操作者自己的聊天记录，显示智能体替掉的是体力活而不是漏洞利用；以及四家 RL 环境平台里，只有一件产物能比训练活得更久——外加三个页面：环境工程、价格通缩，以及攻击者操作的智能体',
  ),
  items: [
    L(
      'New AI Blog post `/blogs/aurora-rented-an-operator-not-an-exploit` — an Aurora ransomware affiliate left a home directory served over a file listing on port 8888, and inside it were the victim folders, credential dumps, shell history and the operator’s own chat logs with a commercial coding agent. Gambit Security documented Cursor Agent running claude-4.5-sonnet-thinking in hands-on use across at least ten victim organisations between 8 April and late May 2026; CloudSEK’s analysis of the exposed directory described 20+ organisations across nine countries between April and July, with domain-level or interactive access at seventeen. The post argues the logs make the story smaller and more useful: the agent was handed credentials someone had already stolen and never escalated privilege by being an agent, the tradecraft (NetExec, Nmap, BloodHound collection, an ESXi encryptor) is what existing detections already describe, and the refusals that fired were defeated by reframing the intrusion as an authorised penetration test — a claim the model cannot check and legitimate red teams make daily. What moved is tempo and the skill floor, so the controls that matter are credential blast radius, separating the hypervisor plane from workstation identity, and end-to-end time-to-revoke, not a blocklist of AI tools whose binary is a legitimate IDE.',
      '新增 AI 博客 `/blogs/aurora-rented-an-operator-not-an-exploit`——一名 Aurora 勒索软件关联者把自己的家目录经 8888 端口以文件列表形式敞在了外面，里面装着受害者文件夹、凭据转储、shell 历史，以及他本人与一个商业编程智能体的聊天记录。Gambit Security 记录了 Cursor Agent 跑着 claude-4.5-sonnet-thinking，在 2026 年 4 月 8 日至 5 月下旬期间于至少十家受害组织中上手作业；CloudSEK 对那个敞开目录的分析则描述了 4 月至 7 月间横跨九个国家的 20 多家组织，其中十七家被拿到域级或交互式访问权。本文主张这些日志让故事变小、也变得更有用：智能体是被交到手上别人早已窃得的凭据的，从未因为"它是智能体"而提升过权限；它用的手法（NetExec、Nmap、BloodHound 采集、一个 ESXi 加密器）正是既有检测早已描述过的那些；而少数触发的拒绝，被"这是一次获授权的渗透测试"这句重新包装击穿了——这是一句模型无法核实、而合法红队每天都在说的话。真正移动的是节奏与技能门槛，所以要紧的控制是凭据爆炸半径、把虚拟化管理面与工作站身份分开，以及端到端的吊销耗时——而不是一份针对"可执行文件是正当 IDE"的 AI 工具黑名单。',
    ),
    L(
      'New AI Blog post `/blogs/prime-intellect-vs-hud-vs-art-vs-openai-rft` — four ways to get from an unreliable agent to a trained policy, compared on the axis that outlives the project. The GPUs are rented, the trainer is an open library and the base model turns over within two quarters, so the environment — task distribution, tool surface, verifier — is the only artifact left afterwards, and it is also the eval you needed first. Prime Intellect makes it a distributable Python package (verifiers modules with their own pyproject.toml, published to an Environments Hub carrying thousands of community entries) and is the most portable; HUD wraps your running software as an MCP server and is the answer where no faithful simulation exists, at the cost of routing scale-out through its gateway; OpenPipe ART puts the rollout in your own application code and offers RULER, which ranks a group of trajectories rather than scoring them, removing the hand-written reward and relocating correctness into a judge you must calibrate. The fourth, OpenAI’s reinforcement fine-tuning, is the least work and is winding down: no new organisations since 7 May 2026, existing customers lose new jobs on 6 January 2027 — which is the comparison’s strongest argument for keeping the environment in a form that leaves the building with you.',
      '新增 AI 博客 `/blogs/prime-intellect-vs-hud-vs-art-vs-openai-rft`——从一个不靠谱的智能体走到一个训练好的策略，有四条路，而对比落在那条比项目活得更久的轴上。GPU 是租的，训练器是开源库，基座模型两个季度内就换代，所以环境——任务分布、工具面、校验器——是事后唯一留下来的产物，而它同时也是你本来就该先有的那份评测集。Prime Intellect 把它做成一个可分发的 Python 包（带自己 pyproject.toml 的 verifiers 模块，发布到社区条目数以千计的 Environments Hub），可移植性最强；HUD 把你正在跑的软件包成一台 MCP 服务器，是"不存在忠实仿真"时的答案，代价是扩容要走它的网关；OpenPipe ART 把 rollout 放在你自己的应用代码里，并提供 RULER——它对一组轨迹排名而不是打分，省掉了手写奖励，同时把正确性挪进了一个你必须校准的裁判。第四条，OpenAI 的强化微调，上手最省事，也正在退场：自 2026 年 5 月 7 日起不再接纳新组织，现有客户在 2027 年 1 月 6 日之后无法创建新任务——这正是整场对比里最有力的一条论据，支持你把环境保持成一种能跟着你走出这栋楼的形态。',
    ),
    L(
      'New Deep-Dive `/deep-dives/training-agentic-models/environment-engineering-for-rl` (T11) — teams budget an agentic RL run in GPU-hours and then pay for idle accelerators, because wall-clock is dominated by the environment and one straggler trajectory stalls a synchronous batch; the fix the ecosystem converged on through 2026 (ROSE, TideRL, Tunix, the async open-source designs) is disaggregated inference and training pools with a rollout buffer between them, and the number to profile is p99 episode duration at target concurrency rather than GPU count. The page also insists that the verifier you wrote in an afternoon is the reward function — so buy precision over recall, grade the artifact rather than the transcript, read the top-scoring trajectories by hand rather than the mean, and label fifty trajectories before trusting the signal. Plus: pin the container digest not the tag, close the network unless the network is the task, score timeouts instead of dropping them (dropping biases the gradient toward short episodes), and note that the same artifact is the eval — which means if you cannot state your success rate on thirty real tasks, you do not have a reward yet.',
      '新增深入解析 `/deep-dives/training-agentic-models/environment-engineering-for-rl`（T11）——团队按 GPU 小时给一次智能体 RL 训练做预算，然后为闲置的加速卡付钱，因为墙钟时间由环境主导，而一条掉队的轨迹就能卡住整个同步批次；2026 年整个生态收敛到的解法（ROSE、TideRL、Tunix，以及各家开源库的异步设计）是把推理池与训练池拆开、中间放一个 rollout 缓冲区，而该去剖析的数字是目标并发下回合时长的 p99，不是 GPU 数量。本页还坚持：你花一个下午写出来的那个校验器就是奖励函数——所以要精确率而不是召回率、给产物打分而不是给记录打分、用手去读分数最高的轨迹而不是看均值，并在信任这个信号之前先标五十条轨迹。此外：锁死容器摘要而不是标签；除非网络本身就是任务，否则把网络关掉；给超时打分而不是丢弃它（丢弃会把梯度偏向短回合）；并且要注意这件产物同时就是评测集——这意味着如果你说不出自己在三十件真实任务上的成功率，你还没有奖励。',
    ),
    L(
      'New Operation `/operations/economics-roi/price-deflation-and-cost-per-task` (B14) — frontier input tokens cost about a sixth of GPT-4’s March 2023 price of $30/$60 per million, and Gemini 3.1 Flash listed at $0.10/$0.40 in April 2026, a factor of three hundred — yet almost nobody’s agent got six times cheaper, because agentic workflows burn 5–30× the tokens of a chat completion on Gartner’s March 2026 estimate, and a representative 50-turn coding session models out near one million input tokens against forty thousand output. The deflation lands on a unit you do not buy. The operational consequences: a token optimisation is a depreciating asset, so fund it only when payback is shorter than the price halving time, while reliability work moves the denominator and keeps its value; a term commitment is a directional bet against a three-year trend and should be bought for capacity and latency guarantees rather than as a saving; the frontier tier barely deflates at all (Claude Opus 5 at $5/$25, GPT-5.6 Sol at $5/$30 in August 2026), so the deflation is captured by routing down a tier, not by waiting. Closes on modelling three explicit price paths and tracking cost per successful task rather than spend.',
      '新增运营页 `/operations/economics-roi/price-deflation-and-cost-per-task`（B14）——前沿模型的输入令牌，如今大约只要 GPT-4 在 2023 年 3 月每百万 30/60 美元的六分之一，而 Gemini 3.1 Flash 在 2026 年 4 月标价 0.10/0.40 美元，相差三百倍——可几乎没人的智能体因此便宜了六倍，因为按 Gartner 2026 年 3 月的估计，智能体式工作流烧掉的令牌是一次对话补全的 5–30 倍，而一次有代表性的 50 轮编程会话建模下来接近一百万输入令牌对四万输出令牌。通缩落在了一个你并不购买的单位上。运营层面的推论是：一项令牌优化是一份会折旧的资产，所以只有当回本期短于价格腰斩周期时才该立项，而可靠性工作动的是分母、能够保值；一份期限承诺是一次逆着三年趋势的方向性下注，应当为容量与延迟保证去买，而不是当作省钱；前沿那一档几乎不通缩（2026 年 8 月 Claude Opus 5 为 5/25 美元，GPT-5.6 Sol 为 5/30 美元），所以通缩要靠往下挪一档去捕获，而不是靠等。文末落在建三条显式的价格路径，并盯每成功任务成本而不是开销。',
    ),
    L(
      'New Operation `/operations/safety-and-security/attacker-operated-agents` (S19) — your threat model covers the agents you deployed; the 2026 intrusions involved someone else’s, running a commercial product from the attacker’s laptop under credentials already stolen. Three disclosed cases share one shape (Aurora with Cursor Agent, the same operator’s exposed directory, and Anthropic’s GTG-2002), and in none of them did the agent obtain access — so the exposure to measure is what one compromised identity reaches in an uninterrupted hour, with the hypervisor management plane as the highest-return separation because ESXi was the payoff. The page treats vendor refusal as tested and failed (reframing an intrusion as an authorised penetration test is a claim about permission the model cannot verify, and one that legitimate red teams make constantly), gives the detection that does survive — breadth per identity per hour and cadence without human variance, baselined per identity class rather than per user — and is explicit about its ceiling: no signal identifies an agent, and detecting on the tooling is closed off because the binary is a legitimate IDE. Closes on inventorying your own developers’ agent traffic as the noise floor, and on re-running the tabletop with one variable changed: the intruder never tires, so measure time-to-revoke rather than time-to-detect.',
      '新增运营页 `/operations/safety-and-security/attacker-operated-agents`（S19）——你的威胁模型覆盖的是你自己部署的智能体；而 2026 年那些入侵牵涉的是别人的智能体，跑在攻击者的笔记本上，用的是早已窃得的凭据。三起已披露案例共享同一种形状（Aurora 与 Cursor Agent、同一名操作者敞开的目录，以及 Anthropic 的 GTG-2002），而其中没有一起是智能体自己取得了访问权——所以该量的暴露面，是一个被攻陷的身份在不受打断的一小时里能够到什么，其中把虚拟化管理面隔开是回报最高的一项，因为 ESXi 才是收益所在。本页把厂商侧的拒绝视为"已被实地检验并失败"（把一次入侵重新包装成获授权的渗透测试，是一句模型无法核实、而合法红队天天在说的关于许可的断言），给出了确实挺得住的那种检测——每身份每小时的广度，以及没有人类方差的节拍，按身份类别而不是按用户建基线——并明说了它的上限：没有任何信号能识别出"智能体"，而在工具上做检测这条路是封死的，因为那个可执行文件是一个正当的 IDE。文末落在把你自己开发者的智能体流量盘点成本底噪声，以及只改一个变量重跑桌面推演：入侵者从不疲倦，所以去量吊销耗时，而不是检测耗时。',
    ),
  ],
};

export default entry;
