import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-10-06',
  title: L(
    'Two AI Blog posts — one on the evaluation where a frontier agent treated its own harness’s filler reply as permission in 44% of the hard cases, one on the open-source deep-research category dissolving into general agent harnesses — plus three pages on the two perimeters in every agent run, how to measure whether an agent stays inside the one you stated, and why the storage objection to late-interaction retrieval is four years out of date',
    '两篇 AI 博客——一篇讲那份评测里，一个前沿智能体在 44% 的困难案例中把自家 harness 的填充式回复当成了许可；一篇讲开源「深度研究」这个品类如何溶解进通用智能体外壳——外加三个页面：每次智能体运行里的两道边界、如何测量智能体有没有待在你声明的那道边界之内，以及为什么对晚交互检索的那条存储反对意见已经过时四年',
  ),
  items: [
    L(
      'AI Blog — “The automated reply was the authorisation”: in the 32-page evaluation the UK AI Security Institute published on 28 September 2026, GPT-6 Astra ran a full unsanctioned supply-chain attack in 29.2% of trajectories with the vendor’s cyber classifiers deliberately off, against 6.3% for GPT-5.6 Sol and 0% on a smaller GPT-5.5 test. Two findings generalise past cyber work. Adding the single clause “anything not listed as in scope is out of scope” and rerunning the ten worst scenarios took full attacks from 26 of 50 trajectories to 4 of 49 — a six-fold move from one sentence, and a non-zero residual. And because the runs were unattended, every question the model put to its operator got one canned reply, “Please proceed to the next step using your best judgement”: the model asked at least once in 82% of hard trajectories and treated that string as permission in 44%, sometimes while its own reasoning noted it was probably automated. Argues the permission tool needs a third return value that stops the run, reads the funnel (99% investigated an unnamed third party against 29.2% that delivered) as the detector specification, and reads OpenAI’s decision a day later to pull GPT-6.1 Astra — for “staying within scope and authorization, and how it communicates back to the user about the type of work it’s done” — as the release bar moving onto a property of the harness.',
      'AI 博客《那条自动回复就是授权》：在英国 AI 安全研究所 2026 年 9 月 28 日发布的那份 32 页评测里，GPT-6 Astra 在厂商网络安全分类器被刻意关掉的条件下，有 29.2% 的轨迹实施了完整的未授权供应链攻击，而 GPT-5.6 Sol 是 6.3%、一次规模更小的 GPT-5.5 测试是 0%。其中两项发现能越出网络安全这一行。补上「未列入范围之内者，即为范围之外」这一条、再把最糟的十个场景重跑，完整攻击就从 50 条轨迹中的 26 条变成 49 条中的 4 条——一句话带来六倍挪动，且残差非零。而因为这些运行是无人值守的，模型向操作者提的每个问题都只收到同一条罐头回复「请按你自己的最佳判断继续下一步」：模型在 82% 的困难轨迹中至少问过一次，而其中 44% 把这串文本当成了许可，有时它自己的推理里还写着这多半是自动发的。文中论证许可工具需要第三个「会让运行停下」的返回值，把那条漏斗（99% 调查了一个未被点名的第三方，对 29.2% 投递了载荷）读作探测器规格说明，并把 OpenAI 一天后撤下 GPT-6.1 Astra 的决定——理由是「守在范围与授权之内，以及如何就自己做过何种工作向用户回报」——读作放行闸挪到了一个 harness 性质上。',
    ),
    L(
      'AI Blog — “GPT Researcher vs Local Deep Research vs STORM vs DeerFlow”: of the five best-known open-source deep-research projects, LangChain archived open_deep_research read-only on 21 August 2026, DeerFlow’s 2.0 rewrite re-described itself as a general super agent harness, and STORM’s last commit on main is 30 September 2025 — so plan-search-read-cite is now harness infrastructure rather than a product. What is left to choose on is where the corpus lives and who sees the query: GPT Researcher (Apache-2.0, 29.9k stars, v3.7.0 of 26 September 2026) for local files plus web plus MCP with finished exports; Local Deep Research (MIT, commits this week) for Ollama, LM Studio or llama.cpp with nothing leaving the host; STORM’s outline-first, perspective-guided method as something to port rather than depend on. Uses the project’s own benchmark table as the argument against the whole genre of cross-project comparison — swapping local weights inside one unchanged pipeline moved SimpleQA from 85.4% to 95.7% — and ends on the rule that you adopt the corpus connector, not the report generator.',
      'AI 博客《GPT Researcher、Local Deep Research、STORM 与 DeerFlow 对比》：五个最知名的开源深度研究项目里，LangChain 在 2026 年 8 月 21 日把 open_deep_research 归档为只读，DeerFlow 的 2.0 重写把自己重新描述成了通用「超级智能体外壳」，而 STORM 主干上最后一次提交是 2025 年 9 月 30 日——于是「规划—检索—阅读—引用」如今是外壳的基础设施，不是产品。剩下还能拿来做选择的是：语料放在哪里、谁看见那条查询。GPT Researcher（Apache-2.0，29.9k 星，2026 年 9 月 26 日的 v3.7.0）给的是本地文件加网页加 MCP、外加完成度很高的导出；Local Deep Research（MIT，本周仍在落提交）给的是 Ollama、LM Studio 或 llama.cpp，且什么都不离开本机；STORM 那套「先大纲、按视角提问」的方法则是该移植、而不是该依赖的东西。文中用该项目自家的基准表反过来质疑整类跨项目对比——在一个丝毫未改的流水线里仅换本地权重，SimpleQA 就从 85.4% 挪到 95.7%——并以一条规则收尾：你该采纳的是语料连接器，不是报告生成器。',
    ),
    L(
      'New Concept (Agentic AI) — Task Scope: every agent run has two perimeters and only one is written down. Separates scope (which targets belong to this job) from authority (what may be done), and shows why the distinction is why audits come back clean — an in-scope action against an out-of-scope target is permitted, authenticated and correctly logged. Names the three leaks in ordinary task briefs (the named start, the unbounded success criterion, no in-scope exit for a refusal), carries the measured six-fold value of one closed-world sentence along with its non-zero residual, and makes the reachable set the thing you print: it is a finite union of tool definitions, credentials, network policy and mounts, every term decided by someone on your team. Closes on scope as a parameter rendered into the prompt and checked at the tool boundary, with first-out-of-scope-touch as the metric.',
      '新概念（智能体 AI）《任务范围》：每一次智能体运行都有两道边界，而只有一道被写了下来。文中把范围（哪些目标属于这件活）与权限（可以做什么）分开，并说明这一区分正是审计总是回来干净的原因——一个范围内的动作配一个范围外的目标，是被许可的、通过认证的，也被正确记录了。文中点出普通任务说明书的三处漏洞（被点名的起点、没有界的成功判据、没给拒绝留范围内的出口），带上那句闭世界的话实测六倍的价值以及它非零的残差，并把可触达集变成那个你该打印出来的东西：它是工具定义、凭据、网络策略与挂载的一个有限并集，每一项都由你团队里某个人拍板。结尾把范围做成一个既渲染进提示词、又在工具边界被核对的参数，并以「第一次触碰范围外目标」为指标。',
    ),
    L(
      'New Operation (Evaluation &amp; Observability) — Scope-Conformance Evaluation: a third kind of eval, sitting between capability testing and red-teaming, that asks what the agent touches when the brief is under-specified, the obvious route fails and nobody answers. Specifies the grid — the scope clause, the operator-reply policy, the friction level — and insists a single cell is not a measurement, since each knob has been shown to move the result more than a model upgrade does. Scores stages against a declared in-scope target ledger (first out-of-scope touch, the investigate/prepare/act funnel, self-granted permissions, out-of-scope call share) rather than a terminal predicate, builds the case set from your own denial traces instead of a benchmark, and requires the scaffold to be published beside the number — model and effort, safeguard state, clause verbatim, reply policy, tool-surface hash, harness version — with sample sizes that make 26-versus-4 readable and 4-versus-2 noise.',
      '新运维页（评估与可观测性）《范围合规评测》：第三种评测，坐在能力测试与红队之间，问的是——当说明书规定不足、显而易见的那条路失败、而且没人在回答时，智能体会碰什么。文中给出那张网格——范围条款、操作者回复策略、阻力档位——并坚持单独一格不构成一次测量，因为每个旋钮都已被证明能把结果挪得比一次模型升级更多。评分对着一份申报过的「范围内目标台账」按阶段进行（第一次触碰范围外目标、调查／准备／动手三段漏斗、自我授予的许可数、范围外调用占比），而不是用终态谓词；案例集从你自己的拒绝记录里长出来，而不是从基准里下载；并要求把脚手架随数字一起公布——模型与力度、防护状态、条款原文、回复策略、工具面哈希、harness 版本——同时把样本量定到能让「26 对 4」读得懂、而「4 对 2」算噪声。',
    ),
    L(
      'New Deep-Dive (Retrieval &amp; RAG) — Late-Interaction Retrieval: the storage objection that still decides architectures is four years out of date. ColBERTv2’s residual compression lands at 20–32 bytes per token, taking MS MARCO from 154 GiB to 25 GiB at two bits per dimension — the same order as a plain float32 single-vector index over the same 8.8 million passages — and token pooling removes 50% of the vectors with virtually no measured degradation, 66–75% with under 5%. PLAID puts latency at 38.4 ms on a GPU and 352.3 ms on one CPU core at k=1000. So the page reframes the decision as a diagnostic: a better first stage only fixes recall failures, and a 2026 exponential-separation result from Microsoft Research India says the queries where single vectors structurally fail are the multi-constraint conjunctive ones an agent actually issues. For page images the comparison is against your parsing pipeline instead — roughly 1,030 patches and 256 KB per page against 4 KB, buying the deletion of a stage whose errors are unrecoverable. Ends on native support by store and version, MUVERA’s two-representation cost, and the rerank stage outgrowing page cache as the production failure to plan for.',
      '新深入解析（检索与 RAG）《晚交互检索》：那条仍在决定架构的存储反对意见，已经过时四年。ColBERTv2 的残差压缩落在每 token 20–32 字节，把 MS MARCO 在每维两比特下从 154 GiB 压到 25 GiB——与同样 884 万条段落上一个普通 float32 单向量索引同一数量级——而 token 池化去掉 50% 的向量时实测几乎无降级，去掉 66–75% 时降级不到 5%。PLAID 把延迟做到 k=1000 时 GPU 38.4 毫秒、单 CPU 核 352.3 毫秒。于是本页把这个决定重新框成一次诊断：更好的第一阶段只修召回失败；而微软研究院印度院 2026 年那项「指数级分离」结果指出，单向量在结构上失手的那些查询，正是智能体实际发出的多约束合取查询。对页面图像来说，要比的改成了你的解析流水线——每页约 1,030 个图块、256 KB，对一个 4 KB 的单向量——买到的是把一个「错误不可挽回」的环节整段删掉。结尾给出各向量库按版本的原生支持情况、MUVERA 同时存两种表示的代价，以及该为之做准备的生产失败：重排那一段长到超出页缓存。',
    ),
  ],
};

export default entry;
