import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-08-29',
  title: L(
    'Two AI Blog posts on the two opposite directions inside the Claudeforce deal and on where a durable-execution engine keeps the agent\'s transcript, plus four pages on the instruction hierarchy, infrastructure-as-code agents, fraud and disputes, and staging environments',
    '两篇 AI 博客——Claudeforce 这笔交易内部那两个方向相反的集成，以及持久化执行引擎把智能体的对话记录放在哪里——外加四个页面：指令层级、基础设施即代码智能体、欺诈与争议处理，以及预发布环境',
  ),
  items: [
    L(
      'New blog post — *Claudeforce runs in two directions, and only one keeps the record inside Salesforce*. Salesforce and Anthropic announced Claudeforce on 26 August 2026, and the post separates the one partnership into two shipments with opposite governance properties. Claude into Agentforce puts the model inside the Salesforce Trust Boundary served through Amazon Bedrock, as a reasoning model for the Atlas engine and the default behind Agentforce Vibes and Agentforce Coworker: tool calls execute as Salesforce actions in a running user\'s context, so sharing rules and field-level security apply per action and the audit machinery predates agents by a decade. Salesforce into Claude — a plugin bundling 37 prebuilt sales skills, in pilot with open beta expected September 2026 — moves the session outside that boundary instead: the write is still a permissioned, logged Salesforce write, but the deliberation that produced it now lives in a workspace with a different vendor\'s retention and legal-hold story. Argues the missing artefact is the join between the two, since field history records that a discount went from 5% to 22% and never records why; that a connected app\'s OAuth scope must be the union of what all 37 skills need, so a conversation that wanted to summarise one account runs with all of it; and that CRM records full of attacker-reachable text landing in a workspace holding the user\'s other connectors is the classic confused-deputy setup. Closes on the cheapest vendor-independent control: have the agent write its rationale and the record ids it read back onto the object at write time. Three themeable SVGs.',
      '新博客文章——《Claudeforce 是双向的，而只有一个方向把记录留在 Salesforce 里》。2026 年 8 月 26 日 Salesforce 与 Anthropic 宣布了 Claudeforce，本文把这一项合作拆成两件治理属性相反的交付物。Claude 进 Agentforce，把模型放进经由 Amazon Bedrock 提供的 Salesforce Trust Boundary 之内，作为 Atlas 引擎的推理模型、以及 Agentforce Vibes 与 Agentforce Coworker 背后的默认模型：工具调用以 Salesforce 动作的形式在某个运行用户的上下文里执行，于是共享规则与字段级安全逐一生效，而那套审计机器比智能体早了十年。Salesforce 进 Claude——一个打包 37 项预置销售技能的插件，已在试点、公开测试预计 2026 年 9 月——则反过来把会话搬到了那条边界之外：写入依然是一次受权限约束、被记录在案的 Salesforce 写入，但导致它的推敲过程如今住在一个由另一家厂商决定留存与法律保全策略的工作区里。文章主张缺失的产物是二者之间的那道连接，因为字段历史会记下折扣从 5% 变成 22%、却从不记下为什么；主张一个 connected app 的 OAuth 范围必须是全部 37 项技能所需权限的并集，于是一段只想总结某个客户的对话正带着全套权限在跑；并主张「塞满攻击者可触及文本的 CRM 记录，落进一个同时握着用户其他连接器的工作区」正是经典的混淆代理局面。文末落在最便宜、且与厂商无关的那项控制：让智能体在写入的当下，把自己的理由与读过的记录 id 一并回写到对象上。配三张可随主题变色的 SVG。',
    ),
    L(
      'New blog post — *Temporal vs Restate vs Inngest vs DBOS: where the agent\'s transcript lives*. All four resume a crashed run from its last completed step, so the feature everyone shops for decides nothing; what separates them for agents is that the durable record is a transcript growing every turn, and each engine answers differently on who absorbs that growth. Temporal warns at a 256 KB payload and errors at 2 MB, warns at 10,240 events, and terminates a workflow at the 51,201st event or 50 MB of history with a non-retryable error — plus a 4 MB cap on a single Workflow Task transaction that a burst of modest activities can hit. Inngest caps step output at 4 MB and run state at 32 MB. Restate publishes no fixed per-run ceiling and added automatic payload compression near the limit in 1.5; DBOS has no engine ceiling because checkpoints are rows in your own Postgres, which trades a hard stop for table growth and a vacuum story. Second axis: what recovery asks of your code — Temporal replays workflow code, so the model call must be an activity and streaming cannot originate in workflow scope, while Restate and Inngest journal ordinary functions and DBOS decorates them in-process. Third: Inngest bills a run plus each step, and an agent loop mints steps at a rate the model controls. The recommendation is the same whichever you pick — store the transcript by reference from the first commit, because the migration after you hit the ceiling is a rewrite of every step signature. Three SVGs.',
      '新博客文章——《Temporal、Restate、Inngest 与 DBOS：智能体的对话记录住在哪里》。四者都能让崩掉的运行从最后一个已完成步骤继续，所以人人拿来挑选的那个功能什么都决定不了；对智能体而言真正区分它们的是：持久化记录是一份每轮都在长大的对话记录，而各引擎对「谁吸收这份增长」的回答各不相同。Temporal 在 256 KB 载荷时告警、2 MB 时报错，在 10,240 个事件时告警，并在第 51,201 个事件或 50 MB 历史处以不可重试的错误终止工作流——另有单个 Workflow Task 事务 4 MB 的上限，一次性调度一批中等大小的 activity 就可能撞上。Inngest 把单步输出限制在 4 MB、单次运行状态限制在 32 MB。Restate 没有公布固定的单次运行上限，并在 1.5 版新增了接近上限时的自动载荷压缩；DBOS 没有引擎侧上限，因为检查点是你自己 Postgres 里的行——这是拿一个硬性停止换来了表增长与一份 vacuum 的功课。第二条轴是恢复机制对你代码的要求：Temporal 重放工作流代码，所以模型调用必须是 activity，且流式输出不能从工作流作用域发起；而 Restate 与 Inngest 是给普通函数记 journal，DBOS 则是在进程内给它们加装饰器。第三条：Inngest 按「一次运行加其中每一个步骤」计费，而智能体循环造步骤的速率由模型控制。无论选哪个，建议都一样——从第一个提交起就按引用存对话记录，因为撞上上限之后的那次迁移，是把每一个步骤签名都重写一遍。配三张 SVG。',
    ),
    L(
      'New Concept (Agentic AI) — *The Instruction Hierarchy*. Your system prompt outranks a fetched web page because the model was trained to prefer it, which gives it a failure rate where an access check has a return value: OpenAI\'s 2024 paper built the behaviour from synthetic data and context distillation and reports around a 63% improvement in robustness to system-prompt extraction — an improvement, on a benchmark nobody claimed to top — and the Model Spec\'s chain of command (root, system, developer, user, guideline, revision dated 18 August 2026) puts retrieved content, tool results and other agents\' messages below all five with no authority at all. Argues that the common design error is reasoning in message roles when the model\'s exposure is to provenance, so concatenating RAG chunks into the system message does not make them trustworthy, it makes them privileged. Names four degradations — distance in a long context, volume and repetition, laundering across a multi-agent hop, and the one that matters: the hierarchy only resolves conflicts, and the injections that work fit inside your instructions rather than contradicting them. Closes on using it as one layer with the real boundary at the tool, and on one edit worth making today: move retrieved documents out of the system message and into a labelled data channel.',
      '新增概念页（智能体 AI）——《指令层级》。你的系统提示词能压过一个抓回来的网页，是因为模型被训练成偏向它；于是它有的是失败率，而权限检查有的才是返回值：OpenAI 2024 年那篇论文用合成数据与上下文蒸馏造出了这个行为，报告在抗系统提示词提取上约有 63% 的稳健性提升——那是一次提升，发生在一条没人声称触顶的基准上——而 Model Spec 的指挥链（root、system、developer、user、guideline，现行版本日期为 2026 年 8 月 18 日）把检索内容、工具返回与其他智能体的消息放在这五层之下，完全没有权威。文章主张常见的设计错误是拿消息角色来推理，而模型真正接触到的是来源；所以把 RAG 切片拼进系统消息不会让它们变可信，只会让它们变特权。文中点名四种削弱——长上下文里的距离、体量与重复、跨多智能体一跳的洗白，以及最要命的那一种：这套层级只解决冲突，而真正得手的注入是严丝合缝装进你指令里的，不是与之矛盾的。文末落在「把它当一层来用、真正的边界放在工具上」，以及今天就值得做的一处改动：把检索到的文档从系统消息里挪进一条带标签的数据通道。',
    ),
    L(
      'New Playbook (Coding &amp; Computer-Use Agents) — *Infrastructure-as-Code Agents*. Every other coding agent has to build its own oracle; this one is handed `terraform plan` for free, so the deliverable is not code but a plan whose every line falls into a class you already agreed to auto-apply — and the whole engineering problem is that the plan is silent about exactly the four things that cause outages: `(known after apply)` values that propagate and cannot be expanded, server-side behaviour the provider only models, a destructive replace announced in the same tone as a new tag, and everything outside the state file. The answer is to classify the plan mechanically from `terraform show -json` into auto-apply, review, named-reviewer and reject classes, so reviewers judge a class rather than 300 lines of diff. Feeds the agent `terraform providers schema -json` (the `forces replacement` flag is exactly the input it needs) and the approved module catalogue rather than the raw repo, and treats state files and plan JSON as secret-bearing. Bans three one-line edits that make a red plan go green while making the plan dishonest — `ignore_changes`, `terraform state rm` and `-target` — as hard rejects in the classifier rather than as prompt instructions, and refuses to let the agent choose the direction of drift reconciliation, since ratifying a 3am fix and reverting it are opposite acts no context can disambiguate. Rolls out on an environment ladder and measures Class A rate and applies requiring rollback.',
      '新增实战手册（编码与计算机操作智能体）——《基础设施即代码智能体》。别的编码智能体都得自己造判据，这一个白得了 `terraform plan`，于是交付物不是代码，而是一份「每一行都落进你事先约定可自动执行的类别」的计划——而全部工程难度在于，计划恰恰对造成故障的那四件事只字不提：会传染且无法展开的 `(known after apply)` 值、provider 只能建模而无法决定的服务端行为、用与「加个新标签」相同语气宣布的破坏性替换，以及状态文件之外的一切。解法是用机器把 `terraform show -json` 的输出定级为自动执行、常规评审、指名评审人与驳回四类，好让评审者判断的是级别，而不是 300 行 diff。要把 `terraform providers schema -json`（其中 `forces replacement` 标记正是它需要的那个输入）与经过审批的模块目录喂给智能体，而不是丢给它整个仓库；并把 state 文件与 plan 的 JSON 都按含密数据对待。文中把三处「能让红计划变绿、同时让计划变得不诚实」的一行改动列为分类器里的硬性驳回而非提示词里的告诫——`ignore_changes`、`terraform state rm` 与 `-target`；并拒绝让智能体去选漂移调和的方向，因为「追认一次凌晨三点的应急处置」与「把它撤销」是两件相反的事，再多上下文也分辨不了。上线按环境阶梯推进，只量 A 级比例与需要回滚的 apply 次数。',
    ),
    L(
      'New Playbook (Domain Playbooks) — *Fraud &amp; Disputes Agents*. Two structural facts invert the design: false declines cost the industry roughly 13× the fraud they prevent (global card fraud losses were $33.41bn for 2024 per Nilson, against projected 2026 merchant losses from false declines above $231bn, at an average false-decline rate near 1.5% of e-commerce sales), and the transactions you decline never settle, so they never generate a label at all. The only honest fix for that second one is a budgeted approve-anyway holdout — a random sample of would-be declines approved on purpose, with the expected loss signed off in advance — because false-decline rate is otherwise not measurable and gets estimated from complaints instead. The calendar is the other constraint: Visa and Mastercard generally allow 120 days to raise a dispute, and Regulation E gives 10 business days before provisional credit and up to 45 (90 for point-of-sale, foreign-initiated and new-account transfers) to resolve — so there is no online eval on the metric that matters, A/B tests take a quarter, and a pipeline retraining on "the last 30 days" is labelling recent fraud as legitimate. Puts the agent in the case file rather than the authorisation path, where the risk decision gets tens of milliseconds. Ends on the compliance edge most likely to bite an ordinary summarisation feature: where a suspicious activity report exists its very existence is confidential, so the customer notification and the internal case note must be separately generated, structurally.',
      '新增实战手册（领域实战手册）——《欺诈与争议处理智能体》。两个结构性事实把设计翻了过来：误拒给行业造成的损失，约为它拦下的欺诈的 13 倍（据 Nilson，2024 年全球银行卡欺诈损失为 334.1 亿美元，而对 2026 年商户因误拒造成损失的预测超过 2,310 亿美元，平均误拒率在电商销售额的 1.5% 上下）；而你拒掉的交易从不结算，因此根本不会产生任何标签。对后一件事唯一诚实的解法，是一个有预算的「照放不误」留出组——把本会被拒的交易随机抽样、有意放行，并事先把预期损失签字确认——否则误拒率根本测不出来，只能从投诉里去估。另一项约束是日历：Visa 与 Mastercard 通常允许 120 天内发起争议，而 Regulation E 规定 10 个工作日内须给出临时入账、至多 45 天内结案（销售点、境外发起与新开户转账为 90 天）——于是在真正重要的那个指标上没有在线评测，A/B 测试要跑一个季度，而一条按「最近 30 天」重训的流水线正在把近期欺诈标成合法。文章把智能体放进案件卷宗，而不是放进那条只给风险决策几十毫秒的授权路径。文末落在最可能咬到一个普通摘要功能的合规边缘：凡涉及可疑活动报告，其存在本身即为保密，所以客户通知与内部案件记录必须在结构上分开生成。',
    ),
    L(
      'New Operation (AgentOps) — *Staging Environments for Agents*. The standard instinct — mock the dependencies, let the model float — is backwards: mocking a tool deletes the latency that dominates a trajectory, the error taxonomy you did not think of, and the drift that a staging environment exists to notice, while the model is the one component you can pin for free (version, prompt hash, tool-catalogue hash, index snapshot — pinned but still not deterministic, so read a pass rate rather than a pass). Lays out four fidelity tiers — replayed recordings that gate every commit and go stale silently, vendor sandboxes that gate merge, production dependencies with side effects neutralised at the last hop that gate release, and a bounded real blast radius that gates GA — under one rule: a tier may only gate a release step whose failures it could have caught. The load-bearing artefact is an egress write-blocker built at the network boundary rather than in the tool wrapper, and it must return a success the agent believes, or every run tests the error path instead. Seeds for volume, mess, permissions and injection attempts, never with a copy of production, and tunes the whole ladder on tier escape rate.',
      '新增运维页（智能体运维）——《给智能体做预发布环境》。标准直觉——把依赖 mock 掉、让模型随意浮动——是反的：把工具 mock 掉，删掉的是主导一条轨迹的延迟、你没想到过的错误分类，以及预发布环境本就为之而存在的「察觉漂移」这件事；而模型才是那个能免费钉住的部件（版本、prompt 哈希、工具目录哈希、索引快照——钉住了但仍非确定性，所以要读通过率而不是读一次通过）。文章给出四级保真度台阶——为每次提交把关、却会无声陈旧的回放录制；为合并把关的厂商沙箱；副作用在最后一跳被中和、为发布把关的生产依赖；以及爆炸半径受限的真实副作用，为全量可用把关——并统一于一条规矩：一级只能为「它本来抓得住其失败」的那一步发布把关。承重的那件产物，是一个建在网络边界而非工具封装里的出网写阻断器；而它必须返回一个智能体会相信的成功，否则每次运行测的都只是错误路径。种子数据按体量、混乱度、权限与注入尝试来灌，绝不用生产数据的副本；而整架梯子用逃逸率来调。',
    ),
  ],
};

export default entry;
