import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-09-19',
  title: L(
    'Two AI Blog posts — on the ad that brought its own agent, and on the smart-home MCP server that gated the half nobody was worried about — plus three pages on the principal–agent problem, smart-home agents, and commercial influence',
    '两篇 AI 博客——一篇讲那则自带智能体的广告，一篇讲那台给「没人担心的那一半」设了闸的智能家居 MCP 服务器——外加三个页面：委托—代理问题、智能家居智能体，以及商业影响',
  ),
  items: [
    L(
      'AI Blog — “The ad brought its own agent”: everyone predicted a bought ranking; OpenAI bought the conversation instead. Sponsored Agents, in limited alpha with selected US advertisers since 16 September and with Wayfair and Angi among the first, attach an advertiser-operated agent to a labelled ad slot, and OpenAI states it does not alter, rank into, or become part of the assistant’s independent answer. That is the stronger of the two designs, because a forked conversation leaves a counterfactual any user can check while a blended ranking leaves none. But the separation is a property of the session and what moves between the lanes is claims — a price, a spec, an SKU carried back by the person and re-entered as their own message, where the instruction hierarchy treats it as the trusted principal’s words. Nothing in the transcript is marked: no provenance attribute, nothing an export, a memory write, a voice read-aloud or another agent could filter on. The ask is one field, in the data rather than the UI, before the agent-to-agent case removes the label entirely.',
      'AI 博客《广告自带了一个智能体》：所有人都预言会是一个被买下的排序；OpenAI 买下的却是那场对话。Sponsored Agents 自 9 月 16 日起面向美国部分广告主小范围内测，Wayfair 与 Angi 属于首批，它把一个由广告主运营的智能体挂在带标注的广告位上；OpenAI 明确表示它不改动助手的独立答案、不排进去，也不成为其中的一部分。这是两种设计里更强的那个，因为分岔出来的对话留下了一个任何用户都能核查的反事实，而揉在一起的排序什么都不留。但那份分隔是会话的属性，而在两条通道之间移动的是论断——一个价格、一份规格、一个 SKU，被人带回去、再以自己的消息重新输入；在那里，指令层级会把它当作那个被信任的委托人的话。记录里没有任何东西被标记：没有溯源属性，导出、记忆写入、语音朗读或另一个智能体都无从过滤。诉求只是一个字段，放在数据里而不是 UI 里——趁智能体对智能体那一档还没有把标注整个抹掉之前。',
    ),
    L(
      'AI Blog — “Four reads and one write”: Google opened Home MCP in early access on 16 September for Home Premium Advanced subscribers in the US ($20 a month or $200 a year), with setup through a Google Cloud project and OAuth credentials, and named Antigravity, Claude, Hermes and OpenClaw as clients. Google blocked the thing everyone asked about — an agent may not unlock a door — and that gate sits on run_home_actions, one of five tools. The other four are reads, and list_home_history returns past state changes and event logs over any window you ask for, which is a behavioural record of the household: unbounded in time, impossible to un-read once it is in a context window, and with no sensitive-read blocklist because the sensitive object is a pattern rather than a row. Two more structural points: run_home_actions executes parameterized commands against trait schemas discovered at runtime, so an allowlist cannot be written in advance, and device names are attacker-supplied strings while camera event summaries are another model’s output. Scope reads as carefully as writes, and cap the window server-side.',
      'AI 博客《四个读与一个写》：Google 于 9 月 16 日开放 Home MCP 早期访问，面向美国的 Home Premium Advanced 订阅者（每月 20 美元或每年 200 美元），配置需经由一个 Google Cloud 项目与 OAuth 凭据，并点名 Antigravity、Claude、Hermes 与 OpenClaw 作为客户端。大家追问的那件事 Google 挡住了——智能体不得开门锁——而那道闸装在 run_home_actions 上，它是五个工具之一。另外四个是读，其中 list_home_history 会按你要的任意时间窗返回历史状态变化与事件日志，那是一份关于这户人家的行为记录：在时间上没有边界，一旦进了上下文窗口就再也读不回去，而且没有「敏感读」的阻止清单——因为敏感的那个对象是模式，不是某一行。还有两个结构性的点：run_home_actions 执行的是针对运行时才发现的 trait schema 的带参命令，所以白名单事先写不出来；而设备名是攻击者可供的字符串，摄像头事件摘要则是另一个模型的输出。给读定作用域要像给写定作用域一样上心，并在服务端给窗口设上限。',
    ),
    L(
      'Concepts — The Principal–Agent Problem: ask who an agent works for and you get at least three true answers — the user, the deployer, the model vendor — plus a fourth party that is not a principal but behaves like one, whoever wrote the text in the context window. Every element of the economic version transfers except the one people assume is protective: a human agent has interests of their own, which is both the source of the conflict and a limit on it, while a model has none and therefore does not negotiate — it silently obeys whichever principal the architecture privileged. So the conflicts that matter are architectural rather than ethical, and the tell is always an objective the user cannot see expressed as a metric someone is measured on. Write the ordering down in one sentence, separate the agents rather than blending the objectives, spend human review where interests diverge, and measure the conflicted metric next to the user metric.',
      '概念 — 委托—代理问题：问一句智能体替谁干活，你会得到至少三个同时成立的答案——用户、部署方、模型厂商——外加第四方：它不是委托人，行为上却像一个，也就是写下上下文窗口里那段文字的那一方。经济学版的每一个要素都迁移得过来，唯独人们默认能起保护作用的那个不行：人类代理人有自己的利益，那既是冲突的源头，也是冲突的限度；而模型一样都没有，于是它根本不斡旋——它默默服从架构抬高的那个委托人。所以真正要紧的冲突是架构性的、而不是道德性的，而破绽始终是「一个用户看不见的目标，被表述成一个有人要为之考核的指标」。把那个排序用一句话写下来，把智能体拆开而不是把目标揉在一起，把人工复核花在利益分岔之处，并把那个有冲突的指标与用户侧指标摆在一起量。',
    ),
    L(
      'Playbooks — Smart-Home &amp; IoT Agents: every demo turns on a light and every incident will be about something the agent read. Sort devices by reversibility rather than category — reversible and cheap, reversible but consequential, irreversible or safety-bearing — and grant unattended autonomy only to the first; refusing to expose a capability beats gating it, because a confirmation that fires often becomes a reflex. Because command schemas are discovered at runtime per trait, an allowlist of actions cannot be written in advance: classify traits, default-deny unknown ones, and alert when the surface grows because somebody went shopping. The physical world has no transactions, so express commands as absolute targets, verify with an observation rather than a return code, and treat a timeout as unknown rather than failed. Then budget the event history like a cost — cap the window, fetch for a stated purpose, exclude it from memory — and design for the household members who never saw the consent screen.',
      '实战手册 — 智能家居与 IoT 智能体：每一场演示都在开灯，而每一起事故都会是关于智能体读到的什么东西。按可撤销性而非品类给设备分类——可撤销且后果轻、可撤销但后果重、不可撤销或承载安全——并且只把无人值守的自主权给第一类；拒绝暴露一项能力好过给它设闸，因为一个触发频繁的确认会变成条件反射。由于命令 schema 是按 trait 在运行时被发现的，动作白名单事先写不出来：请给 trait 分类、对未知的一律默认拒绝，并在「有人去逛街了」导致接口面变大时告警。物理世界没有事务，所以把命令表达成绝对目标、用一次观测而不是返回码来核验，并把超时当作未知而不是失败。然后像做成本预算一样对待事件历史——给窗口设上限、带着明确目的去取、把它排除在记忆之外——并为那些从没看见过同意屏的同住者做设计。',
    ),
    L(
      'Operations — Commercial Influence &amp; Paid Placement: most teams believe they have no advertising problem, and most are wrong — affiliate content in retrieved pages, a connector marketplace with a commercial dimension, a preferred-supplier list, a sponsored conversational surface, cost-based routing, and the model’s own brand priors are all influence arriving through channels nobody registered. The obligations that exist assume a human reader: the FTC Endorsement Guides turn on disclosing a material connection clearly and conspicuously, and the DSA requires platforms to let users identify an ad in real time with a public repository for very large ones — all visible marks on a rendered surface, which is an absent control once the reader is a summariser, a memory store or another agent. So stamp provenance on every tool result at ingestion, compute relevance and then apply commercial adjustment as a named logged step, version the ranking configuration and bind it to the answer, and measure the influence rate with a counterfactual run on fifty real queries before writing any policy.',
      '运维 — 商业影响与付费位：多数团队相信自己没有广告问题，而多数是错的——被检索页面里的联盟营销内容、一个带着商业维度的连接器市场、一份优选供应商名单、一个赞助式对话界面、按成本做的路由，以及模型自己的品牌先验，全都是走在无人登记的通道上的影响。现有的那些义务假定读者是人：FTC《背书指南》的关键在于清晰显著地披露实质关联，而《数字服务法》要求平台让用户实时辨认出广告、并对超大型平台要求公开存档——这些都是渲染面上的可见记号；而一旦读者变成摘要器、记忆库或另一个智能体，它就是一道不存在的管控。所以请在摄入时就把溯源盖在每一份工具结果上，先算相关性、再把商业调整作为一个具名有日志的步骤施加上去，给排序配置打版本并与答案绑定，并在写任何政策之前，先拿五十条真实查询跑一次反事实运行去测量影响率。',
    ),
  ],
};

export default entry;
