import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-09-24',
  title: L(
    'Two AI Blog posts — on the vulnerability finder that beat two frontier labs with small models and a better scaffold, and on the four workload-identity systems that all fix the static key and none fix the confused deputy — plus three pages on context taint tracking, access reviews for agent credentials, and consumer credit agents',
    '两篇 AI 博客——一篇讲那个靠小模型加更好的脚手架赢过两家前沿实验室的漏洞发现器，一篇讲四套工作负载身份系统：它们都修好了静态密钥，却都没修「被搞糊涂的代理人」——外加三个页面：上下文污点追踪、智能体凭据的权限复核，以及消费信贷智能体',
  ),
  items: [
    L(
      'AI Blog — “The scaffold found the bug, not the model”: curl 8.22.0 shipped on 2 September 2026 with nine security advisories, six of them crediting one AISLE reporter for findings filed over four days in late August, all rated Low; AISLE is also credited with six of the eighteen CVEs in curl 8.21.0 in June — a record for a single release — including CVE-2026-8932, first shipped in curl 7.7 on 22 March 2001 and the oldest security issue in the project’s history. The vendor says OpenAI’s Codex and Anthropic’s Mythos found nothing over the same window. The published evidence points at the scaffold rather than the model: HoF-Bench (arXiv 2607.27030) pins 95 public AI-found CVEs across eight repositories at their vulnerable commits, withholds identifiers, descriptions, fixes and expected mechanisms, and credits a finding only when code path, root cause, attack condition and impact all match — and under that protocol a deliberately minimal analyzer recovers up to 65 of 95 (68%) using five open-weight models at 3–13B active parameters and five small proprietary ones, with no frontier model in the detection path anywhere in the study. The binding constraint is precision, not recall: 29 reports filed, six accepted, and curl had already closed its HackerOne bounty in January 2026 over fabricated AI reports. Buy on accepted findings per maintainer-hour, ask about passes and triage rounds rather than about the model, and pin ten of your own historical CVEs to evaluate blind.',
      'AI 博客《找到漏洞的是脚手架，不是模型》：curl 8.22.0 于 2026 年 9 月 2 日发布，带九份安全公告，其中六份署着同一位 AISLE 报告人在八月下旬四天内提交的发现，全部评为 Low；而在六月的 curl 8.21.0 里，十八个 CVE——单次发布的纪录——中也有六个署着 AISLE，其中包括 CVE-2026-8932：它最早随 2001 年 3 月 22 日的 curl 7.7 出厂，是该项目史上最老的安全问题。厂商称 OpenAI 的 Codex 与 Anthropic 的 Mythos 在同一窗口里一无所获。已公开的证据指向脚手架而非模型：HoF-Bench（arXiv 2607.27030）把八个仓库里 95 个公开的「由 AI 发现的 CVE」各自钉在有漏洞的提交上，不给编号、不给描述、不给修复、不给预期成因，只有当代码路径、根因、触发条件与影响四项全部对上才算数——而在这套协议下，一个刻意做得极简的分析器用五个激活参数 3B–13B 的开放权重模型加五个小型专有模型，找回了 95 个中的至多 65 个（68%），全研究的检测环节没有任何前沿模型。真正的约束是精确率而非召回率：提交 29 份、接受 6 份，而 curl 早在 2026 年 1 月就因编造出来的 AI 报告关停了它的 HackerOne 赏金。请按「每维护者分诊工时换来几项被接受的发现」来买，去问轮次与分诊轮数而不是问用了哪个模型，并把你自己历史上的十个 CVE 钉住做一次盲评。',
    ),
    L(
      'AI Blog — “SPIRE vs Teleport vs IAM Roles Anywhere vs Vault”: all four delete the long-lived key in an agent’s environment variable, and the choice between them is mostly where the trust anchor lives. SPIRE attests in two stages — node then workload — with no bootstrap secret, issues X.509 and JWT SVIDs on a one-hour default lifetime with rotation around the half-life, and leaves you a registration database to operate; Teleport issues the same SVIDs over the same Workload API, federates with SPIRE trust domains, and maps policy onto its existing RBAC so human and workload access share one control plane and one audit log; AWS IAM Roles Anywhere exchanges a certificate for temporary AWS credentials, costs nothing itself but sits on AWS Private CA at roughly $400 per month in general-purpose mode against about an eighth of that for short-lived certificates, and terminates at AWS; Vault consumes an identity better than it mints one — its SPIFFE auth method validates externally-issued SVIDs rather than generating them, which is why deploying it alone just moves the bootstrap problem one layer down. The half none of them touches is the one 2026’s incidents are about: an SVID proves which process is calling and says nothing about which user the turn serves or who wrote the instruction now in the context.',
      'AI 博客《SPIRE、Teleport、IAM Roles Anywhere 与 Vault 对比》：四者都能删掉智能体环境变量里那把长期密钥，而它们之间的取舍主要在于信任锚放在哪儿。SPIRE 分两阶段做证明——先节点、后工作负载——无需任何引导秘密，签发默认一小时有效期、在半衰期前后轮换的 X.509 与 JWT SVID，并留给你一个要运维的注册库；Teleport 通过同样的 Workload API 签发同样的 SVID，可与 SPIRE 信任域联邦，并把策略映射到它既有的 RBAC 上，于是人员访问与工作负载访问共用一个控制平面、一份审计日志；AWS IAM Roles Anywhere 拿证书换临时 AWS 凭据，服务本身不收费，却坐在 AWS Private CA 之上——通用模式约每月 400 美元，短命证书模式约为其八分之一——并且终结于 AWS；Vault 消费身份比生产身份更在行，它的 SPIFFE 认证方法校验外部签发的 SVID 而非自己生成，这正是单独部署它只会把引导问题往下挪一层的原因。它们谁也没碰的那一半，恰恰是 2026 年事故在讲的：SVID 证明的是哪个进程在调用，对「这一轮服务哪位用户」和「上下文里那条指令是谁写的」一字不提。',
    ),
    L(
      'Concepts — Context Taint Tracking: a context window is a flat string, so every injection defence that reads the text to judge whether it is an instruction is guessing at something it could simply have recorded. Taint tracking labels data at the boundary and checks the label at the tool call — bookkeeping rather than classification, with a failure mode you can enumerate instead of a false-negative rate you can only estimate. Because the model is not a boundary, honest propagation taints the whole context in one hop, so the label has to gate arguments rather than turns, and the split context is where taint finally stops. CaMeL (arXiv 2503.18813) is the reference construction — a privileged model plans from the trusted request alone, a quarantined model parses untrusted content with no tools, and a custom interpreter attaches capability metadata to every value, completing 77% of AgentDojo tasks with a provable guarantee — and its ceiling is that the plan must be written before the data is seen. The version worth building this week is smaller: a trust level on the tool-result envelope, a reader/writer classification of your tools, and a dispatcher that refuses a privileged write whose arguments trace back to a tool result.',
      '概念 — 上下文污点追踪：上下文窗口是一根扁平的字符串，于是每一种「读文本、判断它是不是指令」的注入防御，都在猜一件本来只要记下来就好的事。污点追踪在边界处给数据打标签，并在工具调用处检查这个标签——是记账而不是分类，其失效方式可以一条条列举，而不是只剩一个你只能估的漏报率。由于模型本身不是一道边界，诚实的传播会一跳之内污染整个上下文，所以标签必须去盖住参数而不是盖住一整轮，而切开的上下文才是污点终于停下来的地方。CaMeL（arXiv 2503.18813）是参照性的构造——一个有特权的模型仅凭可信请求做规划，一个被隔离的模型在没有工具的情况下解析不可信内容，一个定制解释器给每个值挂上能力元数据，在 AgentDojo 上以可证明的保证完成了 77% 的任务——而它的天花板在于：计划必须在看见数据之前就写好。这周值得动手的是更小的版本：给工具结果信封加一个信任级别，把工具分成读方与写方，再让派发器拒绝那些参数可回溯到工具结果的特权写操作。',
    ),
    L(
      'Operations — Access Reviews for Agent Credentials: every access review programme works because HR emits a termination event, and that event — not the quarterly attestation — is what actually removes entitlements. An agent has none, has no manager who can meaningfully attest, and changes its effective reach on a deploy rather than a transfer, so adding service principals to the same review produces approval at scale and cleanup of nothing. Review the reachable call rather than the credential row, because one credential carries many capabilities while one agent carries many credentials plus ambient reach that appears in no credential store; capture reason, named owner and bound limit at grant time, since none of the three can be reconstructed later; and replace the attestation with use-based expiry driven off last-accessed data you already collect — unused for ninety days is revoked with a one-click restore, and a limit never approached gets ratcheted down. The delegated half does have a leaver event: index those grants by the human, revoke on termination, expire consent independently of the OAuth token, and keep acting agent and authorising human as separate log fields. Removals per period is the health metric, and a flat zero should worry you more than a large number.',
      '运维 — 智能体凭据的权限复核：每一套权限复核之所以管用，都因为 HR 会发出一个离职事件，而真正移除权限的是那个事件，不是季度认证。智能体没有离职事件，没有能实质背书的主管，而且它实际可达范围的变化发生在一次部署而不是一次调岗上——所以把服务主体塞进同一场复核，只会产出规模化的「通过」和零清理。请复核「够得着的调用」而不是凭据那一行，因为一份凭据承载多项能力，而一个智能体承载多份凭据、外加压根不出现在任何凭据库里的环境可达范围；在授予的那一刻就记下理由、具名归属方与绑定限额，因为这三样事后一个也重建不出来；并用「按使用情况到期」取代认证，数据就来自你早已在收集的最后访问记录——九十天未使用即吊销，并提供一键恢复；从未接近过的限额则一档档往下拧。受委托的那一半确实有离职事件：把这些授权按人索引、在离职时吊销、让同意的有效期独立于 OAuth 令牌，并把「行动的智能体」与「授权的人」保持为两个日志字段。每期移除数是健康指标，而一个平平的零，比一个很大的数字更该让你担心。',
    ),
    L(
      'Playbooks — Consumer Credit Agents: teams brace for the explainability problem and get caught by the conversation, because under Regulation B three of the four regulated acts happen before anything is decided. What the agent asks is restricted by §1002.5; what it says to a hesitant applicant can be unlawful discouragement under §1002.4(b), which attaches to a statement with no application and no decision required — and telling a marginal applicant they probably will not qualify is exactly what a helpful assistant is trained to do; and the moment it stops collecting documents starts the thirty-day notification clock in §1002.9 that nobody wired a timer to. Build intake as a closed question registry the model selects from but never extends, strip volunteered protected information at the boundary rather than arguing later about whether it was used, write the completeness predicate as a rule that emits a timestamped event, keep scoring in a declared model the agent cannot reach, and draw reasons from a fixed catalogue bound to declared variables. Measure document-extraction accuracy on the denial population specifically — thin files, irregular income, handwritten and foreign-language documents are the tail that produces wrong principal reasons. Anchor on the regulation, not the guidance: supervisory guidance on AI underwriting has been issued, withdrawn and reissued since 2023 while §1002.9 has not moved, and in the EU creditworthiness is Annex III high-risk with the standalone obligations deferred to 2 December 2027.',
      '实战手册 — 消费信贷智能体：团队们绷紧神经准备应对可解释性难题，却栽在那段对话上，因为在 Regulation B 之下，四个受监管的行为里有三个发生在任何决定作出之前。智能体能问什么受 §1002.5 限制；它对一位犹豫的申请人说的话可能构成 §1002.4(b) 下的违法劝退，而这项责任附着在「说了一句话」上，既不需要有申请也不需要有决定——而告诉一位边缘申请人「你多半过不了」，恰恰是一个乐于助人的助手被训练出来要做的事；而它停止收集材料的那一刻，就启动了 §1002.9 里那个没人接上计时器的三十天通知时钟。请把受理环节建成一份封闭的问题登记表，模型只从中挑选、绝不扩充；把主动提供的受保护信息在边界处剥掉，而不是事后去争辩它有没有被用上；把完整性判定写成一条会发出带时间戳事件的规则；把评分留在智能体够不着的、经申报的模型里；并从一份与申报变量绑定的固定目录里取用理由。要专门在拒贷样本上测量文档抽取准确率——薄档案、不规则收入、手写与外文材料，正是那条产出错误主要理由的长尾。把锚下在法规上而不是指引上：关于 AI 授信的监管指引自 2023 年以来经历了发布、撤回、再发布，而同一段时间里 §1002.9 一动没动；在欧盟，信用状况评估属附件三高风险，其独立义务已推迟至 2027 年 12 月 2 日。',
    ),
  ],
};

export default entry;
