import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-09-26',
  title: L(
    'Two AI Blog posts — on the 48 hours Amazon spent blocking one agent and handing another its seller APIs, and on why the standing-instructions argument is about file names when it should be about when the text loads — plus three pages on fail-closed and fail-open, agents in shared channels, and lifecycle hooks as the config surface with no change management',
    '两篇 AI 博客——一篇讲亚马逊用 48 小时拦掉一个智能体、又把卖家 API 交给另一个，一篇讲「常驻指令」之争为何在争文件名、而本该争「文字何时加载」——外加三个页面：失败趋关闭与失败趋开放、共享频道里的智能体，以及生命周期钩子这个没有变更管理的配置面',
  ),
  items: [
    L(
      'AI Blog — “Amazon opened the back office and closed the storefront in the same week”: on 21 September 2026 Amazon began blocking Meta’s Muse agent from shopping on Amazon.com, telling shoppers that continued access by an unauthorized AI agent violates its Conditions of Use; on 23 September, at Accelerate, it shipped a Selling Partner plugin that exposes Seller Central inventory, pricing, listing and analytics actions to outside AI clients, in US beta with Anthropic’s Claude and Amazon Quick. Read as one rule rather than a contradiction, the pair says a platform admits an agent exactly where a delegation already exists that it can verify, scope and revoke — which the seller side has had for a decade in the form of a contracted partner account with its own credential, and which the buyer side does not have at all, because a third-party shopping agent’s only way to act as you is your own login. Amazon’s three stated objections map onto three missing mechanisms rather than missing permissions: no registration, no verifiable operator identity, no per-task mandate. The tell is that Amazon joined the UCP Tech Council in April 2026, five months before the block and alongside Meta: not anti-agent, anti-unmediated, and holding a seat where the mediation gets specified.',
      'AI 博客《亚马逊在同一周里打开了后台、关上了店面》：2026 年 9 月 21 日，亚马逊开始拦阻 Meta 的 Muse 智能体在 Amazon.com 上购物，并告知购物者「未经授权的 AI 智能体继续访问违反其《使用条件》」；9 月 23 日，在 Accelerate 大会上，它交付了一个 Selling Partner 插件，把 Seller Central 的库存、定价、商品信息与分析动作暴露给外部 AI 客户端，以美国 beta 形式随 Anthropic 的 Claude 与 Amazon Quick 上线。把这两件当成同一条规则而不是自相矛盾来读，它们说的是：平台恰恰在「已经存在一份它能核验、限定范围并撤销的委托」的地方放智能体进来——卖家侧以「一个签了约、自带凭据的合作方账号」的形式拥有这个东西已有十年，而买家侧完全没有，因为一个第三方购物智能体要以你的身份行动，唯一的路就是你自己的登录态。亚马逊给出的三条异议，对应的是三项缺失的机制而不是缺失的许可：没有登记、没有可核验的运营方身份、没有按任务的授权令。真正的破绽是：亚马逊在 2026 年 4 月就加入了 UCP 技术理事会，比这次拦阻早五个月，而且与 Meta 同期加入——它不反智能体，它反无中介，并且在那条中介正被规定的房间里占着一个席位。',
    ),
    L(
      'AI Blog — “AGENTS.md vs CLAUDE.md vs Cursor rules vs Agent Skills”: the format war is about file names and the file name decides almost nothing. What separates the four is when their text enters the context window — always, on a glob match, when the model reads a description and asks, or only on an explicit mention — and who is allowed to put text there. Always-on text is a tax with compound interest, because long context degrades selectively: past some length, adding a rule reduces adherence to the rules already present, so the team that documented everything gets worse compliance than the team that documented five things. On-demand text trades that for a failure that emits no error, since a skill that never triggers is indistinguishable from a skill that does nothing, and the description is the only part always in context and therefore the only part you can debug. September settled the portability half — Claude Code 2.1.277 reads AGENTS.md when no CLAUDE.md is present, fixed by 2.1.278 on 19 September 2026 — leaving layering and precedence as the real difference. Cursor’s four declarable modes are the only place a vendor made the rung a first-class choice, and the axis nobody tables is that every repository-scoped instruction file is an attacker-supplied system prompt the moment you check out a fork.',
      'AI 博客《AGENTS.md、CLAUDE.md、Cursor rules 与 Agent Skills 对比》：这场格式之争在争文件名，而文件名几乎什么也决定不了。真正把四者分开的，是它们的文字在什么时候进入上下文窗口——始终、glob 匹配时、模型读了描述主动要的时候，还是只有被显式提及时——以及谁被允许把文字放进那里。始终加载的文字是一笔带复利的税，因为长上下文的退化是有选择性的：过了某个长度，再加一条规则会降低对已有规则的遵循，于是把一切都写下来的团队，服从率反而不如只写了五件事的团队。按需加载的文字则把这笔税换成一种不产生任何报错的失效：一个从不被触发的技能与一个毫无效果的技能无从区分，而描述是唯一始终在上下文里、因而也是唯一你能调试的部分。九月把可移植性那一半定了下来——Claude Code 2.1.277 在没有 CLAUDE.md 时会读 AGENTS.md，并在 2026 年 9 月 19 日的 2.1.278 修定——剩下的真实差别是分层与优先级。Cursor 那四种可声明的模式，是唯一一处厂商把「哪一档」做成一等选择的地方；而没人放进对比表的那根轴是：每一个仓库作用域的指令文件，在你检出一个 fork 的那一刻，就是一份由攻击者提供的系统提示词。',
    ),
    L(
      'Concepts — Fail-Closed and Fail-Open: almost every control in a working agent stack fails open, and it does so in a form your dashboards read as a clean pass, because the timed-out classifier returns nothing and nothing looks exactly like “no injection found”. So the first question is detectability rather than direction — three structural properties push every default towards allow: an empty result means “nothing found” means allow, an instruction in a prompt has no error path at all, and agents retry until a human with production access switches the failing check off. Give each control a third state (clean / findings / unavailable) and an invocation counter, then choose by what the control is: enforcement points fail closed always and deserve a cache and a static fallback policy rather than an exception handler, probabilistic detectors fail open but must carry the unavailable verdict forward into a lower autonomy tier, and irreversibility overrides both. Where fail-closed is unaffordable, bound the authority so the open failure is boring, and test it by killing the policy engine rather than by reading the code.',
      '概念 — 失败趋关闭与失败趋开放：一个跑得起来的智能体技术栈里几乎每一道控制都是失败趋开放的，而且它开放的形态会被你的仪表盘读成「干净通过」，因为那个超时的分类器什么也没返回，而「什么也没有」看起来恰好就是「没发现注入」。所以第一个问题是可察觉性而不是方向——有三条结构性性质把每个默认值推向「允许」：空结果意味着「什么也没发现」意味着允许；提示词里的一条指令根本没有错误路径；而智能体会一直重试，直到某个有生产权限的人把那道失败的检查关掉。请给每道控制第三种状态（干净／有发现／不可用）和一个调用计数器，然后按「这道控制是什么」来选：强制点一律失败趋关闭，并且值得一份缓存和一条静态兜底策略，而不是一个异常处理块；概率型检测器失败趋开放，但必须把「不可用」这个判定往下传成更低的自主档；而不可逆性压倒上面两条。在失败趋关闭负担不起的地方，请框住权限，让那次开放失败变得乏味；并且靠杀掉策略引擎去测它，而不是靠读代码。',
    ),
    L(
      'Playbooks — Agents in Shared Channels: a team channel pulls apart two things a one-to-one thread always kept together, namely who the agent works for and who wrote the text it is reading, and every framework still has exactly one user field for both. Default to silence with explicit address as the only trigger, never act on backscroll, and rate-limit by room rather than by person because two messages into a nine-person channel is eighteen interruptions. Resolve authority from the requester at the moment of the request and intersect it with what the room may see, since an engineer who can query the salary table in a DM must not be able to in #general; treat an unresolvable guest identity as a refusal rather than a fallback to the app’s own token. Then mark only the addressed message as an instruction and label pasted, forwarded and bot-authored content as the untrusted tier it is — a shared channel converts indirect prompt injection from an exotic attack into an everyday accident, because accumulating outside text is the room’s whole purpose.',
      '实战手册 — 共享频道里的智能体：团队频道把一对一对话一直绑在一起的两件事拆开了，也就是智能体在为谁办事、以及是谁写下了它正在读的文字，而每个框架仍然只用一个 user 字段装下两者。请默认沉默、以显式称呼作为唯一触发，绝不照着历史记录行动，并按房间而不是按人限流——因为往九人频道里发两条消息就是十八次打扰。请在请求发生的那一刻从发起者那里解析权限，并与这个房间被允许看到的东西取交集，因为一个能在私聊里查薪酬表的工程师，绝不能在 #general 里这么做；并把「无法解析的访客身份」当作一次拒绝，而不是退回应用自己的令牌。然后只把被称呼的那条消息标为指令，并把粘贴、转发与机器人撰写的内容标成它本来的那个不可信档——共享频道把间接提示词注入从一种异域攻击变成了一桩日常事故，因为「把外面的文字攒进来」正是这个房间的全部用途。',
    ),
    L(
      'Operations — Lifecycle Hooks & Harness Config: every control you built around your coding agent sits between the model proposing something and a human or policy engine approving it, and a lifecycle hook takes neither path — it is a shell command bound to an event, running with the developer’s full environment, firing at moments the model never observes, and shipping as settings rather than code. September 2026’s HookPry results put a number on the gap: a benign versioned plugin trojanised by an update that binds attacker-chosen commands to ordinary events compromised all seven harnesses evaluated across 1,000 runs, so the exposure is version-to-version review rather than installation, which means “read the plugin before installing” protects against the case that was never the problem. Enumerate the effective hook set from every precedence layer on every host including CI runners, hash each command so the inventory becomes a drift detector, move the config into the pipeline you already trust for code with digest pinning and a CODEOWNERS gate, and buy the largest remaining reduction with an explicit environment allow-list and default-deny egress. Do not ban hooks: they are the only mechanism most harnesses give you for a check the model cannot reweigh.',
      '运维 — 生命周期钩子与 harness 配置：你围着编程智能体建起的每一道控制，都坐在「模型提议一件事」与「人或策略引擎批准它」之间，而生命周期钩子两条路都不走——它是一条绑在事件上的 shell 命令，带着开发者的完整环境运行，在模型从未观察到的时刻触发，并以设置而非代码的形态交付。2026 年 9 月的 HookPry 结果给这道缝隙标上了数字：一个良性的、带版本的插件被一次「把攻击者选定的命令绑到寻常事件上」的更新木马化，在 1,000 次运行中攻破了受评的全部七个 harness——所以暴露面在「版本到版本的评审」而不是安装，这意味着「安装前先读一遍插件」防住的恰恰是那个从来就不是问题的情形。请从每台宿主（包括 CI 运行器）上的每一个优先级层枚举出生效的钩子集合、给每条命令做哈希以把清单变成漂移探测器、把配置挪进你已经为代码所信任的那条流水线（含按摘要钉住与一道 CODEOWNERS 关卡），并用一份显式的环境允许清单加默认拒绝出站买下剩下最大的那份削减。不要禁掉钩子：它们是多数 harness 给你的唯一一个做「模型无法重新权衡的检查」的机制。',
    ),
  ],
};

export default entry;
