import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-09-02',
  title: L(
    'Two AI Blog posts — on the four agent frameworks outside Python, where a Spring Boot major version decides the answer, and on the 32% who skipped a software purchase at the cheapest moment to measure it — plus three pages on agent payments, voice recording consent, and insider misuse of the agent you approved',
    '两篇 AI 博客——Python 之外的四个智能体框架，答案由一个 Spring Boot 大版本决定；以及那 32% 在最便宜的时刻放弃了一次软件采购的企业——外加三个页面：智能体支付、语音录音的同意，以及对你自己批准的那台智能体的内部滥用',
  ),
  items: [
    L(
      'New AI Blog post `/blogs/spring-ai-vs-langchain4j-vs-eino-vs-rig` — four agent frameworks outside Python, compared on the axis that actually decides: what each one demands of the runtime you already operate. Spring AI 2.0 went GA on 12 June 2026 targeting Spring Boot 4.0/4.1 on Spring Framework 7 and bringing Jackson 3, so for an estate on Boot 3.x adding an agent to one service is a platform migration; LangChain4j ships starters for both Boot 3.5+ and Boot 4 and is not coupled to a web framework at all, which is its entire argument and enough. Eino (ByteDance, under CloudWeGo) and Rig (Rust, past 7,600 stars mid-2026, WASM-capable) exist because a Go or Rust service already deploys as one binary and nobody wanted a Python sidecar. The load-bearing observation: MCP dissolved the "Python has the integrations" argument — tools now live behind servers reached over HTTP and all four are clients — while the second ring (prompt optimisers, eval harnesses, RL environment tooling) did not cross, because it imports your agent rather than calling it. With the detail most enterprises will not expect: on the 2026-07-28 specification Go and Rust hold Tier 1 SDK conformance and Java sits at Tier 2.',
      '新增 AI 博客 `/blogs/spring-ai-vs-langchain4j-vs-eino-vs-rig`——Python 之外的四个智能体框架，比的是那条真正定胜负的轴：每一个对你已经在跑的运行时提出了什么要求。Spring AI 2.0 于 2026 年 6 月 12 日 GA，面向 Spring Framework 7 之上的 Spring Boot 4.0/4.1，并把 Jackson 3 一起带来，所以对一份还在 Boot 3.x 上的资产来说，给一个服务加上智能体就是一次平台迁移；LangChain4j 则同时发布 Boot 3.5+ 与 Boot 4 两套 starter，且根本不与某个 Web 框架绑定——这就是它的全部理由，而且够了。Eino（字节跳动，CloudWeGo 之下）与 Rig（Rust，2026 年年中越过 7,600 星，可编译到 WASM）之所以存在，是因为一个 Go 或 Rust 服务本来就以单个二进制部署，没人愿意再支一个 Python 边车。承重的那个观察是：MCP 消解了"集成都在 Python 那边"这条理由——工具如今活在通过 HTTP 触达的服务器背后，而这四个都是客户端——但第二环（提示词优化器、评测台、强化学习环境工具）没有跨过来，因为它们是把你的智能体 import 进去而不是调用它。还有一个多数企业不会预料到的细节：在 2026-07-28 规范上，Go 与 Rust 持有一级 SDK 一致性，而 Java 在二级。',
    ),
    L(
      'New AI Blog post `/blogs/a-skipped-purchase-is-not-a-deployment` — McKinsey’s State of AI (surveyed 4 May to 8 June 2026, 1,719 respondents in 97 nations) found 32% of organisations declined at least one software purchase because agentic coding tools could build it internally, with a spread of only nine points across industries — technology 41%, financial institutions 36%, pharma 33% — so this is not a technology-sector story. The post argues the number measures a decision rather than a system, recorded at the cheapest moment that will ever exist for it: respondents were not asked whether the replacement shipped, passed a security review, or is still running a year later, and the same survey has AI’s EBIT contribution flat at 37% and two-thirds of organisations not yet scaling. What a licence actually bundled was maintenance, patching, audit artefacts, integration testing, on-call, a roadmap and someone else’s liability — one of eight line items got cheaper and seven changed owner. Also reads the high-performer correlation the other way (owning software is a capability you must already have) and closes on a register of skipped purchases measured at month 13.',
      '新增 AI 博客 `/blogs/a-skipped-purchase-is-not-a-deployment`——麦肯锡《AI 现状》（2026 年 5 月 4 日至 6 月 8 日调查，97 国 1,719 名受访者）发现 32% 的组织至少放弃了一次软件采购，因为智能体编码工具能在内部把它做出来；而各行业之间只差九个百分点——科技业 41%、金融机构 36%、制药 33%——所以这并不是一个科技行业的故事。本文主张这个数字量的是一个决定而不是一套系统，且是在它这辈子最便宜的那一刻被记录的：没有人问受访者替代品是否发布、是否过了安全评审、一年之后是否还在跑；而同一份调查里，AI 的 EBIT 贡献停在 37% 纹丝不动，三分之二的组织尚未开始规模化。一份许可证真正打包的是维护、打补丁、审计凭证、集成测试、值班、路线图，以及别人的责任——八个条目里只有一个变便宜了，另外七个换了主人。文中还把"高绩效者"那条相关性反过来读（拥有软件是一种你必须先具备的能力），并落在一份「放弃采购」登记册与在第 13 个月做测量上。',
    ),
    L(
      'New Concept `/concepts/agent-payments` (A24) — a card number is a bearer credential, so the ceiling, the merchant and the purpose all live in a system prompt the agent is free to reinterpret. What the 2026 protocols added is not a faster rail but a mandate: a signed, bounded record of what one named human authorised, verifiable by a party that does not trust your agent. The page defines the intent mandate (human absent, spend inside an envelope) against the cart mandate (this exact basket, single-use, worthless to an attacker) as the human-in-the-loop question rewritten as data, and covers why the card networks arrived from the opposite direction — Mastercard Agent Pay’s Agentic Tokens (April 2025), Visa’s Trusted Agent Protocol with a Verified Agent ID plus an issuer-signed consent record (September 2025), the convergence of Visa’s Intelligent Commerce Connect (April 2026) and AP2 plus Mastercard Verifiable Intent going to the FIDO Alliance (May 2026) — because an unlabelled agent purchase looks like card-not-present fraud, so the first symptom of getting this wrong is a decline rate. Closes on the swap: delete "do not spend more than $200" from the prompt and issue a credential that cannot.',
      '新增概念页 `/concepts/agent-payments`（A24）——卡号是一张持有即有效的凭据，于是额度、商户与用途，全都活在一段智能体可以随意重新诠释的系统提示词里。2026 年这批协议补上的不是更快的通道，而是「授权书」：一份签过名、划定边界、写明某位具名的人授权了什么的记录，且能被一个并不信任你的智能体的第三方验证。本页把"意图授权书"（人不在场，在信封之内花钱）与"购物车授权书"（就这一篮子、一次性、对攻击者一文不值）对照定义，作为「人在回路」这个问题被改写成数据的形态；并讲清了卡组织为什么从相反方向到达同一处——Mastercard Agent Pay 的 Agentic Token（2025 年 4 月）、Visa 带 Verified Agent ID 与发卡行签名同意记录的 Trusted Agent Protocol（2025 年 9 月）、以及 Visa Intelligent Commerce Connect（2026 年 4 月）与 AP2、Mastercard Verifiable Intent 进入 FIDO 联盟（2026 年 5 月）所代表的收敛——因为一笔没有标记的智能体购买看上去就像无卡交易欺诈，所以这件事做错了，第一个症状是拒付率。文末落在那次替换：把"不要花超过 200 美元"从提示词里删掉，换成一张根本花不出这么多的凭据。',
    ),
    L(
      'New Playbook `/playbooks/voice-realtime-agents/recording-consent-and-redaction` (V15) — your retention rule points at the call recording, and the recording is now the least interesting copy: the same minute also exists as an ASR transcript, a model context, tool arguments, a trace span and a CRM summary, five artefacts the agent created that inherited no policy. The page walks the consent state machine (attach the recorder on the consent event rather than call setup, because media starts flowing four seconds earlier and those four seconds live in all six sinks; default to all-party consent rather than resolving jurisdiction from an area code, with the twelve all-party states named), treats disclosure as session state the agent must re-assert on warm transfer, outbound, barge-in and direct question now that EU AI Act Article 50 has applied since 2 August 2026, and is blunt about payment data: PCI DSS v4.0.1 treats manual pause-and-resume as a partial control, and a model cannot look away, so the digits must never reach the agent leg. Closes on one versioned redactor in front of every sink at write time, and a quarterly deletion drill that times how long erasure actually takes across all six.',
      '新增实战页 `/playbooks/voice-realtime-agents/recording-consent-and-redaction`（V15）——你的留存规则指着通话录音，而录音如今是最不值一提的那份副本：同样一分钟还以 ASR 转写稿、模型上下文、工具参数、追踪 span 与 CRM 摘要的形式存在，这五件由智能体造出来的产物一条策略都没继承到。本页走了一遍同意状态机（让录音器挂在同意事件而不是呼叫建立上，因为媒体流早四秒就开始流动，而那四秒存在于全部六个落地点里；默认按全体同意来做，而不是拿区号去判定辖区，文中点名了十二个全体同意州），把披露当作智能体必须在热转接、外呼、抢话打断与被直接问到时重申的会话状态——欧盟《AI 法案》第 50 条自 2026 年 8 月 2 日起已经适用；并对支付数据毫不含糊：PCI DSS v4.0.1 把人工的「暂停—恢复」视作部分控制措施，而模型没法把视线挪开，所以那些数字根本不该抵达智能体这条腿。文末落在写入时于每个落地点前跑同一个带版本的脱敏器，以及每季度一次、真正给六个落地点的删除耗时计时的演练。',
    ),
    L(
      'New Operation `/operations/safety-and-security/insider-misuse-of-agents` (S20) — the reports all measure shadow AI, which is unsanctioned and outbound and which your egress controls already handle. The harder case is sanctioned and inbound: an employee with ordinary permissions asks one question, and the agent performs four thousand individually-permitted reads across six systems and returns the synthesis that used to need three weeks and a SQL client. Nothing was violated, so nothing fired — an authorisation system that alerted here would be malfunctioning. The page names what the agent actually removed (the skill floor, and the cost of aggregation that was quietly enforcing need-to-know), gives detection that survives (records returned and distinct data subjects per identity, purpose binding to a case id, baselines per role not globally), and argues that logging tool calls without the verbatim prompt builds a deniability machine. Also covers the leaver window, the works-council constraint on monitoring prompt text, and why hard caps push people onto the unsanctioned tool you cannot see. DTEX’s 2026 finding that only ~19% of organisations classify AI agents as equivalent to human insiders is the gap it is written into.',
      '新增运营页 `/operations/safety-and-security/insider-misuse-of-agents`（S20）——那些报告量的都是影子 AI：未获批、向外，而你的出网管控早已能处理。更棘手的那一类是已获批、向内的：一名权限普通的员工问一个问题，智能体就在六套系统里做了四千次逐条合规的读取，并交回那份过去要三周外加一个 SQL 客户端才拼得出来的综合结论。没有任何东西被违反，所以没有任何东西触发——在这里会报警的授权系统，那是坏了。本页点名了智能体真正拿掉的东西（技能门槛，以及那份一直在悄悄执行「按需知悉」的聚合成本），给出了挺得住的检测（按身份统计返回记录数与不同数据主体数、把检索绑定到案件号、按角色而不是全局建基线），并主张：只记录工具调用而不记录逐字的提示词，等于造了一台推诿机器。还覆盖了离职窗口、监控提示词文本所受的职工委员会约束，以及硬性上限为何会把人推向那个你看不见的未获批工具。DTEX 2026 年那条「只有约 19% 的组织把 AI 智能体视作等同于人类内部人员」的发现，正是这一页写进去的那道缝。',
    ),
  ],
};

export default entry;
