import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-08-20',
  title: L(
    'Two AI Blog posts on what a search API’s price unit really buys and on Gemini Spark moving into your own Chrome profile, plus three pages on ambient authority, eval-set maintenance and accounts-payable agents',
    '两篇 AI 博客——搜索 API 的计价单位到底买了什么，以及 Gemini Spark 搬进你自己的 Chrome 配置文件——外加三个页面：环境权限、评测集维护，以及应付账款智能体',
  ),
  items: [
    L(
      'New blog post — *Brave vs Exa vs Tavily vs Parallel: the price unit tells you who reads the page*. Four APIs price a thousand searches between roughly $1 and $16, and the spread is not margin — it is how far down the retrieval pipeline each one reads. Lays out the published August 2026 list prices (Brave flat at $5 per 1,000 across web-search endpoints with the LLM Context endpoint returning extracted chunks at the same rate; Exa at $7 per 1,000 with page contents for the first ten results bundled since March 2026 and $1 per 1,000 beyond; Tavily at 1 credit basic and 2 for advanced, or $8 and $16 per 1,000 pay-as-you-go; Parallel at $0.001 per basic request plus $0.001 per additional result and excerpt, with the Task API from $300 per 1,000 runs) and then prices a whole research turn — three searches, twelve pages — at $3 per million input tokens. The ordering inverts: links-only search costs 1.5 cents in API charges and 14.4 cents in tokens, while every extraction endpoint lands the turn between 5 and 8.5 cents, so the cheapest rate card produces the dearest turn by roughly three times, and the same vendor sits at both ends of the list one endpoint apart. Closes on what you give up when the API does the reading — a relevance judgement you cannot inspect or eval, an extractor that changes without a deploy, and a 20× latency spread that multiplies inside the loop. Three themeable SVGs.',
      '新博客文章——《Brave vs Exa vs Tavily vs Parallel：计价单位说明了谁去读那个页面》。四家把一千次搜索定在大约 1 到 16 美元之间，而这道价差不是毛利——它是各自在检索流水线上读到多深。文章摆出 2026 年 8 月公布的价目（Brave 各网页搜索端点统一每千次 5 美元，而 LLM Context 端点以同价返回抽取好的分块；Exa 每千次 7 美元，自 2026 年 3 月起前十条结果的正文已含在价内、之后每千条 1 美元；Tavily basic 1 分、advanced 2 分，即用即付合每千次 8 与 16 美元；Parallel 基础请求 0.001 美元，每多一条结果与摘录再加 0.001，Task API 每千次起价 300 美元），然后按每百万输入 token 3 美元，给一整个研究回合——三次搜索、十二个页面——算了一笔账。排序翻转了：纯链接搜索的 API 费用是 1.5 美分、token 费用是 14.4 美分，而每一个抽取端点都把这个回合落在 5 到 8.5 美分之间；于是价目表最便宜的那个，跑出来的回合成本约为最贵的三倍，而同一家厂商只隔一个端点就同时占据了榜单的两端。文末落在"让 API 替你读，你交出去了什么"——一次你无法检视也无法评估的相关性判断、一个不发版就会变的抽取器，以及一个会在循环里相乘的 20 倍延迟跨度。配三张可随主题变色的 SVG。',
    ),
    L(
      'New blog post — *Gemini Spark moved into your Chrome profile, and the handback is on the wrong line*. Chrome auto-browse began rolling out in the US on 3 August 2026 to AI Pro and AI Ultra subscribers, moving the agent out of a Google-managed remote browser and into the desktop Chrome you are logged into, with your saved passwords available to it and a handback to the human on sensitive actions such as payments. Argues the gate is drawn at the one action class that already has a chargeback window, a dispute process and a spending limit, while reading a mailbox, copying data outward, changing a recovery address and granting an OAuth scope are quiet, permanent and unattended — and that no number of extra gates fixes it, because a browser profile is ambient authority: the reachable set is whatever your cookie jar authenticates, which nobody has enumerated. Adds the attribution cost nobody discusses (every log on the other end records the action as yours) and reframes injection defences as a residual rate whose payoff multiplier just changed. Prescribes a separate Chrome profile for agent errands, per-task credentials over inherited sessions, and gating on irreversibility rather than on a currency symbol. Three SVGs.',
      '新博客文章——《Gemini Spark 搬进了你的 Chrome 配置文件，而那道交还控制权的线划错了地方》。Chrome 自动浏览于 2026 年 8 月 3 日起在美国向 AI Pro 与 AI Ultra 订阅者推送，把智能体从一个 Google 托管的远程浏览器搬进了你正登录着的桌面版 Chrome，让它能取用你保存的密码，并在付款这类敏感操作时把控制权交还给人。文章论证：这道闸门恰好设在那唯一一类本就有拒付窗口、有争议处理流程、还常设着消费限额的动作上；而读邮箱、把数据往外拷、改找回地址、授予 OAuth 权限，则安静、永久，且无人值守——并且再加多少道闸门也修不好，因为一份浏览器配置文件就是环境权限：可达集合等于你的 cookie 罐认证过的一切，而这份清单没人列举过。文章还补上了那项没人讨论的归因代价（对面每一条日志记下的都是"你做的"），并把注入防御重新框定为一个残余发生率——而刚刚改变的是它的收益乘数。处方是：给智能体跑腿单开一份 Chrome 配置文件、用按任务签发的凭据取代继承来的会话，并按"能不能撤回"而不是按货币符号来设闸门。配三张 SVG。',
    ),
    L(
      'New Concept (Agentic AI) — *Ambient Authority*. An agent in your logged-in browser profile was not given twelve tools; it was given every site your cookie jar authenticates, and nobody wrote that list down. Separates permission you hold by virtue of where you are (a session cookie, a mounted service-account token, a VPN route) from permission handed over as a specific reference to a specific object, and argues the difference is not strength but whether the reachable set can be enumerated. Traces the confused-deputy pattern back to Norm Hardy’s 1988 compiler to show the agent need not be compromised, only persuaded — and that the same injection payload is worth a rude paragraph against a chatbot and everything the environment reaches against an agent. Explains why confirmation dialogs sit on the wrong axis (they cover only enumerated actions, and confirmable and damaging barely overlap), then gives the conversion to designated authority: per-task credentials, the agent’s own identity rather than a borrowed session, egress control, split read and write principals, disposable environments. Closes on writing down every credential reachable from the agent’s process, and the worst single action each enables.',
      '新增概念页（智能体 AI）——《环境权限》。一个跑在你已登录浏览器配置文件里的智能体，拿到的不是十二个工具，而是你的 cookie 罐认证过的每一个站点——而这份清单从来没人写下来。文章把"凭身处何处而持有的权限"（一枚会话 cookie、一个挂载的服务账号 token、一条 VPN 路由）与"作为指向特定对象的具体引用被交出的权限"区分开，并论证两者的差别不在强弱，而在可达集合数不数得清。它把混淆代理这一模式追溯到 Norm Hardy 1988 年那个编译器，说明智能体不必被攻陷、只需被说服——而同一份注入载荷，打在聊天机器人身上买到的是一段无礼文字，打在智能体身上买到的是这个环境够得着的一切。文章解释了确认弹窗为何站在错误的那根轴上（它只盖得住被列举过的动作，而"可确认的"与"有破坏力的"几乎不重叠），随后给出换成指名权限的路径：按任务签发凭据、给智能体自己的身份而不是借来的会话、出网控制、读写主体分离、环境用完即弃。文末落在把智能体所在进程能够到的每一份凭据、以及每一份所启用的最坏那个动作，都写下来。',
    ),
    L(
      'New Operation (Evaluation &amp; Observability) — *Maintaining an Eval Set*. An eval set decays by being fitted, not by rotting: every regression you fix converts a discriminating case into a permanent pass, so a suite that started as a measurement quietly becomes a regression harness while still producing a number people trust. Gives the saturation formula — the share of cases every candidate in your last quarter of comparisons already passes — with 0.8 as the point where most of the eval bill is buying confirmation. Prescribes scoring the cases as well as the system by recording, per comparison, whether the two candidates disagreed, which typically shrinks the per-commit gate by 5–10× and reveals which capability stopped being tested at all. Then a standing replacement rate rather than a periodic cleanup, a retirement rule with tripwire exemptions and an annual archive re-run, production sourcing corrected for the fact that you only harvest failures you noticed, a holdout that moves to the dev set the moment anyone opens it, and a re-baseline on every set change so a healthy refresh is not read as a quality drop.',
      '新增运维页（评估与可观测性）——《维护一套评测集》。评测集是被拟合掉的，不是放烂的：你每修好一个回归，就把一条有区分力的用例变成一次永久通过；于是一套原本是测量工具的套件，悄悄变成了一台回归护栏，却仍在产出一个大家当真的数字。文章给出饱和度公式——在你上一个季度的比较里，所有候选都已通过的用例占比——并把 0.8 定为"评测账单大部分是在买确认"的那个点。处方是：除了给系统打分，也要给用例打分，办法是每跑一次比较就按用例记下两个候选是否给出了不同结果；这通常能把每次提交的闸门缩小 5–10 倍，并暴露出哪一项能力已经彻底不再被测。随后是常设的更换速率而非周期性大扫除、一条带 tripwire 豁免与年度归档重跑的退役规则、为"你只收割得到你注意到了的失败"做修正的生产取样、一份"任何人一打开就自动并入开发集"的留出集，以及每次改集合都重设基线——好让一次健康的刷新不被读成质量下滑。',
    ),
    L(
      'New Playbook (Domain Playbooks) — *Accounts Payable &amp; Invoice Agents*. Best-in-class touchless rates have hovered near 49% against an industry average around 33%, and the half that fails is not failing on reading the document — it fails because there is no purchase order, the receipt was never entered, or nobody ordered the thing. Prices the two halves separately against the published benchmarks (about $2.78 per invoice and 3.1 days best-in-class, against roughly $10.89 and 10.9 days on average) to show the clean lane is already cheap and the stall is where the money is, then reframes the agent’s job from "match the invoice" to "name the missing document and go get it". Gives the exception taxonomy to build before the agent, argues approval gates should key on irreversibility rather than invoice value — a duplicate payment is usually clawed back, a vendor bank-detail change never is, so the agent must never be able to write the vendor master — and closes on measuring fully loaded cost per invoice, p90 cycle time and first-pass yield by supplier instead of the touchless rate, whose denominator you control.',
      '新增实战手册（领域实战手册）——《应付账款与发票智能体》。同业最佳的无接触处理率在 49% 上下徘徊，行业均值约 33%；而失手的那一半并不是失手在读单据上——它失手，是因为没有采购订单、收货从来没被录入，或者压根没人订过这东西。文章对照公开基准把两半分别计价（同业最佳约每张发票 2.78 美元、周期 3.1 天，均值约 10.89 美元、10.9 天），说明干净通道本来就便宜、钱都在卡住的那些身上，随后把智能体的活儿从"把发票匹配上"重新框定为"点名缺的是哪份单据，然后去把它要来"。文章给出了应当先于智能体建立的例外分类学，论证审批闸门该按"能不能撤回"而不是按发票金额来设——重复付款通常要得回来，供应商银行账号变更则永远要不回来，所以智能体绝不能有权写供应商主数据——并在文末主张衡量全负荷的每张发票成本、p90 周期时间与按供应商的一次通过率，而不是那个分母握在你自己手里的无接触率。',
    ),
  ],
};

export default entry;
