import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-08-27',
  title: L(
    'Two AI Blog posts on what a single-attempt benchmark score hides and on the authority record a Senate bill asks for, plus three pages on repairing an agent\'s committed actions, permission-aware retrieval and spec-driven development',
    '两篇 AI 博客——单次尝试的基准分数藏起了什么，以及一份参议院法案索要的那种权限记录——外加三个页面：修复智能体已经提交出去的动作、带权限的检索，以及规格驱动的开发',
  ),
  items: [
    L(
      'New blog post — *65% once, 25% twenty times: your headline score is mostly flake*. Microsoft released Thinkingbox on 19 August 2026 with collaborators at Pittsburgh, Northwestern and UC Irvine (arXiv:2608.19741, MIT-licensed, tool mocks defined as MCP servers): 507 policy-conditioned workflows across retail, hospitality, auto insurance, neobank internal IT and consulting IT/HR, graded against terminal backend state and collateral effects rather than against the transcript. The strongest model scores 65.36% pass@1 and 25.25% pass^20. The post runs the arithmetic nobody runs — independent failures would put twenty-in-a-row at 0.6536^20 ≈ 0.02%, one task in five thousand — and reads the thousandfold discrepancy as proof that outcomes are correlated within a task, then fits the two populations: a deterministic band equal to the pass^20 figure, and a remainder succeeding about 54% per attempt, so forty of the sixty-five headline points come from tasks the agent solves sometimes. Argues that a 54% task is operationally worse than one that always fails, because the never-task gets a fallback on day one while the coin-flip task passes a review that sampled it once and then compounds — five such steps complete end to end 4.5% of the time. Notes pass^k is not new (τ-bench, 2024) and that the leaderboards still print the single attempt. Prescribes k=5 on your own suite, an always/sometimes/never bucketing with the middle bucket as the roadmap, assertions on state rather than on a judge reading the model\'s own summary, and pass^k as the model-swap gate. Three themeable SVGs.',
      '新博客文章——《65% 跑一次，25% 跑二十次：你的头条分数大半是抖动》。2026 年 8 月 19 日，微软连同匹兹堡大学、西北大学与加州大学欧文分校的合作者发布了 Thinkingbox（arXiv:2608.19741，MIT 许可，工具桩以 MCP 服务器形式定义）：507 条受策略约束的工作流，横跨零售、酒店住宿、车险、新型银行内部 IT 与咨询公司的 IT/HR，评分对照的是后端终态与附带影响，而不是对话记录。最强模型的 pass@1 是 65.36%，pass^20 是 25.25%。文章把没人去做的那道算术做了一遍——若失败彼此独立，连中二十次应为 0.6536^20 ≈ 0.02%，即五千道题里一道——并把这一千倍的落差读作「同一道题内部成败高度相关」的证据，随后拟合出两个总体：一个等于 pass^20 数值的确定性区段，以及一个每次尝试约 54% 成功率的余量；于是那 65 分的头条里有 40 分，来自智能体「有时候」能做对的题。文章论证一道 54% 的题在运维上比一道次次失败的题更糟：后者第一天就会拿到退路，而前者能通过只抽样了一次的评审，随后开始复合——五个这样的步骤端到端完成的概率是 4.5%。文中指出 pass^k 并不新鲜（τ-bench，2024），而排行榜印的仍是单次尝试。处方是：在你自己的套件上取 k=5、分成「总是 / 有时 / 从不」三桶并把中间那桶当路线图、对状态下断言而不是让评审模型去读模型自己的总结，以及把 pass^k 当作换模型的关卡。配三张可随主题变色的 SVG。',
    ),
    L(
      'New blog post — *The AI AGENT Act asks for a record your stack does not keep*. S. 5051 was introduced by Senator Mark Warner on 21 July 2026 after a June discussion draft, and was read twice and referred to Senate Commerce, where it sits with no committee action — the post says plainly that most bills die there and reads it as a specification instead of a prediction. Its object is the "custodial user agent": authorised to act for a user in a transparent, documented, limited and revocable manner, with duties to safeguard data, follow instructions, avoid self-dealing, keep real-time auditable records accessible to the user, stay inside the granted authorisation, and not delegate authority onward without explicit permission. The load-bearing argument is that a trace is a record of behaviour while every one of those duties is about permission, and the two ledgers hold different fields — grantor, scope, purpose, expiry, revocation state, actor chain — so no amount of post-processing turns one into the other; the fix is a grant object with an id stamped on every action, a week of work that cannot be retrofitted onto history. Works the sub-delegation clause against a four-hop chain where only the user-to-orchestrator hop produces evidence: an in-process sub-agent asserts nothing, A2A carries an agent card but no delegation field even after joining the Agentic AI Foundation, and MCP passes a token scoped to the calling service — while RFC 8693 token exchange has had an actor claim for this all along. Sets the interoperability half, which would force platforms above roughly 50 million monthly users to admit a qualifying third-party agent, against an edge that is blocking by default, and shows both converge on the same missing primitive. Three SVGs.',
      '新博客文章——《〈AI AGENT 法案〉要的那份记录，你的栈根本不存》。S. 5051 由参议员 Mark Warner 于 2026 年 7 月 21 日提出（此前六月有一份讨论稿），经两读后被移交参议院商务委员会，至今没有任何委员会行动——文章直说多数法案就死在那里，并选择把它当作一份规格说明、而不是一次预测来读。它的核心对象是「托管型用户智能体」：被授权以透明、有文档记载、有限且可撤销的方式代表用户行事，并负有保护数据、遵循指示、避免自我交易、保留用户可取用的可审计实时记录、不越出被授予的授权，以及未经明确许可不得把权限转委派等义务。吃重的论点是：链路追踪是一份关于行为的记录，而上述每一项义务讲的都是权限，两本账的字段并不相同——授权人、范围、用途、到期、撤销状态、行为主体链——所以再多的后处理也无法把一本变成另一本；解法是一个带 id、并把这个 id 打在每次动作上的授权对象，一周的活儿，但没法给历史补上。文章把转委派那一条放到一条四跳链路上去检验，其中只有「用户到编排智能体」那一跳产出了证据：进程内的子智能体什么也没声明；A2A 即便迁入 Agentic AI Foundation 之后，携带的仍只是 agent card 而没有委派字段；MCP 传的是一枚只属于调用方服务的令牌——而 RFC 8693 的令牌交换早就为此备好了 actor 声明。文中还把互操作那一半（将迫使月活约 5000 万以上的平台接纳合格的第三方智能体）与一个默认阻止的边缘并置，并指出两者汇聚到同一个缺失的原语上。配三张 SVG。',
    ),
    L(
      'New Operation (AgentOps) — *Repairing What the Agent Already Did*. The agent incident you will actually have is not an outage but a Tuesday on which someone notices a tool has been writing something subtly wrong since the 3rd, so the containment machinery fires in four seconds against a fault that landed three weeks ago — and the four thousand already-committed actions are a different discipline, because each was a judgement rather than a row and you have to decide again rather than roll back a table. Names the three fault classes including the invisible one (actions not taken, findable only by counting what should exist), insists that scoping happens over decisions rather than rows and that failing to enumerate affected runs in one query is itself the finding, sorts damage into recompute / compensate / irreversible / derived, and requires replay against pinned prompt, model and tool versions with archived retrieval results rather than a re-fetch that silently substitutes today\'s corpus. Closes on running the backfill as a migration — dry-run diff, an idempotency key derived from the original run id, bounded batches, consolidated customer contact — and on the preparation that decides whether any of it is possible: a per-run side-effect ledger with a reversibility class recorded at write time, an undo path specified with every write tool, retention that outlives the detection lag, and a separate repair credential.',
      '新增运维页（智能体运维）——《修复智能体已经做过的事》。你真正会碰上的智能体事故不是宕机，而是某个星期二有人发现某个工具从 3 号起就一直在写入某种细微错误的东西，于是遏制机制在四秒内触发，对付的却是三周前落地的故障——而那已经提交出去的四千次动作是另一门手艺，因为每一次都是一个判断而不是一行记录，你必须重新判断，而不是回滚一张表。文章点名了三类故障，包括隐形的那一类（没有发生的动作，只能靠数「本应存在多少」来发现），坚持范围要按决策而不是按行来划，并指出「没法用一条查询把受影响的运行枚举出来」这件事本身就是结论；把损害分进重算／补偿／不可逆／派生四个桶；并要求对照钉住的提示词、模型与工具版本重放，且使用归档下来的检索结果，而不是一次会悄悄把今天的语料替换进去的重新取用。文末落在把回填当迁移来跑——空跑差异、以原始 run id 推导的幂等键、有界批次、合并后的客户联络——以及决定这一切可不可行的那些准备：一本按运行、在写入时就记下可逆性分类的副作用台账、每个写入工具都配的撤销路径、长过检测滞后的保留期，以及一份独立的修复凭据。',
    ),
    L(
      'New Operation (Safety &amp; Security) — *Permission-Aware Retrieval*. Indexing takes documents with different audiences, chops them into chunks and discards the container that carried their access rules, so retrieval becomes the widest read the system performs — on behalf of whoever is talking to the bot. Rules out post-filtering as a control on three independent grounds: what the model saw is disclosed and, on a hosted provider, has left your boundary; suppression by instruction is probabilistic; and existence leaks anyway through result counts, citation counts and the difference between a genuine and a filtered miss. Lays out the three enforcement positions — pre-filtered search, whose cost is the unmeasured recall damage a selective filter does to an ANN index; partitioned indexes, structurally safe only at the boundary you partitioned on; and late-binding checks against the source system, the only exactly-correct variant — and recommends combining all three. The sharpest section is that the ACL copy is a cache whose staleness is your revocation latency, so a weekly rebuild is an unstated seven-day revocation SLA: store the permission key rather than the resolved member list and most of that lag becomes zero. Ends on derived artefacts that inherit nothing (memory, semantic caches keyed on the question, digests, traces, eval fixtures, multi-hop retrieval) and on testing it as an authorisation system with differential two-user tests, per-tier canary strings asserted against the assembled context, and retrieval logged as access.',
      '新增运维页（安全与防护）——《带权限的检索》。建索引把受众各不相同的文档切成块，并丢掉了承载其访问规则的那个容器，于是检索成了系统里最宽的一次读取——而且是代表此刻正在跟机器人说话的那个人执行的。文章从三条彼此独立的理由否决了「事后过滤」作为控制手段：模型看见的就算已披露，而在托管服务商那里它还离开了你的边界；靠指令去压制是概率性的；而「存在」本身依然会通过结果计数、引用计数，以及一次真正未命中与一次被过滤掉的未命中之间的差别漏出去。文中摆出三个可强制的位置——前置过滤的检索，其代价是高选择性过滤器对 ANN 索引造成的、没人去量的召回率损伤；分区索引，只在你所分区的那道边界上结构性安全；以及对源系统的延迟绑定检查，唯一严格正确的一种——并建议三者组合使用。最锋利的一节是：那份 ACL 拷贝是一份缓存，它的陈旧程度就是你的撤销时延，于是每周重建就等于一条没人说出口的「七天撤销 SLA」——改存权限键而不是解析后的成员名单，这份滞后大半就归零了。文末落在什么也继承不到的派生产物（记忆、以问题为键的语义缓存、简报、追踪、评测固件、多跳检索），以及把它当授权系统来测：两用户差分测试、每个密级一条对拼装出来的上下文下断言的哨兵字符串，以及把检索记成一次访问。',
    ),
    L(
      'New Playbook (Coding &amp; Computer-Use Agents) — *Spec-Driven Development with Coding Agents*. A spec earns its place only if something can fail the build on it, and the reason it matters more with agents than with people is that the plan, the tests, the code and the summary all descend from one reading of the task — so when that reading is wrong every artefact agrees with every other and the review passes. Gives a test for whether a spec is load-bearing (delete the implementation, hand the spec to a fresh agent, see whether what comes back is behaviourally equivalent), separates what belongs in it (observable behaviour, edge contracts, invariants, error cases, and the explicit non-goals list everyone omits) from what does not (file names, algorithm choices, and any criterion nobody can check), and makes the central move: every acceptance criterion gets a check id or a named human, written before the agent starts, with the agent writing the tests that satisfy criteria it did not author. Treats the plan as a separate, disposable artefact worth five minutes of review at the last cheap moment, argues that a stale spec is worse than none because an agent obeys it with undiminished confidence and will regenerate the behaviour it describes, and closes by naming where the technique does not pay — bug fixes where the failing test is already the spec, exploratory work, and changes smaller than the document.',
      '新增实战手册（编码与计算机操作智能体）——《以规格驱动的编码智能体开发》。一份规格只有在「有东西能凭它把构建判失败」时才配占位置；而它在智能体身上比在人身上更要紧，是因为计划、测试、代码与总结全都源自对任务的同一次理解——于是这次理解一旦错了，每件产物都与其他每一件彼此印证，评审就这么过了。文章给出了判断规格是否承重的测试（删掉实现，把规格交给一个全新的智能体，看拿回来的东西在行为上等不等价），把该放进去的（可观察行为、边界契约、不变式、错误情形，以及人人都省掉的那份明确的非目标清单）与不该放进去的（文件名、算法选择，以及任何没人核查得了的标准）分开，并给出核心动作：每一条验收标准都配一个检查项 id 或一位具名的人，且在智能体动手之前写好，再由智能体去写满足这些「不是它自己定的」标准的测试。文中把计划视作另一件可丢弃的产物，值得在最后一个便宜的时刻花五分钟评审；论证一份过期的规格比没有规格更糟，因为智能体会以毫不打折的笃定去遵从它，并把它所描述的行为重新生成出来；文末点名这套技法在哪儿不划算——失败的测试本身就是规格的缺陷修复、探索性工作，以及比文档还小的改动。',
    ),
  ],
};

export default entry;
