import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-09-07',
  title: L(
    'Two AI Blog posts — on the AI-outage statistic whose denominator has no agents in it, and on four MCP libraries ranked by a millisecond nobody feels — plus three pages on blast radius, protocol deprecation windows, and permission-grant UX',
    '两篇 AI 博客——一个分母里根本没有智能体的 AI 故障统计；以及四个 MCP 库被拿一毫秒来排名而没人感觉得到——外加三个页面：爆炸半径、协议弃用窗口，以及权限授予体验',
  ),
  items: [
    L(
      'New AI Blog post `/blogs/one-in-ten-outages-is-not-about-agents` — the week\'s most-quoted figure, that AI-related incidents rose from 1.7% of all disclosed outages in 2023 to 10.7% in 2026 to date, is a sector-composition measure across roughly 178,000 status-page records from 390+ companies: its numerator is incidents at AI companies and its denominator is incidents everywhere, so it climbs on the growth of the AI sector alone, with agent reliability held constant. Status pages also have no field for "an agent did this", so the corpus cannot separate a destructive tool call from a bad deploy. The post moves to the figure that does have agents in its denominator — 188 of 344 hand-verified enterprise AI incidents involved no attacker at all, which invalidates a threat model rather than trending a rate — and to the nine documented 2026 cases of an agent deleting production with valid credentials, which converge on one stage: the grant issued for a build phase that ended while nothing revoked it. Closes on why that stage is where the cheap fix is: it is the only one of the four with no event attached to it.',
      '新增 AI 博客 `/blogs/one-in-ten-outages-is-not-about-agents`——本周被引用最多的那个数字，即 AI 相关事故从 2023 年占全部披露故障的 1.7% 升到 2026 年至今的 10.7%，是一项在约 178,000 条状态页记录（来自 390 多家公司）上做的行业构成度量：它的分子是 AI 公司的事故、分母是所有地方的事故，所以光靠 AI 行业本身变大它就会往上爬，哪怕智能体的可靠性纹丝不动。状态页里也没有「这是智能体干的」这个字段，所以这份语料压根分不开一次破坏性工具调用和一次糟糕的发布。本文转向那个分母里真有智能体的数字——344 起人工核实的企业级 AI 事故中有 188 起完全没有攻击者，这推翻的是一个威胁模型，而不是在给一个比率做趋势——以及 2026 年那九起有据可查的、智能体用有效凭据删除生产的案例，它们收敛到同一个阶段：为某段已经结束的构建工作发出去、却没有任何东西去收回的那份授权。文末落在为什么便宜的修法就在那个阶段：它是四个阶段里唯一一个身上没有附着任何事件的。',
    ),
    L(
      'New AI Blog post `/blogs/fastmcp-vs-typescript-sdk-vs-mcp-go-vs-rmcp` — an independent five-language benchmark puts p50 proxy handling at 0.38 ms (Rust/rmcp) to 2.25 ms (Python/FastMCP), and its own author says language does not matter for a proxying server because the 50–500 ms upstream round trip dominates; the axis with a date attached, specification currency, has no leaderboard and so loses to a chart. Three of the four implement the 2026-07-28 stateless revision — which retired the initialize handshake and Mcp-Session-Id, added routable headers, deprecated HTTP+SSE and started twelve-month clocks on Roots, Sampling and Logging — while mcp-go, the library most Go MCP servers were built on, states 2025-11-25, and Go\'s Tier 1 slot belongs to a different project, making that a port rather than an upgrade. The post\'s argument is that "supports the new revision" is the wrong question: you own one end of the connection, so what you run is a dual-revision window, and the choice is whether the library absorbs it or your topology does.',
      '新增 AI 博客 `/blogs/fastmcp-vs-typescript-sdk-vs-mcp-go-vs-rmcp`——一份独立的五语言基准测试给出的 p50 代理处理耗时从 0.38 毫秒（Rust/rmcp）到 2.25 毫秒（Python/FastMCP），而它的作者自己就说：对一台做代理的服务器语言不重要，因为 50 到 500 毫秒的上游往返压倒一切；那根带日期的轴——版本时效性——因为没有排行榜，就输给了一张图。四者中有三个实现了 2026-07-28 的无状态版本（它退役了 initialize 握手与 Mcp-Session-Id、新增了可路由的请求头、把 HTTP+SSE 标为弃用，并给 Roots、Sampling 与 Logging 起了十二个月的钟），而多数 Go MCP 服务器所建于其上的 mcp-go 写的是 2025-11-25，且 Go 的 Tier 1 位置属于另一个项目——于是那是一次移植而不是一次升级。本文的主张是：「支不支持新版本」问错了——连接的一端归你，所以你实际要跑的是一个双版本窗口，而要选的是让库来吸收它，还是让你的拓扑来吸收它。',
    ),
    L(
      'New Concept `/concepts/blast-radius` (A26) — every other control works on the probability that an agent does the wrong thing and none of them reaches zero, so magnitude is the only agent safety property you can bound before you know how good the model is: probability is estimated from evals and degrades under distribution shift, while blast radius is enumerated from grants and does not move when the model changes underneath you. The page reads it in four multiplicative terms — reach, authority, rate, reversibility — notes that capping rate on a broad grant is often cheaper than narrowing the grant and a reliable undo worth more than either, and lands on why the radius is drawn by credentials that outlive the phase they were issued for. Closes on the distinction that decides whether a radius exists at all: an instruction lives in text the model can reason around, so the bound has to sit in the credential, the network, the tool or the database role.',
      '新增概念页 `/concepts/blast-radius`（A26）——其他每一道控制作用的都是「智能体做错事的概率」，而没有一道能压到零；所以「量级」是你在还不知道模型有多好之前就能框住的唯一一个智能体安全属性：概率是从评测里估出来的、会在分布漂移下退化，而爆炸半径是从授权里枚举出来的，当模型在底下被换掉时它纹丝不动。本页用四项相乘的术语去读它——可达范围、权限、速率、可逆性——指出给一份宽泛授权加速率上限往往比把授权收窄更便宜，而一套可靠的撤销可能比两者都值钱，并落在「这个半径是被那些比签发理由活得更久的凭据画出来的」。文末落在决定「这个半径到底存不存在」的那个区分：一句叮嘱住在模型可以绕过去推理的文字里，所以这道界必须坐在凭据、网络、工具或数据库角色上。',
    ),
    L(
      'New Operation `/operations/agentops/protocol-revisions-and-deprecation-windows` (O23) — a protocol revision expires on someone else\'s calendar and sits on both ends of a connection you own one of, so the model-deprecation playbook (one vendor, one date, a cutover inside your deployment boundary) does not transfer: there is no cutover, only a dual-revision window you run on purpose. The page names the input to every decision in it and the number almost nobody records — negotiated revision stamped on every request, reported by share of traffic and by distinct caller, because 0.3% of requests can be 40% of your integrations — then argues against forking the deployment (it forks your tools, authorization, rate limits and tracing for as long as the window lasts) in favour of negotiating at the edge and normalising inward, with the compatibility layer in one module carrying its removal date. Also: feature deprecations expire while your revision is still current, a capability moved into an extension needs a check and a fallback, CI needs a client pinned to the oldest revision you claim to support, and libraries should be chosen on historical revision lag rather than throughput.',
      '新增运维页 `/operations/agentops/protocol-revisions-and-deprecation-windows`（O23）——协议版本按别人的日历到期，又坐在一条你只拥有一端的连接的两头，所以模型弃用那套打法（一家厂商、一个日期、一次在你部署边界之内的切换）搬不过来：根本没有切换，只有一个你有意去跑的双版本窗口。本页点名了窗口里每个决定的输入、也是几乎没人记录的那个数字——把协商出来的版本打在每一次请求上，既按流量占比报也按去重调用方个数报，因为 0.3% 的请求可能就是 40% 的集成方——继而反对把部署叉开（那会在整个窗口期内把你的工具、鉴权、限流和链路追踪一起叉开），主张在边缘协商、向内归一，并把兼容层收在一个带着移除日期的模块里。另外：特性弃用会在你的版本还是最新时就到期、一个被挪进扩展的能力需要探测与降级、CI 里需要一个钉死在「你声称仍支持的最老版本」上的客户端，而选库要看历史版本滞后而不是吞吐。',
    ),
    L(
      'New Playbook `/playbooks/agent-ux-and-human-interaction/permission-grants-and-revocation-ux` (H21) — the consent screen is where users set the agent\'s blast radius and it is inherited wholesale from OAuth, which assumed an actor whose behaviour is fixed at build time; an agent breaks that every run, because the same grant is exercised differently each time and is exercised at 3am by a scheduled job. The page\'s load-bearing claim is that the screen deciding how much access you get is the revocation screen, not the grant screen: people over-grant when taking access back is invisible and under-grant when it looks permanent, so a one-click revoke that previews what will break — with pause as the adjacent option — moves grant behaviour more than any wording change. Also: resolve scopes into counts of real objects, sort by consequence rather than API surface, make duration a first-class choice whose default is not "always", expire on disuse, and make a 403 terminal rather than retryable so the model cannot narrate its way around a permission that just disappeared.',
      '新增实战手册 `/playbooks/agent-ux-and-human-interaction/permission-grants-and-revocation-ux`（H21）——授权页是用户给智能体划定爆炸半径的地方，而它整个是从 OAuth 继承来的，那套假定的是一个行为在构建期就固定下来的行动者；智能体每跑一次都在打破它，因为同一份授权每次被行使的方式都不同，而且会在凌晨三点被一次定时任务行使。本页承重的那条主张是：决定你能拿到多少访问权的，是撤销那块界面，不是授权那块——收回访问权不可见时人们会超额授予，看上去永久时人们会吝啬授予；所以一个「会预演什么将会坏掉」并把「暂停」放在旁边的一键撤销，对授权行为的影响胜过任何措辞改动。另外：把范围解析成真实对象的计数、按后果而不是按 API 面排序、把时长做成默认不是「始终」的一等选项、按「不用」过期，以及把 403 做成终止性而非可重试的，好让模型没法用叙述绕过一份刚刚消失的权限。',
    ),
  ],
};

export default entry;
