import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-08-11',
  title: L(
    'Two AI Blog posts on the Agent Plugins standard shipping without a trust model and on who really holds a cloud browser session, plus four pages on rendering agent output, agent inventory, trace sampling and public-benefits casework',
    '两篇 AI 博客——Agent Plugins 标准在没有信任模型的情况下发布，以及云浏览器会话究竟握在谁手里——外加四个页面：渲染智能体输出、智能体清单、轨迹采样，以及公共福利经办',
  ),
  items: [
    L(
      'New blog post — *Agent Plugins 1.0 Standardises the Bundle and Leaves Trust to Whoever Installs It*. Amazon, Cursor, Microsoft, OpenAI and Vercel published the spec on 6 August with Google joining as a core maintainer the same day; six clients supported it at launch (ChatGPT, Codex, Cursor, GitHub Copilot, Kiro, VS Code) and a plugin is simply a directory with plugin.json, an optional skills/ folder and an optional mcp.json. Argues that the news is the scope section: v1 defines no install mechanism, no distribution protocol, no permission model, no sandboxing and no provenance verification, and the project\'s own FUTURE_CONSIDERATIONS names provenance as unaddressed. Because one bundle now carries both instructions the model follows and MCP servers that run on the installer\'s credentials — portably, across six clients — the fragmentation that used to cap a bad bundle at one ecosystem is gone, and the compensating controls are the reader\'s: pin and vendor the bundle, diff skills/ as prompt content, route mcp.json through your own gateway, and register the install as a change to the agent\'s grant. Three themeable SVGs.',
      '新博客文章——《Agent Plugins 1.0 标准化了那个捆绑包，却把信任留给了装它的那个人》。8 月 6 日，Amazon、Cursor、Microsoft、OpenAI 与 Vercel 发布该规范，Google 同日以核心维护者身份加入；发布时有六个客户端支持（ChatGPT、Codex、Cursor、GitHub Copilot、Kiro、VS Code），而一个插件不过是一个目录，含 plugin.json、可选的 skills/ 与可选的 mcp.json。文章论证：真正的新闻在范围声明里——v1 没有定义安装机制、分发协议、权限模型、沙箱与来源验证，而项目自己的 FUTURE_CONSIDERATIONS 把来源验证列为未处理。由于如今一个捆绑包同时携带"模型会遵循的指令"与"跑在安装者凭据上的 MCP 服务端"，并且可在六个客户端之间通行，过去把一个坏包困在单一生态里的碎片化消失了，补偿性控制落到了读者头上：钉版本并 vendor 进来、把 skills/ 当提示词内容去 diff、让 mcp.json 走你自己的网关，并把安装登记为智能体授权的一次变更。配三张可随主题变色的 SVG。',
    ),
    L(
      'New blog post — *Browserbase vs Steel vs Hyperbrowser vs Anchor Browser: You Are Choosing Who Holds the Session*. All four expose a real Chrome over CDP, so the automation code ports in an afternoon and the SDK comparison decides nothing; what does not move is the state — logged-in profiles, warmed proxy reputation and any credentials the provider holds. Steel ships an Apache-2.0 self-hostable server, Anchor injects secrets so the model never sees a credential and offers per-session VM isolation with BYOC and on-prem tiers, Hyperbrowser sells stealth and captcha solving as the product, and Browserbase leads on debugging ergonomics. Also reports the one public benchmark, steel-dev/browserbench — published by Steel itself, so read the ranking sceptically, but open source and re-runnable: session creation at roughly 229 ms for Steel against 1.6× for Browserbase, 12.8× for Hyperbrowser and 28.6× for Anchor, with the control plane accounting for around 80% of total latency at the slow end. Closes on stealth as a liability transfer rather than a capability. Three SVGs including a control-plane latency chart.',
      '新博客文章——《Browserbase vs Steel vs Hyperbrowser vs Anchor Browser：你选的是谁持有那个会话》。四家都通过 CDP 暴露一个真实 Chrome，所以自动化代码一个下午就能搬走，SDK 对比什么也决定不了；搬不走的是状态——已登录的 profile、养熟的代理信誉，以及供应商持有的任何凭据。Steel 提供 Apache 2.0、可自托管的服务端；Anchor 以密钥注入让模型永远看不到凭据，并提供按会话的虚拟机隔离以及 BYOC 与本地部署档位；Hyperbrowser 把隐身与验证码求解当作产品本体来卖；Browserbase 则在调试手感上领先。文中还报告了唯一那份公开基准 steel-dev/browserbench——它由 Steel 自己发布，排名要带着怀疑读，但它开源且可复跑：创建会话 Steel 约 229 毫秒，Browserbase 为其 1.6 倍、Hyperbrowser 12.8 倍、Anchor 28.6 倍，而在慢的那一端控制面约占总延迟的 80%。文章以"隐身是一次责任转移而非一项能力"收尾。配三张 SVG，含一张控制面延迟图。',
    ),
    L(
      'New Operation (Safety, Alignment &amp; Agentic Security) — *Rendering Agent Output Safely*. EchoLeak (CVE-2025-32711) exfiltrated data from Microsoft 365 Copilot with no click, no tool call and no outbound request by the agent: the model was steered into writing a markdown image, reference-style syntax evaded link redaction, the client auto-prefetched it, and a proxy already on the CSP allowlist carried the request. Argues that model output is attacker-influenced input to every renderer, so the leak happens downstream of every egress control you built — the response leaves from the user\'s browser, the chat platform\'s unfurl service or the terminal, none of which route through your proxy. Covers markdown as a network client, HTML allowlisting and the libraries that pass raw HTML through by default, the non-browser renderers nobody hardened (terminal escape sequences, server-side chat unfurls, notebooks, email), invisible Unicode as the payload a human reviewer approves without seeing, and downstream sinks where output written for one agent is read as trusted by the next.',
      '新增运维页（安全、对齐与智能体安全）——《安全地渲染智能体输出》。EchoLeak（CVE-2025-32711）把数据从 Microsoft 365 Copilot 里带走时没有点击、没有工具调用，智能体也没有发出任何出站请求：模型被诱导写下一张 markdown 图片，引用式写法绕过了链接脱敏，客户端自动预取，而一个早已在 CSP 允许名单上的代理替它送出了请求。文章论证：模型输出对每一个渲染器而言都是被攻击者影响过的输入，所以泄漏发生在你所建的每一道出站控制的下游——回复是从用户浏览器、聊天平台的链接预览服务或终端发出去的，没有一个会走你的代理。内容涵盖"markdown 是一个网络客户端"、HTML 允许名单与那些默认放行原始 HTML 的库、没人加固过的非浏览器渲染器（终端转义序列、服务端的聊天链接展开、notebook、邮件）、作为"人类审核者看不见却签了字的载荷"的不可见 Unicode，以及下游落点——为一个智能体写下的输出，被下一个当作可信读入。',
    ),
    L(
      'New Operation (Governance &amp; Compliance) — *Agent Inventory &amp; Registry*. Every governance regime in force opens with "enumerate your AI systems" and almost everyone answers with a voluntary spreadsheet, which omits precisely the agents that carry risk: registration happens once while the system changes weekly, the interesting agents were never scoped as AI projects, and a register whose unit of record is contested cannot be reconciled against anything. Argues for deriving the inventory from the three chokepoints an agent cannot bypass — credential issuance, the gateway and the bill — and reconciling all three, since their blind spots differ. Makes the grant rather than the name the unit of record (identity, tool grants, data scopes, model version, autonomy level, environment), versioned with history because the audit question is always "what did it do on the 14th". Closes on making the register load-bearing: no registry entry, no credential.',
      '新增运维页（治理与合规）——《智能体清单与登记册》。现行的每一套治理规制开篇都是"把你的 AI 系统列全"，而几乎所有人都用一张靠自愿填写的表格作答——它漏掉的恰恰是那些承载风险的智能体：登记只发生一次而系统每周在变，真正值得关注的智能体从来没被当作 AI 项目立过项，而一份记录单元本身有争议的登记册无法与任何东西对账。文章主张从智能体绕不过去的三个咽喉点把清单推导出来——凭据签发、网关与账单——并对三者做交叉对账，因为它们的盲区各不相同。要把"授权"而不是"名字"作为记录单元（身份、工具授权、数据范围、模型版本、自治层级、环境），并带版本与历史，因为审计的问题永远是"14 号那天它干了什么"。全文以"让登记册承重"收尾：没有登记条目，就没有凭据。',
    ),
    L(
      'New Operation (Evaluation &amp; Observability) — *Trace Sampling &amp; Retention*. Sampling 10% of runs at run start keeps 10% of your failures, and at a 2% failure rate over a hundred thousand monthly runs that leaves two hundred bad trajectories to reason from — while nothing observable at step zero predicts which run goes wrong, because two runs with identical inputs diverge at step four. Argues for buffering to run end and deciding on outcome: keep every error, timeout, step-cap termination, guardrail refusal, human override and p95-cost run whole, define "interesting" from the shape of the run rather than a judge, and stratify the success baseline so rare task classes survive. Then splits structure from payload at the collector with different retentions, and reframes retention as a decision about the eval set you have not built yet — colliding in both directions with erasure requests and legal hold.',
      '新增运维页（评估与可观测性）——《轨迹采样与保留》。在运行开始时抽 10%，你就只留下了 10% 的失败；在月十万次运行、2% 失败率下，这只剩两百条坏轨迹可供推断——而第零步没有任何可观测的东西能预测哪次运行会出问题，因为两次输入相同的运行会在第四步分岔。文章主张缓冲到运行结束、按结果决定去留：把每一次报错、超时、撞步数上限而终止、护栏拒绝、人工接管与 p95 成本的运行整条留下；用"运行的形状"而不是裁判来定义"有意思"；并对成功基线做分层，好让稀有任务类别活下来。随后在 collector 处把结构与载荷分开、配不同保留期，并把保留期重新框定为"关于你还没建起来的那个评测集"的决定——它与删除请求和法律保全在两个方向上正面相撞。',
    ),
    L(
      'New Playbook (Domain Playbooks) — *Public-Benefits Casework Agents*. Michigan\'s MiDAS auto-adjudicated unemployment fraud without human review from 2013 to 2015 and accused more than 34,000 people at a roughly 93% error rate, settling for $20 million; the Dutch childcare-benefits scandal wrongly accused some 26,000 families and brought down a cabinet in January 2021. Neither was a model failure — both systems decided. Argues for a hard split where the agent produces a case packet and a named human determines, and makes the load-bearing point that policy is versioned law: eligibility must be evaluated against the rules in force on the claim date, so effective-dating is a mandatory retrieval filter and a stack that always returns current policy is confidently wrong on every backdated claim. Adds the frozen decision packet for the appeal that arrives months later, appeal rate as a structurally broken metric because the wrongly denied who cannot appeal simply leave the data, and an ordering that starts with intake completeness rather than adjudication.',
      '新增实战手册（领域实战手册）——《公共福利经办智能体》。2013 至 2015 年，密歇根州的 MiDAS 在无人复核下自动裁定失业金欺诈，指控了三万四千多人，错误率约 93%，最终以两千万美元和解；荷兰育儿补贴丑闻错误指控了约两万六千个家庭，并在 2021 年 1 月拖垮了一届内阁。两者都不是模型的失败——两套系统都在"做决定"。文章主张一条硬切分：智能体产出卷宗包，由具名的人做出裁定；并立起那个承重论点——政策是带版本的法律：资格必须按申领日期当时生效的规则来判定，所以生效日期是一个强制性的检索过滤条件，而一个总是返回当前政策的栈，在每一份追溯申领上都会自信地答错。此外还有为几个月后才到的申诉而冻结的裁定卷宗、作为结构性坏指标的申诉率（因为申诉不了的被错误拒绝者干脆从数据里消失了），以及一条"从收件完整性而不是从裁定开始"的推进次序。',
    ),
  ],
};

export default entry;
