import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-09-22',
  title: L(
    'Two AI Blog posts — on the approval that was never bound to the action it approved, and on the four managed knowledge bases whose real product is the permission plumbing — plus three pages on activation probes, fault injection, and contextual retrieval',
    '两篇 AI 博客——一篇讲那次从未与所批准动作绑定的批准，一篇讲四套托管知识库真正在卖的其实是权限管道——外加三个页面：激活探针、故障注入，以及上下文化检索',
  ),
  items: [
    L(
      'AI Blog — “The approval was never bound to the action”: a preprint posted this week (arXiv 2609.21081, with a reproduction archive and a 10 September evidence cutoff) defines Loopjacking as an implementation-level failure in which a human approves the operation they understand as A and product-owned logic then authorises a materially different B. Two variants: a representation mismatch where the consequential field is already encoded but omitted from what the reviewer is shown, and post-approval state substitution where the approval is recorded as a status flag against a request id while the arguments stay in writable workflow state. The second reproduced across seven Agno AgentOS releases to 3.0.9 and in a conditional in-memory LangGraph Agent Server composition to 0.14.0; the first hit OpenClaw 2026.2.23 and was patched a day later; OpenAI Agents SDK 0.22.0 and 0.22.2 serve as the negative control because serialized continuation preserves the per-call binding and rejects the mutated call. No injection, no sandbox escape, no model misbehaviour — a time-of-check-to-time-of-use race with a human in the middle, which is why nobody’s injection defences touch it. The fix is content addressing: canonicalise the call, show a rendering generated from that same form, store the approval against the digest, and compare digests immediately before execution. The test nobody writes is approve, mutate, execute.',
      'AI 博客《那次批准从未与动作绑定》：本周挂出的一篇预印本（arXiv 2609.21081，附复现存档，证据截止 9 月 10 日）把 Loopjacking 定义为一种实现层面的失败：人批准的是他所理解的那个操作 A，而产品自有的逻辑随后授权了一个实质不同的 B。两个变体：一是表示不一致——那个有后果的字段其实已经编码在内，却被呈现给审阅者的内容省略掉了；二是批准后的状态替换——批准被记成挂在请求 id 上的一个状态标志，而参数留在可写的工作流状态里。第二种在 Agno AgentOS 直到 3.0.9 的七个版本、以及直到 0.14.0 的一种条件式内存内 LangGraph Agent Server 组合上被复现；第一种击中了 OpenClaw 2026.2.23，并在一天后被修复；OpenAI Agents SDK 0.22.0 与 0.22.2 充当阴性对照，因为序列化的续行保留了逐次调用的绑定、拒绝了被篡改的调用。没有注入、没有沙箱逃逸、没有模型的不当行为——这是一场中间夹了个人的「检查时到使用时」竞态，也正因如此，谁家的注入防御都碰不到它。修复是内容寻址：把调用规范化、把从同一份形式生成的渲染呈现给人、把批准存在摘要值上，并在执行前立即比对摘要值。而没人写的那条测试是：批准、改写、执行。',
    ),
    L(
      'AI Blog — “Bedrock Knowledge Bases vs Vertex AI Search vs Azure AI Search vs Vectara”: nobody buys a managed knowledge base for retrieval quality — the ranking gap closed a while ago and pgvector plus a reranker matches it in a fortnight. What you buy is the connector that copies SharePoint’s permissions along with its files and the query path that enforces them per end user, which is why the question to ask is whether the agent integration carries the end user’s identity or only the API you evaluated. Bedrock ships six first-party connectors and layers a real-time access check on top of pre-retrieval ACL filtering; Vertex binds retrieval to your identity provider and takes acl_info on imported data; Azure indexes permission metadata and trims per query on an x-ms-query-source-authorization token — except that the Foundry Agents SDK’s built-in search tool exposes no way to pass it (issue #44454, opened December 2025, still open), so an agent wired the documented way queries as the service and the filter has no principal to apply. Vectara is the only one with a genuine air-gapped path and scores grounding in about 0.6 seconds against roughly 35 for a frontier-LLM judge. Ranked by what it costs to leave: vectors are hours, the parser is weeks, the permission model is quarters — so evaluate the last one first, on the integration you will actually ship.',
      'AI 博客《Bedrock Knowledge Bases、Vertex AI Search、Azure AI Search 与 Vectara 对比》：没有人是冲着检索质量去买托管知识库的——排序差距早就收敛了，pgvector 加一个重排器两周就能追平。你买的是那个把 SharePoint 的权限连同文件一起搬过来的连接器，以及那条按最终用户强制执行权限的查询路径；所以该问的问题是：智能体那条集成路径究竟带不带最终用户的身份，还是只有你评估过的那个 API 才带。Bedrock 提供六个一方连接器，并在检索前 ACL 过滤之上叠加一次实时访问检查；Vertex 把检索绑定到你的身份提供方，并对导入数据接受 acl_info；Azure 把权限元数据建进索引、按查询依据 x-ms-query-source-authorization 令牌做裁剪——只不过 Foundry Agents SDK 内置的搜索工具没有提供任何方式去传它（issue #44454，2025 年 12 月提出，至今仍开着），于是按文档方式接起来的智能体是以服务身份在查询，过滤器没有主体可施加。Vectara 是唯一有真正离网路径的一家，其接地打分约 0.6 秒，而前沿 LLM 裁判约需 35 秒。按「离开的代价」排序：向量以小时计，解析器以周计，权限模型以季度计——所以先评估最后那个，并且在你真正会上线的那条集成路径上评估。',
    ),
    L(
      'Concepts — Interpretability & Probes: interpretability stopped being a research aesthetic in January 2026, when Google DeepMind put activation probes in front of live traffic on Gemini 2.5 Flash, and what shipped was the least glamorous artifact the field had — a logistic regression on one layer’s residual stream, run as the cheap tier of a cascade that defers roughly 8% of traffic to an LLM classifier and lands better accuracy than the LLM alone at about 1/50th its inference cost. Probes read the representation the model built before it chose any words, which is why deception probes report AU-ROCs of 0.96–0.999 on held-out sets where a text classifier has nothing to go on; they also collapse under distribution shift, and short-context training generalises badly to the long contexts an agent actually runs in. Read a handful of layers and ensemble them, refit on every model change, and note that the famous part of the field is not the shipped part: sparse autoencoders repeatedly fail to beat plain probes on downstream tasks. The constraint that decides everything is white-box access — so if you call a hosted model this is a procurement question, and the substitute available to everyone is behavioural detection on the trajectory.',
      '概念 — 可解释性与探针：2026 年 1 月，Google DeepMind 把激活探针放到了 Gemini 2.5 Flash 的线上流量前面，可解释性从此不再只是一种研究趣味；而真正上线的，是这个领域最不体面的那件东西——在某一层残差流上做的逻辑回归，作为级联中廉价的那一档运行，把大约 8% 的流量转给 LLM 分类器，最终准确率优于单用 LLM，推理成本却约为其五十分之一。探针读的是模型在选定任何词之前构建出的那份表示，这正是欺骗探针能在留出集上报出 0.96–0.999 的 AU-ROC、而文本分类器却毫无线索的原因；它们也会在分布漂移下崩塌，而短上下文训练出的探针很难泛化到智能体真正运行其中的长上下文。要读若干层并做集成、每次模型变更都重新拟合，并且注意这个领域出名的那部分并不是上线的那部分：稀疏自编码器在下游任务上一再打不过普通探针。决定一切的约束是白盒访问权——所以如果你调用的是托管模型，这是一个采购问题；而人人都能用的替代品，是在轨迹上做行为层面的检测。',
    ),
    L(
      'Operations — Fault Injection for Agent Stacks: when a dependency fails inside an ordinary service you get a 500 and an alert; inside an agent you get a fluent, confident, wrong answer and a green dashboard, because the component handling the error is a model whose entire training is to keep going. Killing pods and adding jitter exercises the wrong layer — the faults that matter are semantic and arrive at the tool boundary: empty success (a 200 with zero results, indistinguishable in text from “there is nothing to find”), slow but correct, malformed or truncated output, stale success, an error inside a 200 body, a provider refusal mid-run, schema drift, and credential expiry at step 14 of a run that started valid. Inject through a shim in the tool-invocation path with a seeded per-run fault plan so every finding replays, cover the model boundary too, and never touch a write path before idempotency keys exist. Then assert on the trajectory rather than a status code and grade each run correct-degraded, honest stop, or silent fabrication — only the third blocks a release, and one mechanical check catches most of it: a write must never follow a faulted read in the same run.',
      '运维 — 对智能体栈做故障注入：普通服务里依赖挂了，你会拿到一个 500 和一条告警；智能体里，你拿到的是一段流畅、自信、错误的答案和一张全绿的仪表盘，因为处理这个错误的组件是一个全部训练都在于「接着往下做」的模型。杀 Pod、加抖动练的是错的那一层——真正要紧的故障是语义层面的，而且抵达的是工具边界：空的成功（一个带零条结果的 200，在文本上与「确实没有东西可找」无从分辨）、慢但正确、畸形或截断的输出、陈旧的成功、装在 200 响应体里的错误、运行途中提供方的拒答、模式漂移，以及一趟开始时还有效、到第 14 步凭证就过期了。通过工具调用路径上的一层垫片注入，用带种子的按运行故障计划，好让每一个发现都能重放；模型边界也要覆盖；而在幂等键就位之前，绝不碰写路径。然后在轨迹上断言、而不是在状态码上，把每次运行判成正确降级、诚实停下、或无声编造——只有第三种该卡发布，而一条机械的检查就能抓住其中大部分：同一次运行里，写入绝不能跟在一次出故障的读取之后。',
    ),
    L(
      'Deep-Dives — Contextual Retrieval: the largest source of recall failure in a competent RAG stack is not the retriever, it is the moment you cut the document up — “revenue grew 3% over the previous quarter” names no company, no quarter and no year, and that is what your splitter handed the embedding model. Prepending a short generated preamble that situates each chunk before embedding cuts top-20 retrieval failure by 35%, by 49% when the same preamble also feeds a BM25 index, and by 67% with reranking on top (5.7% down to 1.9%), at roughly $1.02 per million document tokens once the whole-document prefix is prompt-cached. The cost nobody prices is architectural: your index is now a function of a chunker, an embedder, a contextualiser model and a prompt you will want to change, so “one-time at ingest” means per index generation and you should budget three rebuilds. Retrieve on the contextualised text and generate from the clean chunk, pin the contextualiser version per generation, and try the cheaper levers first — a deterministic heading-path prefix costs nothing, a reranker needs no re-embedding, and late chunking buys the context without a prompt to maintain.',
      '深入解析 — 上下文化检索：一套称职的 RAG 栈里召回失败最大的来源不是检索器，而是你把文档切开的那一刻——「营收较上一季度增长 3%」既没点公司、也没点季度和年份，而这就是你的切分器递给嵌入模型的东西。在嵌入前给每个分块前置一小段生成的、交代其出处的引子，能把 top-20 检索失败率降低 35%；让同一段引子也进 BM25 索引，降低 49%；再叠上重排，降低 67%（5.7% 降到 1.9%）；把整份文档的前缀做提示词缓存之后，成本约为每百万文档令牌 1.02 美元。没人计价的那笔代价是架构性的：你的索引从此成了切分器、嵌入器、上下文化模型和一段你迟早想改的提示词的函数，所以「摄取时的一次性成本」是按索引代次算的，你该按三次重建做预算。在上下文化文本上检索、用干净的分块做生成，按代次钉住上下文化器版本，并先试更便宜的杠杆——确定性的标题路径前缀不花钱，重排器不需要重新嵌入，而延迟分块能不靠一段要维护的提示词就把上下文买到手。',
    ),
  ],
};

export default entry;
