import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-09-03',
  title: L(
    'Two AI Blog posts — on the visual agent builder that archived itself and named coding agents as the reason, and on the safety log Anthropic moved into your own cloud account — plus three pages on shaping tool results, answering security questionnaires, and redacting PII from agent traces',
    '两篇 AI 博客——一个把自己归档、并点名编码智能体为原因的可视化智能体构建器；以及 Anthropic 挪进你自家云账号的那份安全日志——外加三个页面：塑形工具返回值、回答安全问卷，以及从智能体追踪里脱敏 PII',
  ),
  items: [
    L(
      'New AI Blog post `/blogs/n8n-vs-dify-vs-langflow-vs-flowise` — Flowise archived its own repository on 13 August 2026 (code freeze 29 July, core team presence ending 31 August, npm and Docker artefacts deprecated, forks invited) and its maintainers wrote down why: developers now lean on coding agents, and "the typical rigid workflow low-code approach quickly hits the limit when it comes to complexity." The post takes that as the thesis and asks what is underneath each surviving canvas that a coding agent cannot produce this afternoon — then shows that each licence names it. n8n is fair-code under the Sustainable Use License 1.0, which permits use "only for your own internal business purposes or for non-commercial or personal use" and excludes every `.ee` file entirely: it is defending roughly 1,500 connectors. Dify ships a modified Apache 2.0 that forbids operating a multi-tenant environment (a tenant is defined as one workspace) and locks the `web/` frontend branding, with the condition explicitly inapplicable to headless use: it is defending the workspace-and-retrieval app platform. Langflow is plain MIT with no clause at all, and its risk is roadmap direction — IBM completed its acquisition of DataStax, which had acquired Langflow in April 2024, on 1 November 2025. Closes on the axis nobody compares on: what the stored artefact is worth on the day you stop paying, where an n8n workflow JSON is a re-implementation and a Langflow flow is Python that runs anywhere.',
      '新增 AI 博客 `/blogs/n8n-vs-dify-vs-langflow-vs-flowise`——Flowise 在 2026 年 8 月 13 日把自己的仓库归档了（7 月 29 日代码冻结、8 月 31 日核心团队不再在场、npm 与 Docker 产物弃用、欢迎 fork），而维护者把原因写了下来：开发者如今倚重编码智能体，而「典型的那种僵硬的低代码工作流做法，一碰到复杂度就很快撞到上限」。本文以此为论点，追问每一块还活着的画布底下，有什么是编码智能体今天下午做不出来的——然后指出：每一份许可证都把那是什么点了名。n8n 是 Sustainable Use License 1.0 之下的 fair-code，只允许「为你自己的内部业务目的，或出于非商业或个人用途」使用，并把每一个 `.ee` 文件完全排除在外：它守的是约 1,500 个连接器。Dify 发布的是一份经修改的 Apache 2.0，禁止运营多租户环境（一个租户被定义为一个工作空间）并锁定 `web/` 前端的品牌标识，而该条件明确不适用于无头用法：它守的是那套「工作空间加检索」的应用平台。Langflow 是纯粹的 MIT，一条附加条款也没有，它的风险在路线图方向——IBM 于 2025 年 11 月 1 日完成了对 DataStax（后者已于 2024 年 4 月收购 Langflow）的收购。文末落在那条没人拿来比较的轴上：当你停止付钱的那一天，存下来的产物还值多少——一份 n8n 工作流 JSON 意味着一次重新实现，而一份 Langflow 流程是随处可跑的 Python。',
    ),
    L(
      'New AI Blog post `/blogs/anthropic-moved-the-evidence-not-the-detector` — Enterprise Frontier Safeguards, announced 1 September 2026 and developed with 100-plus customers across financial services, healthcare, manufacturing, telecoms, law, retail and the public sector, resolves a contradiction rather than adding a feature: sophisticated misuse spreads across sessions and accounts, so zero data retention forbade exactly the history cross-session detection requires. Anthropic moved the corpus, not the classifier — activity data lands in the customer\'s own S3, Azure Blob or GCS under the customer\'s keys, access policies and audit logging, while the detector stays on the vendor side and alerts route to the customer, whose human review it is by default. The post argues that last clause is a transfer of duty: "we were not aware" stops being automatic, and a bucket of your employees\' prompts is discoverable, subject-access-visible and legal-hold-bound in a way it never was under ZDR. Also separates the narrow flagged scope (offensive cyber or biological capability, stolen or leaked credentials) from the broad recorded one, argues an EFS alert is an insider-risk queue rather than a SOC queue because nothing was violated, and names the asymmetry that stays: you hold the corpus, not the classifier, so write the appeal path before the first alert. Phased rollout from later this autumn, no charge, with ZDR on Fable 5 and Fable 5.1 in the interim.',
      '新增 AI 博客 `/blogs/anthropic-moved-the-evidence-not-the-detector`——2026 年 9 月 1 日发布、与金融服务、医疗、制造、电信、法律、零售及公共部门的 100 多家客户共同开发的 Enterprise Frontier Safeguards，解开的是一个矛盾，而不是加了一个功能：老练的滥用铺展在多个会话与账号之上，所以零数据留存禁掉的，恰恰是跨会话检测所必需的那段历史。Anthropic 挪走的是语料，不是分类器——活动数据落进客户自己的 S3、Azure Blob 或 GCS，用客户自己的密钥、访问策略与审计日志，而探测器留在厂商一侧，告警发往客户，人工复核默认也归客户。本文主张最后那半句是一次义务转移：「我们并不知情」不再自动成立，而一个装着你员工提示词的存储桶，在诉讼调取、数据主体访问请求与法律保全面前，都变成了 ZDR 之下从未存在过的东西。文中还把很窄的「被标记」范围（攻击性网络能力或生物能力、被窃或泄露的凭据）与很宽的「被记录」范围分开，主张一条 EFS 告警属于内部风险队列而非 SOC 队列——因为没有任何东西被违反；并点名了那处不会消失的不对称：你握住的是语料，不是分类器，所以请在第一条告警之前先把申诉路径写好。自今秋稍晚起分批推出，不收费，过渡期内在 Fable 5 与 Fable 5.1 上提供 ZDR。',
    ),
    L(
      'New Deep-Dive `/deep-dives/tool-capability-design/shaping-tool-results` (K13) — a tool definition costs a few hundred tokens and you pay for it once per turn, inside the cached prefix; one unshaped result costs forty thousand and is re-sent on every turn after it, which is where the quadratic growth actually comes from. It is also the largest untrusted text block in the window, so an unshaped result hands an attacker who controls the upstream document an unbounded span of your prompt. The page gives four moves in payoff order — project to an explicit field allowlist (a GitHub issue is roughly forty fields and a triage agent needs six), rank before truncating, paginate with a stable cursor, hand back a handle — then treats silent truncation as the correctness bug it is, and proposes one five-key envelope (`status`, `summary`, `data`, `omitted`, `next`) enforced by the harness rather than by each tool author, with `empty` distinguished from `error` so agents stop retrying correct queries.',
      '新增深入解析 `/deep-dives/tool-capability-design/shaping-tool-results`（K13）——一份工具定义值几百个 token，每轮只付一次，而且待在被缓存的前缀里；一次未塑形的返回值值四万个 token，并在其后的每一轮被重发——那份二次增长真正的来源就在这里。它同时还是窗口里最大的一整块不可信文本，所以一次未塑形的返回值，等于把你提示词里一段无上限的篇幅交给了控制上游文档的攻击者。本页按收益顺序给出四个动作——做一份显式字段白名单的投影（一个 GitHub issue 约四十个字段，而一台分诊智能体需要六个）、先排序再截断、用稳定游标分页、递回一个句柄——随后把静默截断当作它本来的样子（一个正确性缺陷）来处理，并提出一个五键信封（`status`、`summary`、`data`、`omitted`、`next`），由框架而不是由每位工具作者来强制，且把 `empty` 与 `error` 区分开，好让智能体不再把正确的查询重试五次。',
    ),
    L(
      'New Playbook `/playbooks/domain-playbooks/rfp-and-questionnaire-agents` (Y30) — every answer you return is a representation your company makes to a buyer, so a stale "yes, encrypted at rest with customer-managed keys" is a misrepresentation your sales team signed, not a hallucination your model made. That reorders the build: the answer library is the product, and an answer is five things (claim, evidence pointer, owner, `valid_until`, scope caveat) rather than one string. The page argues the dangerous retrieval failure is not "found nothing" but "found something 0.94 similar and materially different" — at rest versus in transit, do you versus can you versus will you — so match on an extracted claim skeleton and surface the delta; gives three tiers (reuse, adapt, escalate) with a hard block on future-tense commitments, which are contract terms rather than answers; and does the arithmetic nobody puts on the slide, where 300 answers at 92% accuracy means 24 wrong ones invisible among 276 right ones. Closes on the inbound questionnaire as untrusted input and a read-only path to the library.',
      '新增实战页 `/playbooks/domain-playbooks/rfp-and-questionnaire-agents`（Y30）——你交回的每一个答案，都是贵司向买方作出的一项陈述；所以一句过期的「是的，静态加密并使用客户自管密钥」，是一份由你的销售签了字的不实陈述，而不是你的模型犯的一次幻觉。这把整个项目重排了一遍：答案库才是产品，而一条答案是五样东西（主张、证据指针、负责人、`valid_until`、适用范围限定），不是一个字符串。本页主张危险的检索失败不是「什么也没找到」，而是「找到了一条相似度 0.94、但实质不同的」——静态对传输中、你们是否对你们能否对你们将否——所以要按抽取出来的主张骨架去匹配，并把差异摆到台面上；给出三个档位（复用、改写、上报）并对将来时的承诺设一道硬闸，因为那是合同条款而不是答案；还把那笔没人写进 PPT 的算术做了一遍：92% 准确率下的 300 条答案，意味着 24 条错的隐形地散在 276 条对的里面。文末落在「入站问卷是不可信输入」与「对答案库只读」。',
    ),
    L(
      'New Operation `/operations/evaluation-and-observability/pii-redaction-in-agent-traces` (E18) — the OpenTelemetry GenAI conventions make every content-bearing attribute opt-in precisely so content never appears because someone forgot a flag, and that default is the last cheap moment in the process. The page argues redaction belongs in the SDK and nowhere downstream, because at the collector the data has already crossed a process boundary and usually a network — backend masking is display-layer redaction, and the raw value is in the store, the backups and the search index. It argues for deterministic typed tokens over masks (`<EMAIL_7f2a>` keeps the joins that answer "one customer or a systemic bug", and makes an erasure request something you can actually execute), for per-entity-type recall measured against a labelled corpus as a CI gate rather than an aggregate figure dominated by the easy classes, and for sizing the break-glass unredacted tier above your measured MTTD — a 24-hour TTL against a nine-day median time to notice is empty every time you need it.',
      '新增运营页 `/operations/evaluation-and-observability/pii-redaction-in-agent-traces`（E18）——OpenTelemetry 的 GenAI 约定把每一个装内容的属性都设为「选择加入」，正是为了让内容不会因为谁忘了一个开关就出现；而那个默认值，是这整件事里最后一个便宜的时刻。本页主张脱敏属于 SDK，而不属于下游任何位置，因为到了 collector，数据已经跨过了一道进程边界、通常还跨过了一个网络——后端遮蔽只是展示层脱敏，原始值还在存储里、备份里和搜索索引里。文中主张用确定性的带类型令牌取代遮罩（`<EMAIL_7f2a>` 保住了那些能回答「是一个客户还是一个系统性 bug」的关联，也让一次删除请求变成你真的执行得了的事），主张把「按实体类型、对着标注语料量出来的召回率」做成 CI 闸门，而不是看一个被容易类别主导的总体值；并主张把破玻璃未脱敏层的 TTL 定在实测 MTTD 之上——24 小时的 TTL 配上九天的察觉中位耗时，每一次你需要它的时候它都是空的。',
    ),
  ],
};

export default entry;
