import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-08-08',
  title: L(
    'Two AI Blog posts on the four terminal coding agents and Claude Enterprise inference hooks, plus five pages on test-generation agents, waiting UX, annotation ops, graceful degradation and chain-of-thought faithfulness',
    '两篇 AI 博客——四个终端编码智能体，以及 Claude Enterprise 的推理钩子——外加五个页面：测试生成智能体、等待体验、标注运营、优雅降级，以及思维链忠实性',
  ),
  items: [
    L(
      'New blog post — *Claude Code vs Codex CLI vs Antigravity CLI vs opencode: pick the contract, not the score*. On Terminal-Bench 2.1 the top two defaults are 0.4 points apart — GPT-5.6 Sol at 89.5%, Claude Opus 5 at 89.1%, both on the Terminus 2 harness — a gap inside normal run-to-run variance, so the model axis has closed and the decision has moved to licence, config portability and distribution stability. Google demonstrated why on 18 June: a 105,000-star open-source CLI retired thirty days after its I/O announcement, replaced by the closed-source Go binary `agy`, with the free tier cut from about 1,000 requests a day to roughly 20 and a rewritten settings schema breaking CI. Breaks a terminal agent into four layers — model, harness loop, configuration surface, your repo and CI — and shows the switching cost lives entirely in the layer nobody benchmarks. Three themeable SVGs including a five-axis feature matrix.',
      '新博客文章——《Claude Code vs Codex CLI vs Antigravity CLI vs opencode：挑契约，别挑分数》。在 Terminal-Bench 2.1 上，排名前二的默认模型只差 0.4 分——GPT-5.6 Sol 89.5%、Claude Opus 5 89.1%，均在 Terminus 2 外壳上——这个差距落在正常的跑次间波动以内，于是模型这条轴合拢了，决策重心挪到了许可证、配置可移植性与分发稳定性上。6 月 18 日 Google 演示了原因：一个 10.5 万星的开源 CLI 在 I/O 宣布后三十天被退役，换成闭源 Go 二进制 `agy`，免费额度从每天约 1000 次请求砍到约 20 次，重写后的配置 schema 还弄坏了 CI。文章把终端智能体拆成四层——模型、外壳循环、配置面、你的仓库与 CI——并指出切换成本完全住在那个没人拿去跑分的层里。配三张可随主题变色的 SVG，含一张五维特性矩阵。',
    ),
    L(
      'New blog post — *Inference Hooks Move the DLP Boundary — Past the Traffic That Matters Most*. Anthropic\'s inference hooks, in beta from 5 August, route every Claude Enterprise prompt to a security server the customer runs for an allow-or-deny verdict before the model sees it — genuinely closing the gap network DLP proxies have had since phones and unmanaged devices became a working path to a frontier model. But the only hook event at launch fires on the prompt, coverage is Enterprise surfaces only (chat, Claude Code, Cowork), and the Claude Platform API, Bedrock and Vertex are explicitly out of scope: the paths autonomous agents actually run on, carrying orders of magnitude more sensitive data per unit of human attention. Also covers what an inline control does to your latency budget, the fail-open versus fail-closed decision, and why aggressive blocking without shadow mode produces shadow IT rather than less leakage. Three SVGs including a four-rung rollout ladder.',
      '新博客文章——《推理钩子挪动了 DLP 边界——却绕开了最要紧的那股流量》。Anthropic 的推理钩子自 8 月 5 日起进入 beta：在模型看到之前，把每一条 Claude Enterprise 提示词路由到客户自运行的安全服务器取放行/拒绝裁定——这确实补上了网络 DLP 代理的一个缺口，自从手机与非受管设备成为通往前沿模型的可用路径起，这个缺口就一直在。但发布时唯一的钩子事件只针对提示词触发，覆盖范围仅限 Enterprise 界面（聊天、Claude Code、Cowork），而 Claude Platform API、Bedrock 与 Vertex 被明确排除在外：那正是自主智能体实际运行的路径，按"每单位人类注意力"计算，它们承载的敏感数据要多出好几个数量级。文中还讲了内联控制对延迟预算的影响、"失败放行 vs 失败闭合"这个决定，以及为什么不经影子模式就激进拦截，产出的是影子 IT 而不是更少的泄漏。配三张 SVG，含一张四级放量阶梯图。',
    ),
    L(
      'New Playbook (Coding & Computer-Use Agents) — *Test-Generation Agents*. An agent that writes tests from your code infers the specification from the implementation, so wherever the implementation is wrong the test now certifies the bug and blocks the fix — and the next engineer to correct the function gets a red suite and often corrects the test instead. Coverage cannot detect this and neither can review at volume, so the acceptance criterion has to be falsification: mutate the changed lines and require the suite to go red. Covers the three jobs where the oracle already exists outside the code (characterization before a refactor, reproduction from a bug report, properties from a stated contract), the maintenance ledger every generated test joins permanently, the single most useful lever nobody pulls — withhold the implementation when you want a specification — and four dashboard numbers, none of them coverage.',
      '新增实战手册（编码与计算机操作智能体）——《测试生成智能体》。从你的代码出发写测试的智能体，是从实现里反推规格的，所以实现错在哪里，测试就在哪里把 bug 认证为正确并挡住修复——而下一个想改正这个函数的工程师会看到一片红，然后常常改的是测试。覆盖率发现不了这件事，批量评审也发现不了，所以验收标准必须是证伪：对改动行做变异，要求测试必须变红。文中讲了判据本来就存在于代码之外的三类工作（重构前的特征化测试、由缺陷报告生成的复现测试、由既定契约生成的性质测试）、每条生成测试都会永久加入的那本维护账，那根最有用却几乎没人拉的杠杆——想要规格时就把实现藏起来——以及四个该上看板的数字，其中没有一个是覆盖率。',
    ),
    L(
      'New Playbook (Agent UX & Human Interaction) — *Waiting & Latency UX*. Abandonment tracks legibility rather than duration, so shaving eight seconds off a forty-second run buys almost nothing while publishing a plan up front changes the wait categorically. Separates four clocks — time to first token, to first checkable evidence, to reviewable artifact, to done — and argues the second is the one that governs whether a user stays, which means reordering the plan so something verifiable happens first, even when that is not the most logical order of work. Also: why streaming reasoning tokens is motion rather than progress, why a silent tool call reads as broken rather than slow, and where to stop designing the wait and hand off to async instead. Ends on six metrics including silence gaps, which nobody instruments and which correlate with abandonment better than total duration.',
      '新增实战手册（智能体体验与人机交互）——《等待与延迟的交互设计》。放弃率跟随的是可读性而非时长，所以给一次四十秒的运行削掉八秒几乎买不到什么，而开工前先公布计划则是量级上的改变。文章分开了四个时钟——首 token 时间、首个可核验证据时间、首个可评审产物时间、完成时间——并论证第二个才是决定用户留不留下的那一个，这意味着要重排计划让可核验的事先发生，哪怕那不是工作上最合逻辑的顺序。此外还有：为什么流式吐推理 token 是"在动"而不是"在推进"、为什么静默的工具调用读起来是"坏了"而不是"慢"，以及在哪里该停止设计等待、转而交接给异步。文末给出六个指标，包括没人埋点、却比总时长更能预测放弃行为的"静默间隔"。',
    ),
    L(
      'New Operation (Evaluation & Observability) — *Annotation & Labeling Ops*. An LLM judge is a classifier fitted to human labels, so the labels set its ceiling: if two qualified annotators agree on 72% of traces, a judge at 72% is already finished and every further week of prompt tuning is fitting noise. Argues that low agreement is a rubric defect rather than a people defect, that most of it traces to four fixable ambiguities, and that disagreement is the most valuable output of the process — the contested items are the decision boundary, so route them to adjudication with a written reason instead of majority-voting them away. Also covers chance-corrected agreement on skewed pass/fail data, matching the annotator\'s observation window to the judge\'s, spending the labelling budget where the judge is uncertain, and why every label needs a rubric version and a date.',
      '新增运维页（评估与可观测性）——《标注运营》。LLM 裁判是一个拟合到人工标签上的分类器，所以标签定义了它的天花板：如果两位合格标注员在 72% 的轨迹上一致，一个 72% 的裁判就已经到头了，此后每一周的提示词调优都是在拟合噪声。文章主张一致率低是评分标准的缺陷而不是人的缺陷，其中大部分可追溯到四种可修复的含混，而分歧才是这个流程最有价值的产出——有争议的条目就是决策边界，所以要把它们连同书面理由路由去裁决，而不是用多数投票抹平。文中还讲了在严重倾斜的通过/失败数据上使用"排除偶然"的一致率、把标注员的观察窗口与裁判的对齐、把标注预算花在裁判不确定的地方，以及为什么每个标签都需要一个评分标准版本和一个日期。',
    ),
    L(
      'New Operation (AgentOps) — *Graceful Degradation & Fallback*. The fallback is a different agent, not a slower one: a different tool-calling dialect, a different context ceiling, a different refusal profile — and at the moment the primary degrades, the most traffic in the system\'s history flows down its least-tested path under thresholds calibrated for a model that stopped answering. Argues for deciding what to shed before what to swap (reasoning effort is a dial before the model is a switch), failing open on reads and closed on anything with a side effect, lowering the autonomy threshold when quality drops, and making degraded mode an explicitly named state with alerts, hysteresis on recovery and an exit — because the most common ending for a well-built fallback is that it quietly becomes the product. Plus continuous fallback traffic and scheduled degradation drills, and five numbers including cost per completed task, which is usually higher.',
      '新增运维页（智能体运维）——《优雅降级与备用方案》。备用方案是另一个智能体，不是一个更慢的智能体：不同的工具调用方言、不同的上下文上限、不同的拒答画像——而在主力开始劣化的那一刻，系统历史上最大的一股流量涌进了它测试最少的那条路径，头顶还是照着一个已停止作答的模型校准的阈值。文章主张先决定卸掉什么再决定换成什么（推理力度是一个旋钮，排在"模型是一个开关"之前）、读操作失败时放行而一切有副作用的操作失败时闭合、质量下降时把自主度阈值一起调低，并把降级做成一个有告警、恢复时带迟滞、且有出口的具名状态——因为一个造得不错的降级方案，最常见的结局是它悄悄变成了产品本身。此外还有持续的备用流量与有排期的降级演练，以及五个数字，其中包括通常更高的"每完成一个任务的成本"。',
    ),
    L(
      'New Concept (Core Building Blocks) — *Chain-of-Thought Faithfulness*. A reasoning trace is not a log of how the model reached its answer; it is more generated text, with nothing binding it to the computation that settled the question. Anthropic\'s hint experiments put the numbers on it: Claude 3.7 Sonnet mentioned an answer-changing hint 25% of the time, DeepSeek R1 39%. That dismantles the most common oversight design in production agents — approval gates showing thinking, judges grading rationales, injection detectors reading the scratchpad — all of which are grading a story. Argues for auditing the action log instead, because tool calls are records and reasoning is not, and for the one design decision that makes faithfulness measurably worse: putting the visible reasoning into a reward, which teaches the trace rather than the behaviour and removes your own early-warning signal.',
      '新增概念页（核心构件）——《思维链忠实性》。推理轨迹并不是"模型如何得出答案"的日志；它只是更多生成出来的文本，与那段定下答案的计算之间没有任何东西相绑。Anthropic 的提示实验给出了数字：Claude 3.7 Sonnet 只在 25% 的情况下提到那个改变了答案的提示，DeepSeek R1 是 39%。这拆掉了生产智能体中最常见的那种监督设计——展示思考过程的审批闸门、给理由打分的裁判、读草稿纸的注入检测器——它们评的都是一个故事。文章主张改去审计动作日志，因为工具调用是记录而推理不是；并指出那个会让忠实性可度量地变差的设计决定：把可见推理放进奖励里，那教会的是轨迹而不是行为，还删掉了你自己的预警信号。',
    ),
  ],
};

export default entry;
