import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-08-23',
  title: L(
    'Two AI Blog posts on Slack Code putting approval in a channel and on the four MCP indexes, plus three pages on attested inference, agent liability and design-to-code',
    '两篇 AI 博客——Slack Code 把审批搬进频道，以及四个 MCP 索引——外加三个页面：可证明推理、智能体责任，以及设计稿转代码',
  ),
  items: [
    L(
      'New blog post — *Slack Code puts the approval in a channel — name one approver anyway*. Salesforce announced Slack Code on 20 August 2026: five partner coding agents (Claude Code, Devin, GitHub Copilot, ChatGPT, Vercel) that you license separately, working inside a dedicated channel with four views — conversation, plan, code diffs and a live preview — ending in a human approval before anything ships. Argues Slack bought the review surface rather than the agent, which is the correct bottleneck since generation stopped being the constraint and merged-without-edits rate did not, then names the cost nobody covered: a terminal addresses its approval prompt to exactly one person who also holds the intent and the accountability, while a channel addresses it to an audience, and an approval addressed to a group is taken by whoever is least busy — which is usually whoever knows the surrounding system least. Prescribes one named approver per run stated up front, the audience as reviewers rather than approvers, the plan tab as the cheap gate (about two minutes against fifty for a six-hundred-line diff), and channel retention set to match change-record retention rather than the chat default, since the channel is now an audit trail with an expiry date nobody chose. Three themeable SVGs.',
      '新博客文章——《Slack Code 把审批搬进了频道——但你仍然要指定一个人来批》。Salesforce 于 2026 年 8 月 20 日发布 Slack Code：五家合作方的编码智能体（Claude Code、Devin、GitHub Copilot、ChatGPT、Vercel）需单独授权，在一个专属频道里干活，频道提供四个视图——对话、计划、代码 diff 与实时预览——任何东西上线前都要经一个人批准。文章论证 Slack 买下的是复核界面而不是智能体，而这个瓶颈押对了：生成早已不再是约束，"无需人工编辑即合并的比例"却依然是。随后点出没人写到的那笔代价：终端把审批提示只发给一个人，而这个人同时握着意图与问责；频道则是发给一群观众，而发给一群人的审批会被最闲的人接走——那通常也是对周边系统了解最少的人。文章开出处方：每次运行开头就指定一名审批人、让围观者当复核者而非审批者、把计划页当作便宜的闸门（约两分钟，对比六百行 diff 的五十分钟），并把频道保留期设成与变更记录一致而不是聊天默认值——因为这个频道如今是一份带着没人选择过的过期日的审计轨迹。配三张可随主题变色的 SVG。',
    ),
    L(
      'New blog post — *MCP Registry vs Smithery vs Docker MCP Catalog vs PulseMCP: four indexes, one missing signal*. Four places to look an MCP server up, answering four different questions: the official Registry is a namespace whose reverse-DNS names are verified by GitHub OAuth or a DNS TXT / HTTP challenge, with reactive denylist moderation and a public read API that returns 24,330 distinct server names across 79,651 version records, roughly seven in ten under io.github.* namespaces; Smithery sells a runtime — CLI install, hosted remote endpoints and a routing meta-server — which moves your upstream OAuth tokens onto someone else\'s infrastructure; Docker\'s catalog is the only one making a claim about the artefact you execute, shipping containerised servers with signatures, SBOMs, provenance attestations and a gateway that can verify them at launch; and PulseMCP is a large hand-reviewed directory that makes no trust claim at all. Argues that name verification, build provenance and hosted availability are three separable facts and none of them is behavioural, so the tool descriptions your model obeys go unread by all four — leaving four gaps you own: diff descriptions on update, pin versions, declare egress yourself, and re-check after listing, all of which get sharper under the progressive discovery named in the 22 August 2026 MCP roadmap. Three SVGs.',
      '新博客文章——《MCP Registry vs Smithery vs Docker MCP Catalog vs PulseMCP：四个索引，缺的是同一个信号》。同一个 MCP 服务器可以在四个地方查到，而它们回答的是四个不同的问题：官方 Registry 是一个命名空间，其反向 DNS 名字通过 GitHub OAuth 或 DNS TXT／HTTP 挑战验证，审核是被动拉黑式的，而它的公开只读 API 返回 24,330 个不同的服务器名字、79,651 条版本记录，其中约七成落在 io.github.* 命名空间下；Smithery 卖的是运行时——CLI 安装、托管远程端点，以及一个做路由的元服务器——这会把你的上游 OAuth 令牌挪到别人的基础设施里；Docker 的目录是唯一一个对"你将执行的产物"作出承诺的，它以容器镜像分发服务器，带签名、SBOM 与来源证明，网关还能在启动时校验；而 PulseMCP 是一个大型人工审阅目录，完全不做任何信任承诺。文章论证名字验证、构建来源与托管可得性是三件可以拆开的事实，而没有一件是关于行为的，于是你的模型会服从的那些工具描述，四家都没读过——留下四道归你自己的缺口：更新时对描述做 diff、钉住版本、自己声明出站、以及上架之后要复查；而在 2026 年 8 月 22 日 MCP 路线图点名的"渐进式发现"之下，这四道缺口只会更锋利。配三张 SVG。',
    ),
    L(
      'New Concept (AI Ecosystem) — *Confidential Computing &amp; Attested Inference*. A trusted execution environment turns "we can\'t see your data" from a promise into a claim with a proof shape: memory encrypted against the host, a hardware-signed measurement of exactly what booted, and a key released only after a verifier checks that measurement — with Intel TDX, AMD SEV-SNP and AWS Nitro Enclaves on the CPU side and NVIDIA H100/H200 confidential mode on the accelerator, at a reported low-single-digit throughput cost. Argues the guarantee is real and narrow: it excludes the operator of the machine and nothing else, so the trace store, the eval set, the memory layer and the counterparty you chose to send the data to all still leak. Adds that an attestation is worth exactly your verification policy — verify the measurement against a value you hold, gate a key rather than a log line, ask who publishes the expected measurement, and make failure mean refusal — and closes by asking the reader to name the party they are trying to exclude before evaluating a single product.',
      '新增概念页（AI 生态）——《机密计算与可证明推理》。可信执行环境把"我们看不到你的数据"从一句承诺变成一句有证明形状的断言：对宿主加密的内存、一份硬件签名的"到底启动了什么"的度量值，以及只有在验证者比对过该度量值之后才释放的密钥——CPU 侧是 Intel TDX、AMD SEV-SNP 与 AWS Nitro Enclaves，加速器侧是 NVIDIA H100／H200 的机密模式，公开报告的吞吐损耗在个位数百分比低端。文章论证这份保证既真实又狭窄：它排除的只有机器的运营方，别的一概不排，于是追踪存储、评测集、记忆层，以及你自己选择把数据发过去的那个对手方，照漏不误。文章还指出一份远程证明的价值正好等于你的核验策略——拿你手里的值去比对度量值、用密钥而不是日志当闸门、问清期望度量值由谁公布、让失败意味着拒绝——并在结尾要求读者在评估任何产品之前，先点名自己想排除的那一方。',
    ),
    L(
      'New Operation (Governance &amp; Compliance) — *Insurance &amp; Liability for Agent Actions*. Who absorbs an agent-caused loss is settled not by fault but by three documents written months earlier: the model and tool vendors\' liability cap (commonly twelve months of fees, so roughly $24k on a $2k/month tool), the cap and carve-outs in your own customer contract, and whether your policy affirms, silently covers or expressly excludes AI. Notes that silent AI is ending — ISO published optional generative-AI general-liability exclusion endorsements carrying January 2026 edition dates (CG 40 47, CG 40 48 and a products-and-completed-operations companion), and technology E&amp;O and cyber forms are being revised the same way — so the dangerous moment is renewal, not the incident. Surveys the affirmative market (Armilla as a Lloyd\'s coverholder underwritten by Chaucer, limits reaching the $25M range per organisation by early 2026; AIUC writing against its own audit standard; HSB, Counterpart and the Google Cloud risk-protection programme), then makes the operational point: underwriting now reads unattended authority, kill switches, eval sets and incident history, which turns engineering artefacts into a price. Closes on the trace as the instrument that converts a claim into a payment against all three documents, the way the same record cuts back at you, and writing the agent\'s authority ceiling into the customer agreement so there is a limit to argue about. Not legal advice.',
      '新增运维页（治理与合规）——《智能体行为的保险与责任》。由智能体造成的损失谁来吸收，不由过错决定，而由三份几个月前就写好的文件决定：模型与工具厂商的责任上限（常见是十二个月的费用，于是一个月费 2,000 美元的工具约为 24,000 美元）、你自己客户合同里的上限与除外，以及你的保单对 AI 是明确承保、含糊沉默还是明文除外。文章指出"沉默的 AI"正在终结——ISO 发布了版本日期为 2026 年 1 月的生成式 AI 综合责任险可选除外批单（CG 40 47、CG 40 48 及一份产品与已完工作业的配套表格），科技 E&amp;O 与网络险的条款也在被同样修订——所以危险的时刻是续保，不是事故。文中梳理了明确承保市场（作为劳合社承保代理机构、由 Chaucer 承保的 Armilla，到 2026 年初每家机构限额达到 2,500 万美元量级；依据自家审计标准核保的 AIUC；HSB、Counterpart 与 Google Cloud 的风险保障计划），随后给出运维层面的要点：核保如今会去读无人值守权限、急停开关、评测集与事故历史，这把工程产物变成了一个价格。文末落在：追踪记录是把索赔换成赔款、并对三份文件同时生效的那件器械；同一份记录也会反过来割你；以及把智能体的权限上限写进客户协议，好让争论有个限额可争。本页不是法律意见。',
    ),
    L(
      'New Playbook (Coding &amp; Computer-Use Agents) — *Design-to-Code Agents*. A screenshot carries the visual result and destroys the system that produced it, so a pixel-faithful generator rebuilds a Button that already exists, writes #d4421e instead of the token, and measures 14px off a six-step scale — and all three pass a visual review. Argues the deliverable is component reuse rate, not a matching screenshot: hand the agent a typed component API, canonical usage examples, a negative list and the design-component-to-import-path mapping (Figma\'s Code Connect, or a hundred rows of YAML you write yourself) before it ever sees the picture; when only an image exists, extract a layout tree and review the mapping rather than the markup. Replaces visual diffing as the primary oracle — it scores a perfect one-off component perfectly — with reuse rate, token adherence enforced by lint, and explicit coverage of the states designs never draw, and treats accessibility as absent from the picture by construction, which is the strongest argument for composing from real components. Closes with a ten-screen pilot: below roughly seventy per cent reuse you have a design-system problem the agent will scale rather than close.',
      '新增实战手册（编码与计算机操作智能体）——《设计稿转代码智能体》。截图带走了视觉结果，却销毁了产生它的那套系统，于是一个像素级忠实的生成器会重造一个本已存在的 Button、写下 #d4421e 而不用 token、并在一套六档刻度上量出 14px——而这三件事都能通过视觉复核。文章论证交付目标是组件复用率而不是"截图对得上"：在它看到图片之前，先把带类型的组件 API、标准用法示例、一份反面清单，以及"设计组件到 import 路径"的映射（Figma 的 Code Connect，或者你自己写的一百行 YAML）交给它；只有图片时，先抽出一棵布局树，复核映射而不是标记语言。文章把主要裁判从视觉比对换掉——它会给一个完美的一次性组件打满分——改用复用率、由 lint 强制的 token 遵循度，以及对"设计从不画的那些状态"的显式覆盖；并指出无障碍在构造上就不在那张图里，而这正是"用真实组件来拼"最有力的论据。文末给出十个页面的试点：复用率低于大约七成，你面对的就是一个设计系统问题，而智能体只会放大它、不会补上它。',
    ),
  ],
};

export default entry;
