import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-10-07',
  title: L(
    'Two AI Blog posts — one on commodity infostealers adding AI coding tools to their collection rules, so that the loot is a weeks-long refresh token bundled with a machine-readable list of every system it reaches, one on the four GenAI tracing conventions and the awkward fact that the only one calling itself the standard is the only one with no release to pin — plus three pages on the lifetime of a credential pair, the artifacts an agent leaves on a developer endpoint, and the reconnaissance your own configuration performs for an attacker',
    '两篇 AI 博客——一篇讲商品化窃密软件把 AI 编码工具加进了收集规则，于是赃物是一枚有效期数周的刷新令牌，外加一份「它能触达的每一个系统」的机器可读清单；一篇讲四套 GenAI 链路追踪约定，以及那个尴尬的事实：唯一自称是标准的那个，恰恰是唯一没有发布可供固定的那个——外加三个页面：一对凭据的有效期、智能体留在开发者端点上的那些工件，以及你自己的配置替攻击者做掉的那份侦察',
  ),
  items: [
    L(
      'AI Blog — “The token came with the tool list”: Gen Threat Labs’ 8 September 2026 research documents eight commodity infostealer families extending their collection rules to the local artifacts of AI coding tools, with Amatera taking Cline and Continue, Remus taking Claude, Cursor and OpenCode, and CallbackBeaver — 5,000-plus samples in one 30-day window — adding Cursor and Claude. Reads the harvested directory as four artifacts rather than one secret: a refresh token valid twenty-seven days beside a one-hour access token, an MCP config that is a curated routing table for your internal estate, a transcript history that cannot be revoked at all, and project metadata that answers whose estate it is. Notes that mode 0600 is a boundary against other users while the stealer runs as you, that the rules are remotely managed so adding your tooling is a config push, and that the replay never enters your network, which is why the detection has to sit at the provider or in a planted honeytoken.',
      'AI 博客《令牌是连着工具清单一起走的》：Gen Threat Labs 在 2026 年 9 月 8 日发布的研究记录道，八个商品化窃密软件家族把收集规则扩展到了 AI 编码工具的本地工件——Amatera 拿 Cline 与 Continue，Remus 拿 Claude、Cursor 与 OpenCode，而 CallbackBeaver（某 30 天窗口内样本逾 5,000）把 Cursor 与 Claude 加了进来。文章把被收割的那个目录读成四件工件、而不是一个密钥：一枚二十七天的刷新令牌躺在一枚一小时的访问令牌旁边、一份其实是你内部资产的「经过挑选的路由表」的 MCP 配置、一份压根无法撤销的对话历史，以及一份回答「这是谁家的」的项目元数据。文中指出：0600 是一道针对其他用户的边界，而窃密程序正是以你的身份在跑；那些规则是远程管理的，所以把你的工具链加进去只是一次配置推送；而回放压根不经过你的网络——这正是为什么检测必须落在供应商那一侧，或落在一个被种下的蜜标上。',
    ),
    L(
      'AI Blog — “OTel GenAI vs OpenInference vs OpenLLMetry vs OpenLIT”: on 12 June 2026, semantic conventions v1.42.0 deprecated all sixty gen_ai attributes and relocated the namespace, with the MCP conventions, to a dedicated repository that today has 653 commits, no tagged release and a schema-URL section still marked TODO — every attribute, span, metric and event in it badged Development, none Stable. Fifty attributes kept their string, eight were renamed (both token-usage attributes among them, so cost charts under-count silently), and gen_ai.prompt and gen_ai.completion were deleted outright. Separates the churn layer from the contract layer: attribute names break queries, while the span-kind vocabulary — OpenInference’s eleven explicit kinds against OTel’s operation names and the invoke_agent client/internal split — is what backend evals, replay and agent views dispatch on. Closes on the recommendation nobody tables: derive cost metrics under names you own and never point a chart at gen_ai.*.',
      'AI 博客《OTel GenAI、OpenInference、OpenLLMetry 与 OpenLIT 对比》：2026 年 6 月 12 日，语义约定 v1.42.0 把全部六十个 gen_ai 属性标为弃用，并把这个命名空间连同 MCP 约定一起挪进了一个专用仓库——那个仓库如今有 653 次提交、没有打标签的发布，schema URL 那一节仍标着 TODO，而其中每一个属性、span、指标与事件都挂着 Development，无一为 Stable。五十个属性保住了字符串，八个被改名（两个 token 用量属性就在其中，于是成本图表会静默少算），而 gen_ai.prompt 与 gen_ai.completion 是被彻底删掉的。文章把「扰动层」与「契约层」分开：属性名字破掉的是查询，而 span kind 词表——OpenInference 的十一个显式 kind，对上 OTel 的操作名与 invoke_agent 的 client／internal 拆分——才是后端评测、回放与智能体视图据以分派的东西。结尾给出那条没人列进表格的建议：用你自己掌控的名字派生成本指标，并且永远不要让图表指向 gen_ai.*。',
    ),
    L(
      'Concepts — “Credential lifetime”: once a credential has been copied off a machine, the only property still under your control is how long it keeps working, and a refresh token stored beside a short-lived access token quietly sets the pair’s real lifetime, because refresh is renewal without re-authentication. Prices the three bills a shorter lifetime actually incurs — re-authentication friction, outage amplification, and runs that outlive their own credential — then moves the number that matters from TTL to time-to-revoke, with the stopwatch drill and the question of which of your tokens are revocable at all.',
      '概念《凭据有效期》：一份凭据一旦被从机器上复制走，仍由你掌控的属性只剩一个——它还能用多久；而一枚与短命访问令牌存在一起的刷新令牌，会悄悄决定这一对真正的有效期，因为刷新就是「无需重新认证的续期」。文章给缩短有效期真正要付的三笔账定了价——重新认证的摩擦、故障被放大，以及活得比自己凭据更久的那些运行——随后把该在意的那个数字从 TTL 挪到「撤销耗时」，并给出那场秒表演练，以及「你的哪些令牌压根可撤销」这个问题。',
    ),
    L(
      'Operations — “Agent artifacts on the endpoint” (Safety &amp; Security): every control you built for agent security assumes the agent is what is under attack, while its tokens, its connected-system list and a searchable record of everything it was ever asked sit in predictable paths on unmonitored laptops. Enumerates the five artifact classes, walks through why file mode, egress control, secrets management and injection defence each fail to apply, prices the artifacts by what they buy rather than what they are called, and gives the generated inventory, the four changes that make the file worth less, and the honeytoken-and-stopwatch pair that turns the surface into something you can measure.',
      '运维《端点上的智能体工件》（安全与防护）：你为智能体安全建起的每一项控制都假定被攻击的是智能体，而与此同时，它的令牌、它所连接的系统清单、以及一份「它曾被要求过什么」的可检索记录，就躺在无人监控的笔记本上的可预测路径里。文章枚举五类工件，逐项说明权限位、出站控制、密钥管理与注入防御为何各自都不适用，按「它们能买到什么」而不是按名字给工件定价，并给出那份生成式清册、让这个文件更不值钱的四项改动，以及把这个面变成可度量之物的「蜜标加秒表」组合。',
    ),
    L(
      'Deep-Dives — “Configuration as reconnaissance” (Agent Security): reconnaissance used to be the expensive, noisy phase of an intrusion, and agent deployments now ship the answer as a build artifact — a curated, current, machine-readable list of the systems you thought worth connecting, with endpoints and auth hints, under weaker controls than anything it names. Tracks the index across its six copies, shows why traces are the copy that grows (arguments and helpful error strings add observed usage, and Transluce found 6,467 of 37,649 scanner reports carrying agent evidence), prices published discovery as a trade that is only bad when untiered, and ends with the drill: answer the attacker’s question from one of your own artifacts and report the length of the list.',
      '深入解析《配置即侦察》（智能体安全）：侦察曾是一次入侵里最贵、最吵的阶段，而如今智能体部署把答案当成构建产物交付出来——一份经过挑选、保持最新、机器可读的清单，列着你认为值得接上的那些系统，端点与认证线索俱全，而它所受的管控比它点名的任何东西都弱。文章追踪这份索引的六份副本，说明链路记录为何是会长大的那一份（参数与那些「乐于帮忙」的错误字符串会添进被观察到的用法，而 Transluce 在 37,649 份扫描器报告里发现 6,467 份带着智能体证据），把对外发布的发现定价为「只在未分层时才算糟」的一笔交易，并以那场演练收尾：仅凭你自己的某一件工件回答攻击者的那个问题，并把清单的长度报上去。',
    ),
  ],
};

export default entry;
