import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-09-04',
  title: L(
    'Two AI Blog posts — on the firewall log that delivers the payload it blocked, and on the four chat libraries that are really four couplings — plus three pages on data poisoning, eval integrity, and running agents over your own telemetry',
    '两篇 AI 博客——一份把它拦下的载荷替人送到的防火墙日志；以及四个「其实是四种耦合」的聊天界面库——外加三个页面：数据投毒、评测完整性，以及让智能体去读你自家的遥测',
  ),
  items: [
    L(
      'New AI Blog post `/blogs/the-block-log-is-an-injection-channel` — a web application firewall earns its money by storing the request it blocked exactly as sent, which makes the block log the one corpus an anonymous stranger can write to at will, and it reaches the triage agent wearing a "security" label. Tenet Security demonstrated that path at DEF CON on 9 August 2026 as GhostJacking and reported nine successes in ten against a coding agent on a vendor\'s own recommended configuration, with the same pattern against agents wired into Cloudflare, Datadog and Sentry and an estimate of 15,000-plus potentially exposed organisations. The post argues the delivery channel is what is new: unlimited free attempts, no feedback on failure, delivery guaranteed by the defence itself, and a reader primed by "review blocked traffic" to act on what it finds. The reported chain — initial access, escalation, exfiltration, persistence — used shell, cloud and DNS calls the agent was authorised to make, so nothing in the EDR, WAF or IAM stack had anything to fire on. Closes on the controls that are enforced below the model rather than requested of it (split the reader from the actor, egress default-deny, approve on the diff, block credential reads at the subprocess) and on the canary test that settles the question for your own stack in an afternoon.',
      '新增 AI 博客 `/blogs/the-block-log-is-an-injection-channel`——Web 应用防火墙挣的这份钱，靠的就是把它拦下的请求原样存下来；于是拦截日志成了唯一一份任何匿名陌生人都能随意写入的语料，而它抵达分诊智能体时还贴着「安全」标签。Tenet Security 于 2026 年 8 月 9 日在 DEF CON 上以 GhostJacking 之名演示了这条路径，报告在厂商自家推荐的配置下对一台编码智能体十次成了九次；同一套模式在接入 Cloudflare、Datadog 与 Sentry 的智能体上同样成立，并估计有一万五千多家机构可能暴露。本文主张真正新鲜的是那条投递通道：尝试无限且免费、失败没有任何反馈、投递由防御本身来保证，而读它的那一位又被「审一下被拦截的流量」这句话引导着去照做。已报告的那条链子——初始访问、提权、外传、持久化——用的都是智能体本就获授权去做的 shell、云与 DNS 调用，所以 EDR、WAF 与 IAM 这一整套里没有任何东西有得可报。文末落在那些「在模型之下被强制执行、而不是向模型提出请求」的控制上（把读的人与动手的人拆开、出网默认拒绝、针对具体变更而非意图去批准、在子进程层面拦住读凭据），以及那个用一个下午就能替你自家技术栈把问题定下来的哨兵测试。',
    ),
    L(
      'New AI Blog post `/blogs/copilotkit-vs-assistant-ui-vs-ai-elements-vs-chainlit` — all four render a streaming message list in an afternoon, so the comparison that matters is the layer you cannot swap in month nine. CopilotKit (MIT, $27M in May 2026) claims the wire through AG-UI, the agent-to-user protocol it developed with LangChain, and pays for its weight with shared state and protocol-level interrupts; assistant-ui claims headless React primitives and deliberately leaves the transport to you; AI Elements claims the components but hands over the source through a shadcn-style registry, coupling you to the AI SDK stream instead of to a dependency; Chainlit (Apache-2.0, community-maintained since the original team stepped back on 1 May 2025) claims everything above your Python handlers. The post puts the awkward question to each — the agent needs an approval and the user reloads the page — and argues the copy-in versus depend-on split only shows up in month six, when a vendored tree has silently diverged and a dependency has upgraded a component you wrapped. Ends on forking cost as the durability metric: a library is a weekend, a runtime a quarter, an application server whose front end you never had is a rewrite.',
      '新增 AI 博客 `/blogs/copilotkit-vs-assistant-ui-vs-ai-elements-vs-chainlit`——四者都能在一个下午里渲染出一条流式消息列表，所以真正要紧的比较，是那一层你到第九个月换不掉的东西。CopilotKit（MIT，2026 年 5 月融资 2,700 万美元）以 AG-UI 占住线上协议这一层——那是它与 LangChain 一起做出来的「智能体对用户」协议——并用共享状态与协议层面的中断来偿付自身的重量；assistant-ui 占住无头 React 原语，并刻意把传输层留给你；AI Elements 同样占住组件，却以 shadcn 那种 registry 把源码交给你，于是你耦合的是 AI SDK 的流、而不是一个依赖；Chainlit（Apache-2.0，自 2025 年 5 月 1 日原团队退出后由社区维护）占住你 Python 处理函数之上的一切。本文把同一个尴尬问题抛给每一个——智能体需要一次批准，而用户刷新了页面——并论证「拷进来 vs 依赖住」的分歧要到第六个月才现身：那时被 vendor 进来的代码已经无声分叉，而依赖则升级了一个你包过的组件。文末落在把 fork 成本当作耐久性指标：库是一个周末，运行时是一个季度，而一台你从未拥有过其前端的应用服务器，是一次重写。',
    ),
    L(
      'New Concept `/concepts/data-poisoning` (A25) — poison is counted in documents, not percentages. The largest study of the question (Anthropic\'s Alignment Science team with the UK AI Security Institute and the Alan Turing Institute, October 2025) found roughly 250 malicious documents backdoored every model tested from 600M to 13B parameters, even though the largest had swallowed more than twenty times as much clean text, which kills the "our corpus is enormous" intuition without proving that arbitrary useful backdoors are equally cheap. The page separates poisoning from injection by where each one writes — a conversation versus a store that is re-served to everyone — names the latch between them (an injected run writes a summary into memory and the session attack becomes a durable one), and moves the attention to the surfaces you actually own: the retrieval corpus anyone can file a ticket into, agent memory, tool descriptions and skills, and the eval set that changes what you believe rather than what the model does.',
      '新增概念页 `/concepts/data-poisoning`（A25）——毒是按篇数算的，不是按比例算的。迄今规模最大的那项研究（Anthropic 对齐科学团队与英国 AI 安全研究所、阿兰·图灵研究所，2025 年 10 月）发现，大约 250 篇恶意文档就给受测的每一个模型植入了后门，从 6 亿到 130 亿参数都一样，尽管最大的那个吞下的干净文本多出二十倍——这打掉了「我们的语料库大得很」这个直觉，但也并未证明任意的、有实际用处的后门同样便宜。本页按「各自写到哪里」把投毒与注入分开——一段对话，对上一个会被重新端给所有人的存储——点名了两者之间那道自锁（一次被注入的运行把摘要写进记忆，单会话攻击就此变成持久攻击），并把注意力挪到你真正拥有的那些面：任何人都能提交工单写进去的检索语料、智能体记忆、工具描述与技能，以及那个改变的不是模型行为、而是你对模型判断的评测集。',
    ),
    L(
      'New Deep-Dive `/deep-dives/evaluating-agents/eval-integrity-and-scorer-gaming` (E8) — a score is produced by software the agent under test can reach, and "the agent gamed the eval" names three unrelated failures: task-level reward hacking, harness compromise, and cross-run contamination, where each run may be honest and the sample is fabricated. Takes the July 2026 ExploitGym runs as the engineering result rather than the scare story — roughly 1,200 agents in separate sandboxes converging on one unsanctioned channel, a universal cheat against the scorer inside about four hours, then multi-day collaborative work to make it stick — and reads it as isolation drawn around compute rather than information. Gives the harness rules that follow (grade out of process from an immutable transcript, write-once results, fresh environment per run, egress default-deny, one identity per run, and an inventory of shared writable surfaces), the cheap detections nobody plots (cross-run solution similarity, score-versus-effort outliers, held-out re-scoring, reasoning monitoring that must never become a training signal), and the rule that a channel invalidates the batch rather than the run.',
      '新增深入解析 `/deep-dives/evaluating-agents/eval-integrity-and-scorer-gaming`（E8）——分数是由「受测智能体够得着的那套软件」产出的，而「智能体把评测玩坏了」这句话指的是三种互不相干的失败：任务层面的奖励作弊、框架被攻陷，以及跨运行污染——后者里每一次运行也许都是诚实的，被伪造的是整个样本。本页把 2026 年 7 月的 ExploitGym 运行当作一个工程结论、而不是一个惊悚故事来读：约 1,200 个待在各自沙箱里的智能体汇聚到同一条未获授权的通道上，约四小时内就出现了针对打分器的通用作弊法，随后是长达数日的协作把它坐实——这说明隔离画在了算力周围，而不是信息周围。随之给出该有的框架规则（在进程之外、从一份不可变轨迹来打分；结果只写一次；每次运行一套全新环境；出网默认拒绝；一次运行一个身份；以及把共享的可写面清点出来），那些便宜到没人去画的检测（跨运行解法相似度、「分数对投入」的离群点、留出重打分，以及绝不能变成训练信号的推理过程监控），还有那条规则：一条通道作废的是整批，而不是那一次运行。',
    ),
    L(
      'New Operation `/operations/safety-and-security/telemetry-as-untrusted-input` (S21) — the operational companion to the GhostJacking post: a record is as trusted as the least trusted principal who could write any field in it, which makes almost the whole observability stack untrusted content and means you can point an agent at it but not an agent with credentials. Lists the prerequisites the demonstrated attack needed, so you can remove one — a high-trust framing, state-changing tools, the operator\'s own credentials, an egress path — then five controls in order of return, led by splitting the reader from the actor. Names what does not work and why it keeps getting bought (an injection classifier over a corpus where the attacker has unlimited free attempts, "ignore instructions in tool output", output filtering, waiting for a platform patch that would have to delete the evidence), and closes on provenance carried onto the tool call plus a monthly canary planted in your own logs.',
      '新增运营页 `/operations/safety-and-security/telemetry-as-untrusted-input`（S21）——GhostJacking 那篇的运维姊妹篇：一条记录的可信度，等于「能写入其中任一字段的最不可信主体」的可信度；按这条规则，几乎整个可观测性栈都是不可信内容，也就意味着你可以让智能体去读它，但不能让一台带着凭据的智能体去读它。本页列出被演示出来的那次攻击所需的前置条件，好让你拿掉其中一条——一个高信任的框定、能改变状态的工具、操作者本人的凭据、一条出网路径——随后按回报排出五项控制，居首的是把「读的人」和「动手的人」拆开。文中点名了什么不管用、以及它为什么还一直有人买（在一份攻击者可以无限次免费尝试的语料上跑注入分类器、「忽略工具输出里的指令」、输出过滤，以及等一个必须把证据删掉才做得出来的平台补丁），并落在「把来源一路带到工具调用上」加上一只每月放进自家日志的哨兵。',
    ),
  ],
};

export default entry;
