import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-08-12',
  title: L(
    'Two AI Blog posts on what the four managed agent runtimes are really selling and on the enterprise agent pullback being a measurement failure, plus four pages on managed runtimes, leaving one, scaling back a deployment and cost UX',
    '两篇 AI 博客——四家托管智能体运行时真正在卖的是什么，以及企业收缩智能体其实是一次测量失败——外加四个页面：托管运行时、如何退出、收缩部署，以及成本交互设计',
  ),
  items: [
    L(
      'New blog post — *AgentCore vs Foundry vs Vertex AI Agent Engine vs Cloudflare Agents: Nobody Is Selling You the Loop*. Where a per-vCPU-hour rate is published at all the market has converged — AgentCore at $0.0895 against Vertex AI Agent Engine at $0.0864, a 3.6% gap, both billing active CPU only rather than time blocked on model calls — while Foundry charges nothing for running an agent and Cloudflare folds it into Workers. Argues the differentiation is entirely in conversation state: Foundry\'s Standard setup puts threads in your own Cosmos DB for NoSQL, Cloudflare gives each agent instance a Durable Object with its own SQLite, AgentCore keeps a managed but separately callable Memory primitive, and Vertex meters Sessions and Memory Bank at $0.25 per 1,000 events plus $0.30/GiB-month storage — the only one of the four that charges per write, which quietly shapes your memory policy. Reads AWS closing Bedrock Agents Classic to new customers on 30 July 2026 while shipping AgentCore Harness on 17 June 2026 as proof that config-defined loops did not lose; bundles did. Three themeable SVGs.',
      '新博客文章——《AgentCore vs Foundry vs Vertex AI Agent Engine vs Cloudflare Agents：没人是在把那个循环卖给你》。凡是公布了每 vCPU 小时费率的地方，市场都已收敛——AgentCore $0.0895 对 Vertex AI Agent Engine $0.0864，相差 3.6%，且两家都只按活跃 CPU 计费、而非阻塞在模型调用上的时间——而 Foundry 对运行智能体不收费，Cloudflare 把它折进了 Workers。文章论证：差异化完全在对话状态上——Foundry 的 Standard 配置把线程放进你自己的 Cosmos DB for NoSQL；Cloudflare 给每个智能体实例一个自带 SQLite 的 Durable Object；AgentCore 的 Memory 虽是托管的，却可以单独调用；而 Vertex 对 Sessions 与 Memory Bank 按每 1,000 条事件 $0.25 计费、外加每 GiB 月 $0.30 的存储——它是四家里唯一按写入收费的，这会悄悄塑造你的记忆策略。文章把"AWS 于 2026 年 7 月 30 日把 Bedrock Agents Classic 对新客户关闭，却在 2026 年 6 月 17 日发布 AgentCore Harness"读作一个证明：输的不是以配置定义的循环，输的是捆绑。配三张可随主题变色的 SVG。',
    ),
    L(
      'New blog post — *Half of Enterprises Scaled Back Their Agents. Seven Percent Can Compute the Ratio.* KPMG\'s Q2 2026 Global AI Pulse (2,145 senior leaders, 20 countries, organisations above $50M revenue) found 49% had scaled back, narrowed, delayed or paused an agent deployment after expected costs began to outweigh anticipated value, while only 26% have full real-time visibility into what AI costs to run and only 7% report established ROI. Argues the pullback is asymmetric measurement rather than a verdict on agents: the vendor meters cost because it needs to bill you, nobody meters value, so the only signal that arrives unbidden is the one on the cost side and the only actuator wired up is the one that turns things off. Names the pre-agent baseline — volume, measured human time per unit, the incumbent process\'s own error rate, and the existing tail — as the measurement you cannot add later, and steelmans the cases where pausing is correct. Three SVGs including a four-rung control-granularity ladder.',
      '新博客文章——《一半的企业收缩了自己的智能体。只有 7% 算得出那个比值。》KPMG 2026 年第二季度 Global AI Pulse（20 个国家、年收入 5,000 万美元以上组织的 2,145 位高管）发现，49% 曾在预期成本开始盖过预期价值后收缩、收窄、推迟或暂停过智能体部署，而只有 26% 对 AI 的运行成本拥有完整实时可见性、只有 7% 有已确立的 ROI。文章论证：这次收缩是一次不对称的测量，而不是对智能体的判决——厂商计量成本是因为它得向你收钱，而没有人计量价值，于是唯一不请自来的信号在成本那一侧，唯一接上线的执行机构是那个把东西关掉的。文章把"智能体进场前的基线"——数量、量出来的每单位人工时间、在位流程自身的出错率，以及既有的长尾——点名为那项事后补不上的测量，并为"暂停是对的"那些情形做了正面辩护。配三张 SVG，含一张四级控制颗粒度阶梯图。',
    ),
    L(
      'New Concept (AI Ecosystem) — *Managed Agent Runtimes*. Defines the layer that sits between an agent framework and an inference provider, and decomposes it into five primitives — compute, the orchestration loop, the tool gateway, the identity broker and conversation state — sorted by how hard each is to walk away from. Argues that four of the five are a sprint and the fifth is a migration project whose size is set by how long you waited, so bundling rather than managed-ness is the lock-in. Gives the single test that separates a rentable runtime from a trap: if the loop product were frozen tomorrow, what would you still hold? Closes on what a frozen model catalog does — the practical deadline is not the shutdown notice but the day the model you want is one the service cannot give you.',
      '新增概念页（AI 生态）——《托管智能体运行时》。定义了夹在智能体框架与推理提供方之间的那一层，并把它拆成五个原语——算力、编排循环、工具网关、身份代理与对话状态——按"离开有多难"排序。文章论证：五者中有四个是一个迭代周期的事，第五个是一个迁移项目，其规模由你拖了多久决定；因此锁定来自捆绑，而不是"托管"这件事本身。文中给出把"可租的运行时"与"陷阱"区分开的那一个检验：如果循环产品明天被冻结，你手里还剩什么？全文以"模型目录冻结意味着什么"收尾——真正的期限不是停服通知，而是你想用的那个模型成了这个服务给不了你的那一天。',
    ),
    L(
      'New Operation (AgentOps) — *Exiting a Managed Agent Runtime*. Maintenance mode promises that existing workloads keep running, which is precisely what makes teams wait; the page lists the four expiries that actually bind — model, compliance, dependency, announced shutdown — and insists you put a date on the nearest. Inventories the four assets living inside the vendor boundary (conversation state, identity bindings, trace history, gateway configuration) and flags trace history as the one nobody assigns an owner to and the one carrying a retention obligation that does not care you changed vendors. Inverts the usual order: the loop is fixed-cost and small, state grows while you work, so prove the export on a sample as a go/no-go, start dual-writing, and only then port code against a backlog that has stopped growing. Adds session-boundary cutover, and the case for staying — which must be a written decision with dates, not a default.',
      '新增运维页（AgentOps）——《退出一个托管智能体运行时》。维护模式承诺既有负载继续运行，而这恰恰是让团队一等再等的原因；本页列出真正会约束你的四个到期日——模型、合规、依赖、已宣布的停服——并坚持要你给最近的那个定一个日期。文中清点了住在厂商边界内的四类资产（对话状态、身份绑定、轨迹历史、网关配置），并把轨迹历史标记为"没人认领负责人"的那一个，也是背着保留义务、而这份义务并不在乎你换了厂商的那一个。文章把惯常次序倒了过来：循环成本固定且很小，状态却在你干活期间不断长大，所以先在样本上把导出验证成一个"走还是不走"的决策点、开双写，然后才在一个已停止增长的积压面前去搬代码。此外还有按会话边界切换，以及"留下"的正当理由——那必须是一个带日期的书面决定，而不是一种默认。',
    ),
    L(
      'New Operation (Economics &amp; ROI) — *Scaling Back an Agent Deployment*. "Scaled back, narrowed, delayed or paused" is four names for one blunt instrument, and the granularity of your response is set by the granularity of your data. Works a three-workflow portfolio where ticket triage clears its manual baseline by 55× while document reconciliation loses money at $4.10 against $1.80 — a blended figure that says the deployment works and hides everything — and shows that cutting the one losing class beats an across-the-board reduction on both cost and value. Insists on carving out the tail before condemning a class (a class at $4.10 mean can be $0.90 median and $38 at p99), ranks the four responses from retune to pause, and prices the hidden bill of a pause: the baseline dies, the re-ramp is not free, and the production signal that would have told you which class was salvageable stops.',
      '新增运维页（经济与 ROI）——《收缩一次智能体部署》。"收缩、收窄、推迟或暂停"是同一件钝器的四个名字，而你反应的颗粒度由你数据的颗粒度决定。文中演算了一个三工作流的组合：工单分诊把人工基线甩开 55 倍，而单据核对以 $4.10 对 $1.80 在亏钱——那个混合后的数字说部署是好的，却把一切都藏了起来——并表明砍掉那一个亏损的类，在成本与价值两侧都胜过一刀切的削减。文章坚持在给一个类定罪之前先切出长尾（均值 $4.10 的类，中位数可能是 $0.90 而 p99 是 $38），把四种反应从"重新调优"排到"暂停"，并给暂停的隐形账单标了价：基线死了、重启不免费，而那个本来能告诉你哪个类还有救的生产信号停了。',
    ),
    L(
      'New Playbook (Agent UX &amp; Human Interaction) — *Cost &amp; Quota UX*. Nobody budgets in tokens, and the surface most teams ship next — a live dollar counter with no control attached — is anxiety with a number on it. Separates the three moments (estimate for consent, meter for control, receipt for calibration) and argues the receipt is the one to build first, since an estimate nobody has seen reconciled is an estimate users have learned to ignore. Requires a band rather than a point on a heavy-tailed distribution with the top of the band enforced as a real cap, and a reachable control on every live meter — stop-and-keep, downshift, or approve-to-continue. Closes on the metric: optimising the surface to reduce spend throttles the 55× workflow alongside the losing one, because the user can see cost and cannot see value, so measure estimate-to-actual calibration instead.',
      '新增实战手册（智能体 UX 与人机交互）——《成本与额度的交互设计》。没人拿 token 做预算，而多数团队接着会发的那个界面——一个不带控制件的实时金额计数器——只是一份带数字的焦虑。文章把三个时刻分开（估价用于取得同意、仪表用于控制、账单用于校准），并主张先造那份账单，因为一个从没被对过账的估价，就是一个用户已经学会忽略的估价。文中要求在重尾分布上给区间而不是给点，并把区间顶端作为真实上限强制执行；也要求每一块实时仪表都接上一个够得到的控制件——停下并保留、降档，或批准后继续。全文以指标收尾：以"降低开销"为目标去优化这个界面，会把回报 55 倍的工作流连同亏钱的那条一起掐住，因为用户看得见成本、看不见价值——所以该量的是估价与实际之间的校准度。',
    ),
  ],
};

export default entry;
