import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-09-14',
  title: L(
    'Two AI Blog posts — on the coordinator agent that opens pull requests nobody asked for, and on the four cloud coding agents whose meters each break in a different way — plus three pages on asking, ambient clinical notes, and the trace store that stops a rollout',
    '两篇 AI 博客——一篇关于那个开出无人索求的 PR 的协调者智能体，一篇关于那四个云端编码智能体、它们各自以不同方式失灵的计费表——外加三个页面：该不该问、环境式病历，以及那个能拦下一次铺开的 trace 存储',
  ),
  items: [
    L(
      'AI Blog — “The coordinator is the requester now — and nobody scoped the grant”: Cursor put Projects into beta on 10 September, a coordinator agent that plans, delegates to thousands of subagents, and — the part worth arguing about — watches a Slack channel, a schedule or all your PRs and acts without waiting for a prompt. The fan-out is visible; the invisible change is that a pull request now arrives with no human who asked for it, and every control the field has built (approval by consequence, audit trails, delegated-access records) assumes a request exists. A trigger list is a standing grant with no scope, no expiry and no named principal, stored in a settings pane. The arithmetic is unforgiving too: Cursor’s own design-system project is on track to touch 20 to 100 PRs a day, which at twenty minutes of genuine review each is four full-time reviewers doing nothing else — so review the plan before the fan-out, and give every standing trigger an expiry.',
      'AI 博客《如今提出需求的是那个协调者——而没人给这份授权划过范围》：Cursor 于 9 月 10 日把 Projects 放入公测——一个会做规划、把活派给成千上万个子智能体的协调者，而真正值得争论的那部分是：它会盯着一个 Slack 频道、一份日程表、或你所有的 PR，不等提示就动手。扇出是看得见的；看不见的那处变化是，一个 PR 送达时背后没有任何一个提出它的人，而这个领域建起来的每一道控制（按后果设审批、审计轨迹、委派访问记录）都假定「存在一个请求」。一份触发器清单，是一份没有范围、没有到期、也没有具名主体的长期授权，被存在一个设置面板里。算术也毫不留情：Cursor 自家的设计系统项目正朝着每天触及 20 到 100 个 PR 走，而按每个 PR 二十分钟的认真评审计，那是四个全职评审者什么别的都不做——所以要在扇出之前评审计划，并给每一个长期触发器一个到期日。',
    ),
    L(
      'AI Blog — “Cursor Projects vs Codex cloud vs Claude Code on the web vs Jules: buy the meter”: four cloud coding agents that look interchangeable on a feature table bill in four different shapes, and each shape induces a specific misuse — a usage pool with arrears billing is a speed bump rather than a cap and lets fan-out run without a ceiling; one allowance shared across web, CLI, IDE and chat means Monday’s background batches eat the budget you wanted for Tuesday’s hard bug; Jules’ hard task counts are the only genuinely predictable cap and they push you to over-stuff a task until the diff is unreviewable; and Devin’s ACUs, billed by wall-clock of autonomous work, charge most for the runs that are going worst. Cursor alone changed how it charges three times in 2026, so every published plan table is already stale — the durable axes are the meter’s shape and the sandbox boundary, which is identical everywhere and excludes your local files, your dev server, your local MCP servers and your private network.',
      'AI 博客《Cursor Projects、Codex cloud、Claude Code on the web 与 Jules：该买的是那块表》：四个在功能表上看似可以互换的云端编码智能体，计费形状有四种，而每一种都诱发一种具体的误用——事后结算的用量池是减速带而不是上限，让扇出跑得没有天花板；一份被 web、CLI、IDE 与聊天共用的额度，意味着周一的后台批量会吃掉你留给周二那个硬 bug 的预算；Jules 给死的任务次数是这里唯一真正可预测的上限，而它推着你把任务塞到 diff 没法评审为止；Devin 的 ACU 按自主工作的挂钟时间计费，于是跑得最糟的那些运行收你最多。光是 2026 年，仅 Cursor 一家就改过三次收费方式，所以已发表的方案表统统已经过期——耐久的轴是那块表的形状，和那条到处都一样的沙箱边界：它把你的本地文件、开发服务器、本地 MCP 服务端与私有网络全部排除在外。',
    ),
    L(
      'Concepts — Clarifying Questions: the agent that asks whenever it is unsure is the one people stop delegating to, because a question spends a human’s attention to buy certainty a tool call could usually have bought — and the same question costs seconds interactively and hours in a background run. Confidence is the wrong trigger; gate on two tests instead, whether the ambiguity would change the work and whether the wrong branch is expensive to undo. The large reversible-but-load-bearing middle should get a stated assumption placed where the result is read, and the numbers to watch are rework caused by unstated assumptions and runs abandoned at a question, never clarification rate.',
      '概念 — 澄清式提问：一拿不准就发问的智能体，正是人们逐渐不再托付的那个——一次提问要花掉人的注意力，去买一份一次工具调用通常就能买到的确定性；而同一个问题，在交互式里代价是几秒，在后台运行里是几小时。置信度是错误的触发器；改用两道判断设闸门：这处歧义会不会改变要做的事，以及走错的那条岔路是不是难以撤回。「可撤回但承重」这个很大的中间地带，该得到一个写在结果被阅读之处的假设；而要盯的数字是「由未言明的假设引发的返工」与「在一个问题前被放弃的运行」，绝不是澄清提问率。',
    ),
    L(
      'Playbooks — Ambient Clinical Documentation Agents: the headline JAMA Network Open result moved burnout from 51.9% to 38.8% and did not measure documentation quality at all, so time-to-signature — the metric every dashboard ships — is maximised by a clinician who signs without reading. Design backwards from the signature as an authorship transfer: make review faster than writing, refuse bulk-sign, enforce provenance tiers so a physical-exam finding appears only if it was said aloud, and surface omissions explicitly because “hallucination by simplification” is the error review cannot catch. Keep code assignment out of the scribe (a richer note supports a higher E/M level, and an optimiser finds that direction), decide audio retention before the first subpoena, and fund the weekly adjudicated sample that is the only number measuring the note.',
      '实战手册 — 环境式临床病历智能体：那个被反复引用的 JAMA Network Open 结果把倦怠从 51.9% 降到 38.8%，而它压根没测量病历质量；于是每块看板自带的「签署耗时」，其最大化解法是让医生不读就签。从「签署是一次著作权转移」倒着设计：让复核比书写更快、拒绝批量签署、强制来源层级以使体格检查所见只有被说出口才允许出现，并把遗漏显式摆出来——因为「简化型幻觉」正是复核抓不住的那种错。把编码归属挡在病历助手之外（更丰满的病历能支撑更高的 E/M 等级，而优化器会找到那个方向），在收到第一张传票之前就定好音频留存，并给每周那次经裁定的抽样拨预算：它是唯一一个量病历本身的数字。',
    ),
    L(
      'Operations — Worker Consultation &amp; Co-Determination: German co-determination attaches to a system objectively suitable for recording behaviour or performance, and the employer’s intent never to look is legally irrelevant — so the per-user trace store you built for debugging, not the agent, is what can stop a workplace rollout, and courts have rejected the “its primary purpose was something else” defence. Separate the EU AI Act’s one-directional duty to inform workers’ representatives before use (Article 26(7); deployer duties for standalone Annex III systems from 2 December 2027) from the bilateral duty to agree, bring your own versioned system description rather than inheriting someone else’s defensive draft, and design for a yes: aggregate by default, pseudonymise at write time, shorten retention, and make the prohibition demonstrable as a view with no individual dimension rather than promised in a meeting.',
      '运维 — 职工协商与共同决定：德国的共同决定权附着于「客观上适合记录行为或绩效」的系统，而雇主打算永不去看这一点在法律上无关紧要——于是能拦下一次工作场所铺开的，是你为调试而建的那套按用户归属的 trace 存储，不是那个智能体；而法院驳回过「它的主要目的是别的」这类抗辩。把欧盟《AI 法案》那项「使用前告知职工代表」的单向义务（第 26 条第 7 款；独立的附件三系统之部署者义务自 2027 年 12 月 2 日起适用），与「须达成合意」的双向义务分开；自带一份带版本的系统描述，而不是继承别人出于防御心态写的草案；并按「让对方能说好」来设计：默认聚合、写入时假名化、缩短留存，并把禁令做成一个不含个人维度的视图来展示，而不是在会上口头承诺。',
    ),
  ],
};

export default entry;
