import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-08-14',
  title: L(
    'Two AI Blog posts on the two agentic numbers Meta’s open-weights model shipped with and on where the four agent-payment protocols store the spending cap, plus four pages on task horizon, on-device agent architecture, travel booking and scheduled agents',
    '两篇 AI 博客——Meta 开放权重模型交出的那两个"智能体"分数，以及四套智能体支付协议各把支出上限存在哪里——外加四个页面：任务时长视野、端侧智能体架构、旅行预订，以及定时智能体',
  ),
  items: [
    L(
      'New blog post — *Muse Glimmer Ships Two Agentic Numbers, and the Wrong One Is in the Headline*. Meta Superintelligence Labs released a 30B Apache-2.0 agent model distilled from a larger Muse system — a 2B ViT-style encoder feeding a 28B decoder, 128K context, roughly 4-bit with block-level speculative decoding, one consumer GPU. It reports 94.7 on AIME 2026, 76.0 on SWE-Bench Verified, 75.5 on MCP-Atlas, 74.6 on DeepSearch QA, 51.2 on SWE-Bench Pro — and 24% on τ³-Banking. Argues five of those six measure the same structure (a model alone against a machine-checkable goal) and only the sixth puts a simulated user and a policy manual in the loop, which is the axis an always-on local assistant lives on; notes the class result, with Gemini 3.5 Flash-Lite at 18% and Qwen3.6 27B at 17%, so the gap is small-model policy adherence rather than one vendor cutting a corner. Reads the 4-bit and speculative-decoding choices as a bet that per-step latency, not quality, is the binding constraint in a loop. Three themeable SVGs.',
      '新博客文章——《Muse Glimmer 交出了两个"智能体"分数，而上标题的是错的那个》。Meta Superintelligence Labs 发布了一个 300 亿参数、Apache 2.0 许可、从更大的 Muse 系统蒸馏而来的智能体模型——20 亿参数 ViT 式编码器接 280 亿参数解码器，128K 上下文，约 4 bit 量化外加块级投机解码，单张消费级 GPU 即可运行。它在 AIME 2026 上报 94.7，SWE-Bench Verified 76.0，MCP-Atlas 75.5，DeepSearch QA 74.6，SWE-Bench Pro 51.2——而 τ³-Banking 只有 24%。文章论证：这六项里有五项测的是同一种结构（模型独自面对一个可被程序核验的目标），只有第六项把一位模拟用户与一本规程手册放进了循环，而常驻本地助手活的正是这条轴；并指出这是整档模型的结果——Gemini 3.5 Flash-Lite 为 18%，Qwen3.6 27B 为 17%——所以这道落差是小模型的政策遵从问题，而不是某一家偷了工。文章还把 4 bit 与投机解码这两个选择读作一次押注：在循环里卡住你的是每一步的时延，不是质量。配三张可随主题变色的 SVG。',
    ),
    L(
      'New blog post — *x402 vs AP2 vs ACP vs MPP: The Only Difference That Changes Your Risk*. Places the four standards on the layers they actually occupy — AP2 authorises with Intent/Cart/Payment mandates signed as W3C Verifiable Credentials, ACP checks out with a Shared Payment Token scoped to one cart, x402 and MPP settle — and argues the comparison worth making is where the spending cap is stored: a pre-funded wallet balance, the issuer’s authorization rules, a single-use token, or a signature the user gave. Separates enforcement (someone independent refuses in flight) from evidence (someone proves afterwards what was authorised), notes that no single protocol supplies both, and reads Cloudflare Wallets — an Account Wallet funding capped Virtual Wallets over x402 — as the enforcement layer being rebuilt at the infrastructure vendor because the protocol deliberately omits one. Three SVGs.',
      '新博客文章——《x402、AP2、ACP、MPP：唯一会改变你风险的那个差别》。文章把四套标准放回它们实际所在的层——AP2 用以 W3C 可验证凭证签名的 Intent/Cart/Payment 授权书做授权，ACP 用只作用于一个购物车的共享支付令牌做结账，x402 与 MPP 做清算——并论证值得做的比较是"支出上限存放在哪里"：一个预充值的钱包余额、发卡机构的授权规则、一枚一次性令牌，还是用户给出的一个签名。文中把"执行"（某个独立方能在途中拒绝）与"证据"（某人能在事后证明当初授权了什么）分开，指出没有任何单一协议两样都给，并把 Cloudflare Wallets——用一个 Account Wallet 为若干带上限的 Virtual Wallets 充值、经 x402 清算——读作执行层因协议刻意不带而在基础设施厂商这边被重造了一遍。配三张 SVG。',
    ),
    L(
      'New Concept (Agentic AI) — *Task Horizon*. Defines the one capability figure stated in a unit you can plan with: the length of job, in human working time, that an agent completes on its own at a stated success rate. Traces the trend — the frontier’s 50%-success horizon doubling roughly every seven months across six years, with recent re-estimates nearer four — and then makes the point the retelling drops: the headline is a coin flip, and METR’s own reporting puts the 80% horizon at roughly one fifth of the 50% figure, so a fifty-minute model is a ten-minute model if you need four runs in five. Explains why the published trend transfers badly (clean start states, machine-checkable finishes, no second party) and gives a half-day in-house method — thirty real tasks, five runs each, read off the 80% crossing — plus the three policies it should set: unattended work sized below the horizon, autonomy level by task length, and re-measurement when the environment drifts rather than only when the model changes.',
      '新增概念页（智能体 AI）——《任务时长视野》。定义了唯一一个用"你能拿来做计划的单位"表述的能力数字：以人类工时衡量、智能体在指定成功率下能独立完成的任务长度。文章梳理了那条趋势——前沿模型 50% 成功率下的视野在六年里大致每七个月翻一番，较新的重新估计接近四个月——然后点出转述中总被丢掉的那一层：头条数字是一次抛硬币，而 METR 自己的报告把 80% 视野放在 50% 那个数字的大约五分之一，于是一个五十分钟的模型，若你需要五次里成四次，就是一个十分钟的模型。文章解释了公开趋势为何迁移得很差（干净的起始状态、机器可核验的终点、没有第二方），并给出一套半天就能做完的自测方法——三十件真实任务、每件跑五遍、读出 80% 的交点——外加它该去定的三条政策：把无人值守的工作切到视野以下、按任务长度设自主性等级，以及环境漂移时（而不只是模型变更时）重新测量。',
    ),
    L(
      'New Deep-Dive (Architectures & Patterns) — *On-Device Agent Architecture*. Local inference buys three real things — marginal cost at zero, no network inside the inner loop, and offline operation — and not the fourth it is always sold as, because the tools still egress. Decomposes the loop five ways (model, index, tool execution, policy checks, session state) and shows only one of those rows is a privacy row and it is not the model. Covers the device-specific latency regime: speculative decoding wins on an idle personal GPU and loses on a busy shared one, prefill is unpaid-for without provider prefix caching and no local runtime keeps a KV cache across an application restart, and dense beats mixture-of-experts when the card is yours. Argues the escalation gate should be a static list of action properties — irreversible, policy-bound, third-party-visible — rather than a learned difficulty estimate, and closes on the operational half: permanent version skew, rollback measured in app releases, consent-gated traces, per-hardware-class evaluation, and a kill switch the client must consult server-side.',
      '新增深入解析（架构与模式）——《端侧智能体架构》。本地推理能换来三样真东西——边际成本归零、内层循环无网络、离线可用——却换不来它一直被当作卖点的第四样，因为工具照样出网。文章把循环拆成五份（模型、索引、工具执行、策略检查、会话状态），并指出其中只有一行是隐私那一行，而它不是模型。文中覆盖了设备特有的时延情形：投机解码在空闲的个人 GPU 上赢、在繁忙的共享 GPU 上输；没有服务商前缀缓存时预填充要自己全付，而且没有任何本地运行时能跨应用重启保住 KV 缓存；卡是你自己的时候，稠密胜过专家混合。文章论证升级闸门应当是一张按动作属性列出的静态清单——不可逆、受规程约束、会被第三方看到——而不是一个学出来的难度估计器，并以运维那一半收尾：永久性的版本歪斜、以应用发版计的回滚、受同意约束的追踪、按硬件档位分别评测，以及一个客户端必须去查服务端取值的紧急开关。',
    ),
    L(
      'New Playbook (Domain Playbooks) — *Travel & Booking Agents*. Everything before the booking is free and repeatable; the booking is a payment, a contract and a seat someone else loses — so the two halves are different systems. Names the failure other domains do not have: the price the user approved is a photograph, and three things go stale independently (price, availability, and the fare conditions that produce a complaint six weeks later). Prescribes binding every approval to a quote object with an ID and an expiry, re-pricing at commit, and failing rather than adapting on any delta outside a numeric tolerance held in code. Makes the booking tool the one place where agent defaults invert — idempotency key derived from the quote, reconcile instead of retry, terse terminal errors, spend cap enforced outside the loop, single writer — and buys back reversibility where the market sells it, including the US DOT 24-hour rule. Argues autonomy should go up, not down, during disruption, inside an envelope pre-authorised at booking time, and closes on measuring duplicates, expired-quote commits and silent substitutions as incidents rather than percentages.',
      '新增实战手册（领域实战手册）——《旅行与预订智能体》。下单之前的一切都免费、可重复；下单则是一笔支付、一份合同，外加一个别人再也拿不到的座位——所以这两半是两套系统。文章点出其他领域没有的那种失效：用户批准的那个价格是一张照片，而会过期的有三样彼此独立的东西（价格、可用性，以及那个六周后才变成投诉的票价条件）。处方是把每一次批准绑定到一个带 ID 与有效期的报价对象上、在提交时重新计价，并对任何超出代码中数值容差的差额直接失败而不是自适应。文中把下单工具定为"智能体默认值全部反转"的唯一场所——由报价派生的幂等键、用对账代替重试、简短的终止性错误、在循环之外强制的支出上限、单写者——并在市场愿意卖可逆性的地方把它买回来，包括美国交通部的 24 小时规则。文章论证中断恢复期间自主性该往上调而不是往下调，前提是待在一个下单时就预先授权好的信封之内，并以"把重复预订、过期报价提交与静默替换当成事故而不是百分比来度量"作结。',
    ),
    L(
      'New Operation (AgentOps) — *Scheduled & Triggered Agents*. Remove the user and three defaults invert: ask becomes abstain, retry becomes reconcile, and reporting becomes rationing — while the defining property is that a scheduled agent fails silently, because a broken nightly run and a healthy quiet night both produce nothing. Treats trigger semantics as design decisions rather than config: skip rather than queue on overlap, no catch-up backfill by default, at-least-once delivery meaning keyed side effects, and jitter so every schedule does not hit the provider at the top of the hour. Makes the notification decision explicit — a structured acted / no-op / blocked verdict per firing, notify on transitions, collapse consecutive no-ops, and rate-limit the channel independently of the agent’s judgement, because the muted channel is a failure your monitoring will not report. Adds a per-firing cap on external write actions and a rolling daily spend cap, and inverts the monitoring: a dead-man’s switch on every schedule, traces for the no-ops, the no-op ratio as a quality metric, and a registry with an owner and an expiry.',
      '新增运维页（AgentOps）——《定时与事件触发的智能体》。把用户拿走，三条默认值就会翻转："问"变成"弃权"，"重试"变成"对账"，"汇报"变成"配给"——而那个定义性的性质是：定时智能体是静默失败的，因为一次坏掉的夜间运行和一个健康的安静夜晚，产出的都是"什么都没有"。文章把触发语义当作设计决策而非配置项：重叠时跳过而不是排队、默认不做补跑、至少一次投递意味着副作用必须带键，以及用抖动避免每条排程都在整点砸向服务商。文中把"要不要通知"做成显式决定——每次触发给出一个结构化的"动了/无事/卡住"判定、按状态转移通知、合并连续的无事，并独立于智能体自身判断给频道限流，因为"频道被静音"是一种你的监控不会报告的失效。文章还加上每次触发的对外写动作上限与跨触发的滚动日支出上限，并把监控反过来做：给每条排程装守尸开关、给无事也留追踪、把无事比例当作质量指标，以及一份带负责人与到期日的登记册。',
    ),
  ],
};

export default entry;
