import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-08-18',
  title: L(
    'Two AI Blog posts on the browser becoming cheap enough to throw away and on why memory benchmarks cannot arbitrate a memory purchase, plus three pages on automatic prompt optimization, retrieval inside the voice turn and erasure against agent memory',
    '两篇 AI 博客——浏览器已经便宜到可以用完就扔，以及为什么记忆基准分无法为一次记忆采购做裁决——外加三个页面：自动提示词优化、把检索塞进语音轮次，以及针对智能体记忆的删除请求',
  ),
  items: [
    L(
      'New blog post — *Cloudflare’s Kitesurf Makes a Browser Cheap Enough to Throw Away*. Kitesurf runs a from-parts engine (Blitz layout, Stylo CSS, Parley text shaping) inside Workers V8 isolates rather than Chromium in a container, at 3–7× less CPU and memory and about 1.7× slower wall time, passing 215,000+ Web Platform Tests at roughly 97% of DOM subtests, speaking CDP so Playwright and MCP clients connect unchanged. Argues the quoted resource number matters for what it bills rather than what it saves: a container is rented and an isolate is metered, so the amortisation that forces warm pools and reused sessions disappears — and reused sessions are where cookies, injected page state and cross-tenant bleed live. Sets against that a compatibility tail that per-subtest conformance does not predict and that fails silently, since a half-hydrated DOM returns no error and the agent acts on it anyway. Closes on building a per-target compatibility harness before migrating, routing by target rather than preference, and the general principle that the cost of a fresh execution context is a security parameter. Three themeable SVGs.',
      '新博客文章——《Cloudflare 的 Kitesurf 让浏览器便宜到可以用完就扔》。Kitesurf 把一台用零件拼出来的引擎（Blitz 布局、Stylo CSS、Parley 文本排版）跑在 Workers 的 V8 isolate 里，而不是把 Chromium 跑在容器里：CPU 与内存少 3–7 倍、墙钟时间慢约 1.7 倍，通过 215,000+ 项 Web Platform Tests、DOM 子测试约 97%，并且讲 CDP，所以 Playwright 与 MCP 客户端无需改动即可接入。文章论证：被引用的那个资源数字，重要之处在于它计什么费，而不在于它省了多少——容器是租的，isolate 是按表计的，于是那套逼出热池与会话复用的摊销逻辑就消失了；而会话复用正是 cookie、被注入的页面状态与跨租户渗漏的所在。与之相对的是一条兼容性长尾：逐项子测试的合规度预测不了它，而它会静默失败——一个只 hydrate 了一半的 DOM 不会报任何错，智能体照样据以动手。文末落在"迁移之前先搭好按目标的兼容性测试台"、"按目标而不是按偏好做路由"，以及那条一般性原则：启动一个全新执行上下文的成本是一个安全参数。配三张可随主题变色的 SVG。',
    ),
    L(
      'New blog post — *Mem0 vs Zep vs Letta vs LangMem: The Memory Benchmark Is Not the Buying Decision*. The same product has been reported at 49.0% (in a competitor’s comparison) and at 94.4% (in its own) on a benchmark with the same name, a spread wider than the gap between any two of the four — because in this category the vendor is the harness. Sorts the four by who owns the write path: Mem0 extracts and promotes facts across conversation/session/user/organisation scopes, Zep’s Graphiti resolves entities into a temporal graph whose edges carry validity intervals, Letta is an agent runtime where the model edits its own labelled memory blocks with sleep-time agents consolidating off the critical path, and LangMem hands you primitives over the LangGraph store and no policy. Argues the two axes that survive adoption are invalidation — only Zep dates a changed fact — and deletion, where Zep’s historical edges, Letta’s shared blocks and Mem0’s scope promotion each break a per-subject boundary. Closes on running the same three-part evaluation on your own transcripts, including one synthetic person you ask each system to forget. Three SVGs.',
      '新博客文章——《Mem0、Zep、Letta 与 LangMem：记忆基准分不是那个采购决策》。同一个产品，在名字相同的基准上被报出过 49.0%（出自竞品的对比）与 94.4%（出自它自己），这个跨度比这四者中任意两个之间的差距都大——因为在这个品类里，厂商就是那层外壳。文章按"谁拥有写入路径"来梳理四者：Mem0 抽取事实并在对话／会话／用户／组织作用域之间提升，Zep 的 Graphiti 把实体消解进一张时序图谱、边上带有效区间，Letta 是一个由模型自己编辑带标签记忆块的智能体运行时、并由睡眠期智能体在关键路径之外做整合，而 LangMem 在 LangGraph store 之上把原语交给你、不给策略。文章论证：采用之后仍然成立的两条轴是失效——只有 Zep 给变更过的事实标日期——与删除，而 Zep 保留的历史边、Letta 的共享块、Mem0 的作用域提升，各自都会打破一条按当事人划分的边界。文末落在"用你自己的对话记录跑同一套三段式评测"，其中包括一个你要求每个系统去忘掉的合成的人。配三张 SVG。',
    ),
    L(
      'New Concept (Building Blocks) — *Automatic Prompt Optimization*. A prompt is the last unfitted parameter in a model pipeline: weights are trained, retrieval thresholds are tuned on a validation set, and the component with the largest effect on quality is written by a person and judged on a sample of about three. Covers the three optimizer families that ship — bootstrapped example selection, instruction search, and reflective feedback-driven mutation of the DSPy/GEPA kind — and argues the optimizer is the cheap part: without a held-out split you are memorising, a weak LLM judge gets gamed faster than a weak prompt, and an objective with no token term will happily quadruple your per-call input forever. Closes on treating the winning prompt as a build artifact — versioned with the model ID and dataset hash, re-fitted on every model change, never hand-edited — and on the rule that the dataset is the asset while the optimizer is a script that runs against it.',
      '新增概念页（基础构件）——《自动提示词优化》。提示词是模型流水线里最后一个没被拟合的参数：权重是训练的，检索阈值是在验证集上调的，而对质量影响最大的那个部件由人写下、并在大约三个样本上被判定。文章讲了实际落地的三个优化器流派——自举式示例挑选、指令搜索，以及 DSPy/GEPA 那一类带反思的反馈驱动变异——并论证优化器才是便宜的那部分：没有留出划分你就是在背题，一个弱的 LLM 评判者比一个弱的提示词更快被钻空子，而一个目标函数里不含令牌项，就会欣然把你每次调用的输入永久地翻上四倍。文末落在"把胜出的提示词当作构建产物"——连同模型 ID 与数据集哈希一起版本化、每次换模型都重新拟合、永不手工编辑——以及那条规则：数据集才是资产，优化器只是跑在它上面的一个脚本。',
    ),
    L(
      'New Playbook (Voice & Realtime Agents) — *Retrieval Inside the Voice Turn*. A grounded answer must start leaving the speaker about 800ms after the caller stops, and once endpointing, time-to-first-token and time-to-first-audio are paid, retrieval has roughly 150–300ms — less than a query-rewrite call alone. Argues the consequence is that retrieval latency is an accuracy metric, because the timeout you configured converts an overrun into an ungrounded answer nobody can see failing. Prescribes speculative queries fired on the partial transcript and cancelled on barge-in, precomputed spoken answers and pre-synthesised audio for the head of the question distribution, account context warmed during the greeting, and deleting the query-rewrite and rerank stages outright rather than tuning them down. Covers filler as a designed instrument with a specificity rule, a trigger threshold and a hard ceiling, and closes on measuring entity-level correctness from recorded audio plus a timeout rate as the closest observable to an ungrounded-answer rate.',
      '新增实战手册（语音与实时智能体）——《把检索塞进语音轮次》。一个有依据的回答必须在来电者停口后约 800 毫秒开始从扬声器出来，而在端点检测、首 token 时间与首段音频时间都付过账之后，检索大约只剩 150–300 毫秒——比单单一次查询改写调用还少。文章论证由此得出的推论是：检索延迟是一个准确率指标，因为你配置的那个超时，会把超支转化成一个没人看得见其失败的、无依据的回答。处方包括：对着部分转写发出、并在打断时取消的投机查询；为问题分布头部预先算好的口播答案与预先合成的音频；在问候语期间预热的账户上下文；以及干脆删掉查询改写与重排阶段，而不是把它们往下调。文中还把填充语讲成一件设计过的乐器，配有具体性规则、触发阈值与硬上限；文末落在"从录下来的音频去量实体级正确性"，外加把超时率当作最接近"无依据回答率"的可观测量。',
    ),
    L(
      'New Operation (Governance & Compliance) — *Erasure Requests Against Agent Memory*. A deletion request names a person; your storage names a chunk, a vector, a summary and a graph edge, and a memory system earns its value precisely by deriving state that no longer carries the identifier. Enumerates the six copies — raw turns, embeddings, extracted facts, rolling summaries, graph nodes and edges, and the downstream eval sets, few-shot pools and fine-tuning extracts nobody thinks of as memory — and gives the one-day diagnostic: list every artefact that would change if this user had never spoken. Prescribes source IDs on every derived record at write time, deletion by rebuilding rather than patching (you cannot subtract a turn from a summary), and flags the temporal-graph conflict where marking a fact historical is the opposite of what erasure demands and inbound edges asserted by other people still describe the subject. Covers vendor delete APIs verified by semantic search rather than key lookup, the split from trace retention and legal hold, and closes on a quarterly synthetic-subject drill and a per-request manifest, because a deletion you cannot evidence is one you did not perform.',
      '新增运维页（治理与合规）——《针对智能体记忆的删除请求》。一份删除请求点的是一个人的名字；而你的存储里点的是一个切片、一个向量、一段摘要和一条图上的边，而记忆系统的价值恰恰来自派生出不再带标识符的状态。文章清点了那六份副本——原始轮次、嵌入、抽取出来的事实、滚动摘要、图上的节点与边，以及没人当成记忆的下游评测集、少样本池与微调抽取——并给出一天就能做的自检：列出"如果这位用户从没开口过就会不一样"的每一件产物。处方是：在写入时就给每条派生记录记下来源 ID；用重建而不是打补丁来删除（你没法从一段摘要里减去某一轮）；并点出时序图谱里的那个冲突——把一个事实标记为历史，恰恰是删除所要求的反面，而由别人断言出来的入边，描述的仍然是当事人。文中还讨论了"用语义搜索而非按键查找去验证的厂商删除 API"、与 trace 留存和法务保全之间的分界，并以每季度的合成当事人演练和每次请求的清单收尾——因为一次拿不出证据的删除，就是一次没有发生的删除。',
    ),
  ],
};

export default entry;
