import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-08-28',
  title: L(
    'Two AI Blog posts on what an open trajectory corpus actually transfers and on the two questions that decide an AI gateway, plus three pages on constrained decoding, failure taxonomies and performance-optimization agents',
    '两篇 AI 博客——一套开放轨迹语料真正迁移的是什么，以及决定 AI 网关选型的那两个问题——外加三个页面：受约束解码、失败分类法，以及性能优化智能体',
  ),
  items: [
    L(
      'New blog post — *207,489 open traces buy you a scaffold, not a skill*. NVIDIA\'s Open-SWE-Traces added a fresh batch of agent trajectories on 26 August 2026, joining SWE-Zero (318k) and SWE-Hero (34k) as the open supervised-fine-tuning corpora for coding agents. The post reads what is actually inside one: issue statements drawn from SWE-rebench-V2 under MIT / Apache-2.0 / BSD licences across roughly 20,000 pull requests in nine languages, with the trajectories themselves synthesised by running other models through the OpenHands and SWE-agent harnesses in a dual-mode split of thinking and non-thinking traces. Splits a trajectory into a portable strategy layer (reproduce, localise, minimal patch, verify) and a harness layer that carries most of the tokens — tool names, argument schemas, observation formatting, truncation markers, retry and stop rules — and argues the consequence: fine-tune on OpenHands traces and you reliably get a model that is better inside OpenHands, whose failures in your own loop read as a capability regression when they are an interface mismatch. Second argument: the contamination line has moved from the answer to the environment, because ten recorded runs over a repository teach its layout, test names and failure strings while every n-gram check comes back clean — so hold out repositories rather than tasks, publish the train/eval repository intersection, and keep a post-cutoff slice. Closes on provenance (the licence on the pull requests is not the licence on the teacher models\' outputs) and on the monoculture risk of an open ecosystem distilled from a handful of models through two harnesses. Three themeable SVGs.',
      '新博客文章——《207,489 条开放轨迹买到的是脚手架，不是能力》。2026 年 8 月 26 日，NVIDIA 的 Open-SWE-Traces 又新增了一批智能体轨迹，与 SWE-Zero（31.8 万条）和 SWE-Hero（3.4 万条）一同构成编码智能体的开放有监督微调语料。文章读的是其中一条轨迹里究竟装了什么：issue 陈述取自 SWE-rebench-V2，以 MIT／Apache-2.0／BSD 许可覆盖约 20,000 个 pull request、九种语言；而轨迹本身是合成的——把另外一些模型放进 OpenHands 与 SWE-agent 框架里跑出来，并按「带思考」与「不带思考」做双模式划分。文章把一条轨迹拆成可迁移的策略层（复现、定位、最小补丁、验证）与占了绝大多数 token 的框架层——工具名、参数 schema、观测格式、截断标记、重试与停止规则——并给出后果：拿 OpenHands 轨迹去微调，你稳稳得到的是一个在 OpenHands 里更强的模型，而它在你自己循环里的失败会被读成能力退化，实际却是接口不匹配。第二个论点：污染的界线已从答案挪到了环境，因为在一个仓库上录制的十次运行会教会它的目录结构、测试名与失败字符串，而每一项 n-gram 检查都显示干净——所以要留出仓库而不是留出任务、公布训练与评测的仓库交集，并保留一片截止日之后的切片。文末落在来源问题（pull request 上的许可证不等于教师模型输出上的许可证），以及一个由少数几个模型透过两个框架蒸馏出来的开放生态所面临的单一栽培风险。配三张可随主题变色的 SVG。',
    ),
    L(
      'New blog post — *LiteLLM vs Portkey vs Helicone vs OpenRouter: in the path, or beside it*. Argues that the feature tables in this category are interchangeable and two binary questions decide it instead. First: is the gateway inside the request path? Helicone\'s own docs frame this as an explicit proxy-versus-async choice and state the trade — async keeps logging off the critical path but cannot offer the proxy\'s tools, because caching, rate limiting, key management, threat detection and moderation all require gatekeeping the request. Second: who holds the provider credential — you on a gateway you run, you via bring-your-own-key behind a managed control plane, or the vendor, in which case your fallback on an outage is a provider account you do not have. Then the agent multiplier: a proxy hop and a p99 are paid once per step rather than once per user action (a 1% per-call failure rate is a 22% task failure rate over twenty-five steps), a percentage fee is levied per model call, and — the trap that generates no alert — a gateway that normalises headers, injects system content or load-balances one conversation across providers can silently cut your provider-side prompt-cache hit rate. Clarifies OpenRouter\'s structure (5.5% on card top-ups, 5% on crypto, $0.80 transaction floor, 5% on BYOK above a monthly allowance; no markup on token rates) and closes on the combination mature teams converge on. Three SVGs.',
      '新博客文章——《LiteLLM、Portkey、Helicone 与 OpenRouter：在请求路径上，还是在旁边》。文章主张这个品类里的功能表可以互换，真正决定选型的是两个二选一的问题。其一：网关在不在请求路径之内？Helicone 自己的文档就把这写成一次显式的「代理 vs 异步」选择，并说明了这笔交易——异步把日志留在关键路径之外，却提供不了代理那套工具，因为缓存、限流、密钥管理、威胁检测与内容审核都要求充当请求的守门人。其二：谁持有厂商凭证——你在自运行的网关上持有、你以 BYOK 方式放在托管控制平面之后，还是厂商持有；若是最后一种，宕机时你的兜底是一个你并不拥有的厂商账户。接着是智能体的乘数效应：代理的那一跳与 p99 是按步而不是按用户动作支付的（二十五步下，每次调用 1% 的失败率就是 22% 的任务失败率），百分比费率是按模型调用征收的；而那个不产生任何告警的陷阱是——会归一化请求头、注入系统内容或把同一段对话跨厂商做负载均衡的网关，可能悄悄砍掉你在厂商侧的提示词缓存命中率。文中厘清了 OpenRouter 的结构（信用卡充值 5.5%、加密货币 5%、每笔最低 0.80 美元，BYOK 超出每月额度部分收 5%；token 价格不加价），并以成熟团队最终收敛到的那种组合收尾。配三张 SVG。',
    ),
    L(
      'New Concept (AI Foundations) — *Constrained Decoding*. A 100% valid-JSON rate is not a 100% correct-answer rate, and the mask that buys the first deletes the model\'s ability to abstain: a required field gets filled from an input that never supported one, an enum coerces to the nearest legal member with "none of these" masked out of existence, and an array closes early when the automaton allows it. Covers the mechanism (an automaton compiled from the schema, logits of illegal tokens set to negative infinity, XGrammar\'s sub-40-microsecond per-token overhead as the default backend in vLLM, SGLang and TensorRT-LLM), the FSM-versus-CFG ceiling on recursive schemas, and the fact that "structured outputs" names three different guarantees across vendors. Treats the disputed quality question honestly — *Let Me Speak Freely?* against dottxt\'s *Say What You Mean* — and designs around the undisputed half instead: a schema starting at token one removes the scratchpad, so reason unconstrained and constrain only the answer. Ends on schema design for the decoder, where field order is generation order and putting evidence before the label is the cheapest accuracy win available.',
      '新增概念页（AI 基础）——《受约束解码》。100% 的 JSON 合法率并不等于 100% 的答案正确率，而换来前者的那层掩码，删掉了模型弃答的能力：必填字段会从根本不支持它的输入里被填出来，枚举会被挤压到最接近的合法成员、而「以上皆非」这个信号已被掩码抹除，数组也会在自动机允许时提前收尾。文章讲了机制（由 schema 编译出的自动机、把非法 token 的 logits 置为负无穷、XGrammar 作为 vLLM／SGLang／TensorRT-LLM 默认后端时每 token 低于 40 微秒的开销），讲了 FSM 与 CFG 在递归 schema 上的天花板，也讲了「结构化输出」这个词在不同厂商那里其实指三种不同的保证。文中诚实处理了有争议的质量问题——《Let Me Speak Freely?》对上 dottxt 的《Say What You Mean》——转而围绕没有争议的那一半来设计：一个从第一个 token 就开始的 schema 等于收走了草稿纸，所以推理不受约束、只约束答案。文末落在「为解码器设计 schema」：字段顺序就是生成顺序，把证据排在标签之前是能拿到的最便宜的一次准确率提升。',
    ),
    L(
      'New Operation (Evaluation &amp; Observability) — *Failure Taxonomies &amp; Triage*. "Hallucination" names the smoke at the end of a cascade and routes the ticket to whoever owns the prompt when the fault was a stale index — so label instead the earliest step at which a competent operator holding the agent\'s context would have acted differently, and give nothing downstream a label at all. Lands in seven classes that each name a component you own (task interpretation, grounding and retrieval, tool selection, argument construction, tool-error handling, state and memory, stopping), then insists the list be re-derived bottom-up from 100 traces read independently by two people, clustered out loud, and checked for about 80% inter-rater agreement before anyone else uses it. Sampling decides the roadmap, so draw from three separated streams — known-bad, the cost tail, and uniform random — and weight back to the random stream\'s prevalence before prioritising, since a class that is 40% of complaints and 3% of production is a support-messaging problem. Every class carries an owner, a promoted regression case and a detector, because a class you cannot detect automatically is one you can never say you fixed. Closes on the "other" bucket as the health metric: under 5% healthy, over about 15% means re-derive.',
      '新增运维页（评估与可观测性）——《失败分类法与分诊》。「幻觉」命名的是一条级联链末端的烟，而当故障其实是索引过期时，它会把工单派给负责提示词的人——所以改为标注「一个握着智能体同样上下文的称职操作者本会做出不同动作」的最早那一步，其下游一律不打标签。这样落下来是七个类别，每一个都点名一个你自己拥有的组件（任务理解、接地与检索、工具选择、参数构造、工具错误处理、状态与记忆、停止）；文章随即坚持这份清单必须自下而上重新长出来：两个人独立读 100 条轨迹、当面聚簇、并在交给别人使用之前把标注者一致率检查到约 80%。抽样决定路线图，所以要从三条分开的流里取样——已知坏例、成本尾部、均匀随机——并在排优先级前按随机流的发生率加权回来，因为一个占投诉 40%、只占生产 3% 的类别是客服话术问题。每个类别都要背上归属人、一条被提升进评测集的回归用例，以及一个检测器，因为一个你无法自动检测的类别，是一个你永远说不出「已修复」的类别。文末落在把「其他」桶当健康指标：低于 5% 算健康，高于约 15% 就该重新推导。',
    ),
    L(
      'New Playbook (Coding &amp; Computer-Use Agents) — *Performance-Optimization Agents*. Every other coding agent gets a verifier that cannot lie; this one gets a stopwatch. Forty candidate patches each measured once will keep pure noise with near-certainty — the multiple-comparisons problem, arriving as an agent feature rather than a statistics mistake — and a 2026 reliability study found SWE-Perf especially fragile because many of its own reference patches produce close-to-zero runtime change. Across GSO (102 tasks), SWE-Perf (140) and SWE-fficiency (498), models average well under a quarter of the expert speedup while routinely introducing correctness bugs. The playbook builds the harness first: a measure() that returns a confidence interval rather than a scalar, a published minimum detectable effect enforced as a hard floor, a repetition budget fixed before the run so the agent cannot re-measure until the number is favourable, and machine identity as part of the comparison. Correctness is a gate that runs first, never a term in the score — full suite, differential output checks, an eviction and thread-safety argument demanded of every caching patch, and always a second workload. The largest reported gains come from the profile, not the model: PerfAgent roughly doubled expert-matching patches on GSO (19.6% to 39.2%) and took SWE-fficiency-Lite from 26% to 74%. Closes on the rejection list and on shipping the measurement with the patch.',
      '新增实战手册（编码与计算机操作智能体）——《性能优化智能体》。别的编码智能体拿到的是不会骗人的核验器，这一个拿到的是秒表。四十个候选补丁各测一次，几乎必然会留下纯粹的噪声——多重比较问题以「智能体特性」而非「统计错误」的形式登场；而 2026 年一项可靠性研究发现 SWE-Perf 尤其脆弱，因为它自己的许多参考补丁带来的运行时变化接近于零。在 GSO（102 个任务）、SWE-Perf（140 个）与 SWE-fficiency（498 个）上，模型平均取得的加速远不到专家的四分之一，过程中还经常引入正确性缺陷。本手册主张先建测量台：一个返回置信区间而非标量的 measure()、一个作为硬性下限强制执行且公开的最小可检出效应、在开跑前就定死的重复次数预算（好让智能体不能一直重测到数字中意为止），以及把机器身份算进比较里。正确性是先跑一步的关卡，绝不是分数里的一项——全量套件、输出的差分检查、对每个缓存类补丁都索要淘汰策略与线程安全论证，并且永远用两种工作负载。已报告的最大增益来自剖析结果而非模型：PerfAgent 在 GSO 上把与专家相符的补丁比例大致翻倍（19.6% 到 39.2%），在 SWE-fficiency-Lite 上从 26% 提到 74%。文末落在那份拒收清单，以及让测量结果跟着补丁一起交付。',
    ),
  ],
};

export default entry;
