import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-09-25',
  title: L(
    'Two AI Blog posts — on the plugin pin that four coding agents requested and none of them verified, and on the four ways to give an agent a browser, sorted by whose cookie jar it ends up holding — plus three pages on pinning and verification, screenshot and DOM artefacts in traces, and what a sub-agent actually inherits',
    '两篇 AI 博客——一篇讲那个被四个编程智能体请求过、却没有一个去核对的插件「钉」，一篇讲给智能体一个浏览器的四种方式：按它最终握着谁的 cookie 罐来排序——外加三个页面：钉版本与校验、轨迹里的截图与 DOM 产物，以及子智能体究竟继承了什么',
  ),
  items: [
    L(
      'AI Blog — “The pin was a name, not a digest”: Plugin4Shell, disclosed on 17 September 2026 by AIR Security researchers Or Nevo, Dor Granat and Niv Hoffman, found the same omission in Claude Code, OpenAI Codex, GitHub Copilot and Gemini CLI at once — each checks out a plugin at a pinned 40-character commit SHA and then never asks git which commit it landed on. Because a 40-hex string is also a legal ref name, a repository owner who creates a branch with exactly that name and makes it the default can serve different code while the manifest stays byte-identical, with no click, no reinstall and nothing for a reviewer to diff; plugins run with the developer’s permissions, which is why it rates as it does. Anthropic patched in Claude Code 2.1.179 and OpenAI in Codex 0.146.0; GitHub declined a client fix on the grounds that its own naming rules limit the surface, and Google deprecated Gemini CLI in favour of Antigravity. The split response is the real story: GitHub does reject 40-hex ref names outright and GitLab blocks them in a pre-receive hook, so the security property everyone relied on was being supplied for free by two git hosts as a usability guard — a defence that is invisible in your lockfile and gone the first time a plugin is mirrored, vendored or moved to a self-hosted forge. The fix is one line: resolve HEAD after checkout and compare.',
      'AI 博客《那个钉是一个名字，不是一个摘要》：2026 年 9 月 17 日由 AIR Security 的研究者 Or Nevo、Dor Granat 与 Niv Hoffman 披露的 Plugin4Shell，一次性在 Claude Code、OpenAI Codex、GitHub Copilot 与 Gemini CLI 里发现了同一处遗漏——每一个都会把插件检出到一个被钉住的 40 字符 commit SHA，之后再也没问过 git 自己落在了哪个 commit 上。由于 40 位十六进制串同时也是一个合法的引用名，仓库所有者只要创建一个名字恰好相同的分支并把它设为默认分支，就能在清单逐字节不变的情况下送出不同的代码：不用点击、不用重装，也没有任何 diff 给评审者看；而插件是以开发者的权限运行的，这正是它评级如此的原因。Anthropic 在 Claude Code 2.1.179、OpenAI 在 Codex 0.146.0 修复；GitHub 以「自家命名规则已压缩攻击面」为由不出客户端修复，Google 则弃用 Gemini CLI、转向 Antigravity。分裂的应对才是真正的故事：GitHub 确实直接拒绝 40 位十六进制引用名，GitLab 也在 pre-receive 钩子里拦掉，于是所有人都在依赖的那条安全性质，一直是由两家 git 托管方作为易用性防护免费提供的——这道防御在你的锁文件里看不见，并且在插件第一次被镜像、内嵌或搬到自托管代码服务时就消失了。修法只有一行：检出之后解析 HEAD 再比对。',
    ),
    L(
      'AI Blog — “Safari MCP vs Chrome DevTools MCP vs Playwright MCP vs extension agents”: tool counts decide nothing; the axis that decides both capability and exposure is which session the agent holds. Apple ships its server as a mode of safaridriver, stable since Safari 27, with around seventeen debugging tools and a dedicated automation session that has no cookies, saved passwords, AutoFill or history — so it cannot act as you anywhere. Chrome DevTools MCP wraps the DevTools Protocol with roughly sixty tools, including the performance traces nothing else offers, and launches Chrome against its own user-data directory that is reused across runs unless you set the isolated option. Playwright MCP acts on the accessibility tree rather than pixels, runs three engines, and is the only one with a complete answer on state: persistent by default, --isolated for clean sessions, and --storage-state to seed exactly the logins a run needs. Extension agents such as Claude in Chrome, generally available on paid plans since late August 2026, are the only rung that can actually run the errand, because they use the logins you already have — and the ShadowPrompt and ClaudeBleed disclosures are what that costs: an injection there executes as you. Both browser vendors that shipped an MCP server deliberately kept the user’s own session out of it — Apple at the bottom rung outright, Google one up with a separate profile — which is why neither does the agentic-shopping demo people expected.',
      'AI 博客《Safari MCP、Chrome DevTools MCP、Playwright MCP 与扩展式智能体对比》：工具数量什么也决定不了；同时决定能力与暴露面的那根轴，是智能体握着哪个会话。苹果把服务器做成 safaridriver 的一个模式，自 Safari 27 起进入稳定版，约十七个调试工具，配一个没有 cookie、没有已保存密码、没有自动填充、没有历史的专用自动化会话——所以它在任何地方都无法以你的身份行动。Chrome DevTools MCP 封装 DevTools 协议，约六十个工具，包含别家都没有的性能追踪，并用自己的 user-data 目录启动 Chrome，除非你打开 isolated 选项，否则该目录跨多次运行复用。Playwright MCP 在无障碍树而不是像素上行动，能跑三个引擎，也是唯一在「状态」这件事上给出完整答案的：默认持久、--isolated 给干净会话、--storage-state 只种入这次运行所需的那份登录态。而像 Claude in Chrome 这样的扩展式智能体——自 2026 年 8 月下旬起在付费方案上全面可用——是唯一真能把事办完的一档，因为它用的是你已有的登录态；ShadowPrompt 与 ClaudeBleed 两次披露就是它的代价：在那里，一次注入是以你的身份执行的。两家交付了 MCP 服务器的浏览器厂商都有意把用户自己的会话排除在外——苹果干脆走到最低那一档，谷歌停在往上一档、用一个单独的配置档——这正是它们都做不了大家以为会有的「智能体帮你下单」演示的原因。',
    ),
    L(
      'Concepts — Pinning and Verification: a pin you never check is a preference, not a lock, because pinning is two operations — naming the artefact and proving the bytes match — and nearly every agent toolchain ships only the first. The distinction that settles it is between an identifier that resolves through somebody else’s namespace (a tag, a branch, latest, a model alias, a registry entry) and one that is the content (a sha256 digest, a commit object ID, an npm integrity hash), because only the second is checkable locally with no network call and no cooperation from the server. When the check is missing the system is not necessarily exploitable — it is exploitable unless the namespace forbids the ambiguity, which means the security property has quietly moved to the git host or registry, where it is invisible in your lockfile, travels badly across mirrors and self-hosting, and can change without a CVE. In agent stacks the exposed half is the new half: model aliases, tool schemas served fresh on every MCP connection, and skill and prompt bundles pulled by name. Add the comparison wherever a digest already exists, and where none does, shrink what the artefact can reach instead.',
      '概念 — 钉版本与校验：一个你从不核对的钉是偏好而不是锁，因为钉版本是两个操作——说出制品，以及证明字节吻合——而几乎所有智能体工具链只交付了前一个。真正决定成败的区分，是「要经过别人的命名空间才能解析的标识符」（一个标签、一个分支、latest、一个模型别名、一条注册表条目）与「本身就是内容的标识符」（sha256 摘要、commit 对象 ID、npm 的 integrity 哈希）之别，因为只有后者能在本地被核对：不发网络请求，也不需要服务器配合。校验缺席时，系统并不一定就可被利用——它是「除非命名空间禁止那种歧义，否则可被利用」，这意味着安全性质已经悄悄搬到了 git 托管方或注册中心那边：在你的锁文件里看不见、经不起镜像与自托管的迁移，而且可以在没有任何 CVE 的情况下改变。在智能体技术栈里，暴露的那一半正是新的那一半：模型别名、每次 MCP 连接都重新送来的工具 schema，以及按名字拉取的技能与提示词包。凡是摘要本来就存在的地方就补上比对；没有摘要的地方，转而缩小那件制品够得着的范围。',
    ),
    L(
      'Operations — Screenshots & DOM Artefacts in Agent Traces: the first browser agent in production turns your trace store into an image archive, and every control you built assumes text — a redactor scoring 99% recall on prompts scores zero on a PNG, a full-page frame is 300 KB to 3 MB against a few kilobytes for a text span, and the frame is simultaneously the model’s input, your only audit evidence, and an injection channel nobody scans. Make the accessibility snapshot the text-of-record and demote the screenshot to supporting evidence, because then your existing redactor, retention and search all apply again; mask inside the page using the screenshot API’s own selector list, driven off a CSS class the product owns, failing closed when a selector matches nothing; keep full frames only before an irreversible action and at the last step of a failure, thumbnail the successful middles, and never capture document.documentElement.outerHTML when a bounded subtree will do. Blobs get their own store and their own clock, and replaying a recorded browser trace re-feeds the payload to an agent holding current credentials, so replay belongs somewhere with no production reach.',
      '运维 — 智能体轨迹里的截图与 DOM 产物：放上生产的第一个浏览器智能体，会把你的轨迹存储变成一座图像档案馆，而你建的每项控制都假定内容是文本——一个在提示词上有 99% 召回率的脱敏器，在一张 PNG 上是零；一张整页画面帧是 300 KB 到 3 MB，而一个文本 span 只有几 KB；而那一帧同时是模型的输入、你唯一的审计证据，以及一条没人扫描的注入通道。请把无障碍快照定为文本正本、把截图降为辅助证据，因为这样你现有的脱敏、留存与搜索就全都重新适用；请用截图 API 自带的选择器清单在页面内部做遮罩，由产品自己拥有的 CSS 类驱动，并在选择器什么都没匹配上时失败闭合；只在不可逆动作之前和失败的最后一步保留全分辨率画面帧，成功的中段降成缩略图，并且在一棵有界子树够用时绝不采集 document.documentElement.outerHTML。大块二进制该有自己的存储和自己的时钟；而回放一段录制的浏览器轨迹，等于把负载重新喂给一个此刻握着当前凭据的智能体，所以回放该待在一个够不着生产的地方。',
    ),
    L(
      'Deep-Dives — What a Sub-Agent Actually Inherits: every framework gives you a switch for how much conversation a sub-agent inherits and none for how much authority, so the setting teams tune is the one that shows up in the bill and the setting nobody sees is the one that shows up in the incident report. Five things can cross the boundary — transcript, instructions, authority, budget, provenance — and configuration covers two. Tools bind to the process rather than to the conversation, so deepagents’ isolated mode isolates the transcript and leaves the MCP connections, environment variables and OAuth tokens identical: an isolated sub-agent is a fresh context window with the parent’s exact reach, and fan-out buys concurrency at constant authority while collapsing the audit trail onto one identity. Worse, isolation launders provenance, because a brief the parent wrote from a hostile page arrives in the child’s instruction position looking trusted — the mirror image of the split-context construction that actually works. Taint flows down into the hand-off, returns flow up as untrusted, budgets are a shared ledger with an absolute deadline, and every writer gets its own role with its own credential.',
      '深入解析 — 子智能体究竟继承了什么：每个框架都给了你一个开关去决定子智能体继承多少对话，却没有一个去决定它继承多少权限——于是团队调的那个会出现在账单上，而没人看见的那个会出现在事故报告里。能跨过边界的有五样——对话记录、指令、权限、预算、出处——而配置只覆盖两样。工具绑在进程上而不是对话上，所以 deepagents 的 isolated 模式隔离的是对话记录，MCP 连接、环境变量与 OAuth 令牌一样没改：一个 isolated 的子智能体只是一个拥有父智能体完全相同可达范围的新上下文窗口，而扇出买到的是「权限不变的并发」，同时把审计轨迹压成了同一个身份。更糟的是，隔离会洗白出处，因为父智能体照着一个恶意页面写出的简报，会出现在子智能体的指令位上、看起来可信——这恰是那种真正有效的「切开上下文」构造的镜像。请让污点向下流进交接、让返回值向上流时算作不可信、让预算成为一本带绝对截止时间的共享账，并让每一个写者拥有自己的角色和自己的凭据。',
    ),
  ],
};

export default entry;
