import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-08-17',
  title: L(
    'Two AI Blog posts on which authorization engine an agent needs and on the expiry date attached to Gemini 3.7 Flash’s price, plus three pages on the agent harness, load-testing agents and logistics agents',
    '两篇 AI 博客——智能体到底需要哪种授权引擎，以及 Gemini 3.7 Flash 价格上挂着的那个到期日——外加三个页面：智能体外壳、智能体压测，以及物流智能体',
  ),
  items: [
    L(
      'New blog post — *OPA vs Cedar vs OpenFGA vs SpiceDB: Who Is Trusted to Supply the Facts*. All four express the same policy, so the syntax argument is a distraction; the split that decides it is whether the engine evaluates a request you hand it (OPA, Cedar) or answers from a relationship graph it owns (OpenFGA, SpiceDB). Argues that an agent dissolves the assumption every one of them was built on — a trustworthy enforcement point — because the caller’s context contains attacker-controlled text, so any attribute the model can influence is an attribute an injection can widen. Covers the delegation modelling where "on behalf of" is not "as", Cedar’s per-tool-call enforcement at an AgentCore gateway, and the check budget nobody sizes: one check per web request against dozens per agent task and thousands when filtering a retrieval set one chunk at a time, which bulk enumeration collapses and no amount of single-check speed rescues. Closes on operational cost running opposite to capability, and on the enforcement point belonging outside the agent regardless of engine. Three themeable SVGs.',
      '新博客文章——《OPA、Cedar、OpenFGA 与 SpiceDB：谁有资格提供那些事实》。四者都能表达同一条策略，所以关于语法的争论是个干扰项；真正做决定的那道分界，是引擎评估的是你递给它的一次请求（OPA、Cedar），还是从它自己持有的关系图里作答（OpenFGA、SpiceDB）。文章论证：智能体消解了它们四个共同建立在其上的那个假设——一个可信的执行点——因为调用方的上下文里装着攻击者可控的文本，于是任何模型能影响的属性，都是一次注入可以据以自行拓宽的属性。文中讨论了"代表某人"不等于"就是某人"的委派建模、Cedar 在 AgentCore 网关上对每次工具调用的执行，以及没人估算过的检查预算：一次 Web 请求一次检查，对上一次智能体任务几十次、而逐块过滤一次检索结果时上千次——后者只有批量枚举能压平，单次检查再快也救不了。文末落在"运维代价与能力排序恰好相反"，以及"无论选哪个引擎，执行点都属于智能体之外"。配三张可随主题变色的 SVG。',
    ),
    L(
      'New blog post — *Gemini 3.7 Flash Did Not Cut the Price — It Put a Date on It*. The standard rate is $1.50 / $7.50 per million input and output tokens, which is exactly what 3.6 Flash already listed at; the 50% headline is a discount expiring 31 December 2026, so the offer is a better model at last generation’s price plus a dated 2× step in unit cost. Argues agent workloads feel this differently from chat for two reasons: spend grows with roughly the square of the step count, and harness configuration is far stickier than price — four and a half months is long enough for a cheap-window thinking budget to become what your quality numbers assume, and thinking tokens bill as output at the higher rate. Notes that Google’s own coding results are self-computed with a mini SWE-agent harness at high thinking, so the headline configuration is the expensive one, and that roughly 85.8% on Terminal-Bench 2.1 against about 14.9% on 3.0 shows what a suite version is worth. Closes on budgeting at the standard rate from day one and treating an introductory rate as a term sheet rather than a price. Three SVGs.',
      '新博客文章——《Gemini 3.7 Flash 没有降价——它给价格加了一个日期》。标准价是每百万输入/输出 token 1.50 / 7.50 美元，与 3.6 Flash 早已挂出的价格分毫不差；那个"五折"标题是一份 2026 年 12 月 31 日到期的折扣，所以这份要约是"上一代价位上的一个更好的模型"，外加一次带日期的单位成本翻倍。文章论证智能体负载对此的感受与聊天不同，原因有二：花费大约随步数的平方增长，而外壳配置的黏性远高于价格——四个半月足够让一份"便宜窗口期"的思考预算变成你的质量数字所默认的东西，而思考 token 是按输出、按更高那档计费的。文中指出 Google 自己的编码成绩是用一套 mini SWE-agent 外壳、在高思考档下自行计算的，所以那个上标题的配置正是昂贵的那套；而 Terminal-Bench 2.1 上约 85.8% 对 3.0 上约 14.9%，说明了一个套件版本值多少钱。文末落在"从第一天起就按标准价做预算"，以及"促销价是一份条款清单，不是一个价格"。配三张 SVG。',
    ),
    L(
      'New Concept (Agentic AI) — *The Agent Harness*. Every agentic benchmark number scores a model and the harness it ran inside, and only one of them is named on the chart. Separates model from framework from harness, and names the seven decisions the harness makes that the model never gets to make — tool catalog and descriptions, context eviction, stop conditions, tool-error text, auto-approval, output parsing, effort budget. Uses Google’s own mini SWE-agent scaffold and the 85.8% / 14.9% Terminal-Bench spread to argue that a published score is an upper bound reachable by a well-tuned harness rather than a property you get by buying the model, and that a model comparison run on someone else’s harness is evidence about their harness. Argues harness work has the better return per unit of risk because a model swap is a re-qualification and a tool description is a deploy, reads managed agent runtimes as vendor-supplied harnesses, and closes by asking you to spend a day on the harness and re-run the eval on the old model.',
      '新增概念页（智能体 AI）——《智能体外壳》。每个智能体基准分都同时给一个模型和它所在的那层外壳打分，而图表上只写了其中一个的名字。文章把模型、框架与外壳区分开，并点出外壳替模型做的七个模型自己永远碰不到的决定——工具目录与描述、上下文淘汰、停止条件、工具报错文本、自动放行、输出解析、努力度预算。文中用 Google 自己的 mini SWE-agent 脚手架，以及 Terminal-Bench 上 85.8% 与 14.9% 的落差来论证：一个公布出来的分数，是一层调好的外壳所能触及的上界，而不是买下模型就随之到手的属性；而跑在别人外壳上的模型对比，是关于他们那层外壳的证据。文章论证外壳上的功夫在单位风险回报上更划算，因为换模型是一次重新资格认证、而改一句工具描述只是一次部署；并把托管智能体运行时读作厂商供应的外壳；文末请你拿一天花在外壳上，然后在旧模型上重跑一遍评估。',
    ),
    L(
      'New Operation (AgentOps) — *Load-Testing an Agent System*. The first decision is not the tool but what to do about side effects, and every answer changes the measurement: mocked tools delete the seconds of real latency that dominate a trajectory, so you measure the model and ship a system bottlenecked on its vendors. Points out that nothing you own saturates first — provider tokens-per-minute, a third-party tool’s rate limit, worker slots pinned by the tail, or KV-cache memory — and sizes the run from Little’s Law rather than from RPS. Prescribes sampled production tasks rather than one repeated prompt (which measures a warm prompt cache), context length as a load axis, failure paths included so retry amplification can appear, and an eval carried inside the load because saturation degrades quality silently through fallbacks and truncation while latency stays inside the SLO. Lists the metrics that mean something — concurrent in-flight tasks, steps per task, quota headroom, 429s counted per dependency, retry amplification, queue age, dollars per run — and closes on a single test worth running and the two numbers to take from it.',
      '新增运维页（智能体运维）——《给智能体系统做压测》。第一个决定不是选工具，而是拿副作用怎么办，而每一个答案都会改变测量：mock 掉的工具抹去了主导一条轨迹的那几秒真实延迟，于是你测的是模型，发出去的却是一个被自家供应商卡住脖子的系统。文章指出最先饱和的没有一样是你自己的东西——厂商的每分钟 token 配额、某个第三方工具的限流、被长尾钉住的 worker 槽位，或 KV 缓存内存——并主张用利特尔法则而不是 RPS 来定测试规模。处方包括：用采样来的真实生产任务而不是一条重复的提示（后者测的是一个热的提示词缓存）、把上下文长度当作一根负载轴、把失败路径放进去以便重试放大显形，以及把一份评估带进负载里跑——因为饱和会经由降级与截断无声地拉低质量，而延迟仍待在 SLO 之内。文中列出了真正有意义的指标——并发在途任务数、每任务步数、配额余量、按依赖分别计数的 429、重试放大系数、队列年龄、每次运行的美元数——并以"只做一次的话该做哪一次压测"及从中要拿走的两个数字收尾。',
    ),
    L(
      'New Playbook (Domain Playbooks) — *Supply-Chain & Logistics Agents*. The failure mode here is not hallucination, it is acting confidently on a fact that was true four hours ago, because every system the agent reads is a photograph of an already-moved world. Sorts the four products sharing this name and argues that routing belongs to a solver while the agent belongs on exception triage, then makes freshness a tool contract: a mandatory as_of and source on every read, three staleness classes with different rules, and a per-field maximum age enforced in code rather than requested in the prompt — noting that "no event" means "no event reported" on a carrier feed that batches every four hours. Prescribes a closed exception taxonomy of eight to fifteen types, each with a detection rule, a consequence-derived severity, a named owner and an explicit no-action branch, with the unclassified rate as the health metric. Covers writes as contracts a counterparty can refuse (reversibility gating, re-read at commit, never retry blindly), the integration layer nobody budgets for, and measuring the exception the agent never raised through backtests on resolved history and a weekly sample of the silence.',
      '新增实战手册（领域实战手册）——《供应链与物流智能体》。这里的失效模式不是幻觉，而是自信地依据一个四小时前才为真的事实动手，因为智能体读到的每一个系统，都是一张已经动过的世界的照片。文章梳理了共用这个名字的四种产品，论证路径规划归求解器、智能体归异常分诊；随后把新鲜度写进工具契约：每次读取都必须带 as_of 与 source、三个陈旧度等级各用各的规则，以及一个由代码强制而非在提示词里请求的按字段最大年龄——并指出在一条四小时一批的承运商数据流上，"没有事件"意味着"没有事件被上报"。处方是一份封闭的、八到十五种的异常分类法，每一种都配检测规则、由后果推导的严重度、具名责任人和一条显式的"不动"分支，并以未分类率作为健康指标。文中还讨论了"写入是对方可以拒绝的契约"（按可逆性设闸、提交时重读、绝不盲目重试）、没人给它留预算的集成层，以及如何通过对已了结历史的回测与每周对沉默的抽样，去测那个智能体从未报出的异常。',
    ),
  ],
};

export default entry;
