import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-08-06',
  title: L(
    'Two AI Blog posts on Google\'s calling agent and the four agent frameworks, plus five pages on telephony, IT helpdesk agents, first-run UX, agent SLOs and production feedback',
    '两篇 AI 博客——Google 的外呼智能体与四大智能体框架——外加五个页面：电话接入、IT 服务台智能体、首次运行体验、智能体 SLO，以及生产反馈',
  ),
  items: [
    L(
      'New blog post — *Google\'s Agent Calls the Store, and Every Protocol Guarantee Falls Off*. Google\'s shopping agent now phones local shops to check stock, in selected US categories, announcing itself as automated and letting businesses opt out. The argument is that the same companies spent two years building the opposite thing: AP2\'s signed Intent, Cart and Payment Mandates, released as v0.2 and contributed to the FIDO Alliance in 2026. Line up the guarantees and the phone carries none of them — caller identity is a spoken claim, scoped authorisation has no object, there is no idempotency key to retry against, and the only record is the summary the agent wrote about itself. And the phone is not transitional: it covers the merchant tail that will never implement an API, so it is the permanent floor of agent commerce. Ends with what a callee would need (a signed caller identity, one cross-operator opt-out registry, a receipt issued to both sides) and why none of the three exists. Three themeable SVGs.',
      '新博客文章——《Google 的智能体打电话给商店，而每一项协议保证都掉了下去》。Google 的购物智能体如今会在美国部分品类里致电本地商店查询库存，会表明自己是自动呼叫，商家也可以退订。文章主张：同一批公司花了两年在建造相反的东西——AP2 的签名 Intent、Cart 与 Payment Mandate，2026 年发布 v0.2 并贡献给 FIDO Alliance。把保证逐项排开，电话一样都不承载：主叫身份只是一句口头声明、受限授权没有对应的对象、没有幂等键可供重试，而唯一的记录是智能体自己写的关于自己的摘要。而且电话不是过渡性的：它覆盖着那条永远不会实现 API 的商家长尾，因此它是智能体商务的永久地板。文末给出被叫方真正需要的三样东西（可验证的签名主叫身份、一个跨运营方的退订登记处、向双方各出具的凭证），以及为何它们一样都不存在。配三张可随主题变色的 SVG。',
    ),
    L(
      'New blog post — *LangGraph vs CrewAI vs OpenAI Agents SDK vs Google ADK: Pick the State Model*. Framework comparisons argue about graphs versus crews versus handoffs versus agent trees, and the metaphor stops mattering by week three. What does not is where a run lives: LangGraph checkpoints typed graph state to an external store at every superstep and gets resume, time travel and a durable `interrupt()` from it; ADK holds shared session state behind a pluggable session service and encodes order in Sequential / Parallel / Loop workflow agents; CrewAI threads Flow state through `@start` / `@listen` / `@router` with opt-in `@persist`; the OpenAI SDK keeps run context in the process and gives you the best out-of-the-box tracing of the four. Prompts and tool definitions port in hours, orchestration shape in weeks, and the state contract not at all — which is the migration that hurts eighteen months in. Three SVGs including a five-axis feature matrix.',
      '新博客文章——《LangGraph vs CrewAI vs OpenAI Agents SDK vs Google ADK：照状态模型来选》。框架对比总在争论图 vs 团队 vs 交接 vs 智能体树，而比喻到第三周就不再要紧。真正要紧的是一次运行住在哪里：LangGraph 在每个 superstep 把带类型的图状态检查点写入外部存储，并由此得到恢复、时间旅行与持久的 `interrupt()`；ADK 把共享 session state 放在可插拔的 session service 后面，并用 Sequential / Parallel / Loop 工作流智能体把顺序编码进来；CrewAI 用 `@start` / `@listen` / `@router` 串起 Flow 状态，持久化则要 `@persist` 选择性开启；OpenAI SDK 把 run context 留在进程内，却给了四者中开箱即用最好的追踪。提示词与工具定义以小时计迁移，编排形态以周计，状态契约则根本迁不动——而那正是十八个月后真正痛的那次迁移。配三张 SVG，含一张五维特性矩阵。',
    ),
    L(
      'New Playbook (Voice & Realtime Agents) — *Telephony & PSTN Integration*. You can shave 200ms off time-to-first-token and still ship a phone agent that sounds worse than the demo, because roughly half the turn latency, all the audio quality and whether the call connects at all live in a carrier path you cannot profile. Covers the fixed transport tax (post-dial delay, the jitter buffer as a deliberate quality-versus-speed dial, transcoding, the 8 kHz ceiling), your number as a reputation asset where STIR/SHAKEN A-level attestation moves connect rate more than any agent change and number rotation makes labelling worse, the missing metadata channel (the callee\'s IVR is your API and nothing is idempotent), transfers as where state dies, and the US consent regime as a code path — the FCC\'s February 2024 ruling that AI voices are "artificial" under the TCPA, written versus oral consent after the Fifth Circuit\'s *Bradford* decision in February 2026, and $500–$1,500 per call uncapped.',
      '新增实战手册（语音与实时智能体）——《电话与 PSTN 接入》。你可以把首 token 时间压掉 200ms，交付出来的电话智能体仍然比 demo 更难听——因为大约一半的轮次延迟、全部音质，以及通话到底接不接得通，都住在一条你无法剖析的运营商链路里。文中讲了固定的传输税（拨后延迟、作为"音质换速度"旋钮的抖动缓冲、转码、8 kHz 天花板）、作为信誉资产的号码（做到 STIR/SHAKEN A 级对接通率的提升超过你在智能体里的任何改动，而换号只会让标记来得更快）、缺失的元数据通道（对方的 IVR 就是你的 API，且没有任何东西是幂等的）、转接是状态死掉的地方，以及作为代码路径的美国同意制度——FCC 2024 年 2 月裁定 AI 语音属于 TCPA 下的"人工语音"、第五巡回法院 2026 年 2 月 *Bradford* 案之后的书面 vs 口头同意之争，以及每通 500–1,500 美元且无上限的法定赔偿。',
    ),
    L(
      'New Playbook (Domain Playbooks) — *IT Helpdesk Agents*. The reason to build one is that it can reset the password and grant the access — and those are exactly what an attacker phones a helpdesk to obtain. In September 2023 a caller spent about ten minutes with MGM Resorts\' helpdesk impersonating an employee, walked out with a privileged reset, and cost the company roughly $100 million; the only control in that path was a human\'s sense that something felt off, which is the control an agent removes. Argues the product is the authorisation layer: never proof identity conversationally, verify on a possession factor out of band, derive the action set from entitlements in the IdP and HR system rather than from the request, keep a fail-closed deny-list no entitlement can satisfy, and ship password and MFA recovery last or never. Ends on why deflection rate rewards a bad agent and reopen rate does not.',
      '新增实战手册（领域实战手册）——《IT 服务台智能体》。你之所以要建它，是因为它能重置密码、发放权限——而这恰恰是攻击者打电话给服务台想要拿到的东西。2023 年 9 月，一名来电者花约十分钟冒充员工与 MGM Resorts 服务台通话，带走一次特权重置，让公司损失约一亿美元；这条路径上唯一的控制是人对"哪里不对劲"的直觉，而那正是智能体会移除掉的控制。文章主张产品其实就是那层授权：绝不在对话里核验身份、用带外的持有型因子验证、从身份提供商与 HR 系统的权限而非从请求推导动作集合、保留一份任何权限都无法满足的 fail-closed 拒绝清单，并把密码与 MFA 恢复放到最后或干脆不上。文末讲了为何分流率奖励糟糕的智能体，而重开率不会。',
    ),
    L(
      'New Playbook (Agent UX & Human Interaction) — *First Run & Onboarding*. The first session produces a durable estimate of what an agent can do, and every later interaction is read through it rather than replacing it — so the capability tour calibrates users to the ceiling and manufactures a disappointment on task two, while a single first-session failure costs more trust than ten failures a month later. Argues for onboarding to the edge: demonstrate a refusal on purpose, show an uncertain answer alongside a confident one, pick the first task by measured reliability on the user\'s real data rather than by how it demos, stop bundling permissions at a moment the user has no basis to evaluate them, and teach the repair — steering mid-task, a visible undo, a first failure handled as a designed path. Plus why first-session metrics have to be reported separately from your aggregates.',
      '新增实战手册（智能体体验与人机交互）——《首次运行与用户引导》。第一次会话会生成一个关于"它能干什么"的持久估计，而之后的每次交互都是透过它被解读、而非取代它——所以能力巡礼把用户校准到了天花板，为第二个任务预制了一场失望；而首轮的一次失手，代价高于一个月后的十次。文章主张把用户引导到边界：刻意演示一次拒绝、把不确定的回答与自信的回答一起展示、按实测可靠性而非 demo 效果在用户真实数据上挑首个任务、别在用户毫无评估依据的时刻打包索取权限，并教会修复——任务中途纠偏、可见的撤销、把第一次失败当作一条设计好的路径。文末讲了为何首轮会话的指标必须与汇总指标分开上报。',
    ),
    L(
      'New Operation (AgentOps) — *SLOs & Error Budgets for Agents*. Every team starts with "99% of answers are correct" and stalls, because correctness has no label in production, its proxy is a model with its own error rate, and adjudication arrives days after the alert would have helped. Split the indicators into three tiers instead: mechanical ones you compute deterministically from traces get a real error budget (task completion rate in particular catches step-limit loops, tool schema drift and refusal regressions in seconds); proxy signals get change detection, not thresholds; judged scores go on a weekly control chart and never on a pager. Then adds the tier classic SRE has no analogue for — a harm budget denominated in actions taken rather than requests served, weighted by reversibility, whose exhaustion reduces autonomy rather than stopping the service.',
      '新增运维页（智能体运维）——《智能体的 SLO 与错误预算》。每个团队都从"99% 的回答是正确的"开始，然后卡住——因为正确性在生产中没有标签、它的代理指标是一个自带错误率的模型，而裁定结果在告警本该有用之后好几天才到。改成把指标分三层：能从 trace 确定性算出的机械指标配一份真正的错误预算（尤其是任务完成率，它能在秒级抓到撞步数上限的循环、工具 schema 漂移与拒绝率回归）；代理信号配变化检测而不是阈值；裁定分数放到每周控制图上，永不上传呼。文章还补上了经典 SRE 没有对应物的那一层——一份以"已采取动作数"而非"已服务请求数"为分母、按可逆性加权的危害预算，它被烧穿时收缩的是自主度，而不是停服。',
    ),
    L(
      'New Operation (Evaluation & Observability) — *Production Feedback Signals*. Thumbs arrive from under one percent of sessions, skew bimodal by construction, and reward confidence over correctness — so optimising that ratio optimises for agreeableness. Meanwhile the densest quality signal your product emits is the diff between what the agent produced and what the user actually shipped: a free, dense, expert-written correction that most products discard at send. Store the pair joined by task ID, track normalised edit distance as the continuous signal, cluster the diffs and the defect taxonomy writes itself. Then treat every signal as a router into the eval set rather than a metric to move, keep a uniform sample running so the weighted one stays interpretable, and settle consent with data governance before the pipeline exists.',
      '新增运维页（评估与可观测性）——《生产反馈信号》。点赞点踩来自不足百分之一的会话、天生呈双峰分布，且奖励自信甚于正确——所以优化这个比率优化出来的是讨好。与此同时，你的产品所释放的最稠密的质量信号，是"智能体产出的东西"与"用户最终真正交付的东西"之间的差异：一份免费、稠密、由领域专家写下的纠正，而多数产品在点下发送的那一刻就把它扔了。把这一对以任务 ID 关联存下来、用归一化编辑距离作连续信号、把差异聚类，缺陷分类体系就会自己写出来。随后把每个信号都当作通往评测集的路由器而非要拉动的指标，并行保留一条均匀抽样让加权那条仍可解读，并在流水线存在之前就与数据治理把同意问题定下来。',
    ),
  ],
};

export default entry;
