import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-08-31',
  title: L(
    'Two AI Blog posts — on the sandbox cold-start number nobody measures on the right workload, and on the survey where 85.5% trust agents and 41.1% debug them daily — plus three pages on CI repair agents, after-call work, and the tool catalog',
    '两篇 AI 博客——沙箱冷启动那个从来没在正确负载上测过的数字；以及一份「85.5% 信任智能体、41.1% 每天在给它擦屁股」的调查——外加三个页面：CI 修复智能体、通话后处理，以及工具目录',
  ),
  items: [
    L(
      'New AI Blog post `/blogs/e2b-vs-daytona-vs-modal-vs-northflank-sandboxes` — four agent sandbox platforms compared on the two axes nobody publishes. Every vendor cold-start figure (Daytona 27–90 ms, E2B ~150 ms) measures sequential creates, which is the one shape an agent fleet never produces; the third-party burst measurements published in August 2026 put Vercel at 0.67 s median with a 1.12 s p99, Modal at 0.88 s, E2B at 1.61 s and Cloudflare at 5.06 s — a 7× spread between providers and roughly 10× between E2B’s own two numbers — and neither Daytona nor Northflank appears in any published burst set. The second axis is the meter: a coding agent’s sandbox spends most of its life waiting on inference, E2B is explicit that its clock does not distinguish idle from active, Daytona and Northflank bill the same alive-time shape, and Modal drops compute charges to zero when nothing executes. The post gives the arithmetic that decides between them (alive-seconds over executing-seconds, above ~5:1 the meter wins the case before rates are compared), ranks the isolation column as real but not the hard decision, and notes that Daytona moving its production codebase closed in June 2026 leaves only E2B’s open source and Northflank’s self-serve BYOC as exits.',
      '新增 AI 博客 `/blogs/e2b-vs-daytona-vs-modal-vs-northflank-sandboxes`——四个智能体沙箱平台，按两条没人公布的轴来比较。每一个厂商冷启动数字（Daytona 27–90 毫秒，E2B 约 150 毫秒）量的都是顺序创建，而那恰恰是智能体集群唯一不会产生的形状；2026 年 8 月公布的第三方突发测量把 Vercel 放在中位数 0.67 秒、p99 1.12 秒，Modal 0.88 秒，E2B 1.61 秒，Cloudflare 5.06 秒——提供商之间 7 倍的跨度，E2B 自家两个数字之间约 10 倍的落差——而 Daytona 与 Northflank 都不出现在任何已公布的突发数据里。第二条轴是计价器：编码智能体的沙箱一生大半在等推理，E2B 明说它的时钟不区分闲置与活跃，Daytona 与 Northflank 用的是同一种「按存活时长」的形状，而 Modal 在无代码执行时把算力费用降为零。文章给出了在两者之间做决定的那笔算术（存活秒数除以执行秒数，高于约 5:1 时，还没比费率计价器就已经赢了），把隔离那一列判为真实但并非难做的决定，并指出 Daytona 在 2026 年 6 月把生产代码库转为闭源之后，退出路径只剩 E2B 的开源与 Northflank 的自助式 BYOC。',
    ),
    L(
      'New AI Blog post `/blogs/trust-outran-the-agent-incident-rate` — Temporal’s 2026 State of Development Report surveyed 554 engineers in the US and UK between 29 April and 25 May 2026, and its headline is adoption: daily agent use at 80.8%, up from 47.3% a year earlier, with 91.1% reporting improved productivity and 85.5% trusting agent output at least somewhat. The post reads it against the numbers underneath: 41.1% hit agent-related issues daily or more and 9.0% continuously. The report’s framing — that state tracking, named by 35.7%, is the blocker — is a durable-execution vendor’s reading and is a ranking of visibility rather than of cause. The argument instead is that "trust" is a scalar the survey inherits and teams should not: the operational question is which actions may run unreviewed, and the combination is stable only because the error handler is a person whose minutes never reach a dashboard. Closes on the one instrumentation that answers it for your own team — a boolean per run for "a human intervened", plus the task class — and on the methodology caveats, including that daily agent use among software engineers is largely a coding assistant rather than a deployment.',
      '新增 AI 博客 `/blogs/trust-outran-the-agent-incident-rate`——Temporal 的 2026 年《开发现状报告》于 2026 年 4 月 29 日至 5 月 25 日在美英调查了 554 名工程师，其头条是采用率：每日使用智能体的比例达 80.8%，一年前为 47.3%；91.1% 报告生产力提升，85.5% 至少在某种程度上信任智能体的产出。本文拿底下那几个数字来对读它：41.1% 每天或更频繁地遇到智能体相关问题，9.0% 是持续遇到。报告的框架——被 35.7% 的人点名的「状态追踪」是那个阻碍——是一家持久化执行厂商的读法，而且那是一份可见度排名而非成因排名。本文的论点则是：「信任」是一个被调查继承下来、而团队不该继承的标量；可操作的问题是「哪些动作可以不经复核就跑」，而这个组合之所以稳定，只因为错误处理器是一个人，他花掉的那些分钟从未抵达任何看板。文末落在能为你自己团队回答这个问题的那一件仪表——每次运行一个「有人介入过」的布尔值，外加任务类别——以及方法论上的若干提醒，包括：在软件工程师中，「每日使用智能体」在很大程度上指的是编码助手而不是一次部署。',
    ),
    L(
      'New Playbook `/playbooks/coding-and-computer-use-agents/ci-repair-agents` (U21) — this agent is handed a reproduction on a plate, which is why teams reach for it first and why it is the one most likely to make things worse. The deliverable is the classification, not the patch: caused by this diff, pre-existing on the base branch, environment or infrastructure, or non-deterministic — and each class needs different evidence and grants different authority. The load-bearing move is mechanical and nobody runs it: execute the failing check against the merge base as well as the head, because two extra CI runs cost minutes while a wrong push costs a pipeline, a stale review, a reset approval and a permanent increment to how much the team discounts the bot. Also: "flake" is not a root cause but the conclusion an agent under pressure reaches for, so the re-run budget is one; never skip, disable or quarantine a test to reach green; never rewrite history on a branch you do not own; deduplicate on (check name, head commit) rather than on the webhook; and page yourself on wrong-push rate rather than builds turned green.',
      '新增实战手册 `/playbooks/coding-and-computer-use-agents/ci-repair-agents`（U21）——这个智能体是被人把复现端到面前的，这既是团队最先想到它的原因，也是它最可能把事情弄得更糟的原因。交付物是分类而不是补丁：由这个 diff 造成、基线分支上本就存在、环境或基础设施问题，还是非确定性——每一类要的证据不同，授予的权限也不同。真正撑起全篇的那一步既机械又没人去跑：把失败的检查同时对着合并基线跑一遍；因为多跑两次 CI 花的是几分钟，而一次错误的推送花掉的是一整条流水线、一份作废的评审、一次被重置的批准，以及团队对这个机器人打折程度的一次永久性上调。另外：「flaky」不是根因，而是一个被逼着产出的智能体会去够的那个结论，所以重跑预算是一次；绝不为了拿到绿色而跳过、禁用或隔离测试；绝不在不属于你的分支上重写历史；按（检查名，head 提交）而不是按 webhook 去重；并把告警设在错误推送率上而不是转绿的构建数上。',
    ),
    L(
      'New Playbook `/playbooks/voice-realtime-agents/after-call-work-and-crm-writeback` (V14) — the caller hears the conversation once; the disposition code and the summary are read for years by the next agent, the router, the analyst and eventually the regulator, and a voice eval suite typically stops the moment the caller hangs up. The page separates four artefacts with four different consumers and argues that review effort should run inversely to visibility: the summary sits next to its own evidence and is self-correcting, the disposition is consumed as a number and is not. The disposition is a classification problem wearing a generation problem’s clothes — constrain it to the vocabulary at the schema layer, force an explicit abstention distinct from "Other", and audit the wrap-up taxonomy against a month of real calls before blaming the model for a distribution shift, because most code sets were designed for humans clicking under time pressure. Also covers quoting rather than characterising when ASR errors concentrate on names and amounts, extracting commitments as structured output, one idempotency key per call on every write, the transferred-call case where a human is also writing, and daily reconciliation of calls against records.',
      '新增实战手册 `/playbooks/voice-realtime-agents/after-call-work-and-crm-writeback`（V14）——来电者只听一次对话；而处置码与摘要会被下一个坐席、路由、分析师，乃至最终的监管方读上好几年，可一套语音评测通常在来电者挂断那一刻就停了。本页把四样产物按四种消费者拆开，并主张复核投入应当与可见度成反比：摘要挨着自己的证据、是自纠的，处置码被当成数字消费、不是。处置码是一个披着生成外衣的分类问题——在 schema 层把它约束在词表内，强制留出一个与「其他」相区分的明确弃权项，并且在为分布漂移责怪模型之前，先拿一个月的真实通话把结案码分类体系审一遍，因为多数码表是为「在时间压力下点鼠标的人」设计的。文中还讲了：当 ASR 的错误集中在姓名与金额上时要去引用而不是去定性、把承诺抽成结构化输出、每通电话一个幂等键并带在每次写入上、通话被转接时人也在往同一份记录里写的情形，以及每日把通话与记录对账。',
    ),
    L(
      'New Operation `/operations/agentops/tool-catalog-lifecycle` (O22) — adding a tool feels additive and is not, because selection is a function of the whole catalog: the fortieth tool changes behaviour on the thirty-nine tasks that were working, through description overlap, attention dilution and name collisions, and the only place it shows up is a success rate nobody was watching. The gate for adding a tool is therefore the existing eval set rather than a new one demonstrating the newcomer works, and the admission request should carry an owner, the task it enables, the regression delta, a disambiguation sentence that usually edits the incumbent’s description too, and the narrowest scope that satisfies the requester. The page also argues that a per-task allowlist beats dynamic tool retrieval wherever you already know what a task needs, that tool definitions are a permanent per-step cost sitting in every cached prefix, that removal is a migration needing a three-phase retirement and a tombstone that names the replacement, and that the catalog should be serialised, hashed and stamped on every trace so it becomes the third element of the (model, prompt, tools) triple instead of the one left floating.',
      '新增运营页 `/operations/agentops/tool-catalog-lifecycle`（O22）——加一个工具感觉上是「只增不减」，其实不是，因为工具选择是整份目录的函数：第四十个工具会通过描述重叠、注意力稀释与名称冲突，改变那三十九项本来跑得好好的任务上的行为，而唯一能看出这件事的地方是一个没人在盯的成功率。因此，新增工具的闸门是那份既有评测集，而不是一份用来展示新来者能用的新评测集；准入申请则应当带上负责人、它使之成为可能的那项任务、回归差值、一句往往连既有工具描述也要一并改动的消歧说明，以及能满足申请方的最窄作用域。本页还论证了：凡是你已经知道某项任务需要什么的地方，一份按任务的白名单都胜过动态工具检索；工具定义是坐在每一份缓存前缀里的一笔永久性「每步成本」；移除是一次迁移，需要三阶段退役和一块点名替代者的墓碑；以及这份目录应当被序列化、取哈希并打在每一条 trace 上，好让它成为（模型，提示词，工具）三元组里的第三项，而不是那个被放任漂浮着的一项。',
    ),
  ],
};

export default entry;
