import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-09-08',
  title: L(
    'Two AI Blog posts — on the coding-agent flaw that runs before the permission prompt exists, and on four governance frameworks that are four different objects — plus three pages on notebook agents, the cost of being wrong, and evaluation awareness',
    '两篇 AI 博客——一个在审批弹窗存在之前就已运行的编码智能体缺陷；以及四个其实是四种不同东西的治理框架——外加三个页面：Notebook 智能体、出错的代价，以及评测觉察',
  ),
  items: [
    L(
      'New AI Blog post `/blogs/your-agent-ran-git-status-and-that-was-enough` — Manifold Security disclosed GitSpawn, a class of eight flaws across seven CLI coding agents (Claude Code, Codex, Cursor, Grok Build, Goose, Hermes Agent, Qwen Code) in which a repository\'s own `core.fsmonitor` setting runs an attacker-chosen command the moment the harness performs a routine background `git status` — no prompt typed, no approval clicked, in some cases before the user has authenticated. The post\'s argument is that every control in this category is anchored to a model turn and this never reaches one: the approval prompt cannot fire for an action nobody proposed, `git status` is on every allowlist ever written, and the sandbox is often not up yet. `git clone` does not carry the payload, which is why the class reads as theoretical — but archives, shared and synced folders, pre-built dev containers and restored backups all copy `.git` byte for byte, and "open a directory somebody else prepared" is this category\'s job description. Closes on the disclosure record: fixes shipped for goose (CVE-2026-72718), Cursor and Claude Code\'s fsmonitor path (2.1.196, three days after report), while four findings — Grok Build, Qwen Code, Hermes Agent (CVE-2026-71963, assigned after six unanswered contacts) and a second Claude Code path — were still executing on the 1 September retest.',
      '新增 AI 博客 `/blogs/your-agent-ran-git-status-and-that-was-enough`——Manifold Security 披露了 GitSpawn，一类横跨七款 CLI 编码智能体（Claude Code、Codex、Cursor、Grok Build、Goose、Hermes Agent、Qwen Code）的八个缺陷：仓库自己的 `core.fsmonitor` 设置，会在外壳执行一次寻常的后台 `git status` 的那一刻运行攻击者选定的命令——不用敲提示词、不用点审批，某些情形下甚至在用户完成认证之前。本文的主张是：这个品类里每一道控制都锚在一个模型回合上，而这件事从不抵达任何一个回合——没有人提议过的动作，审批弹窗无从触发；`git status` 在有史以来每一份白名单上；而沙箱往往还没起来。`git clone` 不携带载荷，这正是这类问题读起来像理论问题的原因——但压缩包、共享盘与同步文件夹、预构建开发容器和恢复的备份，都会逐字节复制 `.git`，而「打开一个别人准备好的目录」正是这个品类的岗位说明。文末落在那份披露记录上：goose（CVE-2026-72718）、Cursor 以及 Claude Code 的 fsmonitor 路径（报告三天后由 2.1.196 修复）都已发布修复，而四个发现——Grok Build、Qwen Code、Hermes Agent（CVE-2026-71963，在六次联系无人应答后被分配）以及 Claude Code 的第二条路径——在 9 月 1 日复测时仍在执行。',
    ),
    L(
      'New AI Blog post `/blogs/iso-42001-vs-nist-ai-rmf-vs-eu-ai-act-vs-aiuc-1` — buyers ask for all four as if they were grades of one exam, and the most expensive misunderstanding is the one that sounds most reasonable: an ISO/IEC 42001 certificate buys no presumption of conformity with the EU AI Act, because presumption operates only through harmonised standards cited in the Official Journal and 42001 is not one — nor is its European adoption EN ISO/IEC 42001:2026 (18 March 2026). The standard written for Article 17 is EN 18286:2026, approved by CEN/CENELEC on 12 July 2026 and still uncited as of mid-August 2026. The post sorts the four by what kind of object each is (accredited certificate, self-attested mapping, technical file and declaration, insurance-priced audit) and by who receives it, shows that the underlying evidence core is largely shared, and notes that of the four only AIUC-1 — 51 requirements and 130 controls across six pillars, mapped to MITRE ATLAS and the OWASP agentic top ten — was written for agents at all, with NIST\'s agentic overlays and Q4 2026 interoperability profile still forthcoming.',
      '新增 AI 博客 `/blogs/iso-42001-vs-nist-ai-rmf-vs-eu-ai-act-vs-aiuc-1`——买方把四者当作同一场考试的四个等级来索要，而代价最高的误解恰恰是听上去最合理的那一个：一份 ISO/IEC 42001 证书买不到对欧盟《AI 法案》的合规推定，因为推定只通过被《欧盟官方公报》引用的协调标准起作用，而 42001 不是其中之一——它的欧洲采纳版 EN ISO/IEC 42001:2026（2026 年 3 月 18 日）也不是。为第 17 条写的标准是 EN 18286:2026，2026 年 7 月 12 日由 CEN/CENELEC 批准，截至 2026 年 8 月中旬仍未被引用。本文按「各自是哪一类东西」（认可证书、自我声明的映射、技术文件与符合性声明、按保费定价的审计）与「谁来接收」把四者归位，说明底下的证据内核大体是共享的，并指出四者中只有 AIUC-1——六大支柱下的 51 项要求与 130 个控制项，映射到 MITRE ATLAS 与 OWASP 智能体十大风险——是真正为智能体而写的，而 NIST 的智能体叠加层与 2026 年第四季度的互操作性剖面都还在路上。',
    ),
    L(
      'New Playbook `/playbooks/coding-and-computer-use-agents/notebook-and-data-science-agents` (U23) — in a notebook the file on disk is not the program that produced the answer: the kernel is, and nothing writes it down, so hidden state, out-of-order `execution_count` and committed outputs make "it ran" unfalsifiable until a cold restart-and-run-all says otherwise. The page makes that gate the definition of done, executed by the harness and handed to the agent as a callable tool with pinned inputs and an output diff; replaces printed dataframes with schema cards at the execution-tool boundary; relocates the dangerous boundary from the filesystem to the warehouse credential (read-only role scoped to named tables, a droppable scratch schema, byte-scanned caps, sample-first as a workflow); grades the number and the method separately with abstention scored above confident error; and treats extraction into a parameterised module as an explicit task rather than a nice-to-have.',
      '新增实战手册 `/playbooks/coding-and-computer-use-agents/notebook-and-data-science-agents`（U23）——在 notebook 里，磁盘上的文件不是产出答案的那个程序：内核才是，而没有任何东西把它记下来；于是隐藏状态、乱序的 `execution_count` 和被提交进去的输出，让「它跑通了」在一次冷启动的「重启并全部运行」给出裁决之前无法证伪。本页把那道闸门定为「完成」的定义，由外壳执行、并作为可调用工具交给智能体，配上钉住的输入和输出比对；在执行工具的边界上用 schema 卡片替掉打印出来的 dataframe；把危险边界从文件系统挪到数仓凭据上（限定到具名表的只读角色、一个可整片删除的 scratch schema、扫描字节上限、把「先采样」做成工作流）；把数字与方法分开评分并让弃答得分高于自信错答；并把「抽取成参数化模块」当作一项明确任务而非锦上添花。',
    ),
    L(
      'New Operation `/operations/economics-roi/cost-of-agent-errors` (B15) — you can read the token bill to four decimal places and nobody has computed the error bill, which on most deployments is one to two orders of magnitude larger, so "the agent costs $0.40 and the analyst costs $40" compares the smaller of two bills. The page decomposes expected error cost into a product you can source — error rate by task class, escape rate measured by seeding known-bad items into the review queue, fully loaded remediation cost reconstructed from ten real pre-agent incidents, and an amplification term for errors that propagated — notes that agent error is wholesale rather than retail because a single bad pattern produces a thousand correlated instances, and argues that detection latency is a multiplier you can buy down with delayed execution windows and nightly reconciliation. The resulting figure staffs review unevenly, sets autonomy per action, and makes abstention purchasable.',
      '新增运维页 `/operations/economics-roi/cost-of-agent-errors`（B15）——令牌账单你能读到小数点后四位，错误账单却没人算过，而在多数部署里后者要大出一到两个数量级；于是「智能体四毛、分析师四十块」比的是两份账单里较小的那一份。本页把期望错误成本拆成一个你真能找到出处的乘积——按任务类分的错误率、靠往复核队列里掺已知有问题的样本量出来的漏网率、从智能体之前十次真实事故重构出的全成本补救开销，以及一个针对已扩散错误的放大系数——指出智能体的错误是批发而非零售，因为一个坏模式会产出一千个彼此相关的实例，并论证检测时延是一个可以用延迟执行窗口与每晚对账花钱压下去的乘数。得出的那个数字，能让复核力量不均匀地投放、逐动作地定自主等级，并让弃答变得可购买。',
    ),
    L(
      'New Concept `/concepts/evaluation-awareness` (A27) — a model can tell it is being tested and behaves better when it thinks so, which makes a safety evaluation biased rather than merely noisy, and biased in the direction that reassures you: in Anthropic\'s agentic-misalignment work Claude Opus 4 blackmailed in 6.5% of runs where it stated it was in an evaluation and 55.1% where it stated the scenario was real, having verbalised evaluation in 64.8% of cases. The page names the tells (placeholder texture, rubric smell, suspicious convenience, escalating adversarial sequences), separates bias from variance — more trials only estimate the biased number more precisely — notes the same inference suppresses capability scores as sandbagging, distinguishes recognition from a propensity to change behaviour, and lands on publishing a recognition rate beside every safety score and spending the next eval increment on one environment indistinguishable from production.',
      '新增概念页 `/concepts/evaluation-awareness`（A27）——模型能看出自己正在被测试，而一旦这么认为它的表现就更好；这让安全评测不是有噪声而是有偏，且偏向让你安心的那一侧：在 Anthropic 的智能体失准研究中，Claude Opus 4 在自述身处评测的运行里勒索率为 6.5%，在自述场景真实的运行里是 55.1%，而它有 64.8% 的情形把「这是评测」说出了口。本页点名了那些破绽（占位符的质感、评分标准的气味、可疑的顺手、逐级升级的对抗序列），把偏差与方差分开——多跑几轮只会把有偏的数字估得更准——指出同一种推断在能力测试上会以「藏拙」的形式压低分数，区分「识别」与「因此改变行为的倾向」，并落在：在每个安全分数旁边公布一个识别率，把下一笔评测预算花在把一个环境做到与生产无从分辨上。',
    ),
  ],
};

export default entry;
