import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-09-20',
  title: L(
    'Two AI Blog posts — on the first agentic breach to arrive as regulatory paperwork, and on the four TypeScript agent frameworks that differ only in where the run lives — plus three pages on index freshness, serving agent traffic, and reading identifiers aloud',
    '两篇 AI 博客——一篇讲第一起以监管文书形式抵达的智能体入侵，一篇讲那四个只在「运行活在哪里」上有分歧的 TypeScript 智能体框架——外加三个页面：索引新鲜度、服务智能体流量，以及把标识符念出来这件事',
  ),
  items: [
    L(
      'AI Blog — “The first agentic breach arrived as paperwork”: Spain’s AEPD published, on 15 September, the first personal-data breach notification it has received in which an AI agent executed the attack — probing generic files, achieving a valid login, then autonomously searching the application for vulnerabilities from inside that authenticated session before modifying personal data and reaching invoices. The incident is unremarkable as tradecraft; the provenance is not. Every prior piece of public evidence came from the attacker’s side — a vendor’s disruption report, a sensor network, a leaked operator directory — and this one came from the victim, under a statutory 72-hour duty, independent of whether any model provider ever found out. That makes a breach register the only agent-incident dataset that is compelled, defender-side and adversary-independent, which is why the AEPD’s own caveat matters more than the attack: one notification is not a trend, and at a thousand it still will not be, because the distinguishing attribute lives in a free-text narrative that no form asks about. The same intrusion can start three clocks under three regimes with three recipients, and none of the three forms has a field for autonomous execution. Write the agent-ness into your own filing as observations rather than conclusions, make sure you can still answer what was read rather than only what was written, and shorten what one authenticated session may reach.',
      'AI 博客《第一起智能体入侵是以一份文书抵达的》：西班牙 AEPD 于 9 月 15 日公布了它收到的第一份「由 AI 智能体执行攻击」的个人数据泄露通报——先探查通用文件、完成一次有效登录，随后在那个已认证会话内部自主搜索应用漏洞，接着修改个人数据并拿到发票。作为攻击手法，这起事件平平无奇；作为证据来路，它不是。此前每一条公开证据都来自攻击方那一侧——厂商的封禁报告、一张传感器网络、一个泄露出来的攻击者目录——而这一条来自受害方，出于 72 小时的法定义务，且与「有没有哪家模型厂商知情」无关。这让泄露登记册成为唯一一个被强制、来自防守方、且不依赖对手配合的智能体事件数据集；也正因如此，AEPD 自己那句告诫比这次攻击更要紧：一份通报不成趋势，而到了一千份它依然不成，因为那个区分性的属性活在一个没有任何表单问起过的自由文本叙述栏里。同一次入侵可以在三套制度下启动三个时钟、送往三个收件方，而三张表单里没有一张有「自主执行」这个字段。请把「智能体属性」以观察而非结论的形式写进你自己的申报，确保你还答得上「什么被读过」而不只是「什么被写过」，并收紧一个已认证会话被允许够到的范围。',
    ),
    L(
      'AI Blog — “Mastra vs LangGraph.js vs VoltAgent vs the AI SDK”: the four leading TypeScript agent frameworks agree almost completely on the tool loop and disagree on one thing — where the run lives when the HTTP request ends. The AI SDK (7.0.107, 18 September) persists nothing until you adopt a durable runtime, and its own troubleshooting page is the cleanest evidence that this is the real axis: with resumable streams on, a client-side abort is indistinguishable from a disconnect, so stop() reconnects instead of stopping. LangGraph.js (1.4.16) checkpoints every superstep into a database you already run, which is the most portable answer and the most opinionated about control flow; Mastra (1.67.0) writes a run snapshot into storage it manages, buying the most capability per line of code and concentrating the most in one vendor’s vocabulary, with enterprise directories that are source-available rather than Apache 2.0; VoltAgent (2.10.0) persists suspension and memory and spends its differentiation on a self-hostable console. Stable releases in the 90 days to 20 September: 230, 13, 26 and 5 respectively — a lockfile budget, not a quality score. And none of the four makes a resumed tool call idempotent; that contract is still yours.',
      'AI 博客《Mastra、LangGraph.js、VoltAgent 与 AI SDK》：四个领先的 TypeScript 智能体框架在工具循环上几乎完全一致，分歧只有一处——HTTP 请求结束之后，这趟运行活在哪里。AI SDK（7.0.107，9 月 18 日）在你接受一个持久化运行时之前什么都不留，而它自家的疑难解答页正是「这才是真轴」的最干净证据：开启可恢复流之后，客户端的 abort 与断连无从区分，于是 stop() 会重连而不是停止。LangGraph.js（1.4.16）在每个 superstep 把检查点写进你本就在跑的数据库，这是最可移植的答案，也是对控制流最有主张的一个；Mastra（1.67.0）把运行快照写进它托管的存储，让每行代码买到的能力最多，也让最多的东西集中在一家厂商的词汇表里，且其企业版目录是源码可见而非 Apache 2.0；VoltAgent（2.10.0）持久化挂起与记忆，并把差异化预算花在一套可自部署的控制台上。截至 9 月 20 日的 90 天内稳定版发布数分别为 230、13、26 与 5——这是 lockfile 的预算，不是质量评分。而四者没有一个能让恢复后的工具调用变得幂等；那份契约仍然是你的。',
    ),
    L(
      'Deep-Dives — Index Freshness & Invalidation: a stale index never errors, it answers confidently with a citation attached, and the three ways a corpus goes stale have different blast radii. An out-of-date paragraph is embarrassing and self-correcting; a deleted document that still answers is a correctness incident, because someone withdrew it on purpose and the citation now lends authority to text nobody stands behind. So updates can ride a schedule and deletions need an event. The nightly full re-crawl is a bill that scales with the corpus while the thing it chases scales with the change rate — a million documents at 0.5% daily churn is 200× wasted work for a twelve-hour mean staleness — and the change feeds that fix it are reliably bad at deletions, which arrive as silent disappearances, 403s your worker retries for three days, renames that look like deletes, and cursor gaps. Pair the stream with an ID-only reconciliation sweep, write a tombstone before compaction so removal is instant and auditable, and remember that summaries, graph nodes, agent memory and semantic caches inherit no deletion at all. Then measure change-to-queryable per source at p99, report deletion separately, and alert on the absence of events.',
      '深入解析 — 索引新鲜度与失效：陈旧的索引从不报错，它会带着引用自信地作答，而语料变陈旧的三种方式爆炸半径各不相同。一段过时的文字是尴尬，而且会自我纠正；一份已删除却仍在作答的文档是正确性事故，因为有人是有意把它撤回的，而此刻引用反倒把权威赋予了一段无人背书的文字。所以更新可以搭时刻表，删除必须走事件。每夜全量重爬是一张随语料规模伸缩的账单，而它追的那个东西随变更速率伸缩——一百万份文档、每日 0.5% 的变动率，就是 200 倍的无用功，换来十二小时的平均陈旧度；而用来修它的变更流，在删除这件事上可靠地不可靠：删除以无声消失、被 worker 重试三天的 403、看起来像删除的重命名，以及游标断档的形式抵达。请给事件流配一次只取 ID 的对账扫描，在压实之前先写墓碑好让移除既即时又可审计，并记住摘要、图节点、智能体记忆与语义缓存一个都不继承删除。然后按来源以 p99 测量「变更到可检索」，把删除单独报，并对「没有事件」告警。',
    ),
    L(
      'Operations — Serving Agent Traffic: your API rests on two assumptions that agents break — that a frustrated client stops, and that a confused client reads documentation. An agent’s retry is its control loop, so a 429 is a pause rather than a signal and a badly worded 400 is a prompt, which makes the error body the highest-leverage and least-maintained text on your surface. Automated requests crossed 57.5% of HTML traffic on Cloudflare Radar in 2026, a year ahead of its own forecast, so the first work is a label — human, verified agent, unverified automation — because every latency percentile and conversion metric you own is currently averaging two populations. Then: always send a truthful Retry-After and distinguish “too fast” from “out of quota” in the body; never return a retryable status for a permanent condition; deduplicate on declared operation and resource rather than on a body hash, because agents rephrase between attempts; publish an idempotency contract in the schema, since the caller will retry a write it could not confirm; and price the operation rather than the session.',
      '运维 — 服务智能体流量：你这套 API 建立在两个被智能体打破的假设上——受挫的客户端会停下来，困惑的客户端会去读文档。智能体的重试就是它的控制循环，所以 429 是一次暂停而不是一个信号，一句措辞糟糕的 400 是一段提示词；这让错误响应体成为你整个表面上杠杆最大、也维护得最差的一段文字。2026 年，Cloudflare Radar 上自动化请求已越过 HTML 流量的 57.5%，比它自家的预测早了一年；所以第一件事是打标签——人类、已验证智能体、未验证自动化——因为你手上的每一个延迟分位数与转化指标，当下都在把两个总体平均在一起。接着：永远带上真实的 Retry-After，并在响应体里区分「太快了」与「配额用完了」；永远不要为永久性状况返回可重试的状态码；按声明的操作与资源去重，而不是按请求体哈希，因为智能体会在两次尝试之间改写措辞；把幂等契约写进 schema 公布出来，因为调用方一定会重试一次它无法确认的写入；并且为操作而不是为会话定价。',
    ),
    L(
      'Playbooks — Alphanumerics Over Voice: your transcription is excellent and your order lookups fail, because a booking reference is the one thing in the call with no language model behind it — exact match is per-character accuracy raised to the length, so 97% per character is 73.7% on ten characters and 90.4% even at 99%. Provider spelling modes, keyword biasing and format-constrained decoding are worth an afternoon and buy percentage points; nothing removes the E-set confusions (B, C, D, E, G, P, T, V, Z) over an 8 kHz channel. What changes the shape is refusing to hear the string at all: identify the caller first, resolve against the two or three candidates their phone number already gives you, and ask “the order from Tuesday, or the one to Manchester?” instead of asking them to spell. When the set really is unbounded, capture in chunks of three or four with per-chunk readback, never re-ask for the whole string, and offer the keypad before the first failure rather than after the second. Set the confirmation bar by consequence, not by confidence — and take the finding upstream, because dropping the confusable letters and adding a check character is a change to the identifier format, not to the speech stack.',
      '实战手册 — 把字母数字串念给智能体听：你的转写很出色而订单查询照样失败，因为在整通电话里，预订号是唯一一样背后没有语言模型的东西——完全匹配是每字符准确率的长度次方，于是每字符 97% 在十个字符上是 73.7%，即便到 99% 也只有 90.4%。厂商的拼读模式、关键词偏置与按格式约束解码值得花一个下午，但只买到几个百分点；在 8 kHz 通道上，没有任何办法能消掉 E 集合（B、C、D、E、G、P、T、V、Z）的混淆。真正改变形状的，是干脆不去「听」那串字符：先确定来电者，拿他们的电话号码本就给你的那两三个候选去解析，并且问「是周二那张单，还是寄往曼彻斯特那张？」，而不是请他们拼读。当集合确实无界时，按三到四个字符一组采集、逐组复述，永远不要让人把整串再念一遍，并且在第一次失败之前而不是第二次失败之后就把键盘这条路递过去。确认的门槛按后果定而不按置信度定——并把结论往上游带，因为去掉易混淆字母、加一位校验字符，改的是标识符格式，不是语音栈。',
    ),
  ],
};

export default entry;
