import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-09-29',
  title: L(
    'Two AI Blog posts — on the agent-safety platform whose tamper-proof half has no ship date, and on which runtime sensor can actually tell an agent’s tool calls apart — plus three pages on the reference monitor, forgetting as a write-path problem, and taking a card payment in a voice call',
    '两篇 AI 博客——一篇讲那套「防篡改的一半没有发货日期」的智能体安全平台，一篇讲哪个运行时传感器真能分辨出智能体的工具调用——外加三个页面：引用监视器、把遗忘当作写路径问题，以及在一通语音电话里收一笔卡付款',
  ),
  items: [
    L(
      'AI Blog — “The tamper-proof half did not ship”: on 28 September 2026 NVIDIA launched the Open Agent Safety Platform in two pieces, and only one of them exists. OpenShell is Apache-2.0 Rust on GitHub today, building its sandbox from Landlock LSM filesystem rules and a seccomp BPF syscall filter rather than from a container runtime — declarative YAML applied out of process so a compromised agent cannot rewrite its own rules, a default profile that denies ptrace, mount, pivot_root, namespace-unshare clones and raw sockets with EPERM, rules that survive fork and exec, and live policy updates. Sentry, the out-of-band watchdog on a BlueField-4 DPU that the host cannot address and that quarantines a straying agent in milliseconds, is a reference design with no announced date, and more than 100 organisations are named around it including Anthropic, Microsoft, CrowdStrike, Palo Alto Networks, SAP, Salesforce and ServiceNow. The claim that this would have prevented July’s Hugging Face intrusion splits cleanly by layer and that split is the story: the attack used permitted HTTP GET to allowed hostnames, which no filesystem or syscall policy is configured to block, while its signature was volume and shape, which is exactly what a DPU watching flows sees well. Underneath sits a trade-off no vendor can escape — every step you move a control outward for tamper-resistance, its vocabulary gets coarser, so adopt kernel-level policy now, write the egress policy OpenShell does not give you, get one out-of-band observer even without a DPU, and decide what quarantine means before you have one.',
      'AI 博客《防篡改的那一半没有交付》：2026 年 9 月 28 日，NVIDIA 把 Open Agent Safety Platform 分成两块发布，而其中只有一块真的存在。OpenShell 今天就以 Apache-2.0 的 Rust 代码摆在 GitHub 上，它用 Landlock LSM 文件系统规则加 seccomp BPF 系统调用过滤器搭沙箱、而不是靠某个容器运行时——声明式 YAML 在进程外施加，所以一个被攻破的智能体改不了自己那些规则；默认档位以 EPERM 拒绝 ptrace、mount、pivot_root、带命名空间 unshare 的 clone 与裸 socket；规则在 fork 与 exec 之后依然有效；策略还能实时更新。而 Sentry——那个跑在主机寻址不到的 BlueField-4 DPU 上、能在毫秒级隔离越界智能体的带外看守——是一份没有公布日期的参考设计；围着它点名了逾 100 家机构，包括 Anthropic、Microsoft、CrowdStrike、Palo Alto Networks、SAP、Salesforce 与 ServiceNow。「这本可以阻止 7 月那次 Hugging Face 入侵」这条主张按层一掰就很干净，而这一掰正是故事本身：那次攻击用的是发往被允许主机名的被允许 HTTP GET，没有哪套文件系统或系统调用策略会被配成去拦它；而它的特征是量与形，那恰恰是一块盯着流的 DPU 看得清的东西。底下压着一笔没有哪家厂商躲得开的取舍——你为了防篡改每把一项控制往外挪一步，它的词汇就更粗一层。所以：现在就采用内核级策略、把 OpenShell 不给你的那条出站策略写出来、就算没有 DPU 也弄一个带外观察者，并在你真有隔离能力之前先决定「隔离」意味着什么。',
    ),
    L(
      'AI Blog — “Falco vs Tetragon vs Tracee vs KubeArmor”: rule-library size decides nothing here and neither does detection versus prevention, because Kubernetes runtime security assumes a workload has one describable behavioural baseline and a coding agent’s baseline is anything a developer might do — point Falco’s default ruleset at an agent node and the first successful task trips the shell, package-manager and write-below-etc detections. So the axis is what a sensor can tell apart: process lineage, per-process rather than per-image policy, and a run identifier stamped somewhere the kernel can see (a cgroup per run, a uid per session) so anonymous syscalls become attributable actions. Falco (Sysdig 2016, CNCF 2018, graduated 2024) is the discovery tool — run it alert-only for a fortnight and the output is a behavioural inventory; Tetragon is native process lineage plus an override that stops a call before its body executes, at roughly 6.5 millicores against Falco’s 430 and Tracee’s 92 in one 2025 measurement; Tracee is forensics, with artefact capture and escape and injection signatures; KubeArmor compiles a declarative allow-list to AppArmor, SELinux or BPF-LSM so the kernel denies inline. The second decision is the one nobody frames: killing a tool subprocess does not stop an agent, it hands the loop an unexplained crash and a reason to retry differently, and Tetragon’s own docs note a SIGKILL does not guarantee the in-flight operation stopped — so prefer a denial that returns EPERM, make it reach the model as readable text, and reserve the kill for the run.',
      'AI 博客《Falco、Tetragon、Tracee 与 KubeArmor 对比》：在这件事上规则库大小什么也决定不了，「检测 vs 阻止」也一样，因为 Kubernetes 运行时安全假定一个工作负载有一条可描述的行为基线，而一个编码智能体的基线是「一个开发者可能做的任何事」——把 Falco 的默认规则集指向一个智能体节点，第一个成功任务就会触发「容器里起 shell」、「跑包管理器」与「在 etc 之下写入」这些检测。所以那根轴是「传感器能分辨什么」：进程谱系、按进程而不是按镜像的策略，以及一个盖在内核看得见之处的运行标识（按运行划一个 cgroup、按会话给一个 uid），好让匿名的系统调用变成可归因的动作。Falco（2016 年生于 Sysdig、2018 年进 CNCF、2024 年毕业）是那个勘探工具——以纯告警模式跑两周，输出就是一份行为清单；Tetragon 提供原生的进程谱系，外加一个能在系统调用主体执行前把它拦下的 override，而在一份 2025 年的测量里它约 6.5 毫核、对比 Falco 的 430 与 Tracee 的 92；Tracee 是取证，带制品抓取与逃逸、注入特征；KubeArmor 把一张声明式允许清单编译到 AppArmor、SELinux 或 BPF-LSM，让内核就地拒绝。而第二个决定是那个没人正确表述过的：杀掉一个工具子进程并不能停下一个智能体，它只是给那个循环递去一次无从解释的崩溃与一个换个方式重试的理由；而 Tetragon 自己的文档就提到 SIGKILL 不保证那次正在飞的操作被停住了——所以请优先选那种返回 EPERM 的拒绝、让它以可读文字抵达模型，并把「杀」留给整次运行。',
    ),
    L(
      'Concepts — The Reference Monitor: Anderson’s 1972 test asks three questions of any control — does every path to the protected operation pass through it, can the thing being mediated modify or bypass it, and is it small enough to verify — and almost every agent control fails at least one, usually the second. Score your own stack and the pattern is consistent: a rule in the system prompt fails all three and is still the industry’s most common “control”, a check in the tool wrapper is defeated by the code execution that is a coding agent’s product, and the second path around an approval is usually a retry. Tamper-proofness is a statement about trust domains, so rank each mechanism by what the agent would have to compromise to reach it — same context, same process, same host, kernel-enforced, different machine, different processor. The part usually left out is the price: a tool-wrapper check knows the user, task, plan and arguments, a seccomp filter knows syscall numbers, an egress proxy knows destinations and bytes, so every step outward trades descriptive power for enforcement. Hence the method — restate the invariant as an effect until some layer can enforce it, install the mechanism before the agent rather than around it, fail closed, log at the monitor rather than at the caller, and keep the policy small enough that “verifiable” stays true.',
      '概念 — 引用监视器：Anderson 1972 年那项检验对任何一道控制问三个问题——通往受保护操作的每条路径是否都经过它、被调解的那个对象能否修改或绕过它、以及它是否小到可被验证——而几乎每一项智能体控制都至少挂掉一条，通常是第二条。给你自己的技术栈打一遍分，规律很一致：写在系统提示词里的规则三条全挂，而它仍是这个行业最常见的「控制」；写在工具封装里的检查会被代码执行击破，而代码执行对编码智能体就是产品本身；而绕过一次审批的那第二条路，通常就是一次重试。防篡改是一句关于信任域的话，所以请按「智能体得攻破什么才能碰到它」给每套机制排序——同一上下文、同一进程、同一主机、由内核强制、不同机器、不同处理器。通常被漏掉的那部分是价钱：工具封装里的检查知道用户、任务、计划与参数，一个 seccomp 过滤器知道系统调用号，一个出站代理知道目的地与字节数，所以每往外挪一步都是用描述力去换强制力。于是方法就出来了——把不变式重述成一种「效果」，直到某一层能强制它；把机制装在智能体之前而不是围在它周围；失败拦截；在监视器处而不是在调用方处记日志；并让策略小到足以让「可验证」这条仍然成立。',
    ),
    L(
      'Deep-Dives — Forgetting &amp; Supersession: a memory system that only accumulates degrades into a store where the wrong answer outranks the right one, and no recall tuning gets it back — a small open model RL-trained specifically to answer from a fact’s current value roughly doubled its held-out accuracy and landed at 16.7%, meaning five answers in six still cited something the user had corrected. Forgetting is five structurally different mutations with five different correctness conditions — supersession (the new fact wins AND the old one leaves top-k), decay, amnesia (a width problem: siblings must survive), purge (by identifier, because semantic similarity is the wrong primitive), drift (a chain where only the latest wins) — and TTL implements exactly one of them. The read side cannot fix this: a superseded fact is an excellent candidate on merit, a recency boost only makes a strong match slightly weaker, both facts land in context and the decision becomes an attention problem. Placing model assistance at the mutation-time control plane instead reaches 91.7–93.2% forgetting accuracy, because intent exists for exactly one instant. Then identity is the load-bearing dependency (prefix collision, partial supersession), the minimum schema is nine fields, and rankings invert with tenure — a curated map leading at three weeks falls 96% to 72% by nine weeks while a provenance-typed graph rises to 90%, so a short-horizon benchmark reverses the answer.',
      '深入解析 — 遗忘与取代：一个只会累积的记忆系统会退化成一个「错答案排在对答案前面」的存储，而再怎么调召回也救不回来——一个专门用强化学习训练去按事实当前取值作答的小型开源模型，把留出准确率大致翻了一倍、最后落在 16.7%，也就是六个回答里仍有五个引用的是用户已纠正过的东西。遗忘是五种结构上不同的变更、各有五种不同的正确性条件——取代（新事实要赢、而且旧的要离开 top-k）、衰减、实体级遗忘（一个宽度问题：邻居必须活下来）、硬删除（按标识符，因为语义相似度是错的原语）、漂移（一条只有最新者获胜的链）——而 TTL 恰好只实现其中一种。读那一侧修不了这件事：一条被取代的事实是凭实力站上来的好候选，一个时新度加权只是把强匹配变得略弱一点，两条事实双双落进上下文，于是决策变成了一个注意力问题。反过来，把模型辅助放在变更时刻的控制平面上能达到 91.7–93.2% 的遗忘准确率，因为意图只存在恰好一瞬。接下来，身份是那个承重依赖（前缀碰撞、部分取代），最小模式是九个字段；而排名会随在役时长反转——一个在三周时领先的策划式映射到九周时从 96% 掉到 72%，而一个带来源类型的图升到 90%，所以一份短跨度基准会把答案反过来。',
    ),
    L(
      'Playbooks — Card Payments Over Voice: every contact-centre descoping technique works by removing a listener from the audio path, and DTMF suppression works precisely because the human you are excluding is not the thing driving the conversation — but a voice agent is not a listener on the call, it is the call, so suppressing the digits also removes its input. One spoken card number therefore lands in six artefacts at once: the recording, the ASR transcript (often the speech vendor’s too), the model prompt in an inference provider’s request logs, tool-call arguments, a trace span and a CRM summary — and PCI DSS says CVV and PIN may never be stored after authorisation, anywhere. Three architectures keep the data out of the model and differ only in what they cost the caller: media-layer suppression with the agent narrating, transfer to a deterministic payment module, or an out-of-band link. The change to make today is the tool signature — replace anything that can take a PAN with start_card_collection / get_collection_status / authorize(session_id, …) so a card number is not expressible in what the model can emit, then grep your traces for Luhn-valid strings. Also: callers will read the number aloud, so suppress before recognition and fail closed on detection; and keep a human path with DTMF masking, because a keypad-only flow terminally excludes the cohorts who have the fewest alternatives.',
      '实战手册 — 在语音里收卡付款：呼叫中心的每一项降范围手法靠的都是把某个听者从音频通路里挪走，而 DTMF 抑制之所以成立，恰恰因为你要排除的那个人并不是在驱动这段对话的那个东西——可一个语音智能体不是这通电话上的一个听者，它就是这通电话，所以把数字抑制掉的同时也抑制掉了它的输入。于是一个被念出来的卡号会同时落进六件产物里：录音、ASR 转写稿（往往还有语音厂商那份）、推理厂商请求日志里的模型提示词、工具调用参数、一条追踪 span 与一份 CRM 摘要——而 PCI DSS 明说 CVV 与 PIN 在授权之后在任何地方都不得存储。有三种架构能把数据挡在模型之外，而它们的差别只在于让来电者付出多少代价：在媒体层抑制、智能体继续解说；转给一个确定性的支付模块；或者走一条带外链接。今天就该改的是工具签名——把任何能接受 PAN 的工具换成 start_card_collection / get_collection_status / authorize(session_id, …)，让卡号在模型能吐出的东西里无法被表达，然后去追踪里 grep 通过 Luhn 校验的字符串。另外：来电者一定会把号码念出来，所以请在识别之前抑制、并在检出时失败拦截；同时保留一条带 DTMF 打码的人工路径，因为一条只走键盘的流程会终局性地排除那些替代选择最少的人群。',
    ),
  ],
};

export default entry;
