import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-08-13',
  title: L(
    'Two AI Blog posts on the generative-UI standards splitting over the component catalog and on who holds the user’s token in the four connector platforms, plus four pages on generative UI, third-party tool drift, connector platforms and consent records',
    '两篇 AI 博客——生成式界面的两套标准在“组件目录归谁”上分道扬镳，以及四家连接器平台里用户的令牌握在谁手里——外加四个页面：生成式界面、第三方工具漂移、连接器平台，以及同意记录',
  ),
  items: [
    L(
      'New blog post — *Generative UI Has Two Standards, and They Split Over Who Owns the Catalog*. MCP Apps began as SEP-1865 on 21 November 2025 and shipped on 26 January 2026 as the first official MCP extension — pre-declared HTML bundles addressed as `ui://` resources, rendered by the host in a sandboxed iframe over JSON-RPC on postMessage, live in Claude, Goose and VS Code Insiders on day one. Google introduced A2UI weeks later and reached v0.9 in July 2026, with v0.9.1 now the production release: a flat JSON list of components with ID references, mapped onto the client’s own widgets. Argues the JSON-versus-HTML framing is the least consequential difference, and the real axis is enumerability — MCP Apps is enumerable at the template level, A2UI only at the vocabulary level — which decides whether the review lands inside your design system or at a server boundary, and therefore who owns the defect. Three themeable SVGs.',
      '新博客文章——《生成式界面有了两套标准，分歧在于组件目录归谁所有》。MCP Apps 始于 2025 年 11 月 21 日的 SEP-1865，并在 2026 年 1 月 26 日作为 MCP 的第一个官方扩展发布——预先声明的 HTML 包以 `ui://` 资源寻址，由宿主在沙箱 iframe 中渲染，经 postMessage 上的 JSON-RPC 通信，首日即运行在 Claude、Goose 与 VS Code Insiders 上。Google 在数周后推出 A2UI，2026 年 7 月到达 v0.9，目前以 v0.9.1 作为生产版本：一个带 ID 引用的扁平 JSON 组件列表，映射到客户端自己的控件上。文章论证："JSON 还是 HTML"是两者之间最无关紧要的差别，真正的轴是可穷举性——MCP Apps 在模板这一粒度上可穷举，A2UI 只在词汇这一粒度上可穷举——它决定了评审落在你的设计系统内部还是落在服务器边界上，因而也决定了缺陷归谁。配三张可随主题变色的 SVG。',
    ),
    L(
      'New blog post — *Arcade vs Composio vs Pipedream Connect vs Nango: Who Holds the User’s Token*. The advertised catalogs are counted in four incompatible units — Pipedream 3,000+ APIs and 10,000+ tools, Arcade 7,500+ tools across 81 MCP servers, Composio around 1,000 applications, Nango 900+ APIs with 700+ connectors — so ranking on the headline figure compares verbs against nouns. Argues the durable purchase is the per-user token vault, which Arcade alone prices as its own line item by metering authorization challenges separately from executions, and that the metering unit is an architectural constraint: per-call pricing taxes chatty loops, execution-second credits tax duration, per-connection pricing taxes a wide consumer base. Names whose brand appears on the OAuth consent screen as the one irreversible decision, since changing the OAuth client forces every existing user to re-authorise. Three SVGs.',
      '新博客文章——《Arcade、Composio、Pipedream Connect 与 Nango：用户的令牌握在谁手里》。四家宣传的目录用了互不兼容的四种单位——Pipedream 3,000+ 个 API 与 10,000+ 个工具，Arcade 81 个 MCP 服务器上的 7,500+ 个工具，Composio 约 1,000 个应用，Nango 900+ 个 API 与 700+ 个连接器——所以按头条数字排座次，等于拿动词去比名词。文章论证：真正经久的那笔采购是按用户存放的令牌保险库，而只有 Arcade 把它单列计价，把授权挑战与执行分开计量；并论证计量单位本身就是一项架构约束——按次计费向话多的循环课税，按执行秒数的 credit 向时长课税，按连接数计费则向宽广的消费级用户盘课税。文章把"OAuth 同意页面上出现谁的品牌"点名为那个唯一不可逆的决定，因为换掉 OAuth 客户端会逼着每一个既有用户重新授权。配三张 SVG。',
    ),
    L(
      'New Playbook (Agent UX &amp; Human Interaction) — *Generative UI &amp; Agent-Rendered Surfaces*. The moment an agent renders a screen instead of describing one, the test matrix stops being finite. Lays out four levels of agent authorship — prose, selection, composition, installation — and argues selection is the rung teams skip and should exhaust first, since it solves most of the real problem while staying fully enumerable. Treats the component catalog as a contract with an untrusted caller: every component total over its prop space, validation at the boundary rather than inside components, and an explicit render for unknown component types, which is what prevents the characteristic blank-region failure. States the governing rule — a generated surface may display anything and decide nothing — and closes on testing it as a distribution: snapshot the payload rather than the pixels, replay a golden set through the renderer in CI, and keep a flag back to prose.',
      '新增实战手册（智能体 UX 与人机交互）——《生成式界面与智能体渲染的界面》。智能体一旦开始渲染界面而不是描述界面，测试矩阵就不再有限。文章列出智能体撰写权的四档——散文、挑选、组合、安装——并论证"挑选"是团队会跳过、却应当先榨干的那一档，因为它解决了真实问题的大部分，同时保持完全可穷举。文中把组件目录当作一份与不可信调用方签的合同：每个组件在其 prop 空间上行为完备、在边界处而非组件内部做校验、对未知组件类型有显式渲染——正是后者防住了那个标志性的"空白区域"故障。文章给出统摄性的一条规则——生成出的界面可以展示任何东西，但不能决定任何东西——并以"把它当作一个分布来测"收尾：快照载荷而不是像素、在 CI 里把黄金样本重放过渲染器，并留一个退回散文的开关。',
    ),
    L(
      'New Operation (AgentOps) — *Third-Party Tool Drift*. A tool description is instruction text inside your context window, and someone at another company owns it — so your agent’s behaviour can change with no commit in your repository and no error in your logs. Ranks four kinds of drift by how loudly they fail and shows the ranking inverts by cost: structural breaks throw and page you, while semantic and description drift do the most damage with no error surface at all. Prescribes a build-time catalog snapshot with per-tool hashes that fails the build on an unreviewed diff, contract tests that assert enum sets, golden calls and undocumented defaults against a sandbox tenant, and the highest-value line of code on the page — stamping the catalog hash on every trace, alongside the model ID and prompt version already recorded. Ends by moving the fix out of the prompt and into a facade of your own tool names.',
      '新增运维页（AgentOps）——《第三方工具漂移》。工具描述是你上下文窗口里的指令文本，而它归另一家公司的某个人所有——于是你的智能体行为可能在仓库里没有一次提交、日志里没有一条报错的情况下发生改变。文章按"坏得有多响"给四类漂移排序，并指出这个排序按代价来看是倒过来的：结构性破坏会抛异常、会传呼你，而语义漂移与描述漂移伤害最大、却完全没有错误面。文中给出的处方是：构建期的目录快照加逐工具哈希，未经评审的 diff 就让构建失败；对着沙箱租户断言枚举集合、黄金调用与那些没有文档的默认值的契约测试；以及本页价值最高的一行代码——把目录哈希打在每条 trace 上，与你已经在记的模型 ID 和 prompt 版本并列。全文以"把修法从 prompt 里挪出来、放进一层你自己命名的门面"作结。',
    ),
    L(
      'New Concept (AI Ecosystem) — *Agent Connector Platforms*. Defines the layer that supplies an agent with per-user credentials and callable tools, and decomposes it into three bundled products: the connector catalog everyone advertises and you will outgrow, the token vault nobody markets and you would least enjoy building, and the tool-shaping layer that quietly matters because vendor APIs were designed for developers reading docs rather than models choosing under a token budget. Explains why the security property worth paying for is that the credential is injected server-side at execution and never enters the context window, so a prompt injection in a retrieved document has nothing to ask for. Closes on the decision no pricing page carries — whose name is on the consent screen — and why registering your own OAuth clients is a day of work at adoption and a re-consent campaign afterwards.',
      '新增概念页（AI 生态）——《智能体连接器平台》。定义了为智能体提供"按用户凭据"与"可调用工具"的那一层，并把它拆成捆在一起的三个产品：人人都在宣传、而你迟早会用不下的连接器目录；没人拿来营销、而你最不愿意自己造的令牌保险库；以及那个悄悄要紧的工具重塑层——因为厂商 API 是为读文档的开发者设计的，不是为在 token 预算下做选择的模型设计的。文章解释了值得为之付费的安全性质：凭据在服务端于执行时注入，从不进入上下文窗口，于是一份被检索到的文档里的提示注入无从索要。全文以那个任何定价页都不载明的决定收尾——同意授权页面上写着谁的名字——以及为什么注册你自己的 OAuth 客户端在采纳时只是一天的活，事后却是一场重新授权动员。',
    ),
    L(
      'New Operation (Governance &amp; Compliance) — *Delegated Access &amp; Consent Records*. Connecting a user account creates two things: an access token, which every system stores, and a consent — grantor, subject, scope, purpose text as displayed, client ID, timestamp — which almost nobody does, so three of the four questions teams get asked are questions about a past their credential store silently overwrites on every refresh. Separates granted scope from exercised scope from understood purpose, and argues logging the exercised subset is both the strongest answer to a security review and the evidence that makes narrowing a scope an easy decision. Treats revocation as the untested path: the token dies on a 401 while the transcript, the extracted memory, the vector index, the queued background job and every downstream effect do not, so the fan-out has to be written down and rehearsed like a restore. Notes the three re-consent triggers, including that changing the OAuth client invalidates every existing grant, and that administrator consent needs its own record shape because grantor and subject are different people.',
      '新增运维页（治理与合规）——《委托访问与同意记录》。连上一个用户账号会造出两样东西：一个访问令牌，每个系统都会存它；以及一份同意——授权人、主体、范围、当时展示的用途文本、客户端 ID、时间戳——而这个几乎没人存，于是团队被问到的四个问题里有三个问的是过去，而凭据存储每次刷新都会把过去静默覆写。文章把"被授予的范围""实际行使的范围""被理解的用途"三者分开，并论证记录实际行使的那个子集，既是面对安全评审时最有力的回答，也是让"收窄范围"成为容易决定的证据。文中把撤销当作那条没人测过的路径：令牌会在一次 401 上失效，而对话记录、被抽取的记忆、向量索引、排队中的后台任务与一切下游后果都不会，所以这次扩散必须被写下来，并像演练恢复那样演练。文章还点出重新征求同意的三个触发点——包括更换 OAuth 客户端会让每一份既有授权失效——以及管理员同意需要自己的记录形态，因为授权人与主体不是同一批人。',
    ),
  ],
};

export default entry;
