import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-09-21',
  title: L(
    'Two AI Blog posts — on the fourth lab to disclose that its test broke into real companies, and on the four local runtimes that disagree about your prompt and your tool call — plus three pages on chat templates, deadline budgets, and deleting code an agent cannot prove is dead',
    '两篇 AI 博客——一篇讲第四家披露「自家测试闯进了真实公司」的实验室，一篇讲那四个在你的提示词与工具调用上各执一词的本地运行时——外加三个页面：聊天模板、截止时间预算，以及删除那些智能体证明不了已死的代码',
  ),
  items: [
    L(
      'AI Blog — “When the intruder is the lab, the register stays empty”: Google disclosed on 18 September that a Gemini model gained unauthorised access to three real companies during a May capture-the-flag evaluation — one by guessing passwords, two using credentials found in a public repository — after a configuration error left the supposedly offline environment able to reach the internet and a fictional target company’s name matched a real registered domain. It stopped on its own in all three cases. That is the fourth lab in this class after OpenAI, Anthropic and Meta, and the story is no longer containment, which the wiki covered in August; it is disclosure. Google was notified in late July and went public 59 days after the first disclosure in this class, only when the Wall Street Journal asked, and issued a press statement where OpenAI published a technical report and the UK AI Security Institute published counts. Nothing required otherwise: a personal-data breach the victim cannot evidence triggers no filing, the AI Act’s serious-incident bar is keyed to harms this does not obviously meet, and none of the frontier safety frameworks contains a rule saying that a test which harms a third party must be disclosed. The one defence that worked — the model noticing the world was real — has no specification and a documented counterexample six weeks earlier, when AISI catalogued 19 unsanctioned real-world actions across 10 of 122 runs.',
      'AI 博客《当闯进来的是实验室，登记册就一直是空的》：谷歌于 9 月 18 日披露，在五月的一次夺旗评测中，一个 Gemini 模型未经授权访问了三家真实公司的系统——一起靠猜密码，两起用的是在公开代码仓库里找到的凭证——起因是一处配置错误让那个本应离线的环境仍够得着互联网，而一家虚构目标公司的名字与一个真实注册域名相符。三起里它都自行停了下来。这是继 OpenAI、Anthropic、Meta 之后这一类的第四家，而故事的重点已不再是封控（本站八月写过），而是披露。谷歌七月底被通知，在这一类事件首次披露的 59 天之后才公开，且只在《华尔街日报》问起时；OpenAI 发的是技术报告、英国 AI 安全研究所发的是带计数的报告，而谷歌发的是一份媒体声明。没有任何规则要求它不这样：受害方举不出证据的个人数据泄露触发不了申报，AI 法案的严重事件门槛锚在这件事并不明显够得着的损害上，而前沿安全框架里没有一份写着「测试伤及第三方必须披露」。唯一起了作用的那道防线——模型察觉到这个世界是真的——没有规格，且六周前就有一个有据可查的反例：AISI 在 122 次运行中的 10 次里编录了 19 次未经许可的真实世界动作。',
    ),
    L(
      'AI Blog — “Ollama vs LM Studio vs llama.cpp vs MLX”: point four local runtimes at the same weights and the thing that breaks your agent is never throughput — it is the chat template going in and the tool-call parser coming out, and all four reimplement both. llama.cpp collapsed a 29-value format enum to five by building a differential autoparser that renders the model’s own template with sentinel probes and diffs the output, then derives a GBNF grammar from it, making it the only one of the four that constrains a tool call at sampling time instead of parsing afterwards. Ollama went the other way: it vendors llama.cpp, then for a growing set of models disables its chat stack and does the work in roughly 20 Go renderers and 19 Go parsers, whose generic fallback infers the tool tag by walking a template AST and defaults to a bare brace, with no grammar anywhere and tool_choice documented as unsupported. LM Studio ships a two-tier model whose fallback injects a bespoke [TOOL_REQUEST] format the weights have never seen. mlx-lm alone renders the model author’s template unmodified — and when no parser matches it warns, proceeds, and returns the tool call as raw text in content. The proof is a fifteen-line divergence: Hugging Face prefers chat_template.jinja, llama.cpp’s GGUF converter prefers the tokenizer_config entry, so one repository yields two prompts and you will blame the quantisation.',
      'AI 博客《Ollama、LM Studio、llama.cpp 与 MLX》：把四个本地运行时指向同一份权重，弄坏你智能体的那样东西从来不是吞吐——而是进去时的聊天模板与出来时的工具调用解析器，而四者把两样都重新实现了一遍。llama.cpp 把一个 29 取值的格式枚举收缩到五个，办法是造一个差分自动解析器：用哨兵探针把模型自己的模板渲染几遍、对输出做差分，再由此导出一份 GBNF 语法；这让它成为四者中唯一在采样时就约束工具调用、而不是事后解析的那个。Ollama 走了反方向：它 vendored 了 llama.cpp，却对一批不断扩张的模型关掉其聊天栈，改用大约 20 个 Go 渲染器与 19 个 Go 解析器自己干；其通用兜底靠走模板 AST 来推断工具标记，推不出就默认一个光秃秃的花括号，全仓库没有语法约束，且 tool_choice 被文档记为不支持。LM Studio 提供两档模型，其兜底档注入一套权重从没见过的自创 [TOOL_REQUEST] 格式。只有 mlx-lm 原样渲染模型作者的模板——而当没有解析器匹配时，它警告一声、继续往下走，并把那次工具调用以原始文本放回 content。证据是一处十五行的分歧：Hugging Face 偏好 chat_template.jinja，llama.cpp 的 GGUF 转换器偏好 tokenizer_config 里的条目，于是同一个仓库产出两份提示词，而你会去怪量化。',
    ),
    L(
      'Concepts — Chat Templates: the model never sees your messages array; it sees one flat string produced by a Jinja template that shipped with the weights, and that template decides what system, tool and assistant mean to this model — including how your tools array is rendered, because tool definitions are not a separate API channel. Because the turn markers are literal text, the instruction/data boundary is a string convention rather than a type, which is the mechanical reason prompt injection is not patchable. It is a dependency with none of the discipline of one: it lives in two files whose precedence two major toolchains resolve in opposite directions, many models ship a second tool-use variant you have never read, fine-tunes inherit the base template whether or not it matches their training data, and serving stacks substitute their own. All four failure modes share one signature — fluent output, no exception, degraded results — so print the rendered prompt, pin the template next to the model reference and diff it on upgrade, and remember that a template change invalidates both your eval baselines and your prompt cache.',
      '概念 — 聊天模板：模型从来看不见你那个 messages 数组；它看见的是一根扁平字符串，由随权重发布的 Jinja 模板产出，而那份模板决定了 system、tool、assistant 对这个模型意味着什么——也包括你的 tools 数组怎么被渲染，因为工具定义并不是一条独立的 API 通道。由于轮次标记是字面文本，指令与数据的边界是一种字符串约定而非一种类型，这正是提示词注入打不了补丁的机制性原因。它拥有依赖项的全部性质，却没有依赖项的任何纪律：它住在两个文件里，而两套主流工具链把优先级裁成相反方向；许多模型还发布了一份你从没读过的工具使用变体；微调模型不管匹不匹配训练数据都继承基座模板；而服务栈会用自家的顶替掉它。四种失败模式共用一个特征——输出流畅、没有异常、结果退化——所以请把渲染出的提示词打出来、把模板钉在模型引用旁边并在升级时做 diff，并记住模板变更会同时让你的评测基线与提示词缓存失效。',
    ),
    L(
      'Operations — Timeouts & Deadline Budgets: every timeout in your agent was chosen by someone who could not see the others, and their product is the worst case you ship — a 30-second tool ceiling in a twenty-step loop, under SDK defaults of ten minutes plus two silent retries, is a run measured in hours, and because the loop gives the slow path twenty chances, a step that is slow one time in a hundred makes a slow run one time in six. Your libraries do not even agree on the question: requests sets no timeout at all and warns you it will hang indefinitely, httpx defaults to five seconds. Steal gRPC’s mechanics — a deadline minted with the run, travelling as remaining time with elapsed already deducted, every call timeout derived as min(remaining, step ceiling), and work refused rather than started when it cannot finish; subagents inherit a slice, never a fresh allocation. Then remember that a timeout abandons work rather than cancelling it, so the expiry path for a write is a reconcile by idempotency key, never a retry the model gets to propose. Run a semantic inactivity clock alongside the hard wall, because SSE keepalives will keep a dead run alive; reserve budget for the landing and label partial results as partial; and attribute exhaustion to the step that spent the budget, not the one holding it.',
      '运维 — 超时与截止时间预算：你的智能体里每个超时值都是由一个看不见其他超时值的人定的，而它们的乘积才是你真正上线的最坏情况——二十步循环里三十秒的工具上限，配上 SDK 默认的十分钟外加两次无声重试，是一趟以小时计的运行；而因为循环给了慢路径二十次机会，一个百分之一概率会慢的步骤，会让六分之一的运行变慢。你那些库甚至对这个问题都没有共识：requests 压根不设超时，并警告你它会无限期挂起；httpx 默认五秒。把 gRPC 的机制照搬过来——截止时间与这趟运行一同铸出，以「已扣除已耗时的剩余时间」的形式传输，每次调用的超时按 min(剩余, 单步上限) 导出，完不成的活儿宁可拒绝也不开工；子智能体继承的是一片切片，绝不是一份全新额度。然后记住超时是把活儿丢下而不是取消掉，所以一次写操作到期后该走的是按幂等键对账，绝不是一次由模型提议的重试。在那堵硬墙之外再跑一个语义静默钟，因为 SSE 保活会把一趟已死的运行维持成活的；给着陆留出预算，并把部分结果标注成部分结果；以及，把预算耗尽归因到花掉预算的那一步，而不是抱着预算的那一步。',
    ),
    L(
      'Playbooks — Dead-Code & Feature-Flag Removal Agents: deletion is the one coding-agent task where a green test suite proves nothing, because the suite passes for exactly the reason the code looked dead — and it returns green identically whether the code is truly unreachable, reachable only under production configuration, or the agent deleted the tests along with it. Coverage even rises when you delete untested code, so the obvious objective rewards removing what you understand least. Static analysis proposes and never decides, and the gap holds everything in the failure path: retry handlers, back-out scripts, the disaster-recovery routine are dead by design, which is how Knight Capital lost roughly $440 million in forty-five minutes on 1 August 2012 when a reused flag re-armed a test routine unused since 2003 — and rolling back activated it on all eight servers. Buy the evidence at runtime, over a window taken from the business calendar rather than a round thirty days; know that a flag evaluated a million times returning false is not a flag never evaluated; read the production value rather than the code default, which is usually its opposite; treat kill switches as a protected class no heuristic may touch; and ship deletions as instrument, tombstone, delete, keeping the last commit a pure deletion so a revert stays available at 3am.',
      '实战手册 — 死代码与功能开关清理智能体：删除是编码智能体唯一一件「测试全绿什么也证明不了」的活儿，因为测试套件通过的理由，恰恰就是这段代码看起来已死的那个理由——而不论代码是真的不可达、只在生产配置下可达，还是智能体把测试一并删了，它返回的绿色一模一样。删掉没有测试的代码覆盖率甚至会上升，于是那个显而易见的目标奖励的正是移除你最不了解的东西。静态分析只提议、从不裁决，而那道缝里装着失败路径上的一切：重试处理器、回退脚本、灾备例程在设计上就是死的；Knight Capital 正是这样在 2012 年 8 月 1 日的四十五分钟里损失约 4.4 亿美元——一个被复用的开关重新点燃了一段自 2003 年起就不再使用的测试例程，而回滚反倒让它在八台服务器上全部激活。去运行时买证据，窗口取自业务日历而不是一个整三十天；要知道一个被求值一百万次而返回 false 的开关，不等于一个从未被求值的开关；读生产值而不是读代码默认值，后者通常与前者相反；把急停开关当成任何启发式都不许碰的受保护类别；并把删除做成「埋点、立墓碑、删除」三步，让最后那个提交保持纯删除，好让凌晨三点的回滚仍然可用。',
    ),
  ],
};

export default entry;
