import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-08-19',
  title: L(
    'Two AI Blog posts on the isolation technology under every agent sandbox and on why your eval metric picks your prompt optimizer, plus three pages on documentation agents, field-service dispatch and free-tier economics',
    '两篇 AI 博客——每个智能体沙箱底下的那层隔离技术，以及为什么挑提示词优化器的其实是你的评测指标——外加三个页面：文档智能体、现场服务派工，以及免费额度经济学',
  ),
  items: [
    L(
      'New blog post — *gVisor vs Firecracker vs Kata vs WebAssembly: Cold Start Is the Operating System*. Every sandbox vendor resells one of these four, and the pick decides whether the agent can run `pip install` at all. Lays out where each puts the boundary — a runtime sandbox inside a host process, gVisor’s Sentry answering syscalls in user space, a Firecracker microVM with its own guest kernel, a full Kata VM wearing an OCI runtime — against published figures: isolates at about 1ms, gVisor at 50–100ms with roughly 30MB overhead and a network throughput penalty near a third, Firecracker at about 120ms for a 512MB guest with roughly 5MB overhead, Kata at 150–480ms with an 8% network hit. Argues the two rankings are exact reverses of each other because the boot time *is* the kernel, so the decisive question is whether the agent’s code installs things — and that a 120ms boot to run a 20ms function makes the sandbox, not the model, the latency budget. Closes on warm pools moving the security question rather than solving it, and on egress being a control none of the four gives you. Three themeable SVGs.',
      '新博客文章——《gVisor vs Firecracker vs Kata vs WebAssembly：冷启动就是操作系统本身》。每家沙箱厂商都是在转售这四者之一，而这个选择决定了智能体究竟能不能跑 `pip install`。文章摆出四者各把边界放在哪里——宿主进程内部的运行时沙箱、在用户态应答系统调用的 gVisor Sentry、自带 guest 内核的 Firecracker microVM，以及穿着 OCI runtime 外衣的完整 Kata 虚拟机——并对照已公布的数字：isolate 约 1 毫秒，gVisor 50–100 毫秒、约 30MB 开销、网络吞吐折损接近三分之一，Firecracker 512MB guest 约 120 毫秒、约 5MB 开销，Kata 150–480 毫秒、网络折损 8%。文章论证这两个排序恰好互为倒序，因为启动时间*就是*那个内核；于是决定性的问题变成"智能体的代码要不要装东西"——而用 120 毫秒的启动去跑一个 20 毫秒的函数，会让占住延迟预算的是沙箱而不是模型。文末落在"预热池是挪动了安全问题而不是解决了它"，以及"出网是这四者都不提供的一道控制"。配三张可随主题变色的 SVG。',
    ),
    L(
      'New blog post — *BootstrapFewShot vs MIPROv2 vs GEPA vs TextGrad: Your Metric Picks the Optimizer*. GEPA’s reported margins — up to 20% over GRPO and 13% over MIPROv2 aggregate on Qwen3 8B, 93% against 67% on MATH, about +10% on AIME 2025 — were all measured where an automatic checker was free and a failed run could be described in words. Sorts the four by the shape of feedback each consumes: BootstrapFewShot needs a pass/fail verdict, MIPROv2 a scalar over many rollouts, GEPA a score plus diagnostic text it can reflect on, TextGrad a written critique standing in for a gradient. Argues the eval function is the interface nobody designs, that an optimized prompt is a fitted artefact tied to one model version rather than an asset, and that an optimizer maximises whatever the metric rewards including the reasoning you would not endorse. Closes on the one change that costs an afternoon and unlocks half the field: return a score *and* a short reason string. Three SVGs.',
      '新博客文章——《BootstrapFewShot vs MIPROv2 vs GEPA vs TextGrad：挑优化器的其实是你的指标》。GEPA 报出的优势幅度——在 Qwen3 8B 上较 GRPO 最多 20%、较 MIPROv2 总体 13%，MATH 上 93% 对 67%，AIME 2025 上约 +10%——全都测在自动检查器免费、且失败运行可以被用词句描述的场景上。文章按"各自消费什么形状的反馈"给四者分类：BootstrapFewShot 只要一个通过/失败的判定，MIPROv2 要多轮 rollout 上的一个标量，GEPA 要一个分数外加它能据以反思的诊断文字，TextGrad 要一份顶替梯度的书面批评。文章论证：评测函数才是那个没人去设计的接口；优化出来的提示词是一件绑定某个模型版本的拟合产物而非资产；而优化器会最大化指标所奖励的一切，包括你并不认可的那种推理。文末落在那个只要一个下午、却能解锁半个领域的改动：让指标同时返回一个分数*和*一小段原因文字。配三张 SVG。',
    ),
    L(
      'New Playbook (Coding & Computer-Use Agents) — *Documentation Agents*. Every other coding agent has an oracle — a test suite, a compiler, a reviewer — and this one has none, which is not a tooling gap but what documentation is for: if a sentence’s correctness were derivable from the code, it would not need writing. Splits the corpus into four truth conditions (derived reference and executable prose, both machine-checkable; explanatory prose and obligations, neither) and gives the agent unsupervised authority over exactly the first two. Argues that generating docs from source launders bugs into specification and cannot say "don’t use this", so the valuable inputs are commit messages, issue threads and support tickets; that deletion must be a first-class output with its own evidence bar, because nothing else will ever shrink the corpus; and that the backlog should be ranked by reader-failures per page rather than staleness. Closes on the twenty-support-ticket diagnostic that separates a discovery problem from a coverage hole.',
      '新增实战手册（编码与计算机操作智能体）——《文档智能体》。别的编码智能体都有裁判——测试套件、编译器、评审者——而这一个没有；这不是工具短板，而正是文档存在的理由：如果一句话的正确性能从代码推导出来，那句话就不必写。文章把语料切成四种真值条件（派生型参考与可执行散文，机器可核查；解释型散文与责任性内容，都不可核查），并且只在前两类上给智能体无人监督的权限。文章论证：从源码生成文档会把 bug 洗成规范，也说不出"别用这个"，所以真正有价值的输入是提交信息、issue 线程与支持工单；删除必须成为一等输出并配自己的证据门槛，因为别的什么都不会让语料缩小；积压应当按每页引发的读者失败次数排序，而不是按陈旧程度。文末落在那个"二十张支持工单"自检——它能把发现问题与覆盖缺口区分开。',
    ),
    L(
      'New Playbook (Domain Playbooks) — *Field Service & Dispatch Agents*. Scheduling is the one part of field service already solved: a constraint solver beats a model at assignment and, unlike a model, names the binding constraint when it refuses. So the agent belongs at the two edges the solver cannot read — intake, which decides which parts go on the truck and therefore first-time-fix rate, and the reschedule call at 10am when the plan is already wrong. Argues an appointment window is a promise, so every board write needs reserve-then-confirm with idempotency keys and a compensating flow rather than a rollback; that the board is shared with human dispatchers, so last-write-wins loses the dispatch team permanently and every manual override is labelled data about a constraint you failed to model; and that a globally-optimal reshuffle that moves eleven technicians’ afternoons is a net loss. Closes on classifying last quarter’s second visits by root cause before building anything.',
      '新增实战手册（领域实战手册）——《现场服务与派工智能体》。排程恰恰是现场服务里唯一早已被解决的部分：派工上约束求解器胜过模型，而且与模型不同，它拒绝时会点名那条起约束作用的条件。所以智能体属于求解器读不懂的那两个边缘——受理，它决定哪些零件上车、进而决定一次修复率；以及上午十点计划已经不对时的那通改约电话。文章论证：一个上门时段是一句承诺，所以每一次写入看板都要"先预留后确认"、配幂等键，并且要一套补偿流程而不是一次回滚；看板是与人类派工员共享的，所以"最后写入者获胜"会永久失去派工团队，而每一次手动覆盖都是关于你没能建模的某条约束的标注数据；一次挪动十一位技师下午安排的"全局最优"再平衡是净亏损。文末落在"在动手建任何东西之前，先把上个季度的二次上门按根因归类"。',
    ),
    L(
      'New Operation (Economics & ROI) — *Free Tiers & Trial Economics*. A SaaS free tier is capped by human boredom; an agent free tier is capped by nothing, because the user is a scheduler that runs while its owner sleeps and the marginal cost is tokens, sandbox seconds and tool calls rather than a database read. Works the arithmetic explicitly — a run costing tens of cents, a 3% conversion rate meaning every paying customer funds roughly thirty-three free accounts — and argues you must price off the maximum a single account can consume rather than the average, because the distribution is heavy-tailed enough that "average" is doing dangerous work. Prescribes metering work rather than days or seats, capping concurrency and cadence separately from volume, degrading to a smaller model instead of erroring, and enforcing the ceiling at request time because a monthly spend review finds the problem four weeks late. Closes on the two numbers that decide the tier: cost per free account as a distribution, and free spend attributable to users who converted versus those who did not.',
      '新增运维页（经济性与投资回报）——《免费额度与试用经济学》。SaaS 的免费额度由人类的无聊封顶；智能体的免费额度没有封顶，因为用户是一个在主人睡觉时照跑的调度器，而边际成本是 token、沙箱秒数与工具调用，不是一次数据库读取。文章把账显式算出来——一次运行几十美分，3% 的转化率意味着每位付费客户在供养大约三十三个免费账号——并论证你必须按单个账号能消耗的上限而非平均值来定价，因为这个分布重尾到"平均"两个字承担着危险的分量。处方是：计量工作量而不是天数或席位；把并发与频次和总量分开设限；用降级到更小模型代替直接抛错；并在请求时刻强制那道天花板，因为一次月度开销复盘要晚四个星期才发现问题。文末落在决定这一档存废的两个数字：作为分布来看的单免费账号成本，以及可归因于转化用户与未转化用户的免费开销之比。',
    ),
  ],
};

export default entry;
