import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-08-15',
  title: L(
    'Two AI Blog posts on what OpenAI’s gated cyber model actually gates and on why a speech-to-text choice is really a turn-detector choice, plus three pages on refusals, in-app agent surfaces and simulated users',
    '两篇 AI 博客——OpenAI 那款设了门槛的安全模型究竟拦住了什么，以及选语音转文本其实是在选话轮检测器——外加三个页面：拒绝、应用内智能体界面，以及模拟用户',
  ),
  items: [
    L(
      'New blog post — *GPT-5.6-Cyber Is Gated Because It Refuses Less, Not Because It Knows More*. OpenAI shipped an offensive-security model on 10 August behind Daybreak Red — identity verification, legal attestations, approved-use restrictions, monitoring, and hardware security keys mandatory on individual accounts from 1 September. Reads the three published evaluations against each other: GPT-5.6-Cyber answers 95.0% of advanced cyber prompts where standard Sol answers 1.5%, but scores *worse* than Sol on OpenAI’s own Vulnerability Discovery and Report Writing evaluation, and loses ExploitBench at the standard 300-turn setting on more tokens — with the gap narrowing once the budget is raised to 600. Argues the delta is a refusal policy rather than a capability, that a completion rate is a policy metric wearing a capability metric’s clothes, and that the gate is an attribution boundary rather than a containment one — so the number defenders should have moved on 10 August is patch latency. Credits the one real asymmetry: a vetted, monitored channel is structurally unattractive to attackers, which is why two Chrome V8 zero-days went to Google (one patched as CVE-2026-15903, CVSS 8.8) rather than to a broker. Three themeable SVGs.',
      '新博客文章——《GPT-5.6-Cyber 被设了门槛，是因为它更少拒绝，不是因为它懂得更多》。OpenAI 于 8 月 10 日在 Daybreak Red 之后发布了一款攻击性安全模型——身份核验、法律承诺书、批准用途限制、监控，以及自 9 月 1 日起个人账户强制使用硬件安全密钥。文章把三项已公布的评测对照着读：GPT-5.6-Cyber 回答了 95.0% 的高级网络安全提示，而标准版 Sol 只回答 1.5%；但在 OpenAI 自家的"漏洞发现与报告撰写"评测上它的分数反而低于 Sol，在 300 回合标准设置的 ExploitBench 上也输给 Sol 且用掉更多 token——而一旦把预算抬到 600 回合，差距就会收窄。文章论证：这道差值是一条拒绝策略而非一项能力；完成率是一项穿着能力指标外衣的策略指标；那道门是一条归因边界而不是遏制边界——所以防守方在 8 月 10 日真正该动的数字是补丁上线时延。文中也认下了那一处真实的不对称：一条经审核、受监控的通道在结构上对攻击者很不划算，这正是两个 Chrome V8 零日漏洞去了 Google（其一已修复为 CVE-2026-15903，CVSS 8.8）而不是去了掮客手里的原因。配三张可随主题变色的 SVG。',
    ),
    L(
      'New blog post — *Deepgram vs AssemblyAI vs ElevenLabs vs Speechmatics: You Are Buying a Turn Detector*. Argues that end-of-turn detection, not word error rate, is the slice of a voice turn that decides whether the conversation feels human — several times larger than transcription latency, and the one axis the four genuinely disagree on. Deepgram’s Flux folds turn detection into the recogniser and emits turn events; AssemblyAI layers semantic plus acoustic endpointing with a silence fallback; ElevenLabs optimised ~150 ms first-partials across 90+ languages and leaves the turn decision to your own VAD; Speechmatics hands you a threshold, with 1.5 s as its own suggested starting point. Notes that a Hamming.ai benchmark over 4M+ production calls put AssemblyAI at 307 ms P50 / 8.14% WER against Deepgram Nova-3 at 516 ms / 9.87% — a difference a quarter the size of the endpointing wait sitting on top of it. Also argues WER is close to settled and the errors that break agents are entities, that early cut-ins and late responses are asymmetric failures, and that at $0.15–$0.50 per audio hour the recogniser is the smallest line on the bill. Three SVGs.',
      '新博客文章——《Deepgram、AssemblyAI、ElevenLabs 与 Speechmatics：你买的是一个话轮检测器》。文章论证：决定一段对话像不像人的，是话轮结束检测而不是词错误率——它比转写延迟大出好几倍，也是这四家真正存在分歧的那条轴。Deepgram 的 Flux 把话轮检测折进识别器并直接抛出话轮事件；AssemblyAI 叠了一层语义加声学的端点判定并以静音法兜底；ElevenLabs 优化的是跨 90 多种语言约 150 毫秒的首部分结果，把话轮判断留给你自己的 VAD；Speechmatics 给你一个阈值，并把 1.5 秒作为它自己建议的起点。文中指出，Hamming.ai 覆盖四百多万通生产通话的基准给出 AssemblyAI 307 毫秒 P50 / 8.14% WER，对 Deepgram Nova-3 的 516 毫秒 / 9.87%——而这道差距只有压在它上面那段端点等待的四分之一。文章还论证：WER 已接近尘埃落定，真正弄坏智能体的错误出在实体上；抢话太早与回话太晚是两种不对称的失败；而在每音频小时 0.15 到 0.50 美元的价位上，识别器是账单上最小的那一行。配三张 SVG。',
    ),
    L(
      'New Concept (Core Building Blocks) — *Refusals & Capability Gating*. Separates the three mechanisms that all look like "no" — absence of capability, post-training policy, and an external classifier — and points out that only the first is a property of the model, so the same prompt can be refused on Monday and answered on Thursday with no version change. Argues that gating access to a permissive model variant buys attribution rather than containment, and that a vendor reporting a permissive model’s advantage shrinking on a longer turn budget is direct evidence the delta was compliance rather than skill. Names over-refusal as a cost nobody instruments, with the real damage being relocation: the user pastes the question into a consumer chatbot outside your logging and retention. Closes on putting enforceable controls at the tool boundary and in a policy engine, and on running two eval sets — legitimate requests near the boundary, and requests that must be declined — against every model change including the ones you did not initiate.',
      '新增概念页（核心构件）——《拒绝与能力门禁》。文章把三种看上去都像"不行"的机制分开——能力的缺席、后训练策略、外部分类器——并指出只有第一种是模型的性质，所以同一条提示词可以周一被拒、周四被答，而版本号纹丝不动。文章论证：给宽松版本的模型访问设门禁，买到的是归因而不是遏制；而一家厂商若报告"给通用模型更多回合后宽松模型的优势就缩小"，那就是直接证据——差的是顺从度，不是本事。文中把过度拒绝点名为一项没人装仪表的成本，而真正的损害在于位移：用户把问题粘进了一个在你日志与留存策略之外的消费级聊天机器人。文章以两点收尾：把真正需要执行的控制放到工具边界与策略引擎上；以及对每一次模型变更——包括不是你发起的那些——都跑两套评测集：贴着边界的合法请求，以及必须被拒绝的请求。',
    ),
    L(
      'New Playbook (Agent UX & Human Interaction) — *Embedding an Agent in an Existing App*. The chat panel bolted to the right edge is the cheapest surface and the reason most in-app agents get used twice, because every request starts with the user re-describing their own application. Sorts the three shapes — panel, inline-anchored, ambient — and argues the value is usually in the second, which needs no chat history at all. Prescribes passing the current view as identifiers and state rather than a screenshot, resolving records server-side under the user’s own permissions, and writing through the same code path as the UI so there is one enforcement point and one audit record with the human principal on it. Names the decision that cannot be retrofitted — client-held versus server-held agent state — with the second-surface test as the tie-breaker, and covers reconciling with a UI that is also being edited: stream into a review container, never overwrite a human edit, keep interruption non-destructive. Closes on metrics anchored to the existing workflow: acceptance rate per tool, edit distance after acceptance, and re-invocation on the same object.',
      '新增实战手册（智能体体验与人机交互）——《把智能体嵌进一个既有应用》。螺在右边缘的那个聊天面板是最便宜的界面，也是多数应用内智能体只被用两次的原因，因为每次提问都得先由用户把自己的应用重新描述一遍。文章给三种形态排了序——面板、锚定在对象上的内联、环境式——并论证价值通常在第二种，而它压根不需要聊天记录。处方是：把当前视图以标识符与状态的形式传过去而不是传截图、在服务端以用户自己的权限去取记录，并沿界面已有的那条代码路径写入，从而只留一个执行点、一条带人类委托人的审计记录。文中点出那个无法事后补救的决定——智能体状态放客户端还是放服务端——并以"第二块界面"作为裁决检验；也覆盖了如何与一个同时正被编辑的界面做调和：把流式输出灌进复核容器、绝不覆盖人类的编辑、让中断不具破坏性。文章以锚在既有工作流上的指标收尾：按工具拆的接受率、接受之后的编辑距离，以及在同一对象上的再次唤起。',
    ),
    L(
      'New Operation (Evaluation & Observability) — *Simulated Users in Agent Evaluation*. Every multi-turn agent score measures two systems, and the second one — a model playing a customer — is usually unversioned and unevaluated while being able to move your agent’s number several points on its own. Prescribes pinning model ID, temperature, seed, persona prompt and stopping rule alongside the results, changing one at a time, never sharing a model between agent, simulator and judge, and treating a simulator upgrade as a breaking change to the measurement instrument. Catalogues the four ways a simulator lies — too cooperative, answer leakage, persona drift around turn eight, adversarial overshoot — all visible in transcripts and invisible in aggregates. Adds calibration against real production transcripts, personas derived from clusters with their frequencies preserved, and scoring that separates outcome from policy adherence, reports pass^k rather than best-of-k, and gives graders an explicit simulator-fault verdict. Closes on when not to simulate: absolute quality claims, production signal, safety-critical acceptance, and anything a static fixture would cover.',
      '新增运维页（评估与可观测性）——《智能体评估中的模拟用户》。每一个多轮智能体分数量的都是两套系统，而第二套——一个扮演客户的模型——通常没有版本、也没被评估过，却单凭自己就能把你智能体的数字挪动好几个点。处方是：把模型 ID、温度、随机种子、人设提示词与停止规则连同结果一起钉住；一次只改一样；绝不让智能体、模拟器与裁判共用一个模型；并把模拟器升级当作对测量仪器的一次破坏性变更。文中列举了模拟器骗你的四种方式——过于配合、答案泄漏、约第八轮开始的人设漂移、对抗性过头——它们在对话记录里都看得见，在汇总数字里都看不见。文章还加上：拿真实生产对话记录做校准、从聚类里派生并保留相对频率的人设，以及把结果与规程遵守分开计分、报告 pass^k 而不是 k 次取最好、并给评分者一个显式的"模拟器故障"裁定项。文末讲了什么时候不该模拟：绝对质量声明、生产信号、安全攸关的验收，以及任何静态样例就能覆盖的东西。',
    ),
  ],
};

export default entry;
