import { L, type ChangelogEntry } from '../types.ts';

const entry: ChangelogEntry = {
  date: '2026-08-16',
  title: L(
    'Two AI Blog posts on the month’s two 9-point agent CVEs and on why agents break per-token inference pricing, plus three pages on unpatchable vulnerabilities, agent latency and dependency upgrades',
    '两篇 AI 博客——本月那两个九分的智能体 CVE，以及智能体为何压垮了按 token 计价的推理服务——外加三个页面：打不了补丁的漏洞、智能体延迟，以及依赖升级',
  ),
  items: [
    L(
      'New blog post — *August’s Worst Agent CVEs Were Authorization Bugs, and There Was No Patch to Apply*. Reads CVE-2026-62830 (Azure SRE Agent, CVSS 9.9, missing authorization, Scope Changed) against CVE-2026-59118 (Microsoft Copilot Cowork, CVSS 9.3, improper authorization, unauthenticated) and argues that neither involved a model at all — both are ordinary control-plane authorization defects sitting in front of unusually broad delegated authority. Traces the 9.9 to the Scope Changed flag, which scores the size of the reachable set and therefore measures your role assignments rather than Microsoft’s code; shows the broken on-behalf-of exchange that drops the user’s identity and substitutes the agent’s managed identity. Then works through what a service-side fix does to a vulnerability-management programme: the asset inventory learns nothing, the scanner cannot confirm remediation, change control has nothing to approve, and there is no rollback — leaving three questions about your own environment, all of which had to be answered before disclosure. Closes on credential scoping as the only available lever and on the two procurement questions that are not on a standard security questionnaire. Three themeable SVGs.',
      '新博客文章——《八月最严重的智能体 CVE 是授权缺陷，而且没有补丁可打》。文章把 CVE-2026-62830（Azure SRE Agent，CVSS 9.9，授权缺失，作用域变更）与 CVE-2026-59118（Microsoft Copilot Cowork，CVSS 9.3，不当授权，无需认证）对照着读，论证两者都与模型毫无关系——它们都是普通的控制平面授权缺陷，只不过挡在一份异常宽泛的受托权限前面。文章把那个 9.9 追溯到"作用域变更"标志：它给"可达集合有多大"打分，因而量的是你的角色分配而不是微软的代码；并展示了那次断裂的 on-behalf-of 交换如何丢掉用户身份、换上智能体的托管标识。接着走了一遍"服务端修复"对一套漏洞管理项目做了什么：资产台账学不到东西、扫描器确认不了修复完成、变更管理没有东西可批、也没有回滚——剩下三个关于你自己环境的问题，而它们全都必须在披露之前就已答好。文章以"凭据收窄是唯一可用的杠杆"，以及两个不在标准安全问卷上的采购问题收尾。配三张可随主题变色的 SVG。',
    ),
    L(
      'New blog post — *Together vs Fireworks vs Baseten vs Modal: Agents Break Per-Token Pricing*. Does the arithmetic once: a dedicated H100 at roughly $7.00/hr against roughly $0.90 per million tokens buys about 7.8M tokens of serverless spend per GPU-hour, which a chat product reaches at close to 400 concurrent users and an agent reaches at about a dozen workers — because a twenty-step trajectory re-sends a 30K working context every step. Argues the choice is therefore about the ladder off per-token pricing rather than the entry rate: Together spans all three rungs including HGX clusters from about $3.99/hr per GPU, Fireworks prices the first rung under the field at about $0.90/M against Together’s $1.04/M and stops at hourly instances, Baseten brokers dedicated capacity across many clouds for custom weights, and Modal has no per-token rung at all. Names prefix caching as where the agent bill is actually won — cached prompt tokens discounted around 50%, TTFT down as much as 80% — with the catch that hit rate depends on routing you do not control on a shared fleet. Closes on tail latency: a 1% slow step becomes a 14% slow task over fifteen steps, and on shared capacity your tail is other tenants. Three SVGs.',
      '新博客文章——《Together、Fireworks、Baseten 与 Modal：智能体压垮了按 token 计价》。文章把算术做一遍：一块专用 H100 约 7.00 美元/小时，对上约 0.90 美元/百万 token，等于每个 GPU 小时的钱能买下约 780 万 token 的无服务器用量；聊天产品要接近 400 个并发用户才碰得到，而智能体十来个工作单元就到——因为一条二十步的轨迹每一步都要把三万 token 的工作上下文重发一遍。文章由此论证：真正要选的是"离开按 token 计价的那条阶梯"，而不是入门单价。Together 三级俱全，含每 GPU 约 3.99 美元/小时起的 HGX 集群；Fireworks 把第一级压在同行之下，约 0.90 美元/百万对 Together 的 1.04，但阶梯止于按小时实例；Baseten 为自定义权重从多家云撮合专用算力；Modal 则完全没有按 token 这一级。文章点出前缀缓存才是智能体账单真正的胜负手——命中的提示词 token 打约五折、首 token 时延最多降八成——而代价是：在共享机群上，命中率取决于你控制不了的路由。文末落在尾延迟上：1% 的慢步骤在十五步之后会变成 14% 的慢任务，而在共享算力上，你的尾部是别的租户。配三张 SVG。',
    ),
    L(
      'New Operation (Safety, Alignment &amp; Agentic Security) — *Vulnerability Management for Agent Platforms*. Sorts an agent stack into three patch regimes — code you wrote, components you self-host, and agent services the vendor operates — and points out that most programmes are built entirely for the middle tier, which holds the least authority. Prescribes inventorying the identity rather than the product, scoring each grant by what one failed authorization check would allow, and putting an expiry on pilot-era permissions so the default is revocation. Walks what replaces each deleted control when a fix ships service-side, and argues the exposure window you must reconstruct starts at defect introduction rather than at disclosure — which makes log retention a capability rather than a cost line. Adds the self-hosted tier everyone forgets (MCP servers with tool-call authority, ageing sandbox and browser images, the gateway that sees every prompt) and closes on the four vendor questions worth asking before signing, including whether control-plane logs of the agent’s actions in your tenant can be exported at all.',
      '新增运维页（安全、对齐与智能体安全）——《智能体平台的漏洞管理》。文章把智能体栈分成三套打补丁的机制——你自己写的代码、你自己托管的组件、厂商运营的智能体服务——并指出多数项目完全是为中间那一层建的，而那恰恰是权限最小的一层。处方是：盘点标识而不是产品、按"一道授权检查失效会放行什么"给每项授权打分，并给试点期权限加上到期时间，让默认结果是回收。文中走了一遍"服务端修复"时每一项被删掉的控制该拿什么顶上，并论证你必须重建的暴露窗口起点在缺陷被引入之时而非披露之时——这让日志保留期成为一项能力而不是一条成本项。文章还补上了人人遗忘的自托管层（持有工具调用权限的 MCP 服务器、老化的沙箱与浏览器镜像、看得见每条提示词的网关），并以签约前值得问的四个厂商问题收尾，其中包括：智能体在你租户内动作的控制平面日志究竟能不能导出。',
    ),
    L(
      'New Operation (Evaluation &amp; Observability) — *Measuring Agent Latency*. A per-call median is the wrong instrument, because chaining multiplies tail risk: a 1% chance of a slow step becomes a 14% chance of a slow task over fifteen steps, so the p99 of a step predicts user experience far better than its p50 — and at forty steps it is 33%. Prescribes reporting duration per completed task with step count alongside, keeping failed and capped runs in the distribution rather than excluding them as errors, and counting retries in the total the user waited. Splits the trajectory into model, tool, queue and orchestration time and notes that teams reliably blame the model and reliably find something else. Separates time-to-first-useful-output from time-to-done as two SLOs with different users, warns against the metric that improves when you stream more and finish later, and lists the per-step fields that make a regression diagnosable six weeks later. Closes on an SLO set per task class at a percentile, with degraded mode decided in advance and alerting on step-count and termination-mix shifts, which move first.',
      '新增运维页（评估与可观测性）——《度量智能体延迟》。按次调用的中位数是错的仪器，因为串成链会把尾部风险乘起来：单步 1% 的慢概率，在十五步之后变成任务级 14%，所以单步的 p99 远比它的 p50 更能预测用户体验——而到了四十步就是 33%。处方是：按已完成任务报告时长并附上步数、把失败与撞上限的运行留在分布里而不是当错误剔除，以及把重试计入用户实际等待的总时长。文章把轨迹拆成模型时间、工具时间、排队时间与编排时间，并指出团队总是先怪模型、又总是发现问题在别处。文中把"到首个有用输出的时间"与"到做完的时间"分成两个面向不同用户的 SLO，警告那种"多流式、晚完成"就会变好看的指标，并列出了让一次回归在六周后仍诊断得出来的每步字段。文章以"按任务类别、按分位设定 SLO"收尾，配上提前定好的降级模式，以及对步数与终止构成位移的告警——因为它们先动。',
    ),
    L(
      'New Playbook (Coding &amp; Computer-Use Agents) — *Dependency Upgrade Agents*. Bumping a version has been automated since 2017; the backlog exists because nobody will merge an upgrade they cannot vouch for, so what you are actually designing is an evidence policy. Argues a green suite is weak evidence exactly where upgrades break — a changed default keeps its signature and passes every test you own — and that the useful report is the one naming its own blind spots, including the call sites with no coverage. Sets out evidence requirements per upgrade class, with reachability of the vulnerable code path as the most valuable sentence an agent can produce on a security advisory. Reframes the deliverable as triage across three lanes rather than merges, measured by lane-two acceptance and lane-one revert rate. Adds an adversarial checklist for reading release notes (defaults, error types, ordering guarantees, deprecation deadlines, the actual upstream diff) with upstream text treated as untrusted input, and closes on batching by rollback unit, never mixing an upgrade with a refactor, and reporting median dependency age rather than PRs opened.',
      '新增实战手册（编码与计算机操作智能体）——《依赖升级智能体》。"把版本号往上抬"从 2017 年起就已自动化；积压之所以存在，是因为没人愿意合并一个自己担保不了的升级——所以你真正在设计的是一份证据规程。文章论证：全绿的测试恰恰在升级最容易出事的地方是弱证据——一个被改动的默认值签名不变，还能通过你手上每一条测试；而真正有用的报告，是那种会点名说出自己盲区、包括列出没有覆盖的调用点的报告。文中按升级类别给出证据要求，并指出面对安全通告时，智能体能产出的最有价值的一句话是"那段有漏洞的代码路径从我们的代码出发可不可达"。文章把交付物从"合并"重新框成"三条道上的分流"，并以第二条道的接受率与第一条道的回滚率来衡量。此外还给了一份读发布说明的对抗式清单（默认值、错误类型、顺序保证、弃用期限、真正的上游 diff），并把上游文本当作不可信输入；文末落在按回滚单元分批、绝不把升级与重构混在一起，以及汇报依赖年龄中位数而不是开了几个 PR。',
    ),
  ],
};

export default entry;
