import { L, type Group } from '../types.ts';

const group: Group = {
  key: 'agent-ux-and-human-interaction',
  order: 110,
  name: L('Agent UX & Human Interaction', '智能体体验与人机交互'),
  groupSummary: L('How agents present themselves, ask for input, and earn trust — UX patterns for human-in-the-loop systems.', '智能体如何呈现自己、请求输入并赢得信任——人在回路系统的交互模式。'),
  entries: [
    { page: 'designing-for-trust', slug: 'designing-for-trust', title: L('Designing for Trust & Calibration','为信任与校准而设计'), summary: L('Trust is a calibration target, not a maximization goal: matching user-perceived reliability to measured reliability per task, displaying confidence only where it changes a decision, and spending friction where it actually calibrates.','信任是一个校准目标，而非追求最大化的目标：让用户感知的可靠性按任务匹配实测可靠性，只在置信度会改变决策时展示它，并把摩擦力花在真正能产生校准的地方。') },
    { page: 'approval-and-confirmation-ux', slug: 'approval-and-confirmation-ux', title: L('Approval & Confirmation UX','审批与确认体验'), summary: L('Consequence-tiered gates, payload-hash pinning so you confirm the action that actually runs, batching and defaults to fight confirmation fatigue, and stronger modalities for genuinely irreversible actions.','按后果分级的关卡、用载荷哈希钉定以确保你确认的就是实际执行的动作、用批量与默认项对抗确认疲劳，以及为真正不可逆的动作采用更强的交互形态。') },
    { page: 'progressive-disclosure-ux', slug: 'progressive-disclosure-ux', title: L('Progressive-disclosure UX for agents','智能体的渐进式披露界面'), summary: L('Show the user only the next decision they need to make — when to surface the chain of thought, the tool call, the diff; and when to keep it folded.','只把用户下一步需要做的决定摆在他面前——什么时候展开思考链、工具调用、diff，什么时候继续折叠。') },
    { page: 'transparency-and-explainability', slug: 'transparency-and-explainability', title: L('Transparency & Explainability','透明度与可解释性'), summary: L('Faithful versus plausible explanations, why a raw chain-of-thought is a persuasive narrative rather than verified causality, choosing the right altitude of explanation, and provenance as the highest-leverage transparency.','忠实的解释与看似合理的解释之别、为何原始思维链是有说服力的叙事而非经过验证的因果、如何选择恰当的解释海拔，以及来源溯源作为杠杆率最高的透明度。') },
    { page: 'interruption-and-handoff', slug: 'interruption-and-handoff', title: L('Interruption, Steering & Handoff','中断、引导与交接'), summary: L('Responsive non-destructive interruption, distinguishing pause/steer/abort, symmetric handover and handback, shared inspectable state, and reconciling on resume so an agent never silently reverts a human fix.','及时且不具破坏性的中断、区分暂停/引导/中止、对称的接管与交还、共享且可检视的状态，以及恢复时调和状态，使智能体绝不悄悄回退人类的修复。') },
    { page: 'progressive-autonomy', slug: 'progressive-autonomy', title: L('Progressive Autonomy','渐进式自主'), summary: L('The autonomy ladder (operator/collaborator/consultant/approver/observer) as a product surface: autonomy scoped to (capability, scope), promotion gated on a visible track record, and automatic reversible demotion.','把自主权阶梯（操作者/协作者/顾问/审批者/观察者）当作产品界面：自主权按 (能力, 范围) 限定、晋升以可见的战绩为门槛、降级则自动且可逆。') },
    { page: 'designing-for-failure', slug: 'designing-for-failure', title: L('Designing for Failure & Recovery','为失败与恢复而设计'), summary: L('Graceful failure that stops before compounding, undo as the safety net that makes lower friction affordable, actionable error messages, failing closed on consequence and open on capability, and the explicit work of trust repair.','在叠加之前就停下的优雅失败、把撤销作为让更低摩擦变得负担得起的安全网、可据以行动的错误提示、在后果上向关闭、在能力上向开放失败，以及信任修复这件显式的工作。') },
    { page: 'async-agent-ux', slug: 'async-agent-ux', title: L('Async &amp; Away: UX for Unwatched Runs','异步与离场：无人盯守运行的体验设计'), summary: L('Past ninety seconds nobody is watching, so the expensive problem is re-entry rather than the wait: an inbox over runs, a notification budget spent only on decisions, status pushed into the artifact, a diff instead of a transcript, and pre-authorisation because a gate with nobody behind it is a deadlock.','过了九十秒就没人在看了，于是贵的问题是重新进入而不是等待：以运行为单位的收件箱、只花在决策上的通知预算、把状态推进交付物、用 diff 取代聊天记录，以及前置授权——因为一道背后没人的闸门就是死锁。') },
    { page: 'shared-and-multi-user-agents', slug: 'shared-and-multi-user-agents', title: L('Shared &amp; Multi-User Agents','共享与多用户智能体'), summary: L('A second pair of eyes breaks three assumptions at once — one intent, one permission set, one accountable person — and the one that ends pilots is attribution collapse, not leakage: bind every run to one human principal, take permissions as the intersection, and print the name in the room.','第二双眼睛会同时打破三条假设——一个意图、一套权限、一个负责的人——而终结试点的是归属塌陷而非泄漏：把每次运行绑定到一个人类委托人、权限取交集，并把名字打印在屋里人看得见的地方。') },
  { page: 'undo-and-reversibility', slug: 'undo-and-reversibility', title: L('Undo &amp; Reversibility','撤销与可逆性'), summary: L('Every confirmation dialog is a bill for the undo you did not build: sort actions by cost of reversal rather than by scariness, buy time with a hold window, and make each tool return a revert handle — because confirmation asks a person to predict a bad outcome while undo only asks them to recognise one.','每一个确认弹窗都是你没做撤销而寄来的账单：按撤销代价而非吓人程度给动作排序，用一个延迟窗口买下时间，并让每个工具返回一个撤销句柄——因为确认要求人去预测一个坏结果，而撤销只要求他认出一个。') },
  { page: 'first-run-and-onboarding', slug: 'first-run-and-onboarding', title: L('First Run &amp; Onboarding','首次运行与用户引导'), summary: L('The first session sets a durable prior about what the agent can do, and the capability tour calibrates it to the ceiling: demonstrate a refusal early, pick a first task you can guarantee on the user\'s real data, and stop bundling permissions the user has no basis to evaluate.','第一次会话立下一个关于"它能干什么"的持久先验，而能力巡礼把它校准到了天花板：尽早演示一次拒绝、在用户真实数据上挑一个你能打包票的首个任务，并停止打包索取用户根本无从评估的权限。') },
  { page: 'memory-and-personalization-ux', slug: 'memory-and-personalization-ux', title: L('Memory &amp; Personalization UX','记忆与个性化的交互设计'), summary: L('Memory is the only agent feature whose worst outcome is a privacy incident rather than a wrong answer, and it gets there through one default: writing silently — a user cannot correct, consent to or forget a fact they never saw being stored.','记忆是唯一一项最坏后果不是答错、而是隐私事故的智能体功能，而它走到那一步靠的是一个默认设置：静默写入——用户无法纠正、无法同意，也无法要求遗忘一条他们从未看见被存下的事实。') },
  ],
};
export default group;
