import { L, type Group } from '../types.ts';

const group: Group = {
  key: 'coding-and-computer-use-agents',
  order: 100,
  name: L('Coding & Computer-Use Agents', '编码与计算机操作智能体'),
  groupSummary: L('Agents that read code, write code, run tools, and drive a computer — patterns, harnesses, and pitfalls.', '能读代码、写代码、运行工具并驱动计算机的智能体——模式、外壳与陷阱。'),
  entries: [
    { page: 'coding-agent-architecture', slug: 'coding-agent-architecture', title: L('Coding Agent Architecture','编码智能体架构'), summary: L('The localize-edit-verify loop that makes a coding agent more than a code generator: the agent-computer interface, why agentic beats pipeline coding, and where the loop fails.','让编码智能体不止是代码生成器的“定位-编辑-验证”循环：智能体-计算机接口、为何智能体式优于流水线式，以及循环在哪里失效。') },
    { page: 'repo-navigation-and-context', slug: 'repo-navigation-and-context', title: L('Repo Navigation & Code Context','仓库导航与代码上下文'), summary: L('Code search vs. embeddings, symbol-level indexing, context budgeting over a large tree, and why confident wrong localization is the expensive failure of code retrieval.','代码搜索 vs 向量检索、符号级索引、在大型目录树上做上下文预算，以及为何自信的错误定位是代码检索代价最高的失败。') },
    { page: 'patch-generation-and-tests', slug: 'patch-generation-and-tests', title: L('Patch Generation & Test-Driven Loops','补丁生成与测试驱动循环'), summary: L('Structured diffs and hunk-apply failures, test-driven self-correction, regression guarding, and the three honest liars in the loop: flakes, overfit, and the deleted assertion.','结构化 diff 与 hunk 应用失败、测试驱动自我纠错、回归守护，以及循环里的三个诚实骗子：flake、过拟合、被删的断言。') },
    { page: 'computer-use-and-gui-agents', slug: 'computer-use-and-gui-agents', title: L('Computer-Use & GUI Agents','计算机操作与 GUI 智能体'), summary: L('Pixel vs. DOM grounding, the action space, the screenshot loop, and the multiplicative latency and reliability tax that makes GUI control a last resort.','像素 vs DOM 定位、动作空间、截图循环，以及那笔让 GUI 操控成为最后手段的乘法式延迟与可靠性税。') },
    { page: 'browser-agents', slug: 'browser-agents', title: L('Browser agents','浏览器智能体'), summary: L('Driving a real browser as a tool — DOM versus pixel observation, login + auth state, the well-trodden failure modes, and when to step up to a full GUI agent.','把一个真实浏览器当工具来驱动——DOM 与像素两种观察方式、登录与认证状态、踩烂了的失败模式，以及何时该升级到完整 GUI 智能体。') },
    { page: 'ide-agents', slug: 'ide-agents', title: L('IDE agents','IDE 智能体'), summary: L('Coding agents that live in the editor — the loop is the same as a CLI coding agent, but the interaction surface, undo expectations, and trust threshold are all different.','住在编辑器里的编码智能体——内循环和 CLI 编码智能体一样，但交互面、撤销预期与信任阈值都不同。') },
    { page: 'sandboxing-and-execution', slug: 'sandboxing-and-execution', title: L('Sandboxing & Safe Execution','沙箱与安全执行'), summary: L('Containerized execution, network and filesystem isolation, capability scoping, and designing for blast radius when an agent runs untrusted, attacker-influenced code.','容器化执行、网络与文件系统隔离、能力作用域，以及当智能体运行不可信、受攻击者影响的代码时如何为爆炸半径做设计。') },
    { page: 'evaluating-coding-agents', slug: 'evaluating-coding-agents', title: L('Evaluating Coding Agents','评估编码智能体'), summary: L('The SWE-bench family, pass@k vs. resolve rate, harness sensitivity, documented contamination, and why a private post-cutoff eval set is the only number to trust.','SWE-bench 系列、pass@k vs 解决率、测试编排敏感性、记录在案的污染，以及为何一个截止日期后的私有评测集才是唯一可信的数字。') },
    { page: 'code-review-agents', slug: 'code-review-agents', title: L('Code Review Agents','代码评审智能体'), summary: L('A review bot lives or dies on precision, not recall: diff-anchored context, an adversarial gate that drops any finding without a concrete failure scenario, a hard comment budget ranked worst-first, and acted-upon rate as the one production metric.','评审机器人的生死取决于精确率而非召回率：以 diff 为锚的上下文、把说不出具体失败场景的发现一律丢弃的对抗性闸门、按最坏优先排序的硬性评论预算，以及作为唯一生产指标的采纳率。') },
    { page: 'large-scale-migration-agents', slug: 'large-scale-migration-agents', title: L('Large-Scale Migration Agents','大规模迁移智能体'), summary: L('Generation went to zero and human review did not, so the deliverable is evidence rather than patches: build the oracle first, batch by verifiability instead of by directory, hand the mechanical head to a codemod and only the tail to the model, and let a hundred-file pilot&rsquo;s unedited-merge rate decide whether the project is viable.','生成成本归零而人工评审没有，所以交付物是证据而不是补丁：先把判据建好、按可核验性而非按目录分批、把机械的头部交给 codemod、只把尾部交给模型，并让一次百文件试点的无需人工编辑落地比例来决定这个项目是否可行。') },
  { page: 'debugging-and-triage-agents', slug: 'debugging-and-triage-agents', title: L('Debugging &amp; Triage Agents','调试与分诊智能体'), summary: L('An agent that reads a stack trace and emits a diff has pattern-matched, not debugged — make the failing test the deliverable and the eval criterion becomes objective, the spend moves from generation to observation, and "cannot reproduce" becomes a result you can trust.','一个读完调用栈就吐出 diff 的智能体是在做模式匹配，不是在调试——把失败的测试定为交付物，评测标准就变得客观，开销从生成挪到观察，而"复现不出来"也成了一个你可以信任的结果。') },
  { page: 'background-coding-agents', slug: 'background-coding-agents', title: L('Background Coding Agents','后台编码智能体'), summary: L('An agent that opens twelve pull requests a day adds nothing if your team merges four — detaching from the editor moves the bottleneck to review, so every decision is either about making a run self-verifying or about keeping the queue short enough that the work lands.','一个每天开十二个 PR 的智能体，如果团队只合得进四个，就什么也没增加——脱离编辑器把瓶颈搬到了复核端，于是每个决策要么是让一次运行能自我验证，要么是把队列压短到工作真能落地。') },
  { page: 'test-generation-agents', slug: 'test-generation-agents', title: L('Test-Generation Agents','测试生成智能体'), summary: L('An agent that writes tests from your code infers the spec from the implementation, so wherever the code is wrong the test now certifies the bug and blocks the fix — coverage cannot see this, mutation score can, and the only jobs worth dispatching are the ones where you can name the oracle in a sentence.','从你的代码出发写测试的智能体，是从实现里反推规格的，所以代码错在哪里，测试就在哪里把 bug 认证为正确并挡住修复——覆盖率看不见这件事，变异得分看得见；而值得派发的任务，只有那些你能用一句话说清判据是什么的。') },
  { page: 'dependency-upgrade-agents', slug: 'dependency-upgrade-agents', title: L('Dependency Upgrade Agents','依赖升级智能体'), summary: L('Bumping a version has been automated since 2017 and is worth nothing — the backlog exists because nobody will merge an upgrade they cannot vouch for, so what you are building is an evidence policy: a green suite proves least about the changed defaults that break silently, and correct triage beats upgrades merged.','把版本号往上抬从 2017 年起就已自动化，且一文不值——积压之所以存在，是因为没人愿意合并一个自己担保不了的升级；所以你真正要建的是一份证据规程：全绿的测试恰恰对那些静默出事的默认值变更证明得最少，而正确分流胜过合并数量。') },
  { page: 'documentation-agents', slug: 'documentation-agents', title: L('Documentation Agents','文档智能体'), summary: L('Documentation is the one artefact in the repo with no oracle, and a wrong paragraph gets believed for years — so split the corpus by what a machine can falsify, give the agent unsupervised authority over derived reference and executable prose only, make deletion a first-class output, and report freshness rather than pages written.','文档是仓库里唯一没有裁判的产物，而写错的一段话会被人信上好几年——所以按"机器能否证伪"切开语料，只在派生型参考与可执行散文上给智能体无人监督的权限，把删除做成一等输出，并报告新鲜度而不是写了多少页。') },
  { page: 'design-to-code-agents', slug: 'design-to-code-agents', title: L('Design-to-Code Agents','设计稿转代码智能体'), summary: L('A screenshot cannot say "this is the Button component", so a pixel-faithful generator rebuilds one, hard-codes the hex instead of the token, and passes every visual review — judge the agent on component reuse rate and token adherence instead, hand it the typed component API and the design-to-import mapping before the picture, and if a ten-screen pilot comes in under seventy per cent reuse you have a design-system problem the agent will only scale.','截图没法说出"这是 Button 组件"，于是一个像素级忠实的生成器会重造一个、把十六进制色值硬编码进去而不用 token，并通过你所有的视觉复核——改用组件复用率与 token 遵循度来评判它，把带类型的组件 API 与"设计组件到 import 路径"的映射摆在图片之前交给它；如果十个页面的试点复用率低于七成，你面对的是一个设计系统问题，而智能体只会把它放大。') },
  { page: 'vulnerability-remediation-agents', slug: 'vulnerability-remediation-agents', title: L('Vulnerability Remediation Agents','漏洞修复智能体'), summary: L('Generating the patch is the cheap half — about a quarter of model-written patches for post-cutoff CVEs fix the bug without changing behaviour, and more than forty per cent of the ones your validation calls correct fail once you test mutated exploits rather than the one you were handed, so the deliverable is a reproduction that fails before and passes after, on a queue triaged by reachability instead of scanner severity.','生成补丁是便宜的那一半——针对训练截止之后 CVE 的模型补丁里，只有约四分之一在不改变行为的前提下修好了问题；而被你的校验判为正确的那些，一旦改用变异过的利用（而不是别人递给你的那一个）来测，超过四成会挂掉。所以交付物是一份“打补丁前失败、打补丁后通过”的复现，而队列的排序依据是可达性，不是扫描器的严重级别。') },
  { page: 'spec-driven-agent-development', slug: 'spec-driven-agent-development', title: L('Spec-Driven Development with Coding Agents','以规格驱动的编码智能体开发'), summary: L('The plan, the tests, the code and the summary all descend from one reading of the task, so when that reading is wrong every artefact agrees and the review passes — a spec earns its place only insofar as it comes from outside that loop, which means human-authored observable criteria with an explicit non-goals list, a check id or a named human beside each one, and spec and behaviour changing in the same pull request.','计划、测试、代码与总结都源自对任务的同一次理解，于是这次理解一旦错了，每件产物都彼此印证，评审就这么过了——一份规格配不配占位置，取决于它有多大程度来自那个循环之外：由人撰写、以可观察措辞表述的标准，一份明确的非目标清单，每条标准旁边配一个检查项 id 或一位具名的人，以及规格与行为在同一个 pull request 里一起改。') },
  { page: 'performance-optimization-agents', slug: 'performance-optimization-agents', title: L('Performance-Optimization Agents','性能优化智能体'), summary: L('Every other coding agent gets a verifier that cannot lie; this one gets a stopwatch — so forty candidate patches scored on one timing run each will keep noise with near-certainty. Build the harness first (confidence intervals, a published minimum detectable effect, a fixed repetition budget), gate on the full test suite rather than folding correctness into the score, and hand the agent a profile instead of a repository.','别的编码智能体拿到的是不会骗人的核验器，这一个拿到的是秒表——于是四十个候选补丁各测一次计时，几乎必然会留下噪声。先把测量台建好（置信区间、公开的最小可检出效应、固定的重复次数预算），用全量测试套件设关卡而不是把正确性揉进分数，并且交给智能体一份剖析结果而不是一个仓库。') },
  { page: 'infrastructure-as-code-agents', slug: 'infrastructure-as-code-agents', title: L('Infrastructure-as-Code Agents','基础设施即代码智能体'), summary: L('Every other coding agent has to build its own oracle; this one is handed terraform plan for free — so the deliverable is a plan whose every line falls into a class you already agreed to auto-apply, the review job becomes classifying the plan rather than reading the diff, and the engineering is all in the four things a plan is silent about: unknown values, server-side behaviour, replacements announced in the same tone as everything else, and whatever is not in state.','别的编码智能体都得自己造判据，这一个白得了 terraform plan——所以交付物是一份「每一行都落进你事先约定可自动执行的类别」的计划，评审工作从读 diff 变成给计划定级，而全部工程难度都在计划只字不提的那四件事上：未知值、服务端行为、与其他一切用同样语气宣布的替换，以及任何不在 state 里的东西。') },
  { page: 'ci-repair-agents', slug: 'ci-repair-agents', title: L('CI Repair Agents','CI 修复智能体'), summary: L('Handed a reproduction on a plate, this agent&rsquo;s real job is the classification nobody runs: caused by this diff, pre-existing on the base, infrastructure, or non-deterministic — prove causation by running the failing check against the merge base before pushing, spend at most one re-run, never touch what a test asserts, and page yourself on wrong-push rate rather than builds turned green.','复现被端到了面前，所以这个智能体真正的工作是那件没人做的分类：由这个 diff 造成、基线上本就存在、基础设施问题，还是非确定性——推送前先把失败的检查对着合并基线跑一遍来证明因果，最多花一次重跑，永远不碰测试所断言的东西，并把告警设在错误推送率上而不是转绿的构建数上。') },
  { page: 'database-migration-agents', slug: 'database-migration-agents', title: L('Database-Migration Agents','数据库迁移智能体'), summary: L('A model writes correct DDL first time, which is why this is the coding-agent task most likely to take production down: the statement is fine and the sequence is wrong, and CI runs it against an empty table with nobody else connected. Make the deliverable an ordered expand–backfill–contract sequence the currently-deployed code still fits, default the agent to additive-only changes, emit the lock_timeout preamble every time, and grade it on lock duration measured by a shadow apply against a production-shaped clone under load — the agent authors, a controlled runner applies.','模型一次就能写对 DDL——这正是它成为最可能把生产打趴下的那类编码智能体任务的原因：语句没问题，错的是顺序，而 CI 是在一张空表上、没有别人连着的情况下跑它的。把交付物做成「扩展-回填-收缩」这段当前已部署代码依然装得进去的有序序列，把智能体的默认输出设成只增不减，每次都产出 lock_timeout 前导，并用「在带负载的生产形态克隆上做影子应用所实测的锁持有时长」给它打分——智能体负责撰写，受控的执行器负责应用。') },
  ],
};
export default group;
