import { L, type Group } from '../types.ts';

const group: Group = {
  key: 'coding-and-computer-use-agents',
  order: 100,
  name: L('Coding & Computer-Use Agents', '编码与计算机操作智能体'),
  groupSummary: L('Agents that read code, write code, run tools, and drive a computer — patterns, harnesses, and pitfalls.', '能读代码、写代码、运行工具并驱动计算机的智能体——模式、外壳与陷阱。'),
  entries: [
    { page: 'coding-agent-architecture', slug: 'coding-agent-architecture', title: L('Coding Agent Architecture','编码智能体架构'), summary: L('The localize-edit-verify loop that makes a coding agent more than a code generator: the agent-computer interface, why agentic beats pipeline coding, and where the loop fails.','让编码智能体不止是代码生成器的“定位-编辑-验证”循环：智能体-计算机接口、为何智能体式优于流水线式，以及循环在哪里失效。') },
    { page: 'repo-navigation-and-context', slug: 'repo-navigation-and-context', title: L('Repo Navigation & Code Context','仓库导航与代码上下文'), summary: L('Code search vs. embeddings, symbol-level indexing, context budgeting over a large tree, and why confident wrong localization is the expensive failure of code retrieval.','代码搜索 vs 向量检索、符号级索引、在大型目录树上做上下文预算，以及为何自信的错误定位是代码检索代价最高的失败。') },
    { page: 'patch-generation-and-tests', slug: 'patch-generation-and-tests', title: L('Patch Generation & Test-Driven Loops','补丁生成与测试驱动循环'), summary: L('Structured diffs and hunk-apply failures, test-driven self-correction, regression guarding, and the three honest liars in the loop: flakes, overfit, and the deleted assertion.','结构化 diff 与 hunk 应用失败、测试驱动自我纠错、回归守护，以及循环里的三个诚实骗子：flake、过拟合、被删的断言。') },
    { page: 'computer-use-and-gui-agents', slug: 'computer-use-and-gui-agents', title: L('Computer-Use & GUI Agents','计算机操作与 GUI 智能体'), summary: L('Pixel vs. DOM grounding, the action space, the screenshot loop, and the multiplicative latency and reliability tax that makes GUI control a last resort.','像素 vs DOM 定位、动作空间、截图循环，以及那笔让 GUI 操控成为最后手段的乘法式延迟与可靠性税。') },
    { page: 'browser-agents', slug: 'browser-agents', title: L('Browser agents','浏览器智能体'), summary: L('Driving a real browser as a tool — DOM versus pixel observation, login + auth state, the well-trodden failure modes, and when to step up to a full GUI agent.','把一个真实浏览器当工具来驱动——DOM 与像素两种观察方式、登录与认证状态、踩烂了的失败模式，以及何时该升级到完整 GUI 智能体。') },
    { page: 'ide-agents', slug: 'ide-agents', title: L('IDE agents','IDE 智能体'), summary: L('Coding agents that live in the editor — the loop is the same as a CLI coding agent, but the interaction surface, undo expectations, and trust threshold are all different.','住在编辑器里的编码智能体——内循环和 CLI 编码智能体一样，但交互面、撤销预期与信任阈值都不同。') },
    { page: 'sandboxing-and-execution', slug: 'sandboxing-and-execution', title: L('Sandboxing & Safe Execution','沙箱与安全执行'), summary: L('Containerized execution, network and filesystem isolation, capability scoping, and designing for blast radius when an agent runs untrusted, attacker-influenced code.','容器化执行、网络与文件系统隔离、能力作用域，以及当智能体运行不可信、受攻击者影响的代码时如何为爆炸半径做设计。') },
    { page: 'evaluating-coding-agents', slug: 'evaluating-coding-agents', title: L('Evaluating Coding Agents','评估编码智能体'), summary: L('The SWE-bench family, pass@k vs. resolve rate, harness sensitivity, documented contamination, and why a private post-cutoff eval set is the only number to trust.','SWE-bench 系列、pass@k vs 解决率、测试编排敏感性、记录在案的污染，以及为何一个截止日期后的私有评测集才是唯一可信的数字。') },
    { page: 'code-review-agents', slug: 'code-review-agents', title: L('Code Review Agents','代码评审智能体'), summary: L('A review bot lives or dies on precision, not recall: diff-anchored context, an adversarial gate that drops any finding without a concrete failure scenario, a hard comment budget ranked worst-first, and acted-upon rate as the one production metric.','评审机器人的生死取决于精确率而非召回率：以 diff 为锚的上下文、把说不出具体失败场景的发现一律丢弃的对抗性闸门、按最坏优先排序的硬性评论预算，以及作为唯一生产指标的采纳率。') },
    { page: 'large-scale-migration-agents', slug: 'large-scale-migration-agents', title: L('Large-Scale Migration Agents','大规模迁移智能体'), summary: L('Generation went to zero and human review did not, so the deliverable is evidence rather than patches: build the oracle first, batch by verifiability instead of by directory, hand the mechanical head to a codemod and only the tail to the model, and let a hundred-file pilot&rsquo;s unedited-merge rate decide whether the project is viable.','生成成本归零而人工评审没有，所以交付物是证据而不是补丁：先把判据建好、按可核验性而非按目录分批、把机械的头部交给 codemod、只把尾部交给模型，并让一次百文件试点的无需人工编辑落地比例来决定这个项目是否可行。') },
  { page: 'debugging-and-triage-agents', slug: 'debugging-and-triage-agents', title: L('Debugging &amp; Triage Agents','调试与分诊智能体'), summary: L('An agent that reads a stack trace and emits a diff has pattern-matched, not debugged — make the failing test the deliverable and the eval criterion becomes objective, the spend moves from generation to observation, and "cannot reproduce" becomes a result you can trust.','一个读完调用栈就吐出 diff 的智能体是在做模式匹配，不是在调试——把失败的测试定为交付物，评测标准就变得客观，开销从生成挪到观察，而"复现不出来"也成了一个你可以信任的结果。') },
  { page: 'background-coding-agents', slug: 'background-coding-agents', title: L('Background Coding Agents','后台编码智能体'), summary: L('An agent that opens twelve pull requests a day adds nothing if your team merges four — detaching from the editor moves the bottleneck to review, so every decision is either about making a run self-verifying or about keeping the queue short enough that the work lands.','一个每天开十二个 PR 的智能体，如果团队只合得进四个，就什么也没增加——脱离编辑器把瓶颈搬到了复核端，于是每个决策要么是让一次运行能自我验证，要么是把队列压短到工作真能落地。') },
  { page: 'test-generation-agents', slug: 'test-generation-agents', title: L('Test-Generation Agents','测试生成智能体'), summary: L('An agent that writes tests from your code infers the spec from the implementation, so wherever the code is wrong the test now certifies the bug and blocks the fix — coverage cannot see this, mutation score can, and the only jobs worth dispatching are the ones where you can name the oracle in a sentence.','从你的代码出发写测试的智能体，是从实现里反推规格的，所以代码错在哪里，测试就在哪里把 bug 认证为正确并挡住修复——覆盖率看不见这件事，变异得分看得见；而值得派发的任务，只有那些你能用一句话说清判据是什么的。') },
  ],
};
export default group;
