import { L, type Group } from '../types.ts';

const group: Group = {
  key: 'domain-playbooks',
  order: 170,
  name: L('Domain Playbooks', '领域实战手册'),
  groupSummary: L('Domain-specific playbooks — customer support, research, sales, data analysis, DevOps — what to build, what to skip.', '按领域的实战手册——客服、研究、销售、数据分析、DevOps——该建什么，可以省什么。'),
  entries: [
  { page: 'customer-support-agents', slug: 'customer-support-agents', title: L('Customer-Support Agents','客户支持智能体'), summary: L('Optimize deflection subject to a near-zero confident-wrong-answer rate: grounded answers autonomous, transactions gated, tone graded in the eval, clean handoff over a confident guess.','在自信错答率近乎为零的约束下优化分流：接地答案自主、交易设关、语气进评估、干净交接胜过自信猜测。') },
  { page: 'data-analysis-agents', slug: 'data-analysis-agents', title: L('Data &amp; Analytics Agents','数据与分析智能体'), summary: L('The failure mode is a confidently wrong number: schema/semantic-layer grounding, read-only execution, verification as a separate stage, and abstention scored above confident error.','失败模式是自信的错误数字：schema/语义层接地、只读执行、核验作为独立阶段、弃答得分高于自信错答。') },
  { page: 'devops-sre-agents', slug: 'devops-sre-agents', title: L('DevOps &amp; SRE Agents','DevOps 与 SRE 智能体'), summary: L('Read-only first because the blast radius is production: diagnosis before remediation, runbooks as tested tools, limits in the tool signature, change control unchanged by the operator being a model.','只读优先，因为爆炸半径是生产：先诊断后修复、运维手册即经测试的工具、限制在工具签名里、变更管控不因操作者是模型而改变。') },
  { page: 'research-agents', slug: 'research-agents', title: L('Research &amp; Synthesis Agents','研究与综合智能体'), summary: L('A fabricated source voids the whole deliverable: retrieve-then-write-then-verify, citation faithfulness as a hard constraint, disagreement preserved not averaged, depth vs breadth as a bounded budget.','一个捏造来源即令整份交付物作废：检索-写作-核验、引用忠实度作为硬约束、保留分歧而非平均、深度与广度作为有界预算。') },
  { page: 'sales-and-gtm-agents', slug: 'sales-and-gtm-agents', title: L('Sales &amp; GTM Agents','销售与 GTM 智能体'), summary: L('The failure mode is automated spam at scale: value in research/personalization not volume, consent as an upstream fail-closed gate, human sign-off scaling with reach, spam-risk weighted heavily in the eval.','失败模式是规模化的自动垃圾邮件：价值在调研/个性化而非量、同意作为上游 fail-closed 关卡、人工签核随触达面伸缩、评估中垃圾邮件风险赋重权。') },
  { page: 'finance-agents', slug: 'finance-agents', title: L('Finance agents','金融场景智能体'), summary: L('Where agents earn their keep in finance — reconciliation, research synthesis, KYC review — and the hard rails (audit, determinism, regulator-readable trails) they must carry.','智能体在金融场景真正能创造价值的地方——对账、研报合成、KYC 审核——以及它们必须背着的硬性约束（审计、确定性、可供监管审阅的轨迹）。') },
  { page: 'healthcare-agents', slug: 'healthcare-agents', title: L('Healthcare agents','医疗场景智能体'), summary: L('Charting, prior auth, intake triage — the few healthcare jobs where agents shave real labor, and the privacy + clinical-safety guardrails you cannot ship without.','病历记录、事前授权、分诊接待——这些是医疗中智能体真正节省人力的少数任务，以及离开它们就不能上线的隐私与临床安全护栏。') },
  { page: 'legal-agents', slug: 'legal-agents', title: L('Legal agents','法律场景智能体'), summary: L('Discovery, contract review, citation checking — where legal agents already work, where they hallucinate, and what supervision they need by jurisdiction.','电子取证、合同审阅、引文核查——法律智能体已经能跑的地方、它们会幻觉的地方，以及不同法域下需要的人工监督。') },
  { page: 'playbook-meta', slug: 'playbook-meta', title: L('Adapting a Playbook to Your Domain','把实战手册适配到你的领域'), summary: L('The meta-method behind every playbook: derive a new vertical by answering five questions in order — job, autonomy by reversibility, tools as grounding-and-limit, eval mirroring the cost asymmetry, structural guardrails.','每份实战手册背后的元方法：按顺序回答五个问题来推导新垂直领域——任务、按可逆性的自主、作为接地与限制的工具、镜像代价不对称的评估、结构性护栏。') },
  { page: 'hiring-and-recruiting-agents', slug: 'hiring-and-recruiting-agents', title: L('Hiring & Recruiting Agents','招聘智能体'), summary: L('The one domain where regulators specified the architecture first: NYC Local Law 144 and EU AI Act Annex III demand a countable, attributable per-candidate decision — which is why the free-text "strong fit, 8/10" design fails an audit, and why the model belongs on the widening side of the funnel.','监管者先一步指定了架构的唯一领域：纽约市第 144 号地方法与欧盟《AI 法案》附件三都要求一个可数、可归因的按候选人决策——这正是自由文本式"匹配度强，8/10"设计过不了审计的原因，也是模型该待在漏斗拓宽一侧的原因。') },
  { page: 'email-and-calendar-agents', slug: 'email-and-calendar-agents', title: L('Email &amp; Calendar Agents','邮件与日历智能体'), summary: L('The only system of record an unauthenticated stranger can write to: provenance tiers that survive a forward, a reader/actor split with a typed interface so message content can never reach the send path, calendar as the zero-click vector nobody hardens, and confirmations that ask only when something is unusual.','唯一一类未经认证的陌生人也能写入的记录系统：能熬过一次转发的来源分级、以强类型接口切开的读取者/执行者结构使邮件内容永远够不到发送通路、作为无人加固的零点击载体的日历，以及只在异常时才发问的确认设计。') },
  { page: 'tutoring-and-learning-agents', slug: 'tutoring-and-learning-agents', title: L('Tutoring &amp; Learning Agents','辅导与学习智能体'), summary: L('The only domain where doing the task well is the failure: measure unaided post-test rather than session satisfaction, enforce the hint ladder in code, diagnose the misconception instead of explaining the topic, and accept that any agent able to do the homework has already broken homework as assessment.','唯一一个把活儿干好就等于失败的领域：测无辅助后测而不是会话满意度、用代码而不是提示词执行提示阶梯、诊断错误概念而不是讲解知识点，并承认任何做得了作业的智能体都已经让作业作为考核失效了。') },
  { page: 'security-operations-agents', slug: 'security-operations-agents', title: L('Security-Operations Agents','安全运营智能体'), summary: L('The only agent whose input is authored by an adversary who knows a model reads it: deterministic enrichment with the verdict kept out of the model, autonomy by reversibility with containment gated, and a golden set built from the closures you were never told were wrong.','唯一一类输入由"知道有模型在读"的对手亲手撰写的智能体：确定性富化、把裁决权挡在模型之外、按可逆性分配自主并给遏制动作设关，以及用那些"没人告诉过你判错了"的结案来搭黄金集。') },
  { page: 'translation-and-localization-agents', slug: 'translation-and-localization-agents', title: L('Translation &amp; Localization Agents','翻译与本地化智能体'), summary: L('Fluency stopped predicting fidelity, so reading the target text catches nothing: review the source-target pair in a diff, gate on machine-checkable invariants — placeholder parity, termbase, structure — and treat terminology as retrieval rather than a glossary in the prompt.','流畅度不再预示忠实度，于是只读译文什么都抓不到：审校 diff 中的原文-译文对、用机器可校验的不变量设关卡（占位符对等、术语库、结构），并把术语当作检索问题而不是塞进提示词的一张术语表。') },
  { page: 'shopping-and-checkout-agents', slug: 'shopping-and-checkout-agents', title: L('Shopping & Checkout Agents','购物与结账智能体'), summary: L('Instant Checkout was pulled back with fewer than fifteen merchants live because product data, not payments, was the hard part — so ground the item, re-verify at purchase time, and gate the one irreversible step outside the model.','Instant Checkout 在上线商家不足十五家时被收回，因为难的是商品数据而不是支付——所以要把商品接地、在下单那一刻重新核验，并把唯一那个不可逆的步骤挡在模型之外的关卡后。') },
  { page: 'content-moderation-agents', slug: 'content-moderation-agents', title: L('Content Moderation Agents','内容审核智能体'), summary: L('The published guidelines are a summary of a decade of unwritten precedent, so build moderation as retrieval over decided cases — and let the base rate, not the accuracy score, tell you how many reviewers you still need.','公开准则只是十年间未成文判例的一份摘要，所以要把审核建成在已决案例上的检索——并让基础发生率而不是准确率分数来告诉你还需要多少审核员。') },
    { page: 'insurance-claims-agents', slug: 'insurance-claims-agents', title: L('Insurance Claims Agents','保险理赔智能体'), summary: L('Cycle time is spent waiting for a missing document, not deciding — so build the completeness engine, stop at the coverage determination, and decline fraud scoring deliberately: it is the use case with the worst risk-adjusted return in the domain.','周期时间花在等一份缺失材料上，而不是花在裁定上——所以去建完备性引擎、在责任认定处停下，并刻意拒绝欺诈评分：它是这个领域里风险调整后回报最差的用例。') },
  ],
};
export default group;
