import { L, type Group } from '../types.ts';

const group: Group = {
  key: 'voice-realtime-agents',
  order: 150,
  name: L('Voice & Realtime Agents', '语音与实时智能体'),
  groupSummary: L('Realtime voice agents — speech stack, turn-taking, barge-in, latency budgets, voice-specific tooling and state.', '实时语音智能体——语音栈、轮替、打断、延迟预算、语音特有的工具与状态。'),
  entries: [
  { page: 'realtime-architecture', slug: 'realtime-architecture', title: L('Realtime Agent Architecture','实时智能体架构'), summary: L('Cascade (STT→LLM→TTS) vs native speech-to-speech, the stateful audio transport, and the one decision everything else hangs on: where the agent loop lives.','级联（STT→LLM→TTS）vs 原生语音到语音、有状态的音频传输，以及一切所系的那个决策：智能体循环住在哪里。') },
  { page: 'latency-budget', slug: 'latency-budget', title: L('The Latency Budget','延迟预算'), summary: L('The sub-second turn accounted for line by line: where the milliseconds go, why endpointing is the biggest slice, and perceived vs actual latency.','把亚秒轮次逐行记账：毫秒去了哪里、为何端点检测是最大一块，以及被感知 vs 实际的延迟。') },
  { page: 'turn-taking-and-barge-in', slug: 'turn-taking-and-barge-in', title: L('Turn-Taking & Barge-In','轮次与打断'), summary: L('VAD vs endpointing, semantic end-of-turn detection, mandatory barge-in, echo cancellation as a prerequisite, and backchannels vs real interruptions.','VAD vs 端点检测、语义轮次结束检测、强制打断、作为前提的回声消除，以及附和 vs 真正的打断。') },
  { page: 'speech-stack', slug: 'speech-stack', title: L('STT, TTS & Speech-to-Speech','STT、TTS 与语音到语音'), summary: L('Streaming STT, the transcription-error tax, TTS time-to-first-audio, native audio models, and why 8 kHz telephony changes every benchmark.','流式 STT、转写错误税、TTS 首段音频时间、原生音频模型，以及为何 8 kHz 电话改变每一个基准。') },
  { page: 'voice-tooling-and-state', slug: 'voice-tooling-and-state', title: L('Tool Use & State in Voice','语音中的工具调用与状态'), summary: L('Calling tools without dead air: preambles, async/parallel tool runs, confirm-by-ear before mutating, and slot state across an interruptible call.','不留空气死寂地调工具：前导语、异步/并行工具运行、变更前靠耳朵确认，以及贯穿可打断通话的槽位状态。') },
  { page: 'voice-failure-modes', slug: 'voice-failure-modes', title: L('Voice Agent Failure Modes','语音智能体失败模式'), summary: L('Hallucinated hearing, dead air, the infinite apology loop, the latency death spiral, and the escalation/handoff you must design for.','幻听、空气死寂、无限道歉循环、延迟死亡螺旋，以及你必须为之设计的升级/移交。') },
  { page: 'outbound-voice-agents', slug: 'outbound-voice-agents', title: L('Outbound voice agents','外呼语音智能体'), summary: L('Agents that **make** the call instead of answering it — pacing, abandonment, identity disclosure, and the regulatory landmines that turn a clever demo into a fine.','主动拨打而非接听的智能体——节奏、放弃率、身份披露，以及把炫酷 demo 变成罚单的合规雷区。') },
  { page: 'evaluating-voice-agents', slug: 'evaluating-voice-agents', title: L('Evaluating Voice Agents','评估语音智能体'), summary: L('Transcript evals score the one layer that was not broken: build the golden set from recorded audio, measure entity error rate rather than WER, and treat timing as a first-class score.','文字记录评测量的是唯一那层本来就没坏的东西：用录下来的音频搭黄金集，量实体错误率而不是 WER，并把时序当作一等公民的评分项。') },
  { page: 'telephony-and-pstn-integration', slug: 'telephony-and-pstn-integration', title: L('Telephony & PSTN Integration','电话与 PSTN 接入'), summary: L('Half the turn latency, all the audio quality and whether the call connects at all live in a carrier path you cannot profile: the fixed transport tax, your number as a reputation asset, the missing metadata channel, and consent as a code path rather than a prompt.','一半的轮次延迟、全部的音质，以及通话到底接不接得通，都住在一条你无法剖析的运营商链路里：固定的传输税、作为信誉资产的号码、缺失的元数据通道，以及作为代码路径而非提示词的同意机制。') },
  { page: 'multilingual-voice-agents', slug: 'multilingual-voice-agents', title: L('Multilingual &amp; Code-Switching Voice Agents','多语言与语码转换语音智能体'), summary: L('Adding a language breaks recognition, not generation — and per-turn language lock, the standard fix, is exactly what a bilingual caller violates in their first sentence, with the damage landing on the names and numbers you were about to pass to a tool.','多加一种语言坏掉的是识别而不是生成——而按轮锁定语言这个标准解法，恰恰会被双语来电者的第一句话打破，而受损的正是你正要传给工具的那些人名与号码。') },
  { page: 'caller-authentication', slug: 'caller-authentication', title: L('Caller Authentication for Voice Agents','语音智能体的来电者核验'), summary: L('Three seconds of audio clones a customer and roughly one in five biometric fraud attempts is now a deepfake, so a voiceprint identifies but no longer authenticates — move the proof out of the audio channel, bind it to the action rather than the call, and notice that your own outbound agent is normalising the attack.','三秒音频就能克隆一位客户，而如今约每五次生物特征欺诈尝试就有一次是深度伪造，于是声纹只能识别、不再能认证——把证明挪出音频通道、绑定到动作而非这通电话，并留意你自己的外呼智能体正在把那套攻击正常化。') },
  { page: 'retrieval-in-the-voice-loop', slug: 'retrieval-in-the-voice-loop', title: L('Retrieval Inside the Voice Turn','把检索塞进语音轮次'), summary: L('A grounded answer has to start leaving the speaker about 800ms after the caller stops, and a retrieve-rewrite-rerank chain spends most of that before the model sees a document — so retrieval latency is an accuracy metric: start querying on the partial transcript, precompute the head of the question distribution, and delete the stages you were told were mandatory.','一个有依据的回答必须在来电者停口后约 800 毫秒开始从扬声器出来，而"检索—改写—重排"链条在模型看到文档之前就花掉了大半——所以检索延迟是一个准确率指标：对着部分转写就开始查、把问题分布的头部预先算好，并删掉那些别人告诉你必不可少的阶段。') },
  { page: 'escalation-and-warm-transfer', slug: 'escalation-and-warm-transfer', title: L('Escalation &amp; Warm Transfer','升级与温转接'), summary: L('A voice agent can nail every turn and still lose the customer in the handoff, because the human answers as if the call never happened — so the handoff is judged by how much the caller repeats, not by whether it connected: escalate before the caller asks, carry a context packet (verified identity, the caller’s own words, actions already taken) that lands before the human’s first word, always design the no-human branch, and page yourself on repeat rate rather than transfer rate.','一个语音智能体可以把每一轮都答对，却仍在交接处丢掉客户，因为人工一句问候仿佛这通电话从未发生——所以衡量交接的是来电者重复了多少，而不是它有没有接通：在来电者开口之前就升级，携带一个在人工第一个字之前送达的上下文包（已验证身份、来电者原话、已采取的动作），永远设计好"没有人工"那条分支，并为重复率而不是转接率给自己传呼。') },
  ],
};
export default group;
