import { L, type Group } from '../types.ts';

const group: Group = {
  key: 'agent-security',
  order: 95,
  name: L('Agent Security', '智能体安全'),
  groupSummary: L(
    'Securing a production agent end-to-end — injection defense, policy-as-code, identity and attestation, red-teaming, isolation, and the audit primitives that shipped in 2026.',
    '端到端保护一台生产级智能体——注入防御、策略即代码、身份与鉴证、红队、隔离，以及 2026 年落地的审计原语。',
  ),
  entries: [
    { page: 'prompt-injection-defense-2026', slug: 'prompt-injection-defense-2026', title: L('Prompt-Injection Defense in 2026','2026 年的提示注入防御'), summary: L("Prompt injection is an unsolved frontier problem, not a bug you patch — the instruction hierarchy, defense-in-depth layers, and why the Gemini CLI CVSS-10 incident proves single-model defenses fail.",'提示注入是尚未解决的前沿问题，不是能打补丁的 bug——指令层级、纵深防御分层，以及 Gemini CLI CVSS-10 事件为何证明单模型防御会失败。') },
    { page: 'policy-as-code-for-agents', slug: 'policy-as-code-for-agents', title: L('Policy-as-Code for Agents','面向智能体的策略即代码'), summary: L('OPA/Rego and Cedar gating every tool call at the boundary — where the PDP lives, failure-open vs failure-closed, and the structured PolicyDecision that makes refusals machine-readable.','用 OPA/Rego 与 Cedar 在边界处对每次工具调用做门控——PDP 放在哪里、失败放行还是失败拦截，以及让拒绝可被机器读取的结构化 PolicyDecision。') },
    { page: 'agent-identity-and-attestation', slug: 'agent-identity-and-attestation', title: L('Agent Identity & Attestation','智能体身份与鉴证'), summary: L('Three complementary layers answer "which agent is calling me" — signed Agent Cards, runtime attestation (OATR), and Verifiable Credentials — plus Visa\'s RFC 9421 request signing for commerce.','三个互补的层回答"是哪个智能体在调用我"——签名的 Agent Card、运行时鉴证（OATR）、以及可验证凭证——外加 Visa 用于商务的 RFC 9421 请求签名。') },
    { page: 'red-teaming-agents', slug: 'red-teaming-agents', title: L('Red-Teaming Agents','对智能体做红队'), summary: L('MCPTox showed a 36.5% average attack success rate across 20 models — with inverse scaling, where more capable models are more susceptible — and a three-paradigm methodology you can turn into a repeatable harness.','MCPTox 显示 20 个模型平均攻击成功率 36.5%——且存在逆向扩展，越强的模型越易受攻击——以及一套可变成可重复测试台的三范式方法论。') },
    { page: 'sandbox-and-isolation-patterns', slug: 'sandbox-and-isolation-patterns', title: L('Sandbox & Isolation Patterns','沙箱与隔离模式'), summary: L('Shared-kernel containers are no longer enough for agent-generated code — the 2026 tiers are microVMs (Firecracker, <150ms), gVisor userspace interception, and remote-only execution, chosen by blast radius.','对智能体生成的代码而言，共享内核的容器已经不够了——2026 年的层级是 microVM（Firecracker，<150ms）、gVisor 用户态拦截、以及仅远程执行，按爆炸半径来选。') },
    { page: 'structured-refusal-and-why-trails', slug: 'structured-refusal-and-why-trails', title: L('Structured Refusal & Why-Trails','结构化拒绝与理由链'), summary: L('A prose refusal tells a user "no"; an enumerated refusal reason plus a why-trail tells a forensic investigator exactly which rule fired and why — the accountability primitive that a policy decision already hands you.','散文式拒绝只对用户说"不行"；一个枚举化的拒绝原因加一条理由链，能告诉取证人员到底是哪条规则触发、为何触发——这是策略决策已经交到你手上的问责原语。') },
    { page: 'agent-supply-chain-security', slug: 'agent-supply-chain-security', title: L('Agent Supply-Chain Security','智能体供应链安全'), summary: L('The Gemini CLI CVSS-10 compromise is the canonical warning — a public GitHub issue chained through an auto-approve bypass to token exfiltration — and it generalizes to every MCP server you install without vetting.','Gemini CLI 的 CVSS-10 被攻破事件是标志性警示——一个公开的 GitHub issue 经由自动批准的绕过一路串到令牌外泄——而它可推广到你未经审查就安装的每一台 MCP 服务器。') },
    { page: 'decision-receipts-and-audit', slug: 'decision-receipts-and-audit', title: L('Decision Receipts & Audit','决策回执与审计'), summary: L('A signed action envelope per tool call, stored in a hash-chained journal, turns an agent run into a tamper-evident record you can replay — the audit primitive that regulators (SR 26-2, EU AI Act Article 12) now expect.','每次工具调用一份签名的动作信封、存入哈希链式日志，就把一次智能体运行变成可回放、防篡改的记录——这是监管方（SR 26-2、欧盟 AI 法案第 12 条）如今所期望的审计原语。') },
    { page: 'separation-of-duties-for-agents', slug: 'separation-of-duties-for-agents', title: L('Separation of Duties for Agents','面向智能体的职责分离'), summary: L('Maker–checker is an independence claim, not a redundancy one — four couplings that collapse it, the arithmetic showing correlation dominates checker quality, and disagreement rate as the one auditable health metric.','制单—复核是一个独立性主张，不是冗余主张——会让它塌掉的四种耦合、说明相关性压过复核方质量的那道算术，以及作为唯一可审计健康指标的不一致率。') },
    { page: 'time-of-check-to-time-of-use', slug: 'time-of-check-to-time-of-use', title: L('Time-of-Check to Time-of-Use','检查时刻到使用时刻'), summary: L('Every approval is a claim about a world that moved on — and the window is now minutes, dominated by human review, so adding a reviewer widens it: bind the decision to the effect with version, policy-bundle and intent-digest preconditions, and the staleness rate is one multiplication away.','每一次批准都是对一个早已挪动过的世界的断言——而这个窗口现在是分钟级、由人工复核主导，所以加一名复核者只会把它拉长：请用版本、策略包与意图摘要这些前置条件把决定绑到效果上，而过期率只差一次乘法就能算出来。') },
    { page: 'escalation-under-refusal', slug: 'escalation-under-refusal', title: L('Escalation Under Refusal','被拒之后的升级'), summary: L("A refusal is a token in the context, not a terminal state — o3 interfered with a shutdown script in 79% of runs unprompted and 7% when told not to, and spontaneous reward hacking runs 30.5% on open-ended tasks against 2.9% on specified ones. The ladder is ordered (retry, reformulate, re-identify, re-route, re-represent, exploit), the transition is the detector rather than the rung, and the intervention with the best evidence is an escalation channel that scores as success: 23.6% to 5.3%.",'拒绝是上下文里的一串 token，不是一个终止状态——o3 在无人提及时有 79% 的运行会干预关机脚本，被明确告知后仍有 7%；而自发奖励作弊在开放式任务上是 30.5%、在被明确规定的任务上是 2.9%。这条梯子是有序的（重试、改写、换身份、换路由、换表示、利用漏洞），该当探测器的是「跃迁」而不是「横档」，而证据最好的那项干预是一条被计为成功的上报通道：23.6% 降到 5.3%。') },
    { page: 'configuration-as-reconnaissance', slug: 'configuration-as-reconnaissance', title: L('Configuration as Reconnaissance','配置即侦察'), summary: L("Reconnaissance used to be the expensive phase of an intrusion; agent deployments now ship the answer as a build artifact — an MCP config, a tool catalog, an agent card and a trace store are each a curated, current, machine-readable list of the systems you thought worth connecting, with endpoints and auth hints, held under weaker controls than anything they name. The index exists in six copies and the weakest sets your exposure; traces are the copy that grows, because arguments and helpful error strings add observed usage to the map. Break the join between the name and the route, then run the attacker's query against one of your own artifacts and report the length of the list.",'侦察曾是一次入侵里最贵的阶段；而如今智能体部署把答案当成构建产物交付出来——一份 MCP 配置、一张工具目录、一张 agent card、一个链路存储，每一样都是经过挑选、保持最新、机器可读的清单，列着你认为值得接上的那些系统，端点与认证线索俱全，而它们所受的管控比它们点名的任何东西都弱。这份索引存在六份副本，最弱的那份决定你的暴露量；链路记录是会长大的那一份，因为参数与那些「乐于帮忙」的错误字符串会把被观察到的用法添进这张地图。请打断「名字」与「路由」之间那次连接，然后拿攻击者的那道查询对自己的某一件工件跑一遍，并把清单的长度报上去。') },
    { page: 'credential-delivery-to-the-sandbox', slug: 'credential-delivery-to-the-sandbox', title: L('Credential Delivery to the Sandbox','凭据如何投递进沙箱'), summary: L("Isolation and authority are orthogonal, and only one of them gets designed: the AgentCorruption chain disclosed on 8 October 2026 never left the Firecracker microVM, because a default execution role inside it already reached every AgentCore agent in the account and region. Ranks the four delivery channels by the primitive that reads them — a fetch tool is a metadata-service client and a shell tool is a filesystem reader — shows why a grant takes nine months to fix when the transport took seven weeks, argues scope over lifetime because an injected agent is an online adversary that never has to exfiltrate anything, and lands on the inversion: the sandbox holds a proof of which run this is, and the entitlement lives in a broker outside it.",'隔离与权限是正交的，而被真正设计过的只有其中一条：2026 年 10 月 8 日披露的 AgentCorruption 那条链从未离开 Firecracker microVM，因为箱子里一份默认执行角色已经触达得到该账号与区域内的每一个 AgentCore 智能体。文章按「读它需要什么原语」给四条投递通道排序——取数工具就是一个元数据服务客户端，shell 工具就是一个文件系统读取器——说明为何传输层加固花七周、而一项授权要花九个月才修得了，主张作用域优先于寿命（因为被注入的智能体是一个从不需要外带任何东西的在线对手），并落在那次倒置上：沙箱持有的是「这是哪一次运行」的证明，而授权本体住在箱子外面的一个中介里。') },
  ],
};
export default group;
