import { L, type Group } from '../types.ts';

const group: Group = {
  key: 'mcp',
  order: 25,
  name: L('MCP', 'MCP'),
  groupSummary: L(
    "Building, testing, securing, and operating Model Context Protocol servers — the practical layer above mcp-architecture's conceptual introduction.",
    '构建、测试、保护与运维模型上下文协议服务器——mcp-architecture 概念介绍之上的实践层。',
  ),
  entries: [
    { page: 'mcp-building-servers-in-practice', slug: 'mcp-building-servers-in-practice', title: L('Building MCP Servers in Practice','实操构建 MCP 服务器'), summary: L('Idiomatic server construction beyond hello-world — FastMCP decorators, TypeScript Standard Schema, when to expose a capability as a tool vs a resource vs a prompt, and what to actually put in the median five-tool server.','超越 hello-world 的地道服务器构建——FastMCP 装饰器、TypeScript Standard Schema、何时把能力做成 tool 与 resource 与 prompt 之分，以及一台中位数五工具的服务器里到底该放什么。') },
    { page: 'mcp-tool-design', slug: 'mcp-tool-design', title: L('Designing MCP Tools','设计 MCP 工具'), summary: L('MCP tools are prompts as much as APIs — description phrasing changes selection, granularity changes token cost, and the search-then-fetch pattern beats "give the model the whole document" every time.','MCP 工具与其说是 API 不如说是提示词——描述措辞决定选择、粒度决定 token 成本，而 search-then-fetch 模式每一次都胜过"把整份文档丢给模型"。') },
    { page: 'mcp-testing', slug: 'mcp-testing', title: L('Testing MCP Servers','测试 MCP 服务器'), summary: L('The in-process pattern still wins, but both SDKs changed the door — and with no handshake left to test, what you assert instead is that every request stands alone.','进程内测试依然是对的，但两个 SDK 都换了门——而在握手已经不存在之后，你要断言的变成了：每一次请求都能独立成立。') },
    { page: 'mcp-streamable-http-deep-dive', slug: 'mcp-streamable-http-deep-dive', title: L('Streamable HTTP: the current MCP transport','Streamable HTTP：MCP 的当前传输'), summary: L('The single-endpoint transport after the session header, the GET stream and resumability were all removed — what every POST must now carry, and what subscriptions/listen replaced.','在会话头、GET 流与可恢复性统统被移除之后的单端点传输——每个 POST 如今必须携带什么，以及 subscriptions/listen 取代了什么。') },
    { page: 'mcp-auth-oauth21', slug: 'mcp-auth-oauth21', title: L('MCP Auth: the OAuth 2.1 Profile','MCP 鉴权：OAuth 2.1 配置'), summary: L('PKCE mandatory, RFC 8707 resource indicators, Protected Resource Metadata for AS discovery, Client ID Metadata Documents beating Dynamic Client Registration — the MCP-shaped subset of OAuth, and why 39% of production servers ship with none of it.','强制 PKCE、RFC 8707 资源指示、用于 AS 发现的 Protected Resource Metadata、以及优于动态客户端注册的 Client ID Metadata Documents——OAuth 中面向 MCP 的那一子集，以及为何 39% 的生产服务器一个都不用。') },
    { page: 'mcp-security-anti-patterns', slug: 'mcp-security-anti-patterns', title: L('MCP Security Anti-Patterns','MCP 安全反模式'), summary: L('The six patterns the 2025-11-25 spec forbids by name — confused deputy, token passthrough, session hijacking, SSRF via discovery, javascript-URL injection, startup-command execution — with the trace signature and mechanical fix for each.','2025-11-25 规范逐一点名禁止的六种模式——confused deputy、令牌透传、会话劫持、通过发现的 SSRF、javascript-URL 注入、启动命令执行——每一种都给出轨迹指纹与机械修法。') },
    { page: 'mcp-sampling-and-elicitation', slug: 'mcp-sampling-and-elicitation', title: L('Sampling & Elicitation via MRTR','经由 MRTR 的采样与征询'), summary: L('Server-initiated requests are gone: the server now returns its questions and the client retries the call carrying the answers — and the state it hands over in between is attacker-controlled input.','服务器发起的请求已被删除：如今服务器把问题返回，客户端再带着答案重试同一次调用——而它在两程之间交出去的那份状态，是攻击者可控的输入。') },
    { page: 'mcp-tool-poisoning', slug: 'mcp-tool-poisoning', title: L('Tool Poisoning: Prompt Injection via Tool Descriptions','工具毒化：经工具描述实施的提示词注入'), summary: L('Tool descriptions are prompts your model reads — when they come from a downstream data source that also takes untrusted input, they become an indirect prompt injection surface (CVE-2025-54136, MCPTox).','工具描述就是模型会读的提示词——当它们来自一个也接受不受信输入的下游数据源时，就变成了间接提示词注入的攻击面（CVE-2025-54136，MCPTox）。') },
    { page: 'mcp-ops-in-production', slug: 'mcp-ops-in-production', title: L('MCP Ops in Production','MCP 生产运维'), summary: L('Per-tool kill switches, argument-shape (not value) audit logs, tenant isolation from verified token claims (not request bodies), and rate-limits sized for agent traffic.','逐工具的 kill switch、按参数形状（而非值）记录的审计日志、从被验证的令牌 claim（而非请求体）取得的租户隔离，以及按 agent 流量规模化的限流。') },
    { page: 'mcp-registry-and-distribution', slug: 'mcp-registry-and-distribution', title: L('MCP Registry & Distribution','MCP 注册表与分发'), summary: L('The registry is still in preview: publishing with mcp-publisher and a server.json manifest, the six package types, the two 2026 changes that break existing publishers, and why the manifest cannot tell a host which protocol revision you speak.','注册表仍处于预览阶段：用 mcp-publisher 与 server.json 清单发布、六种包类型、2026 年两项会让现有发布者失败的变更，以及为何该清单无法告诉宿主你支持哪个协议修订版。') },
    { page: 'mcp-revision-2026-07-28', slug: 'mcp-revision-2026-07-28', title: L('The 2026-07-28 Revision','2026-07-28 修订版'), summary: L('Removing the handshake deleted the one place negotiation, identity and server-initiated requests used to live — so all three reappeared on every single request, and a server that does not restate them is now malformed.','删掉握手，等于删掉了协商、身份与服务器发起请求原本唯一的落脚点——于是这三者都改为在每一次请求上重新出现，而不再逐次声明的服务器，如今就是格式错误的。') },
  ],
};
export default group;
