import { L, type Group } from '../types.ts';

const group: Group = {
  key: 'retrieval-and-rag',
  order: 40,
  name: L('Retrieval & RAG', '检索与 RAG'),
  groupSummary: L('Retrieval-augmented generation past the basics — advanced architectures, graph RAG, retrieval as an agent tool, RAG security.', '检索增强生成的进阶——高级架构、图 RAG、把检索作为智能体工具、RAG 安全。'),
  entries: [
    { page: 'advanced-rag-architectures', slug: 'advanced-rag-architectures', title: L('Advanced RAG Architectures','进阶 RAG 架构'), summary: L('The naive→modular→agentic RAG spectrum and the levers that matter — CRAG, Self-RAG, query transformation, fusion, reranking — all attacking the same garbage-in/confident-wrong-out failure.','朴素→模块化→智能体式 RAG 谱系与关键杠杆——CRAG、Self-RAG、查询变换、融合、重排序——全都在攻击同一个“垃圾进、自信错出”的失败。') },
    { page: 'graph-rag', slug: 'graph-rag', title: L('GraphRAG & Multi-Hop Retrieval','GraphRAG 与多跳检索'), summary: L('Why flat top-k RAG cannot answer thematic or relational multi-hop queries, how Microsoft GraphRAG and iterative retrieve-reason loops solve it, and the cost/staleness heuristic for when not to.','为什么扁平 top-k RAG 回答不了主题型或关系型多跳查询，微软 GraphRAG 与迭代检索-推理循环如何解决，以及何时不该用的成本/陈旧化启发式。') },
    { page: 'hybrid-search-and-reranking', slug: 'hybrid-search-and-reranking', title: L('Hybrid Search & Reranking','混合检索与重排序'), summary: L('Why one retriever is structurally not enough, reciprocal rank fusion across BM25 + dense, the two-stage retrieve-then-cross-encoder pattern, and ColBERT-style late interaction when cross-encoders are too slow.','为什么单一检索器在结构上不够、跨 BM25 + 稠密的倒数排名融合、"检索-再交叉编码器"两阶段模式，以及交叉编码器太慢时 ColBERT 式晚交互的位置。') },
    { page: 'document-parsing-for-rag', slug: 'document-parsing-for-rag', title: L('Document Parsing & Ingestion Quality','文档解析与摄取质量'), summary: L('Ingestion is the half of RAG that doesn\'t get dashboards and decides whether the answer was ever indexable — layout-aware parsing, tables, OCR, structural chunking, and vision-RAG as a parsing escape hatch.','摄取是不被仪表盘照亮、却决定答案是否曾可被索引的那半 RAG——布局感知解析、表格、OCR、结构化分块，以及作为解析逃生阀的视觉 RAG。') },
    { page: 'query-understanding-for-rag', slug: 'query-understanding-for-rag', title: L('Query Understanding & Transformation','查询理解与变换'), summary: L('Fixing the question before you search — rewriting, decomposition, multi-query, HyDE caveats, step-back prompting, and routing — the cheapest place to add intelligence to a RAG pipeline.','在搜索之前先修好问题——改写、分解、多查询、HyDE 告诫、退一步提示、以及路由——给 RAG 流水线加智能最便宜的地方。') },
    { page: 'agentic-retrieval', slug: 'agentic-retrieval', title: L('Agentic Retrieval: Search as a Tool','智能体式检索：把搜索做成工具'), summary: L('Retrieval as a tool the model calls iteratively in a ReAct-style loop, with budget, stopping criteria, and the new failure modes (looping, drift, premature stop) that come with handing the model the steering wheel.','把检索做成模型在 ReAct 式循环中迭代调用的工具，带预算、停止判据，以及把方向盘交给模型后随之而来的新失败模式（原地循环、漂移、过早停止）。') },
    { page: 'evaluating-rag', slug: 'evaluating-rag', title: L('Evaluating RAG','评估 RAG'), summary: L('Score retrieval, grounding, and answer quality as three separate things — recall@k, faithfulness, answer relevance — plus how to build a small living eval set and use LLM judges without lying to yourself.','把检索、接地与答案质量当作三件独立的事来打分——recall@k、忠实性、答案相关性——加上如何构建一个持续生长的小评测集，以及在不自欺欺人前提下使用 LLM 裁判。') },
    { page: 'choosing-a-vector-database', slug: 'choosing-a-vector-database', title: L('Choosing a Vector Database','选向量数据库'), summary: L('A constraint-first selection guide — what a vector DB actually is, the axes that genuinely differ between products (ANN algorithm, filter quality, freshness, hybrid, multi-tenancy, ops, cost), just enough HNSW/IVF/DiskANN internals to read a vendor pitch, and why most teams end at pgvector.','一份约束优先的选型指南——向量库到底是什么、产品之间真正不同的那些轴（ANN 算法、过滤质量、新鲜度、混合检索、多租户、运维、成本）、读懂厂商话术所需的最少 HNSW/IVF/DiskANN 内部知识，以及为何多数团队最终落在 pgvector。') },
    { page: 'local-first-retrieval', slug: 'local-first-retrieval', title: L('Local-First Retrieval','本地优先检索'), summary: L('Building a knowledge base on hardware you own — starting with whether you need an index at all, since the leading coding agents removed theirs in favour of grep. Ingest quality, embedding-model sizing, the four store architectures, hybrid retrieval, serving it to an agent over MCP, and when to run a finished platform instead.','在自己的硬件上搭知识库——先问你到底需不需要索引，因为领先的编程智能体已经把索引拿掉换成了 grep。摄取质量、嵌入模型规格、四种存储架构、混合检索、通过 MCP 交给智能体，以及什么时候干脆跑一个成品平台。'), related: { concepts: ['local-knowledge-bases', 'small-and-local-models', 'knowledge-graphs'] } },
    { page: 'index-freshness-and-invalidation', slug: 'index-freshness-and-invalidation', title: L('Index Freshness & Invalidation','索引新鲜度与失效'), summary: L('A stale index returns a confident answer with a citation, and the three ways a corpus goes stale have different blast radii — an out-of-date paragraph is embarrassing, a deleted document that still answers is an incident. Why the nightly re-crawl is a bill rather than a guarantee, how to drive invalidation from a change stream that is reliably bad at deletions, tombstones before compaction, the derived artefacts that inherit no deletion at all, and change-to-queryable as a per-source p99 with a name on it.','陈旧的索引会给出一个带引用的自信答案，而语料变陈旧的三种方式爆炸半径各不相同——一段过时的文字是尴尬，一份已删除却仍在作答的文档是事故。为什么每夜全量重爬是一张账单而不是一份保证、如何让失效由一条在删除上可靠地不可靠的变更流驱动、压实之前先立墓碑、那些一点都不继承删除的派生物，以及把「变更到可检索」做成按来源的 p99 并且有人署名。'), related: { concepts: ['what-is-rag', 'knowledge-cutoffs-and-time', 'semantic-caching'] } },
    { page: 'contextual-retrieval', slug: 'contextual-retrieval', title: L('Contextual Retrieval','上下文化检索'), summary: L('The largest source of recall failure in a competent RAG stack is the moment you cut the document up: the chunk that says revenue grew 3% names no company, no quarter and no year. Prepending a generated preamble before embedding cuts top-20 retrieval failure by 35%, 49% when the same preamble feeds BM25, and 67% with reranking on top (5.7% to 1.9%), at roughly $1.02 per million document tokens under prompt caching — but your index is now a function of a second model and a prompt you will want to change, so budget three rebuilds and try heading-path prefixes, a reranker and hybrid search first.','一套称职的 RAG 栈里召回失败最大的来源，是你把文档切开的那一刻：那个写着「营收增长 3%」的分块，既没点公司、也没点季度和年份。在嵌入前前置一段生成的引子，能把 top-20 检索失败率降低 35%，让同一段引子也进 BM25 则降低 49%，再叠上重排降低 67%（5.7% 降到 1.9%），在提示词缓存下成本约为每百万文档令牌 1.02 美元——但你的索引从此成了第二个模型与一段你迟早想改的提示词的函数，所以按三次重建做预算，并先试标题路径前缀、重排器与混合检索。'), related: { concepts: ['chunking-and-vector-search', 'embeddings', 'prompt-caching'] } },
  ],
};
export default group;
